irafhy: /home/jianqiang/CLionProjects/irafhy/test/algorithmTest/underApproximateBackwardUsingPolytopeTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <string>
#include <fstream>
#include <memory>
#include <boost/filesystem.hpp>
#include <capd/capdlib.h>
#include <irafhy/utility/parser/hybridAutomatonParser.h>
#include <irafhy/utility/parser/settingsParser.h>
#include <irafhy/utility/parser/visitor/systemVisitor.h>
#include <irafhy/utility/viewer.h>
#include <underApproximateBackwardUsingPolytope/analyser/analyser.h>
#include <underApproximateBackwardUsingPolytope/settings/settings.h>
#include <underApproximateBackwardUsingPolytope/verifier/verifier.h>
Classes
class runUABPAnalyserTest
Functions
TEST_F (runUABPAnalyserTest, runUABPAnalyser_SpikingNeuronModel_single_step_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_0_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_2_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_3_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_4_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_5_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_6_Test)
TEST_F (runUABPAnalyserTest, runUABPAnalyserTest_example_7_Test)
Function Documentation
TEST_F() [1/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyser_SpikingNeuronModel_single_step_Test)
References irafhy::INTERVAL_HULL, irafhy::PLANE, irafhy::Condition::set(), irafhy::viewer::show(), hybridautomatonParser::system(), and runUABPAnalyserTest::systemIfstream.
TEST_F() [2/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_0_Test)
References runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [3/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_2_Test)
References runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [4/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_3_Test)
50
References runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [5/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_4_Test)
References runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [6/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_5_Test)
References runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [7/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_6_Test)
References irafhy::LINE, runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [8/8]
TEST_F (runUABPAnalyserTest , runUABPAnalyserTest_example_7_Test)
References irafhy::LINE, runUABPAnalyserTest::modelPathVec, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), runUABPAnalyserTest::settingPathVec, irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().