irafhy: /home/jianqiang/CLionProjects/irafhy/test/algorithmTest/overApproximateForwardTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <string>
#include <fstream>
#include <boost/filesystem.hpp>
#include <capd/capdlib.h>
#include <irafhy/utility/parser/visitor/hybridautomatonVisitor.h>
#include <irafhy/utility/parser/visitor/settingsVisitor.h>
#include <irafhy/utility/viewer.h>
#include <overApproximateForward/analyser/analyser.h>
#include <overApproximateForward/settings/settings.h>
#include <overApproximateForward/verifier/verifier.h>
Classes
class runOAFAnalyserTest
Functions
TEST_F (runOAFAnalyserTest, runOAFAnalyserTest_SpikingNeuronModel_Test)
TEST_F (runOAFAnalyserTest, runOAFAnalyserTest_helicopterController_Test)
TEST_F (runOAFAnalyserTest, runOAFAnalyserTest_fitzHugNagNeuronModel_Test)
Function Documentation
TEST_F() [1/3]
TEST_F (runOAFAnalyserTest , runOAFAnalyserTest_SpikingNeuronModel_Test)
References hybridautomatonParser::hybridautomaton(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), settingsParser::setting(), irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), runOAFAnalyserTest::SpikingNeuronModelIfstream, runOAFAnalyserTest::SpikingNeuronModelSettingsIfstream, irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [2/3]
TEST_F (runOAFAnalyserTest , runOAFAnalyserTest_helicopterController_Test)
References runOAFAnalyserTest::HelicopterControlerSettingsIfstream, runOAFAnalyserTest::HelicopterControllerModelIfstream, hybridautomatonParser::hybridautomaton(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), settingsParser::setting(), irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().
TEST_F() [3/3]
TEST_F (runOAFAnalyserTest , runOAFAnalyserTest_fitzHugNagNeuronModel_Test)
References runOAFAnalyserTest::FitzHugNagNeuronModelIfstream, runOAFAnalyserTest::FitzHugNagNeuronModelSettingsIfstream, hybridautomatonParser::hybridautomaton(), irafhy::PLANE, irafhy::HybridAutomaton< Analyser, Verifier >::reachableConditions(), settingsParser::setting(), irafhy::viewer::show(), irafhy::HybridAutomaton< Analyser, Verifier >::simulate(), irafhy::HybridAutomaton< Analyser, Verifier >::timeSequence(), and irafhy::HybridAutomaton< Analyser, Verifier >::variables().