irafhy: definitionParser::AtanhExpContext Class Reference
definitionParser::AtanhExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
AtanhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCTANH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AtanhExpContext()
definitionParser::AtanhExpContext::AtanhExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::AtanhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::AtanhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterAtanhExp().
exitRule()
void definitionParser::AtanhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitAtanhExp().
expression()
definitionParser::ExpressionContext * definitionParser::AtanhExpContext::expression ()
KEY_ARCTANH_FUNCTION()
tree::TerminalNode * definitionParser::AtanhExpContext::KEY_ARCTANH_FUNCTION ()
References definitionParser::KEY_ARCTANH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::AtanhExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::AtanhExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp