irafhy: settingsParser Class Reference
settingsParser Class Reference
#include <settingsParser.h>
Classes
class AcosExpContext
class AcoshExpContext
class AcotExpContext
class AcothExpContext
class AnalysissettingContext
class AsinExpContext
class AsinhExpContext
class AtanExpContext
class AtanhExpContext
class ConditionContext
class ConstantContext
class ConstraintContext
class ConstraintsContext
class CosExpContext
class CoshExpContext
class CotExpContext
class CothExpContext
class ExpAddSubContext
class ExpBraContext
class ExpExpContext
class ExpMulDivContext
class ExpressionContext
class FormulaContext
class GeometrysettingContext
class HpolytopeContext
class InitialconditionsettingContext
struct Initializer
class IntervalContext
class IntervalhullContext
class LnExpContext
class LogExpContext
class MatrixContext
class MaxjumpsettingContext
class NegExpContext
class NexpExpContext
class PlotsettingContext
class PolytopeContext
class PosExpContext
class PowExpContext
class PrintsettingContext
class SettingContext
class SinExpContext
class SinhExpContext
class SqrExpContext
class SqrtExpContext
class StartmodelidsettingContext
class StepSettingContext
class SystemContext
class TanExpContext
class TanhExpContext
class TimeHorizonsettingContext
class VariableContext
class VectorContext
class VpolytopeContext
Public Types
enum {
KEY_LOCATIONS = 1, KEY_MODEL = 2, KEY_FLOWS = 3, KEY_INVARIANT_CONDITIONS = 4,
KEY_SETTINGS = 5, KEY_ANALYSIS = 6, KEY_ANALYSIS_FORWARD = 7, KEY_ANALYSIS_BACKWARD = 8,
KEY_TIME_HORIZON = 9, KEY_STEP = 10, KEY_GEOMETRY = 11, KEY_PLOT_FLAG = 12,
KEY_PRINT_FLAG = 13, KEY_MAX_JUMP = 14, KEY_START_MODEL_ID = 15, KEY_INITIAL_CONDITION = 16,
KEY_TRANSITIONS = 17, KEY_URGENT = 18, KEY_JUMP = 19, KEY_DIRECTION = 20,
KEY_GUARD_CONDITIONS = 21, KEY_RESET_MAP = 22, KEY_INTERVAL_HULL = 23, KEY_POLYTOPE = 24,
KEY_CONDITION = 25, KEY_MATRIX = 26, KEY_ROW_MAJOR_ORDER = 27, KEY_COL_MAJOR_ORDER = 28,
KEY_SIN_FUNCTION = 29, KEY_ARCSIN_FUNCTION = 30, KEY_COS_FUNCTION = 31, KEY_ARCCOS_FUNCTION = 32,
KEY_TAN_FUNCTION = 33, KEY_ARCTAN_FUNCTION = 34, KEY_COT_FUNCTION = 35, KEY_ARCCOT_FUNCTION = 36,
KEY_LN_FUNCTION = 37, KEY_LOG_FUNCTION = 38, KEY_NATURAL_EXP_FUNCTION = 39, KEY_SINH_FUNCTION = 40,
KEY_ARCSINH_FUNCTION = 41, KEY_COSH_FUNCTION = 42, KEY_ARCCOSH_FUNCTION = 43, KEY_TANH_FUNCTION = 44,
KEY_ARCTANH_FUNCTION = 45, KEY_COTH_FUNCTION = 46, KEY_ARCCOTH_FUNCTION = 47, KEY_SQR_FUNCTION = 48,
KEY_SQRT_FUNCTION = 49, KEY_ABS_FUNCTION = 50, KEY_POWER_FUNCTION = 51, KEY_NAME = 52,
KEY_SWITCH_ON = 53, KEY_SWITCH_OFF = 54, KEY_BOOL_TRUE = 55, KEY_BOOL_FALSE = 56,
KEY_INFINITY = 57, SCINUM = 58, NUMBER = 59, VARIABLE = 60,
LEFTCURLYBRACKET = 61, RIGHTCURLYBRACKET = 62, LEFTROUNDBRACKET = 63, RIGHTROUNDBRACKET = 64,
LEFTSQUAREBRACKET = 65, RIGHTSQUAREBRACKET = 66, COMMA = 67, EQUAL = 68,
UNEQUAL = 69, GEQ = 70, LEQ = 71, LSS = 72,
GTR = 73, DEFINE = 74, FROMTO = 75, ASSIGN = 76,
PLUS = 77, MINUS = 78, MULTIPLY = 79, DIVIDE = 80,
EXPONENT = 81, DERIVATIVE = 82, COMMENT = 83, WS = 84
}
enum {
RuleTimeHorizonsetting = 0, RuleStepSetting = 1, RuleGeometrysetting = 2, RulePlotsetting = 3,
RulePrintsetting = 4, RuleAnalysissetting = 5, RuleMaxjumpsetting = 6, RuleStartmodelidsetting = 7,
RuleInitialconditionsetting = 8, RuleSetting = 9, RuleCondition = 10, RulePolytope = 11,
RuleHpolytope = 12, RuleVpolytope = 13, RuleMatrix = 14, RuleVector = 15,
RuleIntervalhull = 16, RuleConstraints = 17, RuleConstraint = 18, RuleSystem = 19,
RuleFormula = 20, RuleInterval = 21, RuleExpression = 22
}
Public Member Functions
settingsParser (antlr4::TokenStream *input)
~settingsParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
TimeHorizonsettingContext * timeHorizonsetting ()
StepSettingContext * stepSetting ()
GeometrysettingContext * geometrysetting ()
PlotsettingContext * plotsetting ()
PrintsettingContext * printsetting ()
AnalysissettingContext * analysissetting ()
MaxjumpsettingContext * maxjumpsetting ()
StartmodelidsettingContext * startmodelidsetting ()
InitialconditionsettingContext * initialconditionsetting ()
SettingContext * setting ()
ConditionContext * condition ()
PolytopeContext * polytope ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
MatrixContext * matrix ()
VectorContext * vector ()
IntervalhullContext * intervalhull ()
ConstraintsContext * constraints ()
ConstraintContext * constraint ()
SystemContext * system ()
FormulaContext * formula ()
IntervalContext * interval ()
ExpressionContext * expression ()
ExpressionContext * expression (int precedence)
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool expressionSempred (ExpressionContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEY_LOCATIONS
KEY_MODEL
KEY_FLOWS
KEY_INVARIANT_CONDITIONS
KEY_SETTINGS
KEY_ANALYSIS
KEY_ANALYSIS_FORWARD
KEY_ANALYSIS_BACKWARD
KEY_TIME_HORIZON
KEY_STEP
KEY_GEOMETRY
KEY_PLOT_FLAG
KEY_PRINT_FLAG
KEY_MAX_JUMP
KEY_START_MODEL_ID
KEY_INITIAL_CONDITION
KEY_TRANSITIONS
KEY_URGENT
KEY_JUMP
KEY_DIRECTION
KEY_GUARD_CONDITIONS
KEY_RESET_MAP
KEY_INTERVAL_HULL
KEY_POLYTOPE
KEY_CONDITION
KEY_MATRIX
KEY_ROW_MAJOR_ORDER
KEY_COL_MAJOR_ORDER
KEY_SIN_FUNCTION
KEY_ARCSIN_FUNCTION
KEY_COS_FUNCTION
KEY_ARCCOS_FUNCTION
KEY_TAN_FUNCTION
KEY_ARCTAN_FUNCTION
KEY_COT_FUNCTION
KEY_ARCCOT_FUNCTION
KEY_LN_FUNCTION
KEY_LOG_FUNCTION
KEY_NATURAL_EXP_FUNCTION
KEY_SINH_FUNCTION
KEY_ARCSINH_FUNCTION
KEY_COSH_FUNCTION
KEY_ARCCOSH_FUNCTION
KEY_TANH_FUNCTION
KEY_ARCTANH_FUNCTION
KEY_COTH_FUNCTION
KEY_ARCCOTH_FUNCTION
KEY_SQR_FUNCTION
KEY_SQRT_FUNCTION
KEY_ABS_FUNCTION
KEY_POWER_FUNCTION
KEY_NAME
KEY_SWITCH_ON
KEY_SWITCH_OFF
KEY_BOOL_TRUE
KEY_BOOL_FALSE
KEY_INFINITY
SCINUM
NUMBER
VARIABLE
LEFTCURLYBRACKET
RIGHTCURLYBRACKET
LEFTROUNDBRACKET
RIGHTROUNDBRACKET
LEFTSQUAREBRACKET
RIGHTSQUAREBRACKET
COMMA
EQUAL
UNEQUAL
GEQ
LEQ
LSS
GTR
DEFINE
FROMTO
ASSIGN
PLUS
MINUS
MULTIPLY
DIVIDE
EXPONENT
DERIVATIVE
COMMENT
WS
anonymous enum
anonymous enum
Enumerator
RuleTimeHorizonsetting
RuleStepSetting
RuleGeometrysetting
RulePlotsetting
RulePrintsetting
RuleAnalysissetting
RuleMaxjumpsetting
RuleStartmodelidsetting
RuleInitialconditionsetting
RuleSetting
RuleCondition
RulePolytope
RuleHpolytope
RuleVpolytope
RuleMatrix
RuleVector
RuleIntervalhull
RuleConstraints
RuleConstraint
RuleSystem
RuleFormula
RuleInterval
RuleExpression
Constructor & Destructor Documentation
settingsParser()
settingsParser::settingsParser (antlr4::TokenStream * input)
References _atn, _decisionToDFA, and _sharedContextCache.
~settingsParser()
settingsParser::~settingsParser ()
Member Function Documentation
analysissetting()
settingsParser::AnalysissettingContext * settingsParser::analysissetting ()
References settingsParser::AnalysissettingContext::ANALYSIS, DEFINE, settingsParser::AnalysissettingContext::enterRule(), settingsParser::AnalysissettingContext::exitRule(), KEY_ANALYSIS, KEY_ANALYSIS_BACKWARD, KEY_ANALYSIS_FORWARD, and RuleAnalysissetting.
condition()
settingsParser::ConditionContext * settingsParser::condition ()
References settingsParser::ConditionContext::enterRule(), settingsParser::ConditionContext::exitRule(), settingsParser::ConditionContext::intervalhull(), KEY_CONDITION, KEY_INTERVAL_HULL, KEY_POLYTOPE, LEFTCURLYBRACKET, settingsParser::ConditionContext::polytope(), RIGHTCURLYBRACKET, and RuleCondition.
constraint()
settingsParser::ConstraintContext * settingsParser::constraint ()
References settingsParser::ConstraintContext::enterRule(), EQUAL, settingsParser::ConstraintContext::exitRule(), settingsParser::ConstraintContext::expression(), GEQ, GTR, LEQ, LSS, settingsParser::ConstraintContext::RELATION, RuleConstraint, and UNEQUAL.
constraints()
settingsParser::ConstraintsContext * settingsParser::constraints ()
References settingsParser::ConstraintsContext::constraint(), settingsParser::ConstraintsContext::enterRule(), settingsParser::ConstraintsContext::exitRule(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, NUMBER, PLUS, RuleConstraints, SCINUM, and VARIABLE.
expression() [1/2]
settingsParser::ExpressionContext * settingsParser::expression ()
Referenced by expression().
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::expression (int precedence)
References COMMA, DIVIDE, EXPONENT, expression(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, MULTIPLY, NUMBER, PLUS, RIGHTROUNDBRACKET, RuleExpression, SCINUM, and VARIABLE.
expressionSempred()
bool settingsParser::expressionSempred (ExpressionContext * _localctx, size_t predicateIndex)
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, and _vocabulary.
Referenced by sempred().
formula()
settingsParser::FormulaContext * settingsParser::formula ()
References ASSIGN, DERIVATIVE, settingsParser::FormulaContext::enterRule(), settingsParser::FormulaContext::exitRule(), settingsParser::FormulaContext::expression(), settingsParser::FormulaContext::interval(), LEFTSQUAREBRACKET, RuleFormula, and VARIABLE.
geometrysetting()
settingsParser::GeometrysettingContext * settingsParser::geometrysetting ()
References DEFINE, settingsParser::GeometrysettingContext::enterRule(), settingsParser::GeometrysettingContext::exitRule(), KEY_GEOMETRY, KEY_INTERVAL_HULL, KEY_POLYTOPE, RuleGeometrysetting, and settingsParser::GeometrysettingContext::VALUE.
getATN()
virtual const antlr4::atn::ATN& settingsParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string settingsParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & settingsParser::getRuleNames () const override virtual
References _ruleNames.
Referenced by getTokenNames().
getTokenNames()
virtual const std::vector<std::string>& settingsParser::getTokenNames () const inline override virtual
References _tokenNames, getRuleNames(), and getVocabulary().
getVocabulary()
dfa::Vocabulary & settingsParser::getVocabulary () const override virtual
References _vocabulary.
Referenced by getTokenNames().
hpolytope()
settingsParser::HpolytopeContext * settingsParser::hpolytope ()
References settingsParser::HpolytopeContext::enterRule(), settingsParser::HpolytopeContext::exitRule(), LEFTCURLYBRACKET, settingsParser::HpolytopeContext::matrix(), RIGHTCURLYBRACKET, RuleHpolytope, and settingsParser::HpolytopeContext::vector().
initialconditionsetting()
settingsParser::InitialconditionsettingContext * settingsParser::initialconditionsetting ()
References settingsParser::InitialconditionsettingContext::condition(), DEFINE, settingsParser::InitialconditionsettingContext::enterRule(), settingsParser::InitialconditionsettingContext::exitRule(), KEY_INITIAL_CONDITION, and RuleInitialconditionsetting.
interval()
settingsParser::IntervalContext * settingsParser::interval ()
References settingsParser::IntervalContext::_tset251, settingsParser::IntervalContext::_tset264, settingsParser::IntervalContext::_tset284, settingsParser::IntervalContext::_tset297, COMMA, settingsParser::IntervalContext::enterRule(), settingsParser::IntervalContext::exitRule(), KEY_INFINITY, LEFTSQUAREBRACKET, MINUS, NUMBER, settingsParser::IntervalContext::OP, PLUS, RIGHTSQUAREBRACKET, RuleInterval, SCINUM, and settingsParser::IntervalContext::VAL.
intervalhull()
settingsParser::IntervalhullContext * settingsParser::intervalhull ()
References COMMA, settingsParser::IntervalhullContext::enterRule(), settingsParser::IntervalhullContext::exitRule(), settingsParser::IntervalhullContext::interval(), KEY_INTERVAL_HULL, LEFTCURLYBRACKET, LEFTSQUAREBRACKET, RIGHTCURLYBRACKET, and RuleIntervalhull.
matrix()
settingsParser::MatrixContext * settingsParser::matrix ()
References COMMA, settingsParser::MatrixContext::enterRule(), settingsParser::MatrixContext::exitRule(), KEY_COL_MAJOR_ORDER, KEY_MATRIX, KEY_ROW_MAJOR_ORDER, LEFTCURLYBRACKET, LEFTROUNDBRACKET, settingsParser::MatrixContext::MAJOR_ORDER, RIGHTCURLYBRACKET, RuleMatrix, and settingsParser::MatrixContext::vector().
maxjumpsetting()
settingsParser::MaxjumpsettingContext * settingsParser::maxjumpsetting ()
References DEFINE, settingsParser::MaxjumpsettingContext::enterRule(), settingsParser::MaxjumpsettingContext::exitRule(), KEY_MAX_JUMP, NUMBER, and RuleMaxjumpsetting.
plotsetting()
settingsParser::PlotsettingContext * settingsParser::plotsetting ()
References DEFINE, settingsParser::PlotsettingContext::enterRule(), settingsParser::PlotsettingContext::exitRule(), KEY_PLOT_FLAG, KEY_SWITCH_OFF, KEY_SWITCH_ON, RulePlotsetting, and settingsParser::PlotsettingContext::SWITCH.
polytope()
settingsParser::PolytopeContext * settingsParser::polytope ()
References settingsParser::PolytopeContext::enterRule(), settingsParser::PolytopeContext::exitRule(), settingsParser::PolytopeContext::hpolytope(), KEY_POLYTOPE, RulePolytope, and settingsParser::PolytopeContext::vpolytope().
printsetting()
settingsParser::PrintsettingContext * settingsParser::printsetting ()
References DEFINE, settingsParser::PrintsettingContext::enterRule(), settingsParser::PrintsettingContext::exitRule(), KEY_PRINT_FLAG, KEY_SWITCH_OFF, KEY_SWITCH_ON, RulePrintsetting, and settingsParser::PrintsettingContext::SWITCH.
sempred()
bool settingsParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References expressionSempred().
setting()
settingsParser::SettingContext * settingsParser::setting ()
References settingsParser::SettingContext::analysissetting(), settingsParser::SettingContext::enterRule(), settingsParser::SettingContext::exitRule(), settingsParser::SettingContext::geometrysetting(), settingsParser::SettingContext::initialconditionsetting(), KEY_ANALYSIS, KEY_GEOMETRY, KEY_INITIAL_CONDITION, KEY_MAX_JUMP, KEY_PLOT_FLAG, KEY_PRINT_FLAG, KEY_SETTINGS, KEY_START_MODEL_ID, KEY_STEP, KEY_TIME_HORIZON, LEFTCURLYBRACKET, settingsParser::SettingContext::maxjumpsetting(), settingsParser::SettingContext::plotsetting(), settingsParser::SettingContext::printsetting(), RIGHTCURLYBRACKET, RuleSetting, settingsParser::SettingContext::startmodelidsetting(), settingsParser::SettingContext::stepSetting(), and settingsParser::SettingContext::timeHorizonsetting().
Referenced by irafhy::SettingsParser::parse().
startmodelidsetting()
settingsParser::StartmodelidsettingContext * settingsParser::startmodelidsetting ()
References DEFINE, settingsParser::StartmodelidsettingContext::enterRule(), settingsParser::StartmodelidsettingContext::exitRule(), KEY_START_MODEL_ID, RuleStartmodelidsetting, and VARIABLE.
stepSetting()
settingsParser::StepSettingContext * settingsParser::stepSetting ()
References DEFINE, settingsParser::StepSettingContext::enterRule(), settingsParser::StepSettingContext::exitRule(), KEY_STEP, NUMBER, and RuleStepSetting.
system()
settingsParser::SystemContext * settingsParser::system ()
References settingsParser::SystemContext::enterRule(), settingsParser::SystemContext::exitRule(), settingsParser::SystemContext::formula(), RuleSystem, and VARIABLE.
timeHorizonsetting()
settingsParser::TimeHorizonsettingContext * settingsParser::timeHorizonsetting ()
References DEFINE, settingsParser::TimeHorizonsettingContext::enterRule(), settingsParser::TimeHorizonsettingContext::exitRule(), settingsParser::TimeHorizonsettingContext::interval(), KEY_TIME_HORIZON, and RuleTimeHorizonsetting.
vector()
settingsParser::VectorContext * settingsParser::vector ()
References settingsParser::VectorContext::_tset115, settingsParser::VectorContext::_tset135, COMMA, settingsParser::VectorContext::enterRule(), settingsParser::VectorContext::exitRule(), LEFTROUNDBRACKET, MINUS, NUMBER, settingsParser::VectorContext::OP, PLUS, RIGHTROUNDBRACKET, and RuleVector.
vpolytope()
settingsParser::VpolytopeContext * settingsParser::vpolytope ()
References COMMA, settingsParser::VpolytopeContext::enterRule(), settingsParser::VpolytopeContext::exitRule(), LEFTCURLYBRACKET, LEFTROUNDBRACKET, RIGHTCURLYBRACKET, RuleVpolytope, and settingsParser::VpolytopeContext::vector().
Member Data Documentation
_atn
atn::ATN settingsParser::_atn static private
Referenced by expressionSempred(), getATN(), settingsParser::Initializer::Initializer(), and settingsParser().
_decisionToDFA
std::vector< dfa::DFA > settingsParser::_decisionToDFA static private
Referenced by expressionSempred(), settingsParser::Initializer::Initializer(), and settingsParser().
_init
settingsParser::Initializer settingsParser::_init static private
Referenced by settingsParser::Initializer::Initializer().
_literalNames
std::vector< std::string > settingsParser::_literalNames static private
Initial value:
= {
  "", "'LOCATIONS'", "'MODEL'", "'FLOWS'", "'INVARIANT_CONDITIONS'", "'SETTINGS'",
  "'ANALYSIS'", "'FORWARD'", "'BACKWARD'", "'TIME_HORIZON'", "'STEP'", "'GEOMETRY'",
  "'PLOT'", "'PRINT'", "'MAX_JUMP'", "'START_MODEL_ID'", "'INITIAL_CONDITION'",
  "'TRANSITIONS'", "'URGENT'", "'JUMP'", "'DIRECTION'", "'GUARD_CONDITIONS'",
  "'RESET_MAP'", "'INTERVAL_HULL'", "'POLYTOPE'", "'CONDITION'", "'MATRIX'",
  "'ROW_MAJOR'", "'COL_MAJOR'", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "'NAME'", "'ON'",
  "'OFF'", "'TRUE'", "'FALSE'", "", "", "", "", "'{'", "'}'", "'('", "')'",
  "'['", "']'", "','", "'=='", "'!='", "'>='", "'<='", "'<'", "'>'", "':='",
  "", "'='", "'+'", "'-'", "'*'", "'/'", "'^'", "'''"
}
Referenced by expressionSempred().
_ruleNames
std::vector< std::string > settingsParser::_ruleNames static private
Initial value:
= {
  "timeHorizonsetting", "stepSetting", "geometrysetting", "plotsetting",
  "printsetting", "analysissetting", "maxjumpsetting", "startmodelidsetting",
  "initialconditionsetting", "setting", "condition", "polytope", "hpolytope",
  "vpolytope", "matrix", "vector", "intervalhull", "constraints", "constraint",
  "system", "formula", "interval", "expression"
}
Referenced by expressionSempred(), and getRuleNames().
_serializedATN
std::vector< uint16_t > settingsParser::_serializedATN static private
Referenced by expressionSempred(), and settingsParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache settingsParser::_sharedContextCache static private
Referenced by expressionSempred(), and settingsParser().
_symbolicNames
std::vector< std::string > settingsParser::_symbolicNames static private
Initial value:
= {
  "", "KEY_LOCATIONS", "KEY_MODEL", "KEY_FLOWS", "KEY_INVARIANT_CONDITIONS",
  "KEY_SETTINGS", "KEY_ANALYSIS", "KEY_ANALYSIS_FORWARD", "KEY_ANALYSIS_BACKWARD",
  "KEY_TIME_HORIZON", "KEY_STEP", "KEY_GEOMETRY", "KEY_PLOT_FLAG", "KEY_PRINT_FLAG",
  "KEY_MAX_JUMP", "KEY_START_MODEL_ID", "KEY_INITIAL_CONDITION", "KEY_TRANSITIONS",
  "KEY_URGENT", "KEY_JUMP", "KEY_DIRECTION", "KEY_GUARD_CONDITIONS", "KEY_RESET_MAP",
  "KEY_INTERVAL_HULL", "KEY_POLYTOPE", "KEY_CONDITION", "KEY_MATRIX", "KEY_ROW_MAJOR_ORDER",
  "KEY_COL_MAJOR_ORDER", "KEY_SIN_FUNCTION", "KEY_ARCSIN_FUNCTION", "KEY_COS_FUNCTION",
  "KEY_ARCCOS_FUNCTION", "KEY_TAN_FUNCTION", "KEY_ARCTAN_FUNCTION", "KEY_COT_FUNCTION",
  "KEY_ARCCOT_FUNCTION", "KEY_LN_FUNCTION", "KEY_LOG_FUNCTION", "KEY_NATURAL_EXP_FUNCTION",
  "KEY_SINH_FUNCTION", "KEY_ARCSINH_FUNCTION", "KEY_COSH_FUNCTION", "KEY_ARCCOSH_FUNCTION",
  "KEY_TANH_FUNCTION", "KEY_ARCTANH_FUNCTION", "KEY_COTH_FUNCTION", "KEY_ARCCOTH_FUNCTION",
  "KEY_SQR_FUNCTION", "KEY_SQRT_FUNCTION", "KEY_ABS_FUNCTION", "KEY_POWER_FUNCTION",
  "KEY_NAME", "KEY_SWITCH_ON", "KEY_SWITCH_OFF", "KEY_BOOL_TRUE", "KEY_BOOL_FALSE",
  "KEY_INFINITY", "SCINUM", "NUMBER", "VARIABLE", "LEFTCURLYBRACKET", "RIGHTCURLYBRACKET",
  "LEFTROUNDBRACKET", "RIGHTROUNDBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET",
  "COMMA", "EQUAL", "UNEQUAL", "GEQ", "LEQ", "LSS", "GTR", "DEFINE", "FROMTO",
  "ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", "DERIVATIVE",
  "COMMENT", "WS"
}
Referenced by expressionSempred(), and settingsParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > settingsParser::_tokenNames static private
Referenced by expressionSempred(), getTokenNames(), and settingsParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary settingsParser::_vocabulary static private
Referenced by expressionSempred(), getVocabulary(), and settingsParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp