irafhy: definitionParser::CotExpContext Class Reference
definitionParser::CotExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
CotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CotExpContext()
definitionParser::CotExpContext::CotExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::CotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::CotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterCotExp().
exitRule()
void definitionParser::CotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitCotExp().
expression()
definitionParser::ExpressionContext * definitionParser::CotExpContext::expression ()
KEY_COT_FUNCTION()
tree::TerminalNode * definitionParser::CotExpContext::KEY_COT_FUNCTION ()
References definitionParser::KEY_COT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::CotExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::CotExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp