irafhy: hybridautomatonParser::AcosExpContext Class Reference
hybridautomatonParser::AcosExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
AcosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcosExpContext()
hybridautomatonParser::AcosExpContext::AcosExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::AcosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::AcosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterAcosExp().
exitRule()
void hybridautomatonParser::AcosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitAcosExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::AcosExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitAcosExp().
KEY_ARCCOS_FUNCTION()
tree::TerminalNode * hybridautomatonParser::AcosExpContext::KEY_ARCCOS_FUNCTION ()
References hybridautomatonParser::KEY_ARCCOS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AcosExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AcosExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp