irafhy: transitionsParser::AcotExpContext Class Reference
transitionsParser::AcotExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
AcotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcotExpContext()
transitionsParser::AcotExpContext::AcotExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::AcotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::AcotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterAcotExp().
exitRule()
void transitionsParser::AcotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitAcotExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::AcotExpContext::expression ()
KEY_ARCCOT_FUNCTION()
tree::TerminalNode * transitionsParser::AcotExpContext::KEY_ARCCOT_FUNCTION ()
References transitionsParser::KEY_ARCCOT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcotExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcotExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp