irafhy: settingsParser::CosExpContext Class Reference
settingsParser::CosExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
CosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CosExpContext()
settingsParser::CosExpContext::CosExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::CosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::CosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterCosExp().
exitRule()
void settingsParser::CosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitCosExp().
expression()
settingsParser::ExpressionContext * settingsParser::CosExpContext::expression ()
KEY_COS_FUNCTION()
tree::TerminalNode * settingsParser::CosExpContext::KEY_COS_FUNCTION ()
References settingsParser::KEY_COS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::CosExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::CosExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp