irafhy: definitionParser Class Reference
definitionParser Class Reference
#include <definitionParser.h>
Classes
class AcosExpContext
class AcoshExpContext
class AcotExpContext
class AcothExpContext
class AsinExpContext
class AsinhExpContext
class AtanExpContext
class AtanhExpContext
class ConditionContext
class ConstantContext
class ConstraintContext
class ConstraintsContext
class CosExpContext
class CoshExpContext
class CotExpContext
class CothExpContext
class ExpAddSubContext
class ExpBraContext
class ExpExpContext
class ExpMulDivContext
class ExpressionContext
class FormulaContext
class HpolytopeContext
struct Initializer
class IntervalContext
class IntervalhullContext
class LnExpContext
class LogExpContext
class MatrixContext
class NegExpContext
class NexpExpContext
class PolytopeContext
class PosExpContext
class PowExpContext
class SinExpContext
class SinhExpContext
class SqrExpContext
class SqrtExpContext
class SystemContext
class TanExpContext
class TanhExpContext
class VariableContext
class VectorContext
class VpolytopeContext
Public Types
enum {
KEY_LOCATIONS = 1, KEY_MODEL = 2, KEY_FLOWS = 3, KEY_INVARIANT_CONDITIONS = 4,
KEY_SETTINGS = 5, KEY_ANALYSIS = 6, KEY_ANALYSIS_FORWARD = 7, KEY_ANALYSIS_BACKWARD = 8,
KEY_TIME_HORIZON = 9, KEY_STEP = 10, KEY_GEOMETRY = 11, KEY_PLOT_FLAG = 12,
KEY_PRINT_FLAG = 13, KEY_MAX_JUMP = 14, KEY_START_MODEL_ID = 15, KEY_INITIAL_CONDITION = 16,
KEY_TRANSITIONS = 17, KEY_URGENT = 18, KEY_JUMP = 19, KEY_DIRECTION = 20,
KEY_GUARD_CONDITIONS = 21, KEY_RESET_MAP = 22, KEY_INTERVAL_HULL = 23, KEY_POLYTOPE = 24,
KEY_CONDITION = 25, KEY_MATRIX = 26, KEY_ROW_MAJOR_ORDER = 27, KEY_COL_MAJOR_ORDER = 28,
KEY_SIN_FUNCTION = 29, KEY_ARCSIN_FUNCTION = 30, KEY_COS_FUNCTION = 31, KEY_ARCCOS_FUNCTION = 32,
KEY_TAN_FUNCTION = 33, KEY_ARCTAN_FUNCTION = 34, KEY_COT_FUNCTION = 35, KEY_ARCCOT_FUNCTION = 36,
KEY_LN_FUNCTION = 37, KEY_LOG_FUNCTION = 38, KEY_NATURAL_EXP_FUNCTION = 39, KEY_SINH_FUNCTION = 40,
KEY_ARCSINH_FUNCTION = 41, KEY_COSH_FUNCTION = 42, KEY_ARCCOSH_FUNCTION = 43, KEY_TANH_FUNCTION = 44,
KEY_ARCTANH_FUNCTION = 45, KEY_COTH_FUNCTION = 46, KEY_ARCCOTH_FUNCTION = 47, KEY_SQR_FUNCTION = 48,
KEY_SQRT_FUNCTION = 49, KEY_ABS_FUNCTION = 50, KEY_POWER_FUNCTION = 51, KEY_NAME = 52,
KEY_SWITCH_ON = 53, KEY_SWITCH_OFF = 54, KEY_BOOL_TRUE = 55, KEY_BOOL_FALSE = 56,
KEY_INFINITY = 57, SCINUM = 58, NUMBER = 59, VARIABLE = 60,
LEFTCURLYBRACKET = 61, RIGHTCURLYBRACKET = 62, LEFTROUNDBRACKET = 63, RIGHTROUNDBRACKET = 64,
LEFTSQUAREBRACKET = 65, RIGHTSQUAREBRACKET = 66, COMMA = 67, EQUAL = 68,
UNEQUAL = 69, GEQ = 70, LEQ = 71, LSS = 72,
GTR = 73, DEFINE = 74, FROMTO = 75, ASSIGN = 76,
PLUS = 77, MINUS = 78, MULTIPLY = 79, DIVIDE = 80,
EXPONENT = 81, DERIVATIVE = 82, COMMENT = 83, WS = 84
}
enum {
RuleCondition = 0, RulePolytope = 1, RuleHpolytope = 2, RuleVpolytope = 3,
RuleMatrix = 4, RuleVector = 5, RuleIntervalhull = 6, RuleConstraints = 7,
RuleConstraint = 8, RuleSystem = 9, RuleFormula = 10, RuleInterval = 11,
RuleExpression = 12
}
Public Member Functions
definitionParser (antlr4::TokenStream *input)
~definitionParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
ConditionContext * condition ()
PolytopeContext * polytope ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
MatrixContext * matrix ()
VectorContext * vector ()
IntervalhullContext * intervalhull ()
ConstraintsContext * constraints ()
ConstraintContext * constraint ()
SystemContext * system ()
FormulaContext * formula ()
IntervalContext * interval ()
ExpressionContext * expression ()
ExpressionContext * expression (int precedence)
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool expressionSempred (ExpressionContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEY_LOCATIONS
KEY_MODEL
KEY_FLOWS
KEY_INVARIANT_CONDITIONS
KEY_SETTINGS
KEY_ANALYSIS
KEY_ANALYSIS_FORWARD
KEY_ANALYSIS_BACKWARD
KEY_TIME_HORIZON
KEY_STEP
KEY_GEOMETRY
KEY_PLOT_FLAG
KEY_PRINT_FLAG
KEY_MAX_JUMP
KEY_START_MODEL_ID
KEY_INITIAL_CONDITION
KEY_TRANSITIONS
KEY_URGENT
KEY_JUMP
KEY_DIRECTION
KEY_GUARD_CONDITIONS
KEY_RESET_MAP
KEY_INTERVAL_HULL
KEY_POLYTOPE
KEY_CONDITION
KEY_MATRIX
KEY_ROW_MAJOR_ORDER
KEY_COL_MAJOR_ORDER
KEY_SIN_FUNCTION
KEY_ARCSIN_FUNCTION
KEY_COS_FUNCTION
KEY_ARCCOS_FUNCTION
KEY_TAN_FUNCTION
KEY_ARCTAN_FUNCTION
KEY_COT_FUNCTION
KEY_ARCCOT_FUNCTION
KEY_LN_FUNCTION
KEY_LOG_FUNCTION
KEY_NATURAL_EXP_FUNCTION
KEY_SINH_FUNCTION
KEY_ARCSINH_FUNCTION
KEY_COSH_FUNCTION
KEY_ARCCOSH_FUNCTION
KEY_TANH_FUNCTION
KEY_ARCTANH_FUNCTION
KEY_COTH_FUNCTION
KEY_ARCCOTH_FUNCTION
KEY_SQR_FUNCTION
KEY_SQRT_FUNCTION
KEY_ABS_FUNCTION
KEY_POWER_FUNCTION
KEY_NAME
KEY_SWITCH_ON
KEY_SWITCH_OFF
KEY_BOOL_TRUE
KEY_BOOL_FALSE
KEY_INFINITY
SCINUM
NUMBER
VARIABLE
LEFTCURLYBRACKET
RIGHTCURLYBRACKET
LEFTROUNDBRACKET
RIGHTROUNDBRACKET
LEFTSQUAREBRACKET
RIGHTSQUAREBRACKET
COMMA
EQUAL
UNEQUAL
GEQ
LEQ
LSS
GTR
DEFINE
FROMTO
ASSIGN
PLUS
MINUS
MULTIPLY
DIVIDE
EXPONENT
DERIVATIVE
COMMENT
WS
anonymous enum
anonymous enum
Enumerator
RuleCondition
RulePolytope
RuleHpolytope
RuleVpolytope
RuleMatrix
RuleVector
RuleIntervalhull
RuleConstraints
RuleConstraint
RuleSystem
RuleFormula
RuleInterval
RuleExpression
Constructor & Destructor Documentation
definitionParser()
definitionParser::definitionParser (antlr4::TokenStream * input)
References _atn, _decisionToDFA, and _sharedContextCache.
~definitionParser()
definitionParser::~definitionParser ()
Member Function Documentation
condition()
definitionParser::ConditionContext * definitionParser::condition ()
References definitionParser::ConditionContext::enterRule(), definitionParser::ConditionContext::exitRule(), definitionParser::ConditionContext::intervalhull(), KEY_CONDITION, KEY_INTERVAL_HULL, KEY_POLYTOPE, LEFTCURLYBRACKET, definitionParser::ConditionContext::polytope(), RIGHTCURLYBRACKET, and RuleCondition.
constraint()
definitionParser::ConstraintContext * definitionParser::constraint ()
References definitionParser::ConstraintContext::enterRule(), EQUAL, definitionParser::ConstraintContext::exitRule(), definitionParser::ConstraintContext::expression(), GEQ, GTR, LEQ, LSS, definitionParser::ConstraintContext::RELATION, RuleConstraint, and UNEQUAL.
constraints()
definitionParser::ConstraintsContext * definitionParser::constraints ()
References definitionParser::ConstraintsContext::constraint(), definitionParser::ConstraintsContext::enterRule(), definitionParser::ConstraintsContext::exitRule(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, NUMBER, PLUS, RuleConstraints, SCINUM, and VARIABLE.
expression() [1/2]
definitionParser::ExpressionContext * definitionParser::expression ()
Referenced by expression().
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::expression (int precedence)
References COMMA, DIVIDE, EXPONENT, expression(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, MULTIPLY, NUMBER, PLUS, RIGHTROUNDBRACKET, RuleExpression, SCINUM, and VARIABLE.
expressionSempred()
bool definitionParser::expressionSempred (ExpressionContext * _localctx, size_t predicateIndex)
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, and _vocabulary.
Referenced by sempred().
formula()
definitionParser::FormulaContext * definitionParser::formula ()
References ASSIGN, DERIVATIVE, definitionParser::FormulaContext::enterRule(), definitionParser::FormulaContext::exitRule(), definitionParser::FormulaContext::expression(), definitionParser::FormulaContext::interval(), LEFTSQUAREBRACKET, RuleFormula, and VARIABLE.
getATN()
virtual const antlr4::atn::ATN& definitionParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string definitionParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & definitionParser::getRuleNames () const override virtual
References _ruleNames.
Referenced by getTokenNames().
getTokenNames()
virtual const std::vector<std::string>& definitionParser::getTokenNames () const inline override virtual
References _tokenNames, getRuleNames(), and getVocabulary().
getVocabulary()
dfa::Vocabulary & definitionParser::getVocabulary () const override virtual
References _vocabulary.
Referenced by getTokenNames().
hpolytope()
definitionParser::HpolytopeContext * definitionParser::hpolytope ()
References definitionParser::HpolytopeContext::enterRule(), definitionParser::HpolytopeContext::exitRule(), LEFTCURLYBRACKET, definitionParser::HpolytopeContext::matrix(), RIGHTCURLYBRACKET, RuleHpolytope, and definitionParser::HpolytopeContext::vector().
interval()
definitionParser::IntervalContext * definitionParser::interval ()
References definitionParser::IntervalContext::_tset251, definitionParser::IntervalContext::_tset264, definitionParser::IntervalContext::_tset284, definitionParser::IntervalContext::_tset297, COMMA, definitionParser::IntervalContext::enterRule(), definitionParser::IntervalContext::exitRule(), KEY_INFINITY, LEFTSQUAREBRACKET, MINUS, NUMBER, definitionParser::IntervalContext::OP, PLUS, RIGHTSQUAREBRACKET, RuleInterval, SCINUM, and definitionParser::IntervalContext::VAL.
intervalhull()
definitionParser::IntervalhullContext * definitionParser::intervalhull ()
References COMMA, definitionParser::IntervalhullContext::enterRule(), definitionParser::IntervalhullContext::exitRule(), definitionParser::IntervalhullContext::interval(), KEY_INTERVAL_HULL, LEFTCURLYBRACKET, LEFTSQUAREBRACKET, RIGHTCURLYBRACKET, and RuleIntervalhull.
matrix()
definitionParser::MatrixContext * definitionParser::matrix ()
References COMMA, definitionParser::MatrixContext::enterRule(), definitionParser::MatrixContext::exitRule(), KEY_COL_MAJOR_ORDER, KEY_MATRIX, KEY_ROW_MAJOR_ORDER, LEFTCURLYBRACKET, LEFTROUNDBRACKET, definitionParser::MatrixContext::MAJOR_ORDER, RIGHTCURLYBRACKET, RuleMatrix, and definitionParser::MatrixContext::vector().
polytope()
definitionParser::PolytopeContext * definitionParser::polytope ()
References definitionParser::PolytopeContext::enterRule(), definitionParser::PolytopeContext::exitRule(), definitionParser::PolytopeContext::hpolytope(), KEY_POLYTOPE, RulePolytope, and definitionParser::PolytopeContext::vpolytope().
sempred()
bool definitionParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References expressionSempred().
system()
definitionParser::SystemContext * definitionParser::system ()
References definitionParser::SystemContext::enterRule(), definitionParser::SystemContext::exitRule(), definitionParser::SystemContext::formula(), RuleSystem, and VARIABLE.
vector()
definitionParser::VectorContext * definitionParser::vector ()
References definitionParser::VectorContext::_tset115, definitionParser::VectorContext::_tset135, COMMA, definitionParser::VectorContext::enterRule(), definitionParser::VectorContext::exitRule(), LEFTROUNDBRACKET, MINUS, NUMBER, definitionParser::VectorContext::OP, PLUS, RIGHTROUNDBRACKET, and RuleVector.
vpolytope()
definitionParser::VpolytopeContext * definitionParser::vpolytope ()
References COMMA, definitionParser::VpolytopeContext::enterRule(), definitionParser::VpolytopeContext::exitRule(), LEFTCURLYBRACKET, LEFTROUNDBRACKET, RIGHTCURLYBRACKET, RuleVpolytope, and definitionParser::VpolytopeContext::vector().
Member Data Documentation
_atn
atn::ATN definitionParser::_atn static private
Referenced by definitionParser(), expressionSempred(), getATN(), and definitionParser::Initializer::Initializer().
_decisionToDFA
std::vector< dfa::DFA > definitionParser::_decisionToDFA static private
Referenced by definitionParser(), expressionSempred(), and definitionParser::Initializer::Initializer().
_init
definitionParser::Initializer definitionParser::_init static private
Referenced by definitionParser::Initializer::Initializer().
_literalNames
std::vector< std::string > definitionParser::_literalNames static private
Initial value:
= {
  "", "'LOCATIONS'", "'MODEL'", "'FLOWS'", "'INVARIANT_CONDITIONS'", "'SETTINGS'",
  "'ANALYSIS'", "'FORWARD'", "'BACKWARD'", "'TIME_HORIZON'", "'STEP'", "'GEOMETRY'",
  "'PLOT'", "'PRINT'", "'MAX_JUMP'", "'START_MODEL_ID'", "'INITIAL_CONDITION'",
  "'TRANSITIONS'", "'URGENT'", "'JUMP'", "'DIRECTION'", "'GUARD_CONDITIONS'",
  "'RESET_MAP'", "'INTERVAL_HULL'", "'POLYTOPE'", "'CONDITION'", "'MATRIX'",
  "'ROW_MAJOR'", "'COL_MAJOR'", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "'NAME'", "'ON'",
  "'OFF'", "'TRUE'", "'FALSE'", "", "", "", "", "'{'", "'}'", "'('", "')'",
  "'['", "']'", "','", "'=='", "'!='", "'>='", "'<='", "'<'", "'>'", "':='",
  "", "'='", "'+'", "'-'", "'*'", "'/'", "'^'", "'''"
}
Referenced by expressionSempred().
_ruleNames
std::vector< std::string > definitionParser::_ruleNames static private
Initial value:
= {
  "condition", "polytope", "hpolytope", "vpolytope", "matrix", "vector",
  "intervalhull", "constraints", "constraint", "system", "formula", "interval",
  "expression"
}
Referenced by expressionSempred(), and getRuleNames().
_serializedATN
std::vector< uint16_t > definitionParser::_serializedATN static private
Referenced by expressionSempred(), and definitionParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache definitionParser::_sharedContextCache static private
Referenced by definitionParser(), and expressionSempred().
_symbolicNames
std::vector< std::string > definitionParser::_symbolicNames static private
Initial value:
= {
  "", "KEY_LOCATIONS", "KEY_MODEL", "KEY_FLOWS", "KEY_INVARIANT_CONDITIONS",
  "KEY_SETTINGS", "KEY_ANALYSIS", "KEY_ANALYSIS_FORWARD", "KEY_ANALYSIS_BACKWARD",
  "KEY_TIME_HORIZON", "KEY_STEP", "KEY_GEOMETRY", "KEY_PLOT_FLAG", "KEY_PRINT_FLAG",
  "KEY_MAX_JUMP", "KEY_START_MODEL_ID", "KEY_INITIAL_CONDITION", "KEY_TRANSITIONS",
  "KEY_URGENT", "KEY_JUMP", "KEY_DIRECTION", "KEY_GUARD_CONDITIONS", "KEY_RESET_MAP",
  "KEY_INTERVAL_HULL", "KEY_POLYTOPE", "KEY_CONDITION", "KEY_MATRIX", "KEY_ROW_MAJOR_ORDER",
  "KEY_COL_MAJOR_ORDER", "KEY_SIN_FUNCTION", "KEY_ARCSIN_FUNCTION", "KEY_COS_FUNCTION",
  "KEY_ARCCOS_FUNCTION", "KEY_TAN_FUNCTION", "KEY_ARCTAN_FUNCTION", "KEY_COT_FUNCTION",
  "KEY_ARCCOT_FUNCTION", "KEY_LN_FUNCTION", "KEY_LOG_FUNCTION", "KEY_NATURAL_EXP_FUNCTION",
  "KEY_SINH_FUNCTION", "KEY_ARCSINH_FUNCTION", "KEY_COSH_FUNCTION", "KEY_ARCCOSH_FUNCTION",
  "KEY_TANH_FUNCTION", "KEY_ARCTANH_FUNCTION", "KEY_COTH_FUNCTION", "KEY_ARCCOTH_FUNCTION",
  "KEY_SQR_FUNCTION", "KEY_SQRT_FUNCTION", "KEY_ABS_FUNCTION", "KEY_POWER_FUNCTION",
  "KEY_NAME", "KEY_SWITCH_ON", "KEY_SWITCH_OFF", "KEY_BOOL_TRUE", "KEY_BOOL_FALSE",
  "KEY_INFINITY", "SCINUM", "NUMBER", "VARIABLE", "LEFTCURLYBRACKET", "RIGHTCURLYBRACKET",
  "LEFTROUNDBRACKET", "RIGHTROUNDBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET",
  "COMMA", "EQUAL", "UNEQUAL", "GEQ", "LEQ", "LSS", "GTR", "DEFINE", "FROMTO",
  "ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", "DERIVATIVE",
  "COMMENT", "WS"
}
Referenced by expressionSempred(), and definitionParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > definitionParser::_tokenNames static private
Referenced by expressionSempred(), getTokenNames(), and definitionParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary definitionParser::_vocabulary static private
Referenced by expressionSempred(), getVocabulary(), and definitionParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp