irafhy: locationsParser::MatrixContext Class Reference
locationsParser::MatrixContext Class Reference
#include <locationsParser.h>
Public Member Functions
MatrixContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MATRIX ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
antlr4::tree::TerminalNode * KEY_ROW_MAJOR_ORDER ()
antlr4::tree::TerminalNode * KEY_COL_MAJOR_ORDER ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * MAJOR_ORDER = nullptr
Constructor & Destructor Documentation
MatrixContext()
locationsParser::MatrixContext::MatrixContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::MatrixContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > locationsParser::MatrixContext::COMMA ()
References locationsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * locationsParser::MatrixContext::COMMA (size_t i)
References locationsParser::COMMA.
enterRule()
void locationsParser::MatrixContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterMatrix().
Referenced by locationsParser::matrix().
exitRule()
void locationsParser::MatrixContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitMatrix().
Referenced by locationsParser::matrix().
getRuleIndex()
size_t locationsParser::MatrixContext::getRuleIndex () const override virtual
References locationsParser::RuleMatrix.
KEY_COL_MAJOR_ORDER()
tree::TerminalNode * locationsParser::MatrixContext::KEY_COL_MAJOR_ORDER ()
References locationsParser::KEY_COL_MAJOR_ORDER.
KEY_MATRIX()
tree::TerminalNode * locationsParser::MatrixContext::KEY_MATRIX ()
References locationsParser::KEY_MATRIX.
KEY_ROW_MAJOR_ORDER()
tree::TerminalNode * locationsParser::MatrixContext::KEY_ROW_MAJOR_ORDER ()
References locationsParser::KEY_ROW_MAJOR_ORDER.
LEFTCURLYBRACKET()
tree::TerminalNode * locationsParser::MatrixContext::LEFTCURLYBRACKET ()
References locationsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * locationsParser::MatrixContext::RIGHTCURLYBRACKET ()
References locationsParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< locationsParser::VectorContext * > locationsParser::MatrixContext::vector ()
Referenced by locationsParser::matrix().
vector() [2/2]
locationsParser::VectorContext * locationsParser::MatrixContext::vector (size_t i)
Member Data Documentation
MAJOR_ORDER
antlr4::Token* locationsParser::MatrixContext::MAJOR_ORDER = nullptr
Referenced by locationsParser::matrix().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp