irafhy: locationsParser::ConstraintContext Class Reference
locationsParser::ConstraintContext Class Reference
#include <locationsParser.h>
Public Member Functions
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EQUAL ()
antlr4::tree::TerminalNode * UNEQUAL ()
antlr4::tree::TerminalNode * GEQ ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * LSS ()
antlr4::tree::TerminalNode * GTR ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * RELATION = nullptr
Constructor & Destructor Documentation
ConstraintContext()
locationsParser::ConstraintContext::ConstraintContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ConstraintContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ConstraintContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterConstraint().
Referenced by locationsParser::constraint().
EQUAL()
tree::TerminalNode * locationsParser::ConstraintContext::EQUAL ()
References locationsParser::EQUAL.
exitRule()
void locationsParser::ConstraintContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitConstraint().
Referenced by locationsParser::constraint().
expression() [1/2]
std::vector< locationsParser::ExpressionContext * > locationsParser::ConstraintContext::expression ()
Referenced by locationsParser::constraint().
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::ConstraintContext::expression (size_t i)
GEQ()
tree::TerminalNode * locationsParser::ConstraintContext::GEQ ()
References locationsParser::GEQ.
getRuleIndex()
size_t locationsParser::ConstraintContext::getRuleIndex () const override virtual
References locationsParser::RuleConstraint.
GTR()
tree::TerminalNode * locationsParser::ConstraintContext::GTR ()
References locationsParser::GTR.
LEQ()
tree::TerminalNode * locationsParser::ConstraintContext::LEQ ()
References locationsParser::LEQ.
LSS()
tree::TerminalNode * locationsParser::ConstraintContext::LSS ()
References locationsParser::LSS.
UNEQUAL()
tree::TerminalNode * locationsParser::ConstraintContext::UNEQUAL ()
References locationsParser::UNEQUAL.
Member Data Documentation
RELATION
antlr4::Token* locationsParser::ConstraintContext::RELATION = nullptr
Referenced by locationsParser::constraint().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp