irafhy: definitionParser::ConstraintsContext Class Reference
definitionParser::ConstraintsContext Class Reference
#include <definitionParser.h>
Public Member Functions
ConstraintsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ConstraintContext * > constraint ()
ConstraintContext * constraint (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConstraintsContext()
definitionParser::ConstraintsContext::ConstraintsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ConstraintsContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
constraint() [1/2]
std::vector< definitionParser::ConstraintContext * > definitionParser::ConstraintsContext::constraint ()
Referenced by definitionParser::constraints().
constraint() [2/2]
definitionParser::ConstraintContext * definitionParser::ConstraintsContext::constraint (size_t i)
enterRule()
void definitionParser::ConstraintsContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterConstraints().
Referenced by definitionParser::constraints().
exitRule()
void definitionParser::ConstraintsContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitConstraints().
Referenced by definitionParser::constraints().
getRuleIndex()
size_t definitionParser::ConstraintsContext::getRuleIndex () const override virtual
References definitionParser::RuleConstraints.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp