irafhy: transitionsParser::IntervalContext Class Reference
transitionsParser::IntervalContext Class Reference
#include <transitionsParser.h>
Public Member Functions
IntervalContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTSQUAREBRACKET ()
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTSQUAREBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< antlr4::tree::TerminalNode * > SCINUM ()
antlr4::tree::TerminalNode * SCINUM (size_t i)
std::vector< antlr4::tree::TerminalNode * > KEY_INFINITY ()
antlr4::tree::TerminalNode * KEY_INFINITY (size_t i)
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset251 = nullptr
antlr4::Token * numberToken = nullptr
std::vector< antlr4::Token * > VAL
antlr4::Token * scinumToken = nullptr
antlr4::Token * key_infinityToken = nullptr
antlr4::Token * _tset264 = nullptr
antlr4::Token * _tset284 = nullptr
antlr4::Token * _tset297 = nullptr
Constructor & Destructor Documentation
IntervalContext()
transitionsParser::IntervalContext::IntervalContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::IntervalContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * transitionsParser::IntervalContext::COMMA ()
References transitionsParser::COMMA.
enterRule()
void transitionsParser::IntervalContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterInterval().
Referenced by transitionsParser::interval().
exitRule()
void transitionsParser::IntervalContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitInterval().
Referenced by transitionsParser::interval().
getRuleIndex()
size_t transitionsParser::IntervalContext::getRuleIndex () const override virtual
References transitionsParser::RuleInterval.
KEY_INFINITY() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalContext::KEY_INFINITY ()
References transitionsParser::KEY_INFINITY.
KEY_INFINITY() [2/2]
tree::TerminalNode * transitionsParser::IntervalContext::KEY_INFINITY (size_t i)
References transitionsParser::KEY_INFINITY.
LEFTSQUAREBRACKET()
tree::TerminalNode * transitionsParser::IntervalContext::LEFTSQUAREBRACKET ()
References transitionsParser::LEFTSQUAREBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalContext::MINUS ()
References transitionsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * transitionsParser::IntervalContext::MINUS (size_t i)
References transitionsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalContext::NUMBER ()
References transitionsParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * transitionsParser::IntervalContext::NUMBER (size_t i)
References transitionsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalContext::PLUS ()
References transitionsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * transitionsParser::IntervalContext::PLUS (size_t i)
References transitionsParser::PLUS.
RIGHTSQUAREBRACKET()
tree::TerminalNode * transitionsParser::IntervalContext::RIGHTSQUAREBRACKET ()
References transitionsParser::RIGHTSQUAREBRACKET.
SCINUM() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalContext::SCINUM ()
References transitionsParser::SCINUM.
SCINUM() [2/2]
tree::TerminalNode * transitionsParser::IntervalContext::SCINUM (size_t i)
References transitionsParser::SCINUM.
Member Data Documentation
_tset251
antlr4::Token* transitionsParser::IntervalContext::_tset251 = nullptr
Referenced by transitionsParser::interval().
_tset264
antlr4::Token* transitionsParser::IntervalContext::_tset264 = nullptr
Referenced by transitionsParser::interval().
_tset284
antlr4::Token* transitionsParser::IntervalContext::_tset284 = nullptr
Referenced by transitionsParser::interval().
_tset297
antlr4::Token* transitionsParser::IntervalContext::_tset297 = nullptr
Referenced by transitionsParser::interval().
key_infinityToken
antlr4::Token* transitionsParser::IntervalContext::key_infinityToken = nullptr
minusToken
antlr4::Token* transitionsParser::IntervalContext::minusToken = nullptr
numberToken
antlr4::Token* transitionsParser::IntervalContext::numberToken = nullptr
OP
std::vector<antlr4::Token *> transitionsParser::IntervalContext::OP
Referenced by transitionsParser::interval().
plusToken
antlr4::Token* transitionsParser::IntervalContext::plusToken = nullptr
scinumToken
antlr4::Token* transitionsParser::IntervalContext::scinumToken = nullptr
VAL
std::vector<antlr4::Token *> transitionsParser::IntervalContext::VAL
Referenced by transitionsParser::interval().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp