irafhy: definitionParser::SinhExpContext Class Reference
definitionParser::SinhExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
SinhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SINH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinhExpContext()
definitionParser::SinhExpContext::SinhExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::SinhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::SinhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterSinhExp().
exitRule()
void definitionParser::SinhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitSinhExp().
expression()
definitionParser::ExpressionContext * definitionParser::SinhExpContext::expression ()
KEY_SINH_FUNCTION()
tree::TerminalNode * definitionParser::SinhExpContext::KEY_SINH_FUNCTION ()
References definitionParser::KEY_SINH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::SinhExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::SinhExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp