irafhy: hybridautomatonParser::LnExpContext Class Reference
hybridautomatonParser::LnExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
LnExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LnExpContext()
hybridautomatonParser::LnExpContext::LnExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::LnExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::LnExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterLnExp().
exitRule()
void hybridautomatonParser::LnExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitLnExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::LnExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitLnExp().
KEY_LN_FUNCTION()
tree::TerminalNode * hybridautomatonParser::LnExpContext::KEY_LN_FUNCTION ()
References hybridautomatonParser::KEY_LN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::LnExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::LnExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp