irafhy: definitionParser::PosExpContext Class Reference
definitionParser::PosExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
PosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * PLUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PosExpContext()
definitionParser::PosExpContext::PosExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::PosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::PosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterPosExp().
exitRule()
void definitionParser::PosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitPosExp().
expression()
definitionParser::ExpressionContext * definitionParser::PosExpContext::expression ()
PLUS()
tree::TerminalNode * definitionParser::PosExpContext::PLUS ()
References definitionParser::PLUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp