irafhy: transitionsParser::ExpExpContext Class Reference
transitionsParser::ExpExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ExpExpContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EXPONENT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpExpContext()
transitionsParser::ExpExpContext::ExpExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::ExpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::ExpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterExpExp().
exitRule()
void transitionsParser::ExpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitExpExp().
EXPONENT()
tree::TerminalNode * transitionsParser::ExpExpContext::EXPONENT ()
References transitionsParser::EXPONENT.
expression() [1/2]
std::vector< transitionsParser::ExpressionContext * > transitionsParser::ExpExpContext::expression ()
expression() [2/2]
transitionsParser::ExpressionContext * transitionsParser::ExpExpContext::expression (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp