irafhy: hybridautomatonParser::SystemContext Class Reference
hybridautomatonParser::SystemContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
SystemContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FormulaContext * > formula ()
FormulaContext * formula (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SystemContext()
hybridautomatonParser::SystemContext::SystemContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::SystemContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::SystemContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterSystem().
Referenced by hybridautomatonParser::system().
exitRule()
void hybridautomatonParser::SystemContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitSystem().
Referenced by hybridautomatonParser::system().
formula() [1/2]
std::vector< hybridautomatonParser::FormulaContext * > hybridautomatonParser::SystemContext::formula ()
Referenced by hybridautomatonParser::system(), and irafhy::SystemVisitor::visitSystem().
formula() [2/2]
hybridautomatonParser::FormulaContext * hybridautomatonParser::SystemContext::formula (size_t i)
getRuleIndex()
size_t hybridautomatonParser::SystemContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleSystem.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp