irafhy: hybridautomatonParser::IntervalhullContext Class Reference
hybridautomatonParser::IntervalhullContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
IntervalhullContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< IntervalContext * > interval ()
IntervalContext * interval (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntervalhullContext()
hybridautomatonParser::IntervalhullContext::IntervalhullContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::IntervalhullContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalhullContext::COMMA ()
References hybridautomatonParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalhullContext::COMMA (size_t i)
References hybridautomatonParser::COMMA.
enterRule()
void hybridautomatonParser::IntervalhullContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterIntervalhull().
Referenced by hybridautomatonParser::intervalhull().
exitRule()
void hybridautomatonParser::IntervalhullContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitIntervalhull().
Referenced by hybridautomatonParser::intervalhull().
getRuleIndex()
size_t hybridautomatonParser::IntervalhullContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleIntervalhull.
interval() [1/2]
std::vector< hybridautomatonParser::IntervalContext * > hybridautomatonParser::IntervalhullContext::interval ()
Referenced by hybridautomatonParser::intervalhull(), and irafhy::DefinitionVisitor::visitIntervalhull().
interval() [2/2]
hybridautomatonParser::IntervalContext * hybridautomatonParser::IntervalhullContext::interval (size_t i)
KEY_INTERVAL_HULL()
tree::TerminalNode * hybridautomatonParser::IntervalhullContext::KEY_INTERVAL_HULL ()
References hybridautomatonParser::KEY_INTERVAL_HULL.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::IntervalhullContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::IntervalhullContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp