irafhy: irafhy::ItemVisitor Class Reference
irafhy::ItemVisitor Class Reference
#include <itemVisitor.h>
Public Member Functions
ItemVisitor ()
constructor
ItemVisitor (const std::vector< std::string > &vars)
constructor with given variables
antlrcpp::Any visitTanExp (hybridautomatonParser::TanExpContext *ctx) override
visitor of tangent function
antlrcpp::Any visitSqrExp (hybridautomatonParser::SqrExpContext *ctx) override
visitor of sqr function
antlrcpp::Any visitConstant (hybridautomatonParser::ConstantContext *ctx) override
constant visitor
antlrcpp::Any visitAsinhExp (hybridautomatonParser::AsinhExpContext *ctx) override
visitor of arc sin function
antlrcpp::Any visitAcosExp (hybridautomatonParser::AcosExpContext *ctx) override
visitor of arc cos function
antlrcpp::Any visitAcothExp (hybridautomatonParser::AcothExpContext *ctx) override
visitor of arc coth function
antlrcpp::Any visitAcoshExp (hybridautomatonParser::AcoshExpContext *ctx) override
visitor of arc cosh function
antlrcpp::Any visitCosExp (hybridautomatonParser::CosExpContext *ctx) override
visitor of cos function
antlrcpp::Any visitPowExp (hybridautomatonParser::PowExpContext *ctx) override
visitor of power function
antlrcpp::Any visitCothExp (hybridautomatonParser::CothExpContext *ctx) override
visitor of coth function
antlrcpp::Any visitPosExp (hybridautomatonParser::PosExpContext *ctx) override
visitor of positive function
antlrcpp::Any visitNegExp (hybridautomatonParser::NegExpContext *ctx) override
visitor of negative function
antlrcpp::Any visitExpBra (hybridautomatonParser::ExpBraContext *ctx) override
brackets visitor
antlrcpp::Any visitAtanhExp (hybridautomatonParser::AtanhExpContext *ctx) override
visitor of arc tanh function
antlrcpp::Any visitSinExp (hybridautomatonParser::SinExpContext *ctx) override
visitor of sin function
antlrcpp::Any visitLnExp (hybridautomatonParser::LnExpContext *ctx) override
visitor of ln function
antlrcpp::Any visitTanhExp (hybridautomatonParser::TanhExpContext *ctx) override
visitor of tanh function
antlrcpp::Any visitSqrtExp (hybridautomatonParser::SqrtExpContext *ctx) override
visitor of sqrt function
antlrcpp::Any visitExpMulDiv (hybridautomatonParser::ExpMulDivContext *ctx) override
visitor of multiplication or division
antlrcpp::Any visitAtanExp (hybridautomatonParser::AtanExpContext *ctx) override
visitor of arc tan function
antlrcpp::Any visitAcotExp (hybridautomatonParser::AcotExpContext *ctx) override
visitor of arc cot function
antlrcpp::Any visitExpExp (hybridautomatonParser::ExpExpContext *ctx) override
visitor of exponential function
antlrcpp::Any visitCoshExp (hybridautomatonParser::CoshExpContext *ctx) override
visitor of cosh function
antlrcpp::Any visitLogExp (hybridautomatonParser::LogExpContext *ctx) override
visitor of log function
antlrcpp::Any visitAsinExp (hybridautomatonParser::AsinExpContext *ctx) override
visitor of arc sin function
antlrcpp::Any visitCotExp (hybridautomatonParser::CotExpContext *ctx) override
visitor of cot function
antlrcpp::Any visitVariable (hybridautomatonParser::VariableContext *ctx) override
visitor of a variable
antlrcpp::Any visitSinhExp (hybridautomatonParser::SinhExpContext *ctx) override
visitor of sinh function
antlrcpp::Any visitNexpExp (hybridautomatonParser::NexpExpContext *ctx) override
visitor of natural exponential function
antlrcpp::Any visitExpAddSub (hybridautomatonParser::ExpAddSubContext *ctx) override
visitor of addition or subtraction
antlrcpp::Any visitSqrtConstExp (hybridautomatonParser::SqrtConstExpContext *ctx) override
visitor of sqr function of constant expressions
antlrcpp::Any visitAcothConstExp (hybridautomatonParser::AcothConstExpContext *ctx) override
visitor of arc coth function of constant expression
antlrcpp::Any visitLogConstExp (hybridautomatonParser::LogConstExpContext *ctx) override
visitor of log function of constant expression
antlrcpp::Any visitTanhConstExp (hybridautomatonParser::TanhConstExpContext *ctx) override
visitor of tanh function of constant expression
antlrcpp::Any visitPowConstExp (hybridautomatonParser::PowConstExpContext *ctx) override
visitor of power function of constant expression
antlrcpp::Any visitPosConstExp (hybridautomatonParser::PosConstExpContext *ctx) override
visitor of positive function of constant expression
antlrcpp::Any visitAtanhConstExp (hybridautomatonParser::AtanhConstExpContext *ctx) override
visitor of arc tanh function of constant expression
antlrcpp::Any visitSqrConstExp (hybridautomatonParser::SqrConstExpContext *ctx) override
visitor of sqr function of constant expression
antlrcpp::Any visitConstExpBra (hybridautomatonParser::ConstExpBraContext *ctx) override
visitor of constant expression enclosed in brackets
antlrcpp::Any visitSinhConstExp (hybridautomatonParser::SinhConstExpContext *ctx) override
visitor of sinh function of constant expression
antlrcpp::Any visitAtanConstExp (hybridautomatonParser::AtanConstExpContext *ctx) override
visitor of arc tan function of constant expression
antlrcpp::Any visitAsinhConstExp (hybridautomatonParser::AsinhConstExpContext *ctx) override
visitor of arc sinh function of constant expression
antlrcpp::Any visitConstExp (hybridautomatonParser::ConstExpContext *ctx) override
visitor of constant expression
antlrcpp::Any visitNegConstExp (hybridautomatonParser::NegConstExpContext *ctx) override
visitor of negative function of constant expression
antlrcpp::Any visitAsinConstExp (hybridautomatonParser::AsinConstExpContext *ctx) override
visitor of arc sin function of constant expression
antlrcpp::Any visitTanConstExp (hybridautomatonParser::TanConstExpContext *ctx) override
visitor of tan function of constant expression
antlrcpp::Any visitNexpConstExp (hybridautomatonParser::NexpConstExpContext *ctx) override
visitor of natural exponential function of constant expression
antlrcpp::Any visitCosConstExp (hybridautomatonParser::CosConstExpContext *ctx) override
visitor of cos function of constant expression
antlrcpp::Any visitConstExpMulDiv (hybridautomatonParser::ConstExpMulDivContext *ctx) override
visitor of multiplication or division of constant expression
antlrcpp::Any visitExpConstExp (hybridautomatonParser::ExpConstExpContext *ctx) override
visitor of exponential function of constant expression
antlrcpp::Any visitCotConstExp (hybridautomatonParser::CotConstExpContext *ctx) override
visitor of cot function of constant expression
antlrcpp::Any visitCoshConstExp (hybridautomatonParser::CoshConstExpContext *ctx) override
visitor of cosh function of constant expression
antlrcpp::Any visitAcoshConstExp (hybridautomatonParser::AcoshConstExpContext *ctx) override
visitor of arc cosh function of constant expression
antlrcpp::Any visitSinConstExp (hybridautomatonParser::SinConstExpContext *ctx) override
visitor of sin function of constant expression
antlrcpp::Any visitAcosConstExp (hybridautomatonParser::AcosConstExpContext *ctx) override
visitor of arc cos function of constant expression
antlrcpp::Any visitConstExpAddSub (hybridautomatonParser::ConstExpAddSubContext *ctx) override
visitor of addition or subtraction of constant expression
antlrcpp::Any visitLnConstExp (hybridautomatonParser::LnConstExpContext *ctx) override
visitor of ln function of constant expression
antlrcpp::Any visitAcotConstExp (hybridautomatonParser::AcotConstExpContext *ctx) override
visitor of arc cot function of constant expression
Private Member Functions
double strToNum (const std::string &numStr) const
convert given string to number
Private Attributes
std::vector< std::string > vars_
variables of hybrid automaton
Constructor & Destructor Documentation
ItemVisitor() [1/2]
irafhy::ItemVisitor::ItemVisitor ()
constructor
References vars_.
ItemVisitor() [2/2]
irafhy::ItemVisitor::ItemVisitor (const std::vector< std::string > & vars) explicit
constructor with given variables
Parameters
vars given variables of hybrid automaton
References vars_.
Member Function Documentation
strToNum()
double irafhy::ItemVisitor::strToNum (const std::string & numStr) const private
convert given string to number
Parameters
numStr given string
Returns
resulting number
Referenced by visitConstant(), and visitConstExp().
visitAcosConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcosConstExp (hybridautomatonParser::AcosConstExpContext * ctx) override
visitor of arc cos function of constant expression
Parameters
ctx context of constant expression
Returns
resulting constant
visitAcosExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcosExp (hybridautomatonParser::AcosExpContext * ctx) override
visitor of arc cos function
Parameters
ctx context of arc cos function
Returns
arc cos function instance
References irafhy::ACOS.
visitAcoshConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcoshConstExp (hybridautomatonParser::AcoshConstExpContext * ctx) override
visitor of arc cosh function of constant expression
Parameters
ctx context of arc cosh function
Returns
resulting constant
visitAcoshExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcoshExp (hybridautomatonParser::AcoshExpContext * ctx) override
visitor of arc cosh function
Parameters
ctx context of arc cosh function
Returns
arc cosh function instance
References irafhy::ACOSH.
visitAcotConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcotConstExp (hybridautomatonParser::AcotConstExpContext * ctx) override
visitor of arc cot function of constant expression
Parameters
ctx context of arc cot function
Returns
resulting constant
visitAcotExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcotExp (hybridautomatonParser::AcotExpContext * ctx) override
visitor of arc cot function
Parameters
ctx context of arc cot function
Returns
arc cot function instance
References irafhy::ACOT.
visitAcothConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcothConstExp (hybridautomatonParser::AcothConstExpContext * ctx) override
visitor of arc coth function of constant expression
Parameters
ctx context of coth function
Returns
resulting constant
visitAcothExp()
antlrcpp::Any irafhy::ItemVisitor::visitAcothExp (hybridautomatonParser::AcothExpContext * ctx) override
visitor of arc coth function
Parameters
ctx context of arc coth function
Returns
arc coth function instance
References irafhy::ACOTH.
visitAsinConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAsinConstExp (hybridautomatonParser::AsinConstExpContext * ctx) override
visitor of arc sin function of constant expression
Parameters
ctx context of arc sin function
Returns
resulting constant
visitAsinExp()
antlrcpp::Any irafhy::ItemVisitor::visitAsinExp (hybridautomatonParser::AsinExpContext * ctx) override
visitor of arc sin function
Parameters
ctx context of arc sin function
Returns
arc sin function instance
References irafhy::ASIN.
visitAsinhConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAsinhConstExp (hybridautomatonParser::AsinhConstExpContext * ctx) override
visitor of arc sinh function of constant expression
Parameters
ctx context of arc sinh function
Returns
resulting constant
visitAsinhExp()
antlrcpp::Any irafhy::ItemVisitor::visitAsinhExp (hybridautomatonParser::AsinhExpContext * ctx) override
visitor of arc sin function
Parameters
ctx context of arc sin function
Returns
arc sin function instance
References irafhy::ASINH.
visitAtanConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAtanConstExp (hybridautomatonParser::AtanConstExpContext * ctx) override
visitor of arc tan function of constant expression
Parameters
ctx context of arc tan function
Returns
resulting constant
visitAtanExp()
antlrcpp::Any irafhy::ItemVisitor::visitAtanExp (hybridautomatonParser::AtanExpContext * ctx) override
visitor of arc tan function
Parameters
ctx context of arc tan function
Returns
arc tan function instance
References irafhy::ATAN.
visitAtanhConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitAtanhConstExp (hybridautomatonParser::AtanhConstExpContext * ctx) override
visitor of arc tanh function of constant expression
Parameters
ctx context of arc tanh function
Returns
resulting constant
visitAtanhExp()
antlrcpp::Any irafhy::ItemVisitor::visitAtanhExp (hybridautomatonParser::AtanhExpContext * ctx) override
visitor of arc tanh function
Parameters
ctx context of arc tanh function
Returns
arc tanh function instance
References irafhy::ATANH.
visitConstant()
antlrcpp::Any irafhy::ItemVisitor::visitConstant (hybridautomatonParser::ConstantContext * ctx) override
constant visitor
Parameters
ctx context of constant
Returns
constant instance
References strToNum().
visitConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitConstExp (hybridautomatonParser::ConstExpContext * ctx) override
visitor of constant expression
Parameters
ctx context of constant expression
Returns
resulting constant
References strToNum().
visitConstExpAddSub()
antlrcpp::Any irafhy::ItemVisitor::visitConstExpAddSub (hybridautomatonParser::ConstExpAddSubContext * ctx) override
visitor of addition or subtraction of constant expression
Parameters
ctx context of addition or subtraction
Returns
resulting constant
References irafhy::PLUS.
visitConstExpBra()
antlrcpp::Any irafhy::ItemVisitor::visitConstExpBra (hybridautomatonParser::ConstExpBraContext * ctx) override
visitor of constant expression enclosed in brackets
Parameters
ctx context of brackets enclosing a constant expression
Returns
resulting constant
visitConstExpMulDiv()
antlrcpp::Any irafhy::ItemVisitor::visitConstExpMulDiv (hybridautomatonParser::ConstExpMulDivContext * ctx) override
visitor of multiplication or division of constant expression
Parameters
ctx context of multiplication or division
Returns
resulting constant
References irafhy::MULTIPLY.
visitCosConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitCosConstExp (hybridautomatonParser::CosConstExpContext * ctx) override
visitor of cos function of constant expression
Parameters
ctx context of cos expression
Returns
resulting constant
visitCosExp()
antlrcpp::Any irafhy::ItemVisitor::visitCosExp (hybridautomatonParser::CosExpContext * ctx) override
visitor of cos function
Parameters
ctx context of cos function
Returns
cos function instance
References irafhy::COS.
visitCoshConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitCoshConstExp (hybridautomatonParser::CoshConstExpContext * ctx) override
visitor of cosh function of constant expression
Parameters
ctx context of cosh function
Returns
resulting constant
visitCoshExp()
antlrcpp::Any irafhy::ItemVisitor::visitCoshExp (hybridautomatonParser::CoshExpContext * ctx) override
visitor of cosh function
Parameters
ctx context of cosh function
Returns
cosh function instance
References irafhy::COSH.
visitCotConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitCotConstExp (hybridautomatonParser::CotConstExpContext * ctx) override
visitor of cot function of constant expression
Parameters
ctx context of cot function
Returns
resulting constant
visitCotExp()
antlrcpp::Any irafhy::ItemVisitor::visitCotExp (hybridautomatonParser::CotExpContext * ctx) override
visitor of cot function
Parameters
ctx context of cot function
Returns
cot function instance
References irafhy::LOG.
visitCothExp()
antlrcpp::Any irafhy::ItemVisitor::visitCothExp (hybridautomatonParser::CothExpContext * ctx) override
visitor of coth function
Parameters
ctx context of coth function
Returns
coth function instance
References irafhy::COTH.
visitExpAddSub()
antlrcpp::Any irafhy::ItemVisitor::visitExpAddSub (hybridautomatonParser::ExpAddSubContext * ctx) override
visitor of addition or subtraction
Parameters
ctx context of addition or subtraction
Returns
addition or subtraction instance
References irafhy::MINUS, and irafhy::PLUS.
visitExpBra()
antlrcpp::Any irafhy::ItemVisitor::visitExpBra (hybridautomatonParser::ExpBraContext * ctx) override
brackets visitor
Parameters
ctx context of brackets
Returns
brackets instance
visitExpConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitExpConstExp (hybridautomatonParser::ExpConstExpContext * ctx) override
visitor of exponential function of constant expression
Parameters
ctx context of exponential function
Returns
resulting constant
visitExpExp()
antlrcpp::Any irafhy::ItemVisitor::visitExpExp (hybridautomatonParser::ExpExpContext * ctx) override
visitor of exponential function
Parameters
ctx context of exponential function
Returns
exponential function instance
References irafhy::POWER.
visitExpMulDiv()
antlrcpp::Any irafhy::ItemVisitor::visitExpMulDiv (hybridautomatonParser::ExpMulDivContext * ctx) override
visitor of multiplication or division
Parameters
ctx context of multiplication or division
Returns
multiplication or division instance
References irafhy::DIVIDE, and irafhy::MULTIPLY.
visitLnConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitLnConstExp (hybridautomatonParser::LnConstExpContext * ctx) override
visitor of ln function of constant expression
Parameters
ctx context of ln function
Returns
resulting constant
visitLnExp()
antlrcpp::Any irafhy::ItemVisitor::visitLnExp (hybridautomatonParser::LnExpContext * ctx) override
visitor of ln function
Parameters
ctx context of ln function
Returns
ln function instance
References irafhy::LN.
visitLogConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitLogConstExp (hybridautomatonParser::LogConstExpContext * ctx) override
visitor of log function of constant expression
Parameters
ctx context of log function
Returns
resulting constant
visitLogExp()
antlrcpp::Any irafhy::ItemVisitor::visitLogExp (hybridautomatonParser::LogExpContext * ctx) override
visitor of log function
Parameters
ctx context of log function
Returns
log function instance
References irafhy::LOG.
visitNegConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitNegConstExp (hybridautomatonParser::NegConstExpContext * ctx) override
visitor of negative function of constant expression
Parameters
ctx context of negative function
Returns
resulting constant
visitNegExp()
antlrcpp::Any irafhy::ItemVisitor::visitNegExp (hybridautomatonParser::NegExpContext * ctx) override
visitor of negative function
Parameters
ctx context of negative function
Returns
negative function instance
References irafhy::OPPOSITE.
visitNexpConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitNexpConstExp (hybridautomatonParser::NexpConstExpContext * ctx) override
visitor of natural exponential function of constant expression
Parameters
ctx context of natural exponential function
Returns
resulting constant
visitNexpExp()
antlrcpp::Any irafhy::ItemVisitor::visitNexpExp (hybridautomatonParser::NexpExpContext * ctx) override
visitor of natural exponential function
Parameters
ctx context of natural exponential function
Returns
natural exponential function instance
References irafhy::NEXP.
visitPosConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitPosConstExp (hybridautomatonParser::PosConstExpContext * ctx) override
visitor of positive function of constant expression
Parameters
ctx context of positive function
Returns
resulting constant
visitPosExp()
antlrcpp::Any irafhy::ItemVisitor::visitPosExp (hybridautomatonParser::PosExpContext * ctx) override
visitor of positive function
Parameters
ctx context of positive function
Returns
positive function instance
visitPowConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitPowConstExp (hybridautomatonParser::PowConstExpContext * ctx) override
visitor of power function of constant expression
Parameters
ctx context of power function
Returns
resulting constant
visitPowExp()
antlrcpp::Any irafhy::ItemVisitor::visitPowExp (hybridautomatonParser::PowExpContext * ctx) override
visitor of power function
Parameters
ctx context of power function
Returns
power function instance
References irafhy::POWER.
visitSinConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitSinConstExp (hybridautomatonParser::SinConstExpContext * ctx) override
visitor of sin function of constant expression
Parameters
ctx context of sin function
Returns
resulting constant
visitSinExp()
antlrcpp::Any irafhy::ItemVisitor::visitSinExp (hybridautomatonParser::SinExpContext * ctx) override
visitor of sin function
Parameters
ctx context of sin function
Returns
sin function instance
References irafhy::SIN.
visitSinhConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitSinhConstExp (hybridautomatonParser::SinhConstExpContext * ctx) override
visitor of sinh function of constant expression
Parameters
ctx context of sinh function
Returns
resulting constant
visitSinhExp()
antlrcpp::Any irafhy::ItemVisitor::visitSinhExp (hybridautomatonParser::SinhExpContext * ctx) override
visitor of sinh function
Parameters
ctx context of sinh function
Returns
sinh function instance
References irafhy::SINH.
visitSqrConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitSqrConstExp (hybridautomatonParser::SqrConstExpContext * ctx) override
visitor of sqr function of constant expression
Parameters
ctx context of sqr function
Returns
resulting constant
visitSqrExp()
antlrcpp::Any irafhy::ItemVisitor::visitSqrExp (hybridautomatonParser::SqrExpContext * ctx) override
visitor of sqr function
Parameters
ctx context of sqrt function
Returns
sqrt function instance
References irafhy::SQR.
visitSqrtConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitSqrtConstExp (hybridautomatonParser::SqrtConstExpContext * ctx) override
visitor of sqr function of constant expressions
Parameters
ctx context of sqr function
Returns
resulting constant
visitSqrtExp()
antlrcpp::Any irafhy::ItemVisitor::visitSqrtExp (hybridautomatonParser::SqrtExpContext * ctx) override
visitor of sqrt function
Parameters
ctx context of sqrt function
Returns
sqrt function instance
References irafhy::SQRT.
visitTanConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitTanConstExp (hybridautomatonParser::TanConstExpContext * ctx) override
visitor of tan function of constant expression
Parameters
ctx context of tan function
Returns
resulting constant
visitTanExp()
antlrcpp::Any irafhy::ItemVisitor::visitTanExp (hybridautomatonParser::TanExpContext * ctx) override
visitor of tangent function
Parameters
ctx context of tangent function
Returns
tangent function instance
References irafhy::TAN.
visitTanhConstExp()
antlrcpp::Any irafhy::ItemVisitor::visitTanhConstExp (hybridautomatonParser::TanhConstExpContext * ctx) override
visitor of tanh function of constant expression
Parameters
ctx context of tahh function
Returns
resulting constant
visitTanhExp()
antlrcpp::Any irafhy::ItemVisitor::visitTanhExp (hybridautomatonParser::TanhExpContext * ctx) override
visitor of tanh function
Parameters
ctx context of tanh function
Returns
tanh function instance
References irafhy::TANH.
visitVariable()
antlrcpp::Any irafhy::ItemVisitor::visitVariable (hybridautomatonParser::VariableContext * ctx) override
visitor of a variable
Parameters
ctx context of a variable
Returns
one variable instance
References vars_.
Member Data Documentation
vars_
std::vector<std::string> irafhy::ItemVisitor::vars_ private
variables of hybrid automaton
Referenced by ItemVisitor(), and visitVariable().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/visitor/itemVisitor.h
/home/jianqiang/CLionProjects/irafhy/src/utility/parser/visitor/itemVisitor.cpp