irafhy: settingsParser::SinExpContext Class Reference
settingsParser::SinExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
SinExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SIN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinExpContext()
settingsParser::SinExpContext::SinExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::SinExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::SinExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterSinExp().
exitRule()
void settingsParser::SinExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitSinExp().
expression()
settingsParser::ExpressionContext * settingsParser::SinExpContext::expression ()
KEY_SIN_FUNCTION()
tree::TerminalNode * settingsParser::SinExpContext::KEY_SIN_FUNCTION ()
References settingsParser::KEY_SIN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::SinExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::SinExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp