irafhy: definitionParser::MatrixContext Class Reference
definitionParser::MatrixContext Class Reference
#include <definitionParser.h>
Public Member Functions
MatrixContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MATRIX ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
antlr4::tree::TerminalNode * KEY_ROW_MAJOR_ORDER ()
antlr4::tree::TerminalNode * KEY_COL_MAJOR_ORDER ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * MAJOR_ORDER = nullptr
Constructor & Destructor Documentation
MatrixContext()
definitionParser::MatrixContext::MatrixContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::MatrixContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > definitionParser::MatrixContext::COMMA ()
References definitionParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * definitionParser::MatrixContext::COMMA (size_t i)
References definitionParser::COMMA.
enterRule()
void definitionParser::MatrixContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterMatrix().
Referenced by definitionParser::matrix().
exitRule()
void definitionParser::MatrixContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitMatrix().
Referenced by definitionParser::matrix().
getRuleIndex()
size_t definitionParser::MatrixContext::getRuleIndex () const override virtual
References definitionParser::RuleMatrix.
KEY_COL_MAJOR_ORDER()
tree::TerminalNode * definitionParser::MatrixContext::KEY_COL_MAJOR_ORDER ()
References definitionParser::KEY_COL_MAJOR_ORDER.
KEY_MATRIX()
tree::TerminalNode * definitionParser::MatrixContext::KEY_MATRIX ()
References definitionParser::KEY_MATRIX.
KEY_ROW_MAJOR_ORDER()
tree::TerminalNode * definitionParser::MatrixContext::KEY_ROW_MAJOR_ORDER ()
References definitionParser::KEY_ROW_MAJOR_ORDER.
LEFTCURLYBRACKET()
tree::TerminalNode * definitionParser::MatrixContext::LEFTCURLYBRACKET ()
References definitionParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * definitionParser::MatrixContext::RIGHTCURLYBRACKET ()
References definitionParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< definitionParser::VectorContext * > definitionParser::MatrixContext::vector ()
Referenced by definitionParser::matrix().
vector() [2/2]
definitionParser::VectorContext * definitionParser::MatrixContext::vector (size_t i)
Member Data Documentation
MAJOR_ORDER
antlr4::Token* definitionParser::MatrixContext::MAJOR_ORDER = nullptr
Referenced by definitionParser::matrix().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp