irafhy: hybridautomatonParser::MatrixContext Class Reference
hybridautomatonParser::MatrixContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
MatrixContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MATRIX ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
antlr4::tree::TerminalNode * KEY_ROW_MAJOR_ORDER ()
antlr4::tree::TerminalNode * KEY_COL_MAJOR_ORDER ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * MAJOR_ORDER = nullptr
Constructor & Destructor Documentation
MatrixContext()
hybridautomatonParser::MatrixContext::MatrixContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::MatrixContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::MatrixContext::COMMA ()
References hybridautomatonParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * hybridautomatonParser::MatrixContext::COMMA (size_t i)
References hybridautomatonParser::COMMA.
enterRule()
void hybridautomatonParser::MatrixContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterMatrix().
Referenced by hybridautomatonParser::matrix().
exitRule()
void hybridautomatonParser::MatrixContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitMatrix().
Referenced by hybridautomatonParser::matrix().
getRuleIndex()
size_t hybridautomatonParser::MatrixContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleMatrix.
KEY_COL_MAJOR_ORDER()
tree::TerminalNode * hybridautomatonParser::MatrixContext::KEY_COL_MAJOR_ORDER ()
References hybridautomatonParser::KEY_COL_MAJOR_ORDER.
KEY_MATRIX()
tree::TerminalNode * hybridautomatonParser::MatrixContext::KEY_MATRIX ()
References hybridautomatonParser::KEY_MATRIX.
KEY_ROW_MAJOR_ORDER()
tree::TerminalNode * hybridautomatonParser::MatrixContext::KEY_ROW_MAJOR_ORDER ()
References hybridautomatonParser::KEY_ROW_MAJOR_ORDER.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::MatrixContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::MatrixContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< hybridautomatonParser::VectorContext * > hybridautomatonParser::MatrixContext::vector ()
Referenced by hybridautomatonParser::matrix(), and irafhy::DefinitionVisitor::visitMatrix().
vector() [2/2]
hybridautomatonParser::VectorContext * hybridautomatonParser::MatrixContext::vector (size_t i)
Member Data Documentation
MAJOR_ORDER
antlr4::Token* hybridautomatonParser::MatrixContext::MAJOR_ORDER = nullptr
Referenced by hybridautomatonParser::matrix(), and irafhy::DefinitionVisitor::visitMatrix().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp