irafhy: hybridautomatonParser::IntervalContext Class Reference
hybridautomatonParser::IntervalContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
IntervalContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTSQUAREBRACKET ()
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTSQUAREBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< antlr4::tree::TerminalNode * > SCINUM ()
antlr4::tree::TerminalNode * SCINUM (size_t i)
std::vector< antlr4::tree::TerminalNode * > KEY_INFINITY ()
antlr4::tree::TerminalNode * KEY_INFINITY (size_t i)
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset251 = nullptr
antlr4::Token * numberToken = nullptr
std::vector< antlr4::Token * > VAL
antlr4::Token * scinumToken = nullptr
antlr4::Token * key_infinityToken = nullptr
antlr4::Token * _tset264 = nullptr
antlr4::Token * _tset284 = nullptr
antlr4::Token * _tset297 = nullptr
Constructor & Destructor Documentation
IntervalContext()
hybridautomatonParser::IntervalContext::IntervalContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::IntervalContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * hybridautomatonParser::IntervalContext::COMMA ()
References hybridautomatonParser::COMMA.
Referenced by irafhy::DefinitionVisitor::visitInterval().
enterRule()
void hybridautomatonParser::IntervalContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterInterval().
Referenced by hybridautomatonParser::interval().
exitRule()
void hybridautomatonParser::IntervalContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitInterval().
Referenced by hybridautomatonParser::interval().
getRuleIndex()
size_t hybridautomatonParser::IntervalContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleInterval.
KEY_INFINITY() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalContext::KEY_INFINITY ()
References hybridautomatonParser::KEY_INFINITY.
KEY_INFINITY() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalContext::KEY_INFINITY (size_t i)
References hybridautomatonParser::KEY_INFINITY.
LEFTSQUAREBRACKET()
tree::TerminalNode * hybridautomatonParser::IntervalContext::LEFTSQUAREBRACKET ()
References hybridautomatonParser::LEFTSQUAREBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalContext::MINUS ()
References hybridautomatonParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalContext::MINUS (size_t i)
References hybridautomatonParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalContext::NUMBER ()
References hybridautomatonParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalContext::NUMBER (size_t i)
References hybridautomatonParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalContext::PLUS ()
References hybridautomatonParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalContext::PLUS (size_t i)
References hybridautomatonParser::PLUS.
RIGHTSQUAREBRACKET()
tree::TerminalNode * hybridautomatonParser::IntervalContext::RIGHTSQUAREBRACKET ()
References hybridautomatonParser::RIGHTSQUAREBRACKET.
SCINUM() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::IntervalContext::SCINUM ()
References hybridautomatonParser::SCINUM.
SCINUM() [2/2]
tree::TerminalNode * hybridautomatonParser::IntervalContext::SCINUM (size_t i)
References hybridautomatonParser::SCINUM.
Member Data Documentation
_tset251
antlr4::Token* hybridautomatonParser::IntervalContext::_tset251 = nullptr
Referenced by hybridautomatonParser::interval().
_tset264
antlr4::Token* hybridautomatonParser::IntervalContext::_tset264 = nullptr
Referenced by hybridautomatonParser::interval().
_tset284
antlr4::Token* hybridautomatonParser::IntervalContext::_tset284 = nullptr
Referenced by hybridautomatonParser::interval().
_tset297
antlr4::Token* hybridautomatonParser::IntervalContext::_tset297 = nullptr
Referenced by hybridautomatonParser::interval().
key_infinityToken
antlr4::Token* hybridautomatonParser::IntervalContext::key_infinityToken = nullptr
minusToken
antlr4::Token* hybridautomatonParser::IntervalContext::minusToken = nullptr
numberToken
antlr4::Token* hybridautomatonParser::IntervalContext::numberToken = nullptr
OP
std::vector<antlr4::Token *> hybridautomatonParser::IntervalContext::OP
Referenced by hybridautomatonParser::interval(), and irafhy::DefinitionVisitor::visitInterval().
plusToken
antlr4::Token* hybridautomatonParser::IntervalContext::plusToken = nullptr
scinumToken
antlr4::Token* hybridautomatonParser::IntervalContext::scinumToken = nullptr
VAL
std::vector<antlr4::Token *> hybridautomatonParser::IntervalContext::VAL
Referenced by hybridautomatonParser::interval(), and irafhy::DefinitionVisitor::visitInterval().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp