irafhy: definitionParser::VectorContext Class Reference
definitionParser::VectorContext Class Reference
#include <definitionParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset115 = nullptr
antlr4::Token * _tset135 = nullptr
Constructor & Destructor Documentation
VectorContext()
definitionParser::VectorContext::VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::VectorContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > definitionParser::VectorContext::COMMA ()
References definitionParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * definitionParser::VectorContext::COMMA (size_t i)
References definitionParser::COMMA.
enterRule()
void definitionParser::VectorContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterVector().
Referenced by definitionParser::vector().
exitRule()
void definitionParser::VectorContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitVector().
Referenced by definitionParser::vector().
getRuleIndex()
size_t definitionParser::VectorContext::getRuleIndex () const override virtual
References definitionParser::RuleVector.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::VectorContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > definitionParser::VectorContext::MINUS ()
References definitionParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * definitionParser::VectorContext::MINUS (size_t i)
References definitionParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > definitionParser::VectorContext::NUMBER ()
References definitionParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * definitionParser::VectorContext::NUMBER (size_t i)
References definitionParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > definitionParser::VectorContext::PLUS ()
References definitionParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * definitionParser::VectorContext::PLUS (size_t i)
References definitionParser::PLUS.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::VectorContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
Member Data Documentation
_tset115
antlr4::Token* definitionParser::VectorContext::_tset115 = nullptr
Referenced by definitionParser::vector().
_tset135
antlr4::Token* definitionParser::VectorContext::_tset135 = nullptr
Referenced by definitionParser::vector().
minusToken
antlr4::Token* definitionParser::VectorContext::minusToken = nullptr
OP
std::vector<antlr4::Token *> definitionParser::VectorContext::OP
Referenced by definitionParser::vector().
plusToken
antlr4::Token* definitionParser::VectorContext::plusToken = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp