irafhy: transitionsParser::AcothExpContext Class Reference
transitionsParser::AcothExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
AcothExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOTH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcothExpContext()
transitionsParser::AcothExpContext::AcothExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::AcothExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::AcothExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterAcothExp().
exitRule()
void transitionsParser::AcothExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitAcothExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::AcothExpContext::expression ()
KEY_ARCCOTH_FUNCTION()
tree::TerminalNode * transitionsParser::AcothExpContext::KEY_ARCCOTH_FUNCTION ()
References transitionsParser::KEY_ARCCOTH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcothExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcothExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp