irafhy: transitionsParser::VectorContext Class Reference
transitionsParser::VectorContext Class Reference
#include <transitionsParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset115 = nullptr
antlr4::Token * _tset135 = nullptr
Constructor & Destructor Documentation
VectorContext()
transitionsParser::VectorContext::VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::VectorContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::VectorContext::COMMA ()
References transitionsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * transitionsParser::VectorContext::COMMA (size_t i)
References transitionsParser::COMMA.
enterRule()
void transitionsParser::VectorContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterVector().
Referenced by transitionsParser::vector().
exitRule()
void transitionsParser::VectorContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitVector().
Referenced by transitionsParser::vector().
getRuleIndex()
size_t transitionsParser::VectorContext::getRuleIndex () const override virtual
References transitionsParser::RuleVector.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::VectorContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::VectorContext::MINUS ()
References transitionsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * transitionsParser::VectorContext::MINUS (size_t i)
References transitionsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::VectorContext::NUMBER ()
References transitionsParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * transitionsParser::VectorContext::NUMBER (size_t i)
References transitionsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::VectorContext::PLUS ()
References transitionsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * transitionsParser::VectorContext::PLUS (size_t i)
References transitionsParser::PLUS.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::VectorContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
Member Data Documentation
_tset115
antlr4::Token* transitionsParser::VectorContext::_tset115 = nullptr
Referenced by transitionsParser::vector().
_tset135
antlr4::Token* transitionsParser::VectorContext::_tset135 = nullptr
Referenced by transitionsParser::vector().
minusToken
antlr4::Token* transitionsParser::VectorContext::minusToken = nullptr
OP
std::vector<antlr4::Token *> transitionsParser::VectorContext::OP
Referenced by transitionsParser::vector().
plusToken
antlr4::Token* transitionsParser::VectorContext::plusToken = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp