irafhy: hybridautomatonParser::TransitionsContext Class Reference
hybridautomatonParser::TransitionsContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
TransitionsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_TRANSITIONS ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< JumpContext * > jump ()
JumpContext * jump (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
TransitionsContext()
hybridautomatonParser::TransitionsContext::TransitionsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::TransitionsContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::TransitionsContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterTransitions().
Referenced by hybridautomatonParser::transitions().
exitRule()
void hybridautomatonParser::TransitionsContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitTransitions().
Referenced by hybridautomatonParser::transitions().
getRuleIndex()
size_t hybridautomatonParser::TransitionsContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleTransitions.
jump() [1/2]
std::vector< hybridautomatonParser::JumpContext * > hybridautomatonParser::TransitionsContext::jump ()
Referenced by hybridautomatonParser::transitions().
jump() [2/2]
hybridautomatonParser::JumpContext * hybridautomatonParser::TransitionsContext::jump (size_t i)
KEY_TRANSITIONS()
tree::TerminalNode * hybridautomatonParser::TransitionsContext::KEY_TRANSITIONS ()
References hybridautomatonParser::KEY_TRANSITIONS.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::TransitionsContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::TransitionsContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp