irafhy: hybridautomatonParser::ConstantContext Class Reference
hybridautomatonParser::ConstantContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ConstantContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * NUMBER ()
antlr4::tree::TerminalNode * SCINUM ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ConstantContext()
hybridautomatonParser::ConstantContext::ConstantContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ConstantContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ConstantContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterConstant().
exitRule()
void hybridautomatonParser::ConstantContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitConstant().
NUMBER()
tree::TerminalNode * hybridautomatonParser::ConstantContext::NUMBER ()
References hybridautomatonParser::NUMBER.
SCINUM()
tree::TerminalNode * hybridautomatonParser::ConstantContext::SCINUM ()
References hybridautomatonParser::SCINUM.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp