irafhy: transitionsParser::ExpressionContext Class Reference
transitionsParser::ExpressionContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpressionContext() [1/2]
transitionsParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
ExpressionContext() [2/2]
transitionsParser::ExpressionContext::ExpressionContext () default
Member Function Documentation
copyFrom()
void transitionsParser::ExpressionContext::copyFrom (ExpressionContext * context)
Referenced by transitionsParser::AcosExpContext::AcosExpContext(), transitionsParser::AcoshExpContext::AcoshExpContext(), transitionsParser::AcotExpContext::AcotExpContext(), transitionsParser::AcothExpContext::AcothExpContext(), transitionsParser::AsinExpContext::AsinExpContext(), transitionsParser::AsinhExpContext::AsinhExpContext(), transitionsParser::AtanExpContext::AtanExpContext(), transitionsParser::AtanhExpContext::AtanhExpContext(), transitionsParser::ConstantContext::ConstantContext(), transitionsParser::CosExpContext::CosExpContext(), transitionsParser::CoshExpContext::CoshExpContext(), transitionsParser::CotExpContext::CotExpContext(), transitionsParser::CothExpContext::CothExpContext(), transitionsParser::ExpAddSubContext::ExpAddSubContext(), transitionsParser::ExpBraContext::ExpBraContext(), transitionsParser::ExpExpContext::ExpExpContext(), transitionsParser::ExpMulDivContext::ExpMulDivContext(), transitionsParser::LnExpContext::LnExpContext(), transitionsParser::LogExpContext::LogExpContext(), transitionsParser::NegExpContext::NegExpContext(), transitionsParser::NexpExpContext::NexpExpContext(), transitionsParser::PosExpContext::PosExpContext(), transitionsParser::PowExpContext::PowExpContext(), transitionsParser::SinExpContext::SinExpContext(), transitionsParser::SinhExpContext::SinhExpContext(), transitionsParser::SqrExpContext::SqrExpContext(), transitionsParser::SqrtExpContext::SqrtExpContext(), transitionsParser::TanExpContext::TanExpContext(), transitionsParser::TanhExpContext::TanhExpContext(), and transitionsParser::VariableContext::VariableContext().
getRuleIndex()
size_t transitionsParser::ExpressionContext::getRuleIndex () const override virtual
References transitionsParser::RuleExpression.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp