irafhy: settingsParser::NexpExpContext Class Reference
settingsParser::NexpExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
NexpExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_NATURAL_EXP_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NexpExpContext()
settingsParser::NexpExpContext::NexpExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::NexpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::NexpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterNexpExp().
exitRule()
void settingsParser::NexpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitNexpExp().
expression()
settingsParser::ExpressionContext * settingsParser::NexpExpContext::expression ()
KEY_NATURAL_EXP_FUNCTION()
tree::TerminalNode * settingsParser::NexpExpContext::KEY_NATURAL_EXP_FUNCTION ()
References settingsParser::KEY_NATURAL_EXP_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::NexpExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::NexpExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp