irafhy: settingsParser::AcotExpContext Class Reference
settingsParser::AcotExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
AcotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcotExpContext()
settingsParser::AcotExpContext::AcotExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::AcotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::AcotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterAcotExp().
exitRule()
void settingsParser::AcotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitAcotExp().
expression()
settingsParser::ExpressionContext * settingsParser::AcotExpContext::expression ()
KEY_ARCCOT_FUNCTION()
tree::TerminalNode * settingsParser::AcotExpContext::KEY_ARCCOT_FUNCTION ()
References settingsParser::KEY_ARCCOT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcotExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcotExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp