irafhy: locationsParser::PowExpContext Class Reference
locationsParser::PowExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
PowExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_POWER_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PowExpContext()
locationsParser::PowExpContext::PowExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::PowExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * locationsParser::PowExpContext::COMMA ()
References locationsParser::COMMA.
enterRule()
void locationsParser::PowExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterPowExp().
exitRule()
void locationsParser::PowExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitPowExp().
expression() [1/2]
std::vector< locationsParser::ExpressionContext * > locationsParser::PowExpContext::expression ()
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::PowExpContext::expression (size_t i)
KEY_POWER_FUNCTION()
tree::TerminalNode * locationsParser::PowExpContext::KEY_POWER_FUNCTION ()
References locationsParser::KEY_POWER_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::PowExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::PowExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp