irafhy: definitionParser::NexpExpContext Class Reference
definitionParser::NexpExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
NexpExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_NATURAL_EXP_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NexpExpContext()
definitionParser::NexpExpContext::NexpExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::NexpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::NexpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterNexpExp().
exitRule()
void definitionParser::NexpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitNexpExp().
expression()
definitionParser::ExpressionContext * definitionParser::NexpExpContext::expression ()
KEY_NATURAL_EXP_FUNCTION()
tree::TerminalNode * definitionParser::NexpExpContext::KEY_NATURAL_EXP_FUNCTION ()
References definitionParser::KEY_NATURAL_EXP_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::NexpExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::NexpExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp