irafhy: irafhy::SettingsVisitor Class Reference
irafhy::SettingsVisitor Class Reference
#include <settingsVisitor.h>
Public Member Functions
SettingsVisitor ()=default
constructor
SettingsVisitor (const std::vector< std::string > &vars)
constructor with given variables of hybrid automaton
antlrcpp::Any visitCondition (settingsParser::ConditionContext *ctx) override
visitor of condition
antlrcpp::Any visitPolytope (settingsParser::PolytopeContext *ctx) override
visitor of polytope
antlrcpp::Any visitHpolytope (settingsParser::HpolytopeContext *ctx) override
visitor of polytope which defined by half spaces
antlrcpp::Any visitVpolytope (settingsParser::VpolytopeContext *ctx) override
visitor of polytope which defined by vertices
antlrcpp::Any visitMatrix (settingsParser::MatrixContext *ctx) override
visitor of matrix
antlrcpp::Any visitVector (settingsParser::VectorContext *ctx) override
visitor of vector
antlrcpp::Any visitIntervalhull (settingsParser::IntervalhullContext *ctx) override
visitor of interval hull
antlrcpp::Any visitInterval (settingsParser::IntervalContext *ctx) override
visitor of interval
antlrcpp::Any visitTimeHorizonsetting (settingsParser::TimeHorizonsettingContext *ctx) override
visitor of duration
antlrcpp::Any visitStepSetting (settingsParser::StepSettingContext *ctx) override
visitor of step size
antlrcpp::Any visitPlotsetting (settingsParser::PlotsettingContext *ctx) override
visitor of plotting setting
antlrcpp::Any visitPrintsetting (settingsParser::PrintsettingContext *ctx) override
visitor of print setting
antlrcpp::Any visitGeometrysetting (settingsParser::GeometrysettingContext *ctx) override
visitor of geometry setting
antlrcpp::Any visitAnalysissetting (settingsParser::AnalysissettingContext *ctx) override
visitor of analysis setting
antlrcpp::Any visitMaxjumpsetting (settingsParser::MaxjumpsettingContext *ctx) override
visitor of max jumps setting
antlrcpp::Any visitStartmodelidsetting (settingsParser::StartmodelidsettingContext *ctx) override
visitor of start mode's id setting
antlrcpp::Any visitInitialconditionsetting (settingsParser::InitialconditionsettingContext *ctx) override
visitor of initial condition setting
antlrcpp::Any visitSetting (settingsParser::SettingContext *ctx) override
visitor of settings
antlrcpp::Any visitSqrtConstExp (settingsParser::SqrtConstExpContext *ctx) override
visitor of sqrt function of constant expression
antlrcpp::Any visitAcothConstExp (settingsParser::AcothConstExpContext *ctx) override
visitor of arc cot function of constant expression
antlrcpp::Any visitLogConstExp (settingsParser::LogConstExpContext *ctx) override
visitor of log function of constant expression
antlrcpp::Any visitTanhConstExp (settingsParser::TanhConstExpContext *ctx) override
visitor of tanh function of constant expression
antlrcpp::Any visitPowConstExp (settingsParser::PowConstExpContext *ctx) override
visitor of power function of constant expression
antlrcpp::Any visitPosConstExp (settingsParser::PosConstExpContext *ctx) override
visitor of positive function of constant expression
antlrcpp::Any visitAtanhConstExp (settingsParser::AtanhConstExpContext *ctx) override
visitor of arc tanh function of constant expression
antlrcpp::Any visitSqrConstExp (settingsParser::SqrConstExpContext *ctx) override
visitor of sqr function of constant expression
antlrcpp::Any visitConstExpBra (settingsParser::ConstExpBraContext *ctx) override
visitor of constant expression enclosed in brackets
antlrcpp::Any visitSinhConstExp (settingsParser::SinhConstExpContext *ctx) override
visitor of sinh function of constant expression
antlrcpp::Any visitAtanConstExp (settingsParser::AtanConstExpContext *ctx) override
visitor of arc tan function of constant expression
antlrcpp::Any visitAsinhConstExp (settingsParser::AsinhConstExpContext *ctx) override
visitor of arc sin function of constant exprssion
antlrcpp::Any visitConstExp (settingsParser::ConstExpContext *ctx) override
visitor of constant expression
antlrcpp::Any visitNegConstExp (settingsParser::NegConstExpContext *ctx) override
visitor of negative function of constant expression
antlrcpp::Any visitAsinConstExp (settingsParser::AsinConstExpContext *ctx) override
visitor of arc sin function of constant expression
antlrcpp::Any visitTanConstExp (settingsParser::TanConstExpContext *ctx) override
visitor of tan function of constant expression
antlrcpp::Any visitNexpConstExp (settingsParser::NexpConstExpContext *ctx) override
visitor of natural exponential function of constant expression
antlrcpp::Any visitCosConstExp (settingsParser::CosConstExpContext *ctx) override
visitor of cos function of constant expression
antlrcpp::Any visitConstExpMulDiv (settingsParser::ConstExpMulDivContext *ctx) override
visitor of multiplication or division of constant expression
antlrcpp::Any visitExpConstExp (settingsParser::ExpConstExpContext *ctx) override
visitor of exponential function of constant expression
antlrcpp::Any visitCotConstExp (settingsParser::CotConstExpContext *ctx) override
visitor of cot function of constant expression
antlrcpp::Any visitCoshConstExp (settingsParser::CoshConstExpContext *ctx) override
visitor of cosh function of constant expression
antlrcpp::Any visitAcoshConstExp (settingsParser::AcoshConstExpContext *ctx) override
visitor of arc cosh function of constant expression
antlrcpp::Any visitSinConstExp (settingsParser::SinConstExpContext *ctx) override
visitor of sin function of constant expression
antlrcpp::Any visitAcosConstExp (settingsParser::AcosConstExpContext *ctx) override
visitor of arc cos function of constant expression
antlrcpp::Any visitConstExpAddSub (settingsParser::ConstExpAddSubContext *ctx) override
visitor of addition or subtraction of constant expression
antlrcpp::Any visitLnConstExp (settingsParser::LnConstExpContext *ctx) override
visitor of ln function of constant expression
antlrcpp::Any visitAcotConstExp (settingsParser::AcotConstExpContext *ctx) override
visitor of arc cot function of constant expression
Private Member Functions
double strToNum (const std::string &numStr) const
convert given string to number
Private Attributes
std::vector< std::string > vars_
variables of hybrid automaton
Constructor & Destructor Documentation
SettingsVisitor() [1/2]
irafhy::SettingsVisitor::SettingsVisitor () default
constructor
SettingsVisitor() [2/2]
irafhy::SettingsVisitor::SettingsVisitor (const std::vector< std::string > & vars) explicit
constructor with given variables of hybrid automaton
Parameters
vars given variables of hybrid automaton
References vars_.
Member Function Documentation
strToNum()
double irafhy::SettingsVisitor::strToNum (const std::string & numStr) const private
convert given string to number
Parameters
numStr given string
Returns
resulting number
Referenced by visitConstExp(), visitMaxjumpsetting(), and visitStepSetting().
visitAcosConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAcosConstExp (settingsParser::AcosConstExpContext * ctx) override
visitor of arc cos function of constant expression
Parameters
ctx context of arc cos function
Returns
resulting constant
visitAcoshConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAcoshConstExp (settingsParser::AcoshConstExpContext * ctx) override
visitor of arc cosh function of constant expression
Parameters
ctx context of arc cosh function
Returns
resulting constant
visitAcotConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAcotConstExp (settingsParser::AcotConstExpContext * ctx) override
visitor of arc cot function of constant expression
Parameters
ctx context of arc cot function
Returns
resulting constant
visitAcothConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAcothConstExp (settingsParser::AcothConstExpContext * ctx) override
visitor of arc cot function of constant expression
Parameters
ctx context of arc cot function
Returns
resulting constant
visitAnalysissetting()
antlrcpp::Any irafhy::SettingsVisitor::visitAnalysissetting (settingsParser::AnalysissettingContext * ctx) override
visitor of analysis setting
Parameters
ctx context of analysis setting
Returns
type of analysis, forward or backward
References irafhy::BACKWARD, and irafhy::FORWARD.
visitAsinConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAsinConstExp (settingsParser::AsinConstExpContext * ctx) override
visitor of arc sin function of constant expression
Parameters
ctx context of arc sin function
Returns
resulting constant
visitAsinhConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAsinhConstExp (settingsParser::AsinhConstExpContext * ctx) override
visitor of arc sin function of constant exprssion
Parameters
ctx context of arc sin function
Returns
resulting constant
visitAtanConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAtanConstExp (settingsParser::AtanConstExpContext * ctx) override
visitor of arc tan function of constant expression
Parameters
ctx context of arc tan function
Returns
resulting constant
visitAtanhConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitAtanhConstExp (settingsParser::AtanhConstExpContext * ctx) override
visitor of arc tanh function of constant expression
Parameters
ctx context of arc tanh function
Returns
resulting constant
visitCondition()
antlrcpp::Any irafhy::SettingsVisitor::visitCondition (settingsParser::ConditionContext * ctx) override
visitor of condition
Parameters
ctx context of condition
Returns
condition instance
visitConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitConstExp (settingsParser::ConstExpContext * ctx) override
visitor of constant expression
Parameters
ctx context of constant expression
Returns
resulting constant
References strToNum().
visitConstExpAddSub()
antlrcpp::Any irafhy::SettingsVisitor::visitConstExpAddSub (settingsParser::ConstExpAddSubContext * ctx) override
visitor of addition or subtraction of constant expression
Parameters
ctx context of addition or subtraction
Returns
resulting constant
References irafhy::PLUS.
visitConstExpBra()
antlrcpp::Any irafhy::SettingsVisitor::visitConstExpBra (settingsParser::ConstExpBraContext * ctx) override
visitor of constant expression enclosed in brackets
Parameters
ctx context of brackets enclosing a constant expression
Returns
resulting constant
visitConstExpMulDiv()
antlrcpp::Any irafhy::SettingsVisitor::visitConstExpMulDiv (settingsParser::ConstExpMulDivContext * ctx) override
visitor of multiplication or division of constant expression
Parameters
ctx context of multiplication or division
Returns
resulting constant
References irafhy::MULTIPLY.
visitCosConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitCosConstExp (settingsParser::CosConstExpContext * ctx) override
visitor of cos function of constant expression
Parameters
ctx context of cos function
Returns
resulting constant
visitCoshConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitCoshConstExp (settingsParser::CoshConstExpContext * ctx) override
visitor of cosh function of constant expression
Parameters
ctx context of cosh function
Returns
resulting constant
visitCotConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitCotConstExp (settingsParser::CotConstExpContext * ctx) override
visitor of cot function of constant expression
Parameters
ctx context of cot function
Returns
resulting constant
visitExpConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitExpConstExp (settingsParser::ExpConstExpContext * ctx) override
visitor of exponential function of constant expression
Parameters
ctx context of exponential function
Returns
resulting constant
visitGeometrysetting()
antlrcpp::Any irafhy::SettingsVisitor::visitGeometrysetting (settingsParser::GeometrysettingContext * ctx) override
visitor of geometry setting
Parameters
ctx context of geometry setting
Returns
geometry setting in bool type
References irafhy::INTERVAL_HULL, and irafhy::POLYTOPE.
visitHpolytope()
antlrcpp::Any irafhy::SettingsVisitor::visitHpolytope (settingsParser::HpolytopeContext * ctx) override
visitor of polytope which defined by half spaces
Parameters
ctx context of polytope
Returns
polytope instance
visitInitialconditionsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitInitialconditionsetting (settingsParser::InitialconditionsettingContext * ctx) override
visitor of initial condition setting
Parameters
ctx context of initial condition setting
Returns
initial condition
References irafhy::Condition::Empty(), and vars_.
visitInterval()
antlrcpp::Any irafhy::SettingsVisitor::visitInterval (settingsParser::IntervalContext * ctx) override
visitor of interval
Parameters
ctx context of interval
Returns
interval instance
visitIntervalhull()
antlrcpp::Any irafhy::SettingsVisitor::visitIntervalhull (settingsParser::IntervalhullContext * ctx) override
visitor of interval hull
Parameters
ctx context of interval hull
Returns
interval hull instance
visitLnConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitLnConstExp (settingsParser::LnConstExpContext * ctx) override
visitor of ln function of constant expression
Parameters
ctx context of ln function
Returns
resulting constant
visitLogConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitLogConstExp (settingsParser::LogConstExpContext * ctx) override
visitor of log function of constant expression
Parameters
ctx context of log function
Returns
resulting constant
visitMatrix()
antlrcpp::Any irafhy::SettingsVisitor::visitMatrix (settingsParser::MatrixContext * ctx) override
visitor of matrix
Parameters
ctx context of matrix
Returns
matrix instance
visitMaxjumpsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitMaxjumpsetting (settingsParser::MaxjumpsettingContext * ctx) override
visitor of max jumps setting
Parameters
ctx context of max jump setting
Returns
number of max jumps
References strToNum().
visitNegConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitNegConstExp (settingsParser::NegConstExpContext * ctx) override
visitor of negative function of constant expression
Parameters
ctx context of negative function
Returns
resulting constant
visitNexpConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitNexpConstExp (settingsParser::NexpConstExpContext * ctx) override
visitor of natural exponential function of constant expression
Parameters
ctx context of natural exponential function
Returns
resulting constant
visitPlotsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitPlotsetting (settingsParser::PlotsettingContext * ctx) override
visitor of plotting setting
Parameters
ctx context of plotting setting
Returns
plotting setting in bool type
visitPolytope()
antlrcpp::Any irafhy::SettingsVisitor::visitPolytope (settingsParser::PolytopeContext * ctx) override
visitor of polytope
Parameters
ctx context of polytope
Returns
polytope instance
visitPosConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitPosConstExp (settingsParser::PosConstExpContext * ctx) override
visitor of positive function of constant expression
Parameters
ctx context of positive function
Returns
resulting constant
visitPowConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitPowConstExp (settingsParser::PowConstExpContext * ctx) override
visitor of power function of constant expression
Parameters
ctx context of power function
Returns
resulting constant
visitPrintsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitPrintsetting (settingsParser::PrintsettingContext * ctx) override
visitor of print setting
Parameters
ctx context of print setting
Returns
print setting in bool type
visitSetting()
antlrcpp::Any irafhy::SettingsVisitor::visitSetting (settingsParser::SettingContext * ctx) override
visitor of settings
Parameters
ctx context of settings
Returns
settings instance
References irafhy::Settings::setDuration(), irafhy::Settings::setGeometry(), irafhy::Settings::setInitCondition(), irafhy::Settings::setMaxJump(), irafhy::Settings::setPlot(), irafhy::Settings::setPrint(), irafhy::Settings::setStartModelID(), and irafhy::Settings::setStep().
visitSinConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitSinConstExp (settingsParser::SinConstExpContext * ctx) override
visitor of sin function of constant expression
Parameters
ctx context of sin function
Returns
resulting constant
visitSinhConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitSinhConstExp (settingsParser::SinhConstExpContext * ctx) override
visitor of sinh function of constant expression
Parameters
ctx context of sinh function
Returns
resulting constant
visitSqrConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitSqrConstExp (settingsParser::SqrConstExpContext * ctx) override
visitor of sqr function of constant expression
Parameters
ctx context of sqr function
Returns
resulting constant
visitSqrtConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitSqrtConstExp (settingsParser::SqrtConstExpContext * ctx) override
visitor of sqrt function of constant expression
Parameters
ctx context of sqrt function
Returns
resulting constant
visitStartmodelidsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitStartmodelidsetting (settingsParser::StartmodelidsettingContext * ctx) override
visitor of start mode's id setting
Parameters
ctx context of start mode's id
Returns
start mode's id in string form
visitStepSetting()
antlrcpp::Any irafhy::SettingsVisitor::visitStepSetting (settingsParser::StepSettingContext * ctx) override
visitor of step size
Parameters
ctx context of step size
Returns
step size in double type
References strToNum().
visitTanConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitTanConstExp (settingsParser::TanConstExpContext * ctx) override
visitor of tan function of constant expression
Parameters
ctx context of tanh function
Returns
resulting constant
visitTanhConstExp()
antlrcpp::Any irafhy::SettingsVisitor::visitTanhConstExp (settingsParser::TanhConstExpContext * ctx) override
visitor of tanh function of constant expression
Parameters
ctx context of tanh function
Returns
resulting constant
visitTimeHorizonsetting()
antlrcpp::Any irafhy::SettingsVisitor::visitTimeHorizonsetting (settingsParser::TimeHorizonsettingContext * ctx) override
visitor of duration
Parameters
ctx context of duration
Returns
duration instance
References vars_.
visitVector()
antlrcpp::Any irafhy::SettingsVisitor::visitVector (settingsParser::VectorContext * ctx) override
visitor of vector
Parameters
ctx context of vector
Returns
vector instance
visitVpolytope()
antlrcpp::Any irafhy::SettingsVisitor::visitVpolytope (settingsParser::VpolytopeContext * ctx) override
visitor of polytope which defined by vertices
Parameters
ctx context of polytope
Returns
polytope instance
Member Data Documentation
vars_
std::vector<std::string> irafhy::SettingsVisitor::vars_ private
variables of hybrid automaton
Referenced by SettingsVisitor(), visitInitialconditionsetting(), and visitTimeHorizonsetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/visitor/settingsVisitor.h
/home/jianqiang/CLionProjects/irafhy/src/utility/parser/visitor/settingsVisitor.cpp