irafhy: hybridautomatonParser::ConstraintContext Class Reference
hybridautomatonParser::ConstraintContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EQUAL ()
antlr4::tree::TerminalNode * UNEQUAL ()
antlr4::tree::TerminalNode * GEQ ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * LSS ()
antlr4::tree::TerminalNode * GTR ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * RELATION = nullptr
Constructor & Destructor Documentation
ConstraintContext()
hybridautomatonParser::ConstraintContext::ConstraintContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ConstraintContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ConstraintContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterConstraint().
Referenced by hybridautomatonParser::constraint().
EQUAL()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::EQUAL ()
References hybridautomatonParser::EQUAL.
exitRule()
void hybridautomatonParser::ConstraintContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitConstraint().
Referenced by hybridautomatonParser::constraint().
expression() [1/2]
std::vector< hybridautomatonParser::ExpressionContext * > hybridautomatonParser::ConstraintContext::expression ()
Referenced by hybridautomatonParser::constraint(), and irafhy::ConstraintsVisitor::visitConstraint().
expression() [2/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::ConstraintContext::expression (size_t i)
GEQ()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::GEQ ()
References hybridautomatonParser::GEQ.
getRuleIndex()
size_t hybridautomatonParser::ConstraintContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleConstraint.
GTR()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::GTR ()
References hybridautomatonParser::GTR.
LEQ()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::LEQ ()
References hybridautomatonParser::LEQ.
LSS()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::LSS ()
References hybridautomatonParser::LSS.
UNEQUAL()
tree::TerminalNode * hybridautomatonParser::ConstraintContext::UNEQUAL ()
References hybridautomatonParser::UNEQUAL.
Member Data Documentation
RELATION
antlr4::Token* hybridautomatonParser::ConstraintContext::RELATION = nullptr
Referenced by hybridautomatonParser::constraint(), and irafhy::ConstraintsVisitor::visitConstraint().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp