irafhy: definitionParser::SqrExpContext Class Reference
definitionParser::SqrExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
SqrExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SQR_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SqrExpContext()
definitionParser::SqrExpContext::SqrExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::SqrExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::SqrExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterSqrExp().
exitRule()
void definitionParser::SqrExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitSqrExp().
expression()
definitionParser::ExpressionContext * definitionParser::SqrExpContext::expression ()
KEY_SQR_FUNCTION()
tree::TerminalNode * definitionParser::SqrExpContext::KEY_SQR_FUNCTION ()
References definitionParser::KEY_SQR_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::SqrExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::SqrExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp