irafhy: hybridautomatonParser::NegExpContext Class Reference
hybridautomatonParser::NegExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
NegExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * MINUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NegExpContext()
hybridautomatonParser::NegExpContext::NegExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::NegExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::NegExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterNegExp().
exitRule()
void hybridautomatonParser::NegExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitNegExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::NegExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitNegExp().
MINUS()
tree::TerminalNode * hybridautomatonParser::NegExpContext::MINUS ()
References hybridautomatonParser::MINUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp