irafhy: hybridautomatonParser::JumpContext Class Reference
hybridautomatonParser::JumpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
JumpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_JUMP ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
DirectionContext * direction ()
GuardconditionContext * guardcondition ()
ResetmapContext * resetmap ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
JumpContext()
hybridautomatonParser::JumpContext::JumpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::JumpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
direction()
hybridautomatonParser::DirectionContext * hybridautomatonParser::JumpContext::direction ()
Referenced by hybridautomatonParser::jump().
enterRule()
void hybridautomatonParser::JumpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterJump().
Referenced by hybridautomatonParser::jump().
exitRule()
void hybridautomatonParser::JumpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitJump().
Referenced by hybridautomatonParser::jump().
getRuleIndex()
size_t hybridautomatonParser::JumpContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleJump.
guardcondition()
hybridautomatonParser::GuardconditionContext * hybridautomatonParser::JumpContext::guardcondition ()
Referenced by hybridautomatonParser::jump().
KEY_JUMP()
tree::TerminalNode * hybridautomatonParser::JumpContext::KEY_JUMP ()
References hybridautomatonParser::KEY_JUMP.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::JumpContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
resetmap()
hybridautomatonParser::ResetmapContext * hybridautomatonParser::JumpContext::resetmap ()
Referenced by hybridautomatonParser::jump().
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::JumpContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp