irafhy: locationsParser::SystemContext Class Reference
locationsParser::SystemContext Class Reference
#include <locationsParser.h>
Public Member Functions
SystemContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FormulaContext * > formula ()
FormulaContext * formula (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SystemContext()
locationsParser::SystemContext::SystemContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::SystemContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::SystemContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterSystem().
Referenced by locationsParser::system().
exitRule()
void locationsParser::SystemContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitSystem().
Referenced by locationsParser::system().
formula() [1/2]
std::vector< locationsParser::FormulaContext * > locationsParser::SystemContext::formula ()
Referenced by locationsParser::system().
formula() [2/2]
locationsParser::FormulaContext * locationsParser::SystemContext::formula (size_t i)
getRuleIndex()
size_t locationsParser::SystemContext::getRuleIndex () const override virtual
References locationsParser::RuleSystem.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp