irafhy: definitionParser::ExpExpContext Class Reference
definitionParser::ExpExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
ExpExpContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EXPONENT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpExpContext()
definitionParser::ExpExpContext::ExpExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ExpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ExpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterExpExp().
exitRule()
void definitionParser::ExpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitExpExp().
EXPONENT()
tree::TerminalNode * definitionParser::ExpExpContext::EXPONENT ()
References definitionParser::EXPONENT.
expression() [1/2]
std::vector< definitionParser::ExpressionContext * > definitionParser::ExpExpContext::expression ()
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::ExpExpContext::expression (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp