irafhy: hybridautomatonParser::SinExpContext Class Reference
hybridautomatonParser::SinExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
SinExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SIN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinExpContext()
hybridautomatonParser::SinExpContext::SinExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::SinExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::SinExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterSinExp().
exitRule()
void hybridautomatonParser::SinExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitSinExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::SinExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitSinExp().
KEY_SIN_FUNCTION()
tree::TerminalNode * hybridautomatonParser::SinExpContext::KEY_SIN_FUNCTION ()
References hybridautomatonParser::KEY_SIN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SinExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SinExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp