irafhy: irafhy::Constraints Class Reference
irafhy::Constraints Class Reference
#include <constraints.h>
Public Member Functions
Constraints ()=default
constructor
Constraints (const std::vector< Constraint > &inequalities, std::size_t dimension)
constructor with given inequalities and dimension
~Constraints ()=default
destructor
std::size_t size () const
get the size of the inequalities
std::size_t dimension () const
get the dimension of the system
CONSTRAINTS_SOLUTION isSatisfy (const capd::interval &t, const std::vector< capd::interval > &in, const std::vector< capd::interval > &params) const
check if the given values inside the target domain defined by the given constraints or not
Private Attributes
std::vector< Constraint > inequalities_
constraints of the system
std::size_t dimension_ = 0
dimension of the system
Friends
std::ostream & operator<< (std::ostream &out, const Constraints &rhs)
out the given constraints to standard out stream
Constructor & Destructor Documentation
Constraints() [1/2]
irafhy::Constraints::Constraints () default
constructor
Constraints() [2/2]
irafhy::Constraints::Constraints (const std::vector< Constraint > & inequalities, std::size_t dimension)
constructor with given inequalities and dimension
Parameters
inequalities given inequalities
dimension dimension of the system
References dimension(), dimension_, and inequalities_.
~Constraints()
irafhy::Constraints::~Constraints () default
destructor
Member Function Documentation
dimension()
std::size_t irafhy::Constraints::dimension () const
get the dimension of the system
Returns
the dimension of the system
References dimension_.
Referenced by irafhy::CSPSolver::branchPruneSolve(), and Constraints().
isSatisfy()
CONSTRAINTS_SOLUTION irafhy::Constraints::isSatisfy (const capd::interval & t, const std::vector< capd::interval > & in, const std::vector< capd::interval > & params) const
check if the given values inside the target domain defined by the given constraints or not
Parameters
t given time interval value
in input values
params parameters necessary
Returns
TRUE if the given values hold all the relations of the constraints
References irafhy::ALL_SATISFIED, irafhy::ALL_UNSATISFIED, inequalities_, and irafhy::PARTIAL_SATISFIED.
Referenced by irafhy::CSPSolver::branchPruneSolve().
size()
std::size_t irafhy::Constraints::size () const
get the size of the inequalities
Returns
the size of the inequalities
References inequalities_.
Referenced by irafhy::CSPSolver::branchPruneSolve().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Constraints & rhs) friend
out the given constraints to standard out stream
Parameters
out given out stream
rhs given right hand side constraints
Returns
resulting out stream
Member Data Documentation
dimension_
std::size_t irafhy::Constraints::dimension_ = 0 private
dimension of the system
Referenced by Constraints(), and dimension().
inequalities_
std::vector<Constraint> irafhy::Constraints::inequalities_ private
constraints of the system
Referenced by Constraints(), isSatisfy(), irafhy::operator<<(), and size().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/representation/formal/basic/constraints.h
/home/jianqiang/CLionProjects/irafhy/src/representation/formal/basic/constraints.cpp