irafhy: transitionsParser::MatrixContext Class Reference
transitionsParser::MatrixContext Class Reference
#include <transitionsParser.h>
Public Member Functions
MatrixContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MATRIX ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
antlr4::tree::TerminalNode * KEY_ROW_MAJOR_ORDER ()
antlr4::tree::TerminalNode * KEY_COL_MAJOR_ORDER ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * MAJOR_ORDER = nullptr
Constructor & Destructor Documentation
MatrixContext()
transitionsParser::MatrixContext::MatrixContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::MatrixContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::MatrixContext::COMMA ()
References transitionsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * transitionsParser::MatrixContext::COMMA (size_t i)
References transitionsParser::COMMA.
enterRule()
void transitionsParser::MatrixContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterMatrix().
Referenced by transitionsParser::matrix().
exitRule()
void transitionsParser::MatrixContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitMatrix().
Referenced by transitionsParser::matrix().
getRuleIndex()
size_t transitionsParser::MatrixContext::getRuleIndex () const override virtual
References transitionsParser::RuleMatrix.
KEY_COL_MAJOR_ORDER()
tree::TerminalNode * transitionsParser::MatrixContext::KEY_COL_MAJOR_ORDER ()
References transitionsParser::KEY_COL_MAJOR_ORDER.
KEY_MATRIX()
tree::TerminalNode * transitionsParser::MatrixContext::KEY_MATRIX ()
References transitionsParser::KEY_MATRIX.
KEY_ROW_MAJOR_ORDER()
tree::TerminalNode * transitionsParser::MatrixContext::KEY_ROW_MAJOR_ORDER ()
References transitionsParser::KEY_ROW_MAJOR_ORDER.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::MatrixContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::MatrixContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< transitionsParser::VectorContext * > transitionsParser::MatrixContext::vector ()
Referenced by transitionsParser::matrix().
vector() [2/2]
transitionsParser::VectorContext * transitionsParser::MatrixContext::vector (size_t i)
Member Data Documentation
MAJOR_ORDER
antlr4::Token* transitionsParser::MatrixContext::MAJOR_ORDER = nullptr
Referenced by transitionsParser::matrix().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp