irafhy: transitionsParser::JumpContext Class Reference
transitionsParser::JumpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
JumpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_JUMP ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
DirectionContext * direction ()
GuardconditionContext * guardcondition ()
ResetmapContext * resetmap ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
JumpContext()
transitionsParser::JumpContext::JumpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::JumpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
direction()
transitionsParser::DirectionContext * transitionsParser::JumpContext::direction ()
Referenced by transitionsParser::jump().
enterRule()
void transitionsParser::JumpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterJump().
Referenced by transitionsParser::jump().
exitRule()
void transitionsParser::JumpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitJump().
Referenced by transitionsParser::jump().
getRuleIndex()
size_t transitionsParser::JumpContext::getRuleIndex () const override virtual
References transitionsParser::RuleJump.
guardcondition()
transitionsParser::GuardconditionContext * transitionsParser::JumpContext::guardcondition ()
Referenced by transitionsParser::jump().
KEY_JUMP()
tree::TerminalNode * transitionsParser::JumpContext::KEY_JUMP ()
References transitionsParser::KEY_JUMP.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::JumpContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
resetmap()
transitionsParser::ResetmapContext * transitionsParser::JumpContext::resetmap ()
Referenced by transitionsParser::jump().
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::JumpContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp