irafhy: settingsParser::ExpressionContext Class Reference
settingsParser::ExpressionContext Class Reference
#include <settingsParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpressionContext() [1/2]
settingsParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
ExpressionContext() [2/2]
settingsParser::ExpressionContext::ExpressionContext () default
Member Function Documentation
copyFrom()
void settingsParser::ExpressionContext::copyFrom (ExpressionContext * context)
Referenced by settingsParser::AcosExpContext::AcosExpContext(), settingsParser::AcoshExpContext::AcoshExpContext(), settingsParser::AcotExpContext::AcotExpContext(), settingsParser::AcothExpContext::AcothExpContext(), settingsParser::AsinExpContext::AsinExpContext(), settingsParser::AsinhExpContext::AsinhExpContext(), settingsParser::AtanExpContext::AtanExpContext(), settingsParser::AtanhExpContext::AtanhExpContext(), settingsParser::ConstantContext::ConstantContext(), settingsParser::CosExpContext::CosExpContext(), settingsParser::CoshExpContext::CoshExpContext(), settingsParser::CotExpContext::CotExpContext(), settingsParser::CothExpContext::CothExpContext(), settingsParser::ExpAddSubContext::ExpAddSubContext(), settingsParser::ExpBraContext::ExpBraContext(), settingsParser::ExpExpContext::ExpExpContext(), settingsParser::ExpMulDivContext::ExpMulDivContext(), settingsParser::LnExpContext::LnExpContext(), settingsParser::LogExpContext::LogExpContext(), settingsParser::NegExpContext::NegExpContext(), settingsParser::NexpExpContext::NexpExpContext(), settingsParser::PosExpContext::PosExpContext(), settingsParser::PowExpContext::PowExpContext(), settingsParser::SinExpContext::SinExpContext(), settingsParser::SinhExpContext::SinhExpContext(), settingsParser::SqrExpContext::SqrExpContext(), settingsParser::SqrtExpContext::SqrtExpContext(), settingsParser::TanExpContext::TanExpContext(), settingsParser::TanhExpContext::TanhExpContext(), and settingsParser::VariableContext::VariableContext().
getRuleIndex()
size_t settingsParser::ExpressionContext::getRuleIndex () const override virtual
References settingsParser::RuleExpression.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp