irafhy: settingsParser::ConstantContext Class Reference
settingsParser::ConstantContext Class Reference
#include <settingsParser.h>
Public Member Functions
ConstantContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * NUMBER ()
antlr4::tree::TerminalNode * SCINUM ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ConstantContext()
settingsParser::ConstantContext::ConstantContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ConstantContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::ConstantContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterConstant().
exitRule()
void settingsParser::ConstantContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitConstant().
NUMBER()
tree::TerminalNode * settingsParser::ConstantContext::NUMBER ()
References settingsParser::NUMBER.
SCINUM()
tree::TerminalNode * settingsParser::ConstantContext::SCINUM ()
References settingsParser::SCINUM.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp