irafhy: settingsParser::SettingContext Class Reference
settingsParser::SettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
SettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_SETTINGS ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< TimeHorizonsettingContext * > timeHorizonsetting ()
TimeHorizonsettingContext * timeHorizonsetting (size_t i)
std::vector< StepSettingContext * > stepSetting ()
StepSettingContext * stepSetting (size_t i)
std::vector< PlotsettingContext * > plotsetting ()
PlotsettingContext * plotsetting (size_t i)
std::vector< PrintsettingContext * > printsetting ()
PrintsettingContext * printsetting (size_t i)
std::vector< AnalysissettingContext * > analysissetting ()
AnalysissettingContext * analysissetting (size_t i)
std::vector< GeometrysettingContext * > geometrysetting ()
GeometrysettingContext * geometrysetting (size_t i)
std::vector< MaxjumpsettingContext * > maxjumpsetting ()
MaxjumpsettingContext * maxjumpsetting (size_t i)
std::vector< StartmodelidsettingContext * > startmodelidsetting ()
StartmodelidsettingContext * startmodelidsetting (size_t i)
std::vector< InitialconditionsettingContext * > initialconditionsetting ()
InitialconditionsettingContext * initialconditionsetting (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SettingContext()
settingsParser::SettingContext::SettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::SettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
analysissetting() [1/2]
std::vector< settingsParser::AnalysissettingContext * > settingsParser::SettingContext::analysissetting ()
Referenced by settingsParser::setting().
analysissetting() [2/2]
settingsParser::AnalysissettingContext * settingsParser::SettingContext::analysissetting (size_t i)
enterRule()
void settingsParser::SettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterSetting().
Referenced by settingsParser::setting().
exitRule()
void settingsParser::SettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitSetting().
Referenced by settingsParser::setting().
geometrysetting() [1/2]
std::vector< settingsParser::GeometrysettingContext * > settingsParser::SettingContext::geometrysetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
geometrysetting() [2/2]
settingsParser::GeometrysettingContext * settingsParser::SettingContext::geometrysetting (size_t i)
getRuleIndex()
size_t settingsParser::SettingContext::getRuleIndex () const override virtual
References settingsParser::RuleSetting.
initialconditionsetting() [1/2]
std::vector< settingsParser::InitialconditionsettingContext * > settingsParser::SettingContext::initialconditionsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
initialconditionsetting() [2/2]
settingsParser::InitialconditionsettingContext * settingsParser::SettingContext::initialconditionsetting (size_t i)
KEY_SETTINGS()
tree::TerminalNode * settingsParser::SettingContext::KEY_SETTINGS ()
References settingsParser::KEY_SETTINGS.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::SettingContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
maxjumpsetting() [1/2]
std::vector< settingsParser::MaxjumpsettingContext * > settingsParser::SettingContext::maxjumpsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
maxjumpsetting() [2/2]
settingsParser::MaxjumpsettingContext * settingsParser::SettingContext::maxjumpsetting (size_t i)
plotsetting() [1/2]
std::vector< settingsParser::PlotsettingContext * > settingsParser::SettingContext::plotsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
plotsetting() [2/2]
settingsParser::PlotsettingContext * settingsParser::SettingContext::plotsetting (size_t i)
printsetting() [1/2]
std::vector< settingsParser::PrintsettingContext * > settingsParser::SettingContext::printsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
printsetting() [2/2]
settingsParser::PrintsettingContext * settingsParser::SettingContext::printsetting (size_t i)
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::SettingContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
startmodelidsetting() [1/2]
std::vector< settingsParser::StartmodelidsettingContext * > settingsParser::SettingContext::startmodelidsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
startmodelidsetting() [2/2]
settingsParser::StartmodelidsettingContext * settingsParser::SettingContext::startmodelidsetting (size_t i)
stepSetting() [1/2]
std::vector< settingsParser::StepSettingContext * > settingsParser::SettingContext::stepSetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
stepSetting() [2/2]
settingsParser::StepSettingContext * settingsParser::SettingContext::stepSetting (size_t i)
timeHorizonsetting() [1/2]
std::vector< settingsParser::TimeHorizonsettingContext * > settingsParser::SettingContext::timeHorizonsetting ()
Referenced by settingsParser::setting(), and irafhy::SettingsVisitor::visitSetting().
timeHorizonsetting() [2/2]
settingsParser::TimeHorizonsettingContext * settingsParser::SettingContext::timeHorizonsetting (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp