irafhy: locationsParser::FormulaContext Class Reference
locationsParser::FormulaContext Class Reference
#include <locationsParser.h>
Public Member Functions
FormulaContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * ASSIGN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * DERIVATIVE ()
IntervalContext * interval ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FormulaContext()
locationsParser::FormulaContext::FormulaContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::FormulaContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ASSIGN()
tree::TerminalNode * locationsParser::FormulaContext::ASSIGN ()
References locationsParser::ASSIGN.
DERIVATIVE()
tree::TerminalNode * locationsParser::FormulaContext::DERIVATIVE ()
References locationsParser::DERIVATIVE.
enterRule()
void locationsParser::FormulaContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterFormula().
Referenced by locationsParser::formula().
exitRule()
void locationsParser::FormulaContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitFormula().
Referenced by locationsParser::formula().
expression()
locationsParser::ExpressionContext * locationsParser::FormulaContext::expression ()
Referenced by locationsParser::formula().
getRuleIndex()
size_t locationsParser::FormulaContext::getRuleIndex () const override virtual
References locationsParser::RuleFormula.
interval()
locationsParser::IntervalContext * locationsParser::FormulaContext::interval ()
Referenced by locationsParser::formula().
VARIABLE()
tree::TerminalNode * locationsParser::FormulaContext::VARIABLE ()
References locationsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp