irafhy: irafhy::ConvexHull Class Reference
irafhy::ConvexHull Class Reference
#include <convexHull.hpp>
Static Public Member Functions
static convexConstraints constraints (const std::vector< Point > &points)
constructor of convex hull with given points
Member Function Documentation
constraints()
static convexConstraints irafhy::ConvexHull::constraints (const std::vector< Point > & points) inline static
constructor of convex hull with given points
Parameters
points given points
Returns
the resulting convex hull
References irafhy::convexConstraints::convexConstraints(), irafhy::convexConstraints::dimension(), irafhy::convexConstraints::halfSpaceConstraints(), irafhy::convexConstraints::neighborHalfSpaces(), and irafhy::convexConstraints::pointConstraints().
Referenced by irafhy::Polytope::Polytope(), and irafhy::Polytope::verticesEnumerationDualPly().
The documentation for this class was generated from the following file:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/compGeometry/convexHull.hpp