irafhy: definitionParser::TanExpContext Class Reference
definitionParser::TanExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
TanExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TAN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanExpContext()
definitionParser::TanExpContext::TanExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::TanExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::TanExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterTanExp().
exitRule()
void definitionParser::TanExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitTanExp().
expression()
definitionParser::ExpressionContext * definitionParser::TanExpContext::expression ()
KEY_TAN_FUNCTION()
tree::TerminalNode * definitionParser::TanExpContext::KEY_TAN_FUNCTION ()
References definitionParser::KEY_TAN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::TanExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::TanExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp