irafhy: definitionParser::IntervalContext Class Reference
definitionParser::IntervalContext Class Reference
#include <definitionParser.h>
Public Member Functions
IntervalContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTSQUAREBRACKET ()
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTSQUAREBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< antlr4::tree::TerminalNode * > SCINUM ()
antlr4::tree::TerminalNode * SCINUM (size_t i)
std::vector< antlr4::tree::TerminalNode * > KEY_INFINITY ()
antlr4::tree::TerminalNode * KEY_INFINITY (size_t i)
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset251 = nullptr
antlr4::Token * numberToken = nullptr
std::vector< antlr4::Token * > VAL
antlr4::Token * scinumToken = nullptr
antlr4::Token * key_infinityToken = nullptr
antlr4::Token * _tset264 = nullptr
antlr4::Token * _tset284 = nullptr
antlr4::Token * _tset297 = nullptr
Constructor & Destructor Documentation
IntervalContext()
definitionParser::IntervalContext::IntervalContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::IntervalContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * definitionParser::IntervalContext::COMMA ()
References definitionParser::COMMA.
enterRule()
void definitionParser::IntervalContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterInterval().
Referenced by definitionParser::interval().
exitRule()
void definitionParser::IntervalContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitInterval().
Referenced by definitionParser::interval().
getRuleIndex()
size_t definitionParser::IntervalContext::getRuleIndex () const override virtual
References definitionParser::RuleInterval.
KEY_INFINITY() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalContext::KEY_INFINITY ()
References definitionParser::KEY_INFINITY.
KEY_INFINITY() [2/2]
tree::TerminalNode * definitionParser::IntervalContext::KEY_INFINITY (size_t i)
References definitionParser::KEY_INFINITY.
LEFTSQUAREBRACKET()
tree::TerminalNode * definitionParser::IntervalContext::LEFTSQUAREBRACKET ()
References definitionParser::LEFTSQUAREBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalContext::MINUS ()
References definitionParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * definitionParser::IntervalContext::MINUS (size_t i)
References definitionParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalContext::NUMBER ()
References definitionParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * definitionParser::IntervalContext::NUMBER (size_t i)
References definitionParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalContext::PLUS ()
References definitionParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * definitionParser::IntervalContext::PLUS (size_t i)
References definitionParser::PLUS.
RIGHTSQUAREBRACKET()
tree::TerminalNode * definitionParser::IntervalContext::RIGHTSQUAREBRACKET ()
References definitionParser::RIGHTSQUAREBRACKET.
SCINUM() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalContext::SCINUM ()
References definitionParser::SCINUM.
SCINUM() [2/2]
tree::TerminalNode * definitionParser::IntervalContext::SCINUM (size_t i)
References definitionParser::SCINUM.
Member Data Documentation
_tset251
antlr4::Token* definitionParser::IntervalContext::_tset251 = nullptr
Referenced by definitionParser::interval().
_tset264
antlr4::Token* definitionParser::IntervalContext::_tset264 = nullptr
Referenced by definitionParser::interval().
_tset284
antlr4::Token* definitionParser::IntervalContext::_tset284 = nullptr
Referenced by definitionParser::interval().
_tset297
antlr4::Token* definitionParser::IntervalContext::_tset297 = nullptr
Referenced by definitionParser::interval().
key_infinityToken
antlr4::Token* definitionParser::IntervalContext::key_infinityToken = nullptr
minusToken
antlr4::Token* definitionParser::IntervalContext::minusToken = nullptr
numberToken
antlr4::Token* definitionParser::IntervalContext::numberToken = nullptr
OP
std::vector<antlr4::Token *> definitionParser::IntervalContext::OP
Referenced by definitionParser::interval().
plusToken
antlr4::Token* definitionParser::IntervalContext::plusToken = nullptr
scinumToken
antlr4::Token* definitionParser::IntervalContext::scinumToken = nullptr
VAL
std::vector<antlr4::Token *> definitionParser::IntervalContext::VAL
Referenced by definitionParser::interval().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp