irafhy: transitionsParser::AcosExpContext Class Reference
transitionsParser::AcosExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
AcosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcosExpContext()
transitionsParser::AcosExpContext::AcosExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::AcosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::AcosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterAcosExp().
exitRule()
void transitionsParser::AcosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitAcosExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::AcosExpContext::expression ()
KEY_ARCCOS_FUNCTION()
tree::TerminalNode * transitionsParser::AcosExpContext::KEY_ARCCOS_FUNCTION ()
References transitionsParser::KEY_ARCCOS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcosExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::AcosExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp