irafhy: locationsParser Class Reference
locationsParser Class Reference
#include <locationsParser.h>
Classes
class AcosExpContext
class AcoshExpContext
class AcotExpContext
class AcothExpContext
class AsinExpContext
class AsinhExpContext
class AtanExpContext
class AtanhExpContext
class ConditionContext
class ConstantContext
class ConstraintContext
class ConstraintsContext
class CosExpContext
class CoshExpContext
class CotExpContext
class CothExpContext
class ExpAddSubContext
class ExpBraContext
class ExpExpContext
class ExpMulDivContext
class ExpressionContext
class FlowsContext
class FormulaContext
class HpolytopeContext
struct Initializer
class IntervalContext
class IntervalhullContext
class InvariantconditionContext
class LnExpContext
class LocationsContext
class LogExpContext
class MatrixContext
class ModelContext
class ModelidContext
class NegExpContext
class NexpExpContext
class PolytopeContext
class PosExpContext
class PowExpContext
class SinExpContext
class SinhExpContext
class SqrExpContext
class SqrtExpContext
class SystemContext
class TanExpContext
class TanhExpContext
class VariableContext
class VectorContext
class VpolytopeContext
Public Types
enum {
KEY_LOCATIONS = 1, KEY_MODEL = 2, KEY_FLOWS = 3, KEY_INVARIANT_CONDITIONS = 4,
KEY_SETTINGS = 5, KEY_ANALYSIS = 6, KEY_ANALYSIS_FORWARD = 7, KEY_ANALYSIS_BACKWARD = 8,
KEY_TIME_HORIZON = 9, KEY_STEP = 10, KEY_GEOMETRY = 11, KEY_PLOT_FLAG = 12,
KEY_PRINT_FLAG = 13, KEY_MAX_JUMP = 14, KEY_START_MODEL_ID = 15, KEY_INITIAL_CONDITION = 16,
KEY_TRANSITIONS = 17, KEY_URGENT = 18, KEY_JUMP = 19, KEY_DIRECTION = 20,
KEY_GUARD_CONDITIONS = 21, KEY_RESET_MAP = 22, KEY_INTERVAL_HULL = 23, KEY_POLYTOPE = 24,
KEY_CONDITION = 25, KEY_MATRIX = 26, KEY_ROW_MAJOR_ORDER = 27, KEY_COL_MAJOR_ORDER = 28,
KEY_SIN_FUNCTION = 29, KEY_ARCSIN_FUNCTION = 30, KEY_COS_FUNCTION = 31, KEY_ARCCOS_FUNCTION = 32,
KEY_TAN_FUNCTION = 33, KEY_ARCTAN_FUNCTION = 34, KEY_COT_FUNCTION = 35, KEY_ARCCOT_FUNCTION = 36,
KEY_LN_FUNCTION = 37, KEY_LOG_FUNCTION = 38, KEY_NATURAL_EXP_FUNCTION = 39, KEY_SINH_FUNCTION = 40,
KEY_ARCSINH_FUNCTION = 41, KEY_COSH_FUNCTION = 42, KEY_ARCCOSH_FUNCTION = 43, KEY_TANH_FUNCTION = 44,
KEY_ARCTANH_FUNCTION = 45, KEY_COTH_FUNCTION = 46, KEY_ARCCOTH_FUNCTION = 47, KEY_SQR_FUNCTION = 48,
KEY_SQRT_FUNCTION = 49, KEY_ABS_FUNCTION = 50, KEY_POWER_FUNCTION = 51, KEY_NAME = 52,
KEY_SWITCH_ON = 53, KEY_SWITCH_OFF = 54, KEY_BOOL_TRUE = 55, KEY_BOOL_FALSE = 56,
KEY_INFINITY = 57, SCINUM = 58, NUMBER = 59, VARIABLE = 60,
LEFTCURLYBRACKET = 61, RIGHTCURLYBRACKET = 62, LEFTROUNDBRACKET = 63, RIGHTROUNDBRACKET = 64,
LEFTSQUAREBRACKET = 65, RIGHTSQUAREBRACKET = 66, COMMA = 67, EQUAL = 68,
UNEQUAL = 69, GEQ = 70, LEQ = 71, LSS = 72,
GTR = 73, DEFINE = 74, FROMTO = 75, ASSIGN = 76,
PLUS = 77, MINUS = 78, MULTIPLY = 79, DIVIDE = 80,
EXPONENT = 81, DERIVATIVE = 82, COMMENT = 83, WS = 84
}
enum {
RuleModelid = 0, RuleFlows = 1, RuleInvariantcondition = 2, RuleModel = 3,
RuleLocations = 4, RuleCondition = 5, RulePolytope = 6, RuleHpolytope = 7,
RuleVpolytope = 8, RuleMatrix = 9, RuleVector = 10, RuleIntervalhull = 11,
RuleConstraints = 12, RuleConstraint = 13, RuleSystem = 14, RuleFormula = 15,
RuleInterval = 16, RuleExpression = 17
}
Public Member Functions
locationsParser (antlr4::TokenStream *input)
~locationsParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
ModelidContext * modelid ()
FlowsContext * flows ()
InvariantconditionContext * invariantcondition ()
ModelContext * model ()
LocationsContext * locations ()
ConditionContext * condition ()
PolytopeContext * polytope ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
MatrixContext * matrix ()
VectorContext * vector ()
IntervalhullContext * intervalhull ()
ConstraintsContext * constraints ()
ConstraintContext * constraint ()
SystemContext * system ()
FormulaContext * formula ()
IntervalContext * interval ()
ExpressionContext * expression ()
ExpressionContext * expression (int precedence)
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool expressionSempred (ExpressionContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEY_LOCATIONS
KEY_MODEL
KEY_FLOWS
KEY_INVARIANT_CONDITIONS
KEY_SETTINGS
KEY_ANALYSIS
KEY_ANALYSIS_FORWARD
KEY_ANALYSIS_BACKWARD
KEY_TIME_HORIZON
KEY_STEP
KEY_GEOMETRY
KEY_PLOT_FLAG
KEY_PRINT_FLAG
KEY_MAX_JUMP
KEY_START_MODEL_ID
KEY_INITIAL_CONDITION
KEY_TRANSITIONS
KEY_URGENT
KEY_JUMP
KEY_DIRECTION
KEY_GUARD_CONDITIONS
KEY_RESET_MAP
KEY_INTERVAL_HULL
KEY_POLYTOPE
KEY_CONDITION
KEY_MATRIX
KEY_ROW_MAJOR_ORDER
KEY_COL_MAJOR_ORDER
KEY_SIN_FUNCTION
KEY_ARCSIN_FUNCTION
KEY_COS_FUNCTION
KEY_ARCCOS_FUNCTION
KEY_TAN_FUNCTION
KEY_ARCTAN_FUNCTION
KEY_COT_FUNCTION
KEY_ARCCOT_FUNCTION
KEY_LN_FUNCTION
KEY_LOG_FUNCTION
KEY_NATURAL_EXP_FUNCTION
KEY_SINH_FUNCTION
KEY_ARCSINH_FUNCTION
KEY_COSH_FUNCTION
KEY_ARCCOSH_FUNCTION
KEY_TANH_FUNCTION
KEY_ARCTANH_FUNCTION
KEY_COTH_FUNCTION
KEY_ARCCOTH_FUNCTION
KEY_SQR_FUNCTION
KEY_SQRT_FUNCTION
KEY_ABS_FUNCTION
KEY_POWER_FUNCTION
KEY_NAME
KEY_SWITCH_ON
KEY_SWITCH_OFF
KEY_BOOL_TRUE
KEY_BOOL_FALSE
KEY_INFINITY
SCINUM
NUMBER
VARIABLE
LEFTCURLYBRACKET
RIGHTCURLYBRACKET
LEFTROUNDBRACKET
RIGHTROUNDBRACKET
LEFTSQUAREBRACKET
RIGHTSQUAREBRACKET
COMMA
EQUAL
UNEQUAL
GEQ
LEQ
LSS
GTR
DEFINE
FROMTO
ASSIGN
PLUS
MINUS
MULTIPLY
DIVIDE
EXPONENT
DERIVATIVE
COMMENT
WS
anonymous enum
anonymous enum
Enumerator
RuleModelid
RuleFlows
RuleInvariantcondition
RuleModel
RuleLocations
RuleCondition
RulePolytope
RuleHpolytope
RuleVpolytope
RuleMatrix
RuleVector
RuleIntervalhull
RuleConstraints
RuleConstraint
RuleSystem
RuleFormula
RuleInterval
RuleExpression
Constructor & Destructor Documentation
locationsParser()
locationsParser::locationsParser (antlr4::TokenStream * input)
References _atn, _decisionToDFA, and _sharedContextCache.
~locationsParser()
locationsParser::~locationsParser ()
Member Function Documentation
condition()
locationsParser::ConditionContext * locationsParser::condition ()
References locationsParser::ConditionContext::enterRule(), locationsParser::ConditionContext::exitRule(), locationsParser::ConditionContext::intervalhull(), KEY_CONDITION, KEY_INTERVAL_HULL, KEY_POLYTOPE, LEFTCURLYBRACKET, locationsParser::ConditionContext::polytope(), RIGHTCURLYBRACKET, and RuleCondition.
constraint()
locationsParser::ConstraintContext * locationsParser::constraint ()
References locationsParser::ConstraintContext::enterRule(), EQUAL, locationsParser::ConstraintContext::exitRule(), locationsParser::ConstraintContext::expression(), GEQ, GTR, LEQ, LSS, locationsParser::ConstraintContext::RELATION, RuleConstraint, and UNEQUAL.
constraints()
locationsParser::ConstraintsContext * locationsParser::constraints ()
References locationsParser::ConstraintsContext::constraint(), locationsParser::ConstraintsContext::enterRule(), locationsParser::ConstraintsContext::exitRule(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, NUMBER, PLUS, RuleConstraints, SCINUM, and VARIABLE.
expression() [1/2]
locationsParser::ExpressionContext * locationsParser::expression ()
Referenced by expression().
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::expression (int precedence)
References COMMA, DIVIDE, EXPONENT, expression(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, MULTIPLY, NUMBER, PLUS, RIGHTROUNDBRACKET, RuleExpression, SCINUM, and VARIABLE.
expressionSempred()
bool locationsParser::expressionSempred (ExpressionContext * _localctx, size_t predicateIndex)
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, and _vocabulary.
Referenced by sempred().
flows()
locationsParser::FlowsContext * locationsParser::flows ()
References locationsParser::FlowsContext::enterRule(), locationsParser::FlowsContext::exitRule(), KEY_FLOWS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, RuleFlows, and locationsParser::FlowsContext::system().
formula()
locationsParser::FormulaContext * locationsParser::formula ()
References ASSIGN, DERIVATIVE, locationsParser::FormulaContext::enterRule(), locationsParser::FormulaContext::exitRule(), locationsParser::FormulaContext::expression(), locationsParser::FormulaContext::interval(), LEFTSQUAREBRACKET, RuleFormula, and VARIABLE.
getATN()
virtual const antlr4::atn::ATN& locationsParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string locationsParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & locationsParser::getRuleNames () const override virtual
References _ruleNames.
Referenced by getTokenNames().
getTokenNames()
virtual const std::vector<std::string>& locationsParser::getTokenNames () const inline override virtual
References _tokenNames, getRuleNames(), and getVocabulary().
getVocabulary()
dfa::Vocabulary & locationsParser::getVocabulary () const override virtual
References _vocabulary.
Referenced by getTokenNames().
hpolytope()
locationsParser::HpolytopeContext * locationsParser::hpolytope ()
References locationsParser::HpolytopeContext::enterRule(), locationsParser::HpolytopeContext::exitRule(), LEFTCURLYBRACKET, locationsParser::HpolytopeContext::matrix(), RIGHTCURLYBRACKET, RuleHpolytope, and locationsParser::HpolytopeContext::vector().
interval()
locationsParser::IntervalContext * locationsParser::interval ()
References locationsParser::IntervalContext::_tset251, locationsParser::IntervalContext::_tset264, locationsParser::IntervalContext::_tset284, locationsParser::IntervalContext::_tset297, COMMA, locationsParser::IntervalContext::enterRule(), locationsParser::IntervalContext::exitRule(), KEY_INFINITY, LEFTSQUAREBRACKET, MINUS, NUMBER, locationsParser::IntervalContext::OP, PLUS, RIGHTSQUAREBRACKET, RuleInterval, SCINUM, and locationsParser::IntervalContext::VAL.
intervalhull()
locationsParser::IntervalhullContext * locationsParser::intervalhull ()
References COMMA, locationsParser::IntervalhullContext::enterRule(), locationsParser::IntervalhullContext::exitRule(), locationsParser::IntervalhullContext::interval(), KEY_INTERVAL_HULL, LEFTCURLYBRACKET, LEFTSQUAREBRACKET, RIGHTCURLYBRACKET, and RuleIntervalhull.
invariantcondition()
locationsParser::InvariantconditionContext * locationsParser::invariantcondition ()
References locationsParser::InvariantconditionContext::condition(), locationsParser::InvariantconditionContext::enterRule(), locationsParser::InvariantconditionContext::exitRule(), KEY_CONDITION, KEY_INVARIANT_CONDITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleInvariantcondition.
locations()
locationsParser::LocationsContext * locationsParser::locations ()
References locationsParser::LocationsContext::enterRule(), locationsParser::LocationsContext::exitRule(), KEY_LOCATIONS, KEY_MODEL, LEFTCURLYBRACKET, locationsParser::LocationsContext::model(), RIGHTCURLYBRACKET, and RuleLocations.
matrix()
locationsParser::MatrixContext * locationsParser::matrix ()
References COMMA, locationsParser::MatrixContext::enterRule(), locationsParser::MatrixContext::exitRule(), KEY_COL_MAJOR_ORDER, KEY_MATRIX, KEY_ROW_MAJOR_ORDER, LEFTCURLYBRACKET, LEFTROUNDBRACKET, locationsParser::MatrixContext::MAJOR_ORDER, RIGHTCURLYBRACKET, RuleMatrix, and locationsParser::MatrixContext::vector().
model()
locationsParser::ModelContext * locationsParser::model ()
References locationsParser::ModelContext::enterRule(), locationsParser::ModelContext::exitRule(), locationsParser::ModelContext::flows(), locationsParser::ModelContext::invariantcondition(), KEY_MODEL, LEFTCURLYBRACKET, locationsParser::ModelContext::modelid(), RIGHTCURLYBRACKET, and RuleModel.
modelid()
locationsParser::ModelidContext * locationsParser::modelid ()
References locationsParser::ModelidContext::enterRule(), locationsParser::ModelidContext::exitRule(), KEY_NAME, RuleModelid, and VARIABLE.
polytope()
locationsParser::PolytopeContext * locationsParser::polytope ()
References locationsParser::PolytopeContext::enterRule(), locationsParser::PolytopeContext::exitRule(), locationsParser::PolytopeContext::hpolytope(), KEY_POLYTOPE, RulePolytope, and locationsParser::PolytopeContext::vpolytope().
sempred()
bool locationsParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References expressionSempred().
system()
locationsParser::SystemContext * locationsParser::system ()
References locationsParser::SystemContext::enterRule(), locationsParser::SystemContext::exitRule(), locationsParser::SystemContext::formula(), RuleSystem, and VARIABLE.
vector()
locationsParser::VectorContext * locationsParser::vector ()
References locationsParser::VectorContext::_tset115, locationsParser::VectorContext::_tset135, COMMA, locationsParser::VectorContext::enterRule(), locationsParser::VectorContext::exitRule(), LEFTROUNDBRACKET, MINUS, NUMBER, locationsParser::VectorContext::OP, PLUS, RIGHTROUNDBRACKET, and RuleVector.
vpolytope()
locationsParser::VpolytopeContext * locationsParser::vpolytope ()
References COMMA, locationsParser::VpolytopeContext::enterRule(), locationsParser::VpolytopeContext::exitRule(), LEFTCURLYBRACKET, LEFTROUNDBRACKET, RIGHTCURLYBRACKET, RuleVpolytope, and locationsParser::VpolytopeContext::vector().
Member Data Documentation
_atn
atn::ATN locationsParser::_atn static private
Referenced by expressionSempred(), getATN(), locationsParser::Initializer::Initializer(), and locationsParser().
_decisionToDFA
std::vector< dfa::DFA > locationsParser::_decisionToDFA static private
Referenced by expressionSempred(), locationsParser::Initializer::Initializer(), and locationsParser().
_init
locationsParser::Initializer locationsParser::_init static private
Referenced by locationsParser::Initializer::Initializer().
_literalNames
std::vector< std::string > locationsParser::_literalNames static private
Initial value:
= {
  "", "'LOCATIONS'", "'MODEL'", "'FLOWS'", "'INVARIANT_CONDITIONS'", "'SETTINGS'",
  "'ANALYSIS'", "'FORWARD'", "'BACKWARD'", "'TIME_HORIZON'", "'STEP'", "'GEOMETRY'",
  "'PLOT'", "'PRINT'", "'MAX_JUMP'", "'START_MODEL_ID'", "'INITIAL_CONDITION'",
  "'TRANSITIONS'", "'URGENT'", "'JUMP'", "'DIRECTION'", "'GUARD_CONDITIONS'",
  "'RESET_MAP'", "'INTERVAL_HULL'", "'POLYTOPE'", "'CONDITION'", "'MATRIX'",
  "'ROW_MAJOR'", "'COL_MAJOR'", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "'NAME'", "'ON'",
  "'OFF'", "'TRUE'", "'FALSE'", "", "", "", "", "'{'", "'}'", "'('", "')'",
  "'['", "']'", "','", "'=='", "'!='", "'>='", "'<='", "'<'", "'>'", "':='",
  "", "'='", "'+'", "'-'", "'*'", "'/'", "'^'", "'''"
}
Referenced by expressionSempred().
_ruleNames
std::vector< std::string > locationsParser::_ruleNames static private
Initial value:
= {
  "modelid", "flows", "invariantcondition", "model", "locations", "condition",
  "polytope", "hpolytope", "vpolytope", "matrix", "vector", "intervalhull",
  "constraints", "constraint", "system", "formula", "interval", "expression"
}
Referenced by expressionSempred(), and getRuleNames().
_serializedATN
std::vector< uint16_t > locationsParser::_serializedATN static private
Referenced by expressionSempred(), and locationsParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache locationsParser::_sharedContextCache static private
Referenced by expressionSempred(), and locationsParser().
_symbolicNames
std::vector< std::string > locationsParser::_symbolicNames static private
Initial value:
= {
  "", "KEY_LOCATIONS", "KEY_MODEL", "KEY_FLOWS", "KEY_INVARIANT_CONDITIONS",
  "KEY_SETTINGS", "KEY_ANALYSIS", "KEY_ANALYSIS_FORWARD", "KEY_ANALYSIS_BACKWARD",
  "KEY_TIME_HORIZON", "KEY_STEP", "KEY_GEOMETRY", "KEY_PLOT_FLAG", "KEY_PRINT_FLAG",
  "KEY_MAX_JUMP", "KEY_START_MODEL_ID", "KEY_INITIAL_CONDITION", "KEY_TRANSITIONS",
  "KEY_URGENT", "KEY_JUMP", "KEY_DIRECTION", "KEY_GUARD_CONDITIONS", "KEY_RESET_MAP",
  "KEY_INTERVAL_HULL", "KEY_POLYTOPE", "KEY_CONDITION", "KEY_MATRIX", "KEY_ROW_MAJOR_ORDER",
  "KEY_COL_MAJOR_ORDER", "KEY_SIN_FUNCTION", "KEY_ARCSIN_FUNCTION", "KEY_COS_FUNCTION",
  "KEY_ARCCOS_FUNCTION", "KEY_TAN_FUNCTION", "KEY_ARCTAN_FUNCTION", "KEY_COT_FUNCTION",
  "KEY_ARCCOT_FUNCTION", "KEY_LN_FUNCTION", "KEY_LOG_FUNCTION", "KEY_NATURAL_EXP_FUNCTION",
  "KEY_SINH_FUNCTION", "KEY_ARCSINH_FUNCTION", "KEY_COSH_FUNCTION", "KEY_ARCCOSH_FUNCTION",
  "KEY_TANH_FUNCTION", "KEY_ARCTANH_FUNCTION", "KEY_COTH_FUNCTION", "KEY_ARCCOTH_FUNCTION",
  "KEY_SQR_FUNCTION", "KEY_SQRT_FUNCTION", "KEY_ABS_FUNCTION", "KEY_POWER_FUNCTION",
  "KEY_NAME", "KEY_SWITCH_ON", "KEY_SWITCH_OFF", "KEY_BOOL_TRUE", "KEY_BOOL_FALSE",
  "KEY_INFINITY", "SCINUM", "NUMBER", "VARIABLE", "LEFTCURLYBRACKET", "RIGHTCURLYBRACKET",
  "LEFTROUNDBRACKET", "RIGHTROUNDBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET",
  "COMMA", "EQUAL", "UNEQUAL", "GEQ", "LEQ", "LSS", "GTR", "DEFINE", "FROMTO",
  "ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", "DERIVATIVE",
  "COMMENT", "WS"
}
Referenced by expressionSempred(), and locationsParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > locationsParser::_tokenNames static private
Referenced by expressionSempred(), getTokenNames(), and locationsParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary locationsParser::_vocabulary static private
Referenced by expressionSempred(), getVocabulary(), and locationsParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp