irafhy: hybridautomatonParser Class Reference
hybridautomatonParser Class Reference
#include <hybridautomatonParser.h>
Classes
class AcosExpContext
class AcoshExpContext
class AcotExpContext
class AcothExpContext
class AsinExpContext
class AsinhExpContext
class AtanExpContext
class AtanhExpContext
class ConditionContext
class ConstantContext
class ConstraintContext
class ConstraintsContext
class CosExpContext
class CoshExpContext
class CotExpContext
class CothExpContext
class DirectionContext
class ExpAddSubContext
class ExpBraContext
class ExpExpContext
class ExpMulDivContext
class ExpressionContext
class FlowsContext
class FormulaContext
class GuardconditionContext
class HpolytopeContext
class HybridautomatonContext
class HybridautomatonidContext
struct Initializer
class IntervalContext
class IntervalhullContext
class InvariantconditionContext
class JumpContext
class LnExpContext
class LocationsContext
class LogExpContext
class MatrixContext
class ModelContext
class ModelidContext
class NegExpContext
class NexpExpContext
class PolytopeContext
class PosExpContext
class PowExpContext
class ResetmapContext
class SinExpContext
class SinhExpContext
class SqrExpContext
class SqrtExpContext
class SystemContext
class TanExpContext
class TanhExpContext
class TransitionsContext
class UpdatefunctionContext
class VariableContext
class VariablesContext
class VectorContext
class VpolytopeContext
Public Types
enum {
KEY_HYBRID_AUTOMATON = 1, KEY_VARIABLES = 2, KEY_LOCATIONS = 3, KEY_MODEL = 4,
KEY_FLOWS = 5, KEY_INVARIANT_CONDITIONS = 6, KEY_SETTINGS = 7, KEY_ANALYSIS = 8,
KEY_ANALYSIS_FORWARD = 9, KEY_ANALYSIS_BACKWARD = 10, KEY_TIME_HORIZON = 11, KEY_STEP = 12,
KEY_GEOMETRY = 13, KEY_PLOT_FLAG = 14, KEY_PRINT_FLAG = 15, KEY_MAX_JUMP = 16,
KEY_START_MODEL_ID = 17, KEY_INITIAL_CONDITION = 18, KEY_TRANSITIONS = 19, KEY_URGENT = 20,
KEY_JUMP = 21, KEY_DIRECTION = 22, KEY_GUARD_CONDITIONS = 23, KEY_RESET_MAP = 24,
KEY_INTERVAL_HULL = 25, KEY_POLYTOPE = 26, KEY_CONDITION = 27, KEY_MATRIX = 28,
KEY_ROW_MAJOR_ORDER = 29, KEY_COL_MAJOR_ORDER = 30, KEY_SIN_FUNCTION = 31, KEY_ARCSIN_FUNCTION = 32,
KEY_COS_FUNCTION = 33, KEY_ARCCOS_FUNCTION = 34, KEY_TAN_FUNCTION = 35, KEY_ARCTAN_FUNCTION = 36,
KEY_COT_FUNCTION = 37, KEY_ARCCOT_FUNCTION = 38, KEY_LN_FUNCTION = 39, KEY_LOG_FUNCTION = 40,
KEY_NATURAL_EXP_FUNCTION = 41, KEY_SINH_FUNCTION = 42, KEY_ARCSINH_FUNCTION = 43, KEY_COSH_FUNCTION = 44,
KEY_ARCCOSH_FUNCTION = 45, KEY_TANH_FUNCTION = 46, KEY_ARCTANH_FUNCTION = 47, KEY_COTH_FUNCTION = 48,
KEY_ARCCOTH_FUNCTION = 49, KEY_SQR_FUNCTION = 50, KEY_SQRT_FUNCTION = 51, KEY_ABS_FUNCTION = 52,
KEY_POWER_FUNCTION = 53, KEY_NAME = 54, KEY_SWITCH_ON = 55, KEY_SWITCH_OFF = 56,
KEY_BOOL_TRUE = 57, KEY_BOOL_FALSE = 58, KEY_INFINITY = 59, SCINUM = 60,
NUMBER = 61, VARIABLE = 62, LEFTCURLYBRACKET = 63, RIGHTCURLYBRACKET = 64,
LEFTROUNDBRACKET = 65, RIGHTROUNDBRACKET = 66, LEFTSQUAREBRACKET = 67, RIGHTSQUAREBRACKET = 68,
COMMA = 69, EQUAL = 70, UNEQUAL = 71, GEQ = 72,
LEQ = 73, LSS = 74, GTR = 75, DEFINE = 76,
FROMTO = 77, ASSIGN = 78, PLUS = 79, MINUS = 80,
MULTIPLY = 81, DIVIDE = 82, EXPONENT = 83, DERIVATIVE = 84,
COMMENT = 85, WS = 86
}
enum {
RuleHybridautomatonid = 0, RuleVariables = 1, RuleHybridautomaton = 2, RuleCondition = 3,
RulePolytope = 4, RuleHpolytope = 5, RuleVpolytope = 6, RuleMatrix = 7,
RuleVector = 8, RuleIntervalhull = 9, RuleConstraints = 10, RuleConstraint = 11,
RuleSystem = 12, RuleFormula = 13, RuleInterval = 14, RuleExpression = 15,
RuleModelid = 16, RuleFlows = 17, RuleInvariantcondition = 18, RuleModel = 19,
RuleLocations = 20, RuleDirection = 21, RuleGuardcondition = 22, RuleUpdatefunction = 23,
RuleResetmap = 24, RuleJump = 25, RuleTransitions = 26
}
Public Member Functions
hybridautomatonParser (antlr4::TokenStream *input)
~hybridautomatonParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
HybridautomatonidContext * hybridautomatonid ()
VariablesContext * variables ()
HybridautomatonContext * hybridautomaton ()
ConditionContext * condition ()
PolytopeContext * polytope ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
MatrixContext * matrix ()
VectorContext * vector ()
IntervalhullContext * intervalhull ()
ConstraintsContext * constraints ()
ConstraintContext * constraint ()
SystemContext * system ()
FormulaContext * formula ()
IntervalContext * interval ()
ExpressionContext * expression ()
ExpressionContext * expression (int precedence)
ModelidContext * modelid ()
FlowsContext * flows ()
InvariantconditionContext * invariantcondition ()
ModelContext * model ()
LocationsContext * locations ()
DirectionContext * direction ()
GuardconditionContext * guardcondition ()
UpdatefunctionContext * updatefunction ()
ResetmapContext * resetmap ()
JumpContext * jump ()
TransitionsContext * transitions ()
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool expressionSempred (ExpressionContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEY_HYBRID_AUTOMATON
KEY_VARIABLES
KEY_LOCATIONS
KEY_MODEL
KEY_FLOWS
KEY_INVARIANT_CONDITIONS
KEY_SETTINGS
KEY_ANALYSIS
KEY_ANALYSIS_FORWARD
KEY_ANALYSIS_BACKWARD
KEY_TIME_HORIZON
KEY_STEP
KEY_GEOMETRY
KEY_PLOT_FLAG
KEY_PRINT_FLAG
KEY_MAX_JUMP
KEY_START_MODEL_ID
KEY_INITIAL_CONDITION
KEY_TRANSITIONS
KEY_URGENT
KEY_JUMP
KEY_DIRECTION
KEY_GUARD_CONDITIONS
KEY_RESET_MAP
KEY_INTERVAL_HULL
KEY_POLYTOPE
KEY_CONDITION
KEY_MATRIX
KEY_ROW_MAJOR_ORDER
KEY_COL_MAJOR_ORDER
KEY_SIN_FUNCTION
KEY_ARCSIN_FUNCTION
KEY_COS_FUNCTION
KEY_ARCCOS_FUNCTION
KEY_TAN_FUNCTION
KEY_ARCTAN_FUNCTION
KEY_COT_FUNCTION
KEY_ARCCOT_FUNCTION
KEY_LN_FUNCTION
KEY_LOG_FUNCTION
KEY_NATURAL_EXP_FUNCTION
KEY_SINH_FUNCTION
KEY_ARCSINH_FUNCTION
KEY_COSH_FUNCTION
KEY_ARCCOSH_FUNCTION
KEY_TANH_FUNCTION
KEY_ARCTANH_FUNCTION
KEY_COTH_FUNCTION
KEY_ARCCOTH_FUNCTION
KEY_SQR_FUNCTION
KEY_SQRT_FUNCTION
KEY_ABS_FUNCTION
KEY_POWER_FUNCTION
KEY_NAME
KEY_SWITCH_ON
KEY_SWITCH_OFF
KEY_BOOL_TRUE
KEY_BOOL_FALSE
KEY_INFINITY
SCINUM
NUMBER
VARIABLE
LEFTCURLYBRACKET
RIGHTCURLYBRACKET
LEFTROUNDBRACKET
RIGHTROUNDBRACKET
LEFTSQUAREBRACKET
RIGHTSQUAREBRACKET
COMMA
EQUAL
UNEQUAL
GEQ
LEQ
LSS
GTR
DEFINE
FROMTO
ASSIGN
PLUS
MINUS
MULTIPLY
DIVIDE
EXPONENT
DERIVATIVE
COMMENT
WS
anonymous enum
anonymous enum
Enumerator
RuleHybridautomatonid
RuleVariables
RuleHybridautomaton
RuleCondition
RulePolytope
RuleHpolytope
RuleVpolytope
RuleMatrix
RuleVector
RuleIntervalhull
RuleConstraints
RuleConstraint
RuleSystem
RuleFormula
RuleInterval
RuleExpression
RuleModelid
RuleFlows
RuleInvariantcondition
RuleModel
RuleLocations
RuleDirection
RuleGuardcondition
RuleUpdatefunction
RuleResetmap
RuleJump
RuleTransitions
Constructor & Destructor Documentation
hybridautomatonParser()
hybridautomatonParser::hybridautomatonParser (antlr4::TokenStream * input)
References _atn, _decisionToDFA, and _sharedContextCache.
~hybridautomatonParser()
hybridautomatonParser::~hybridautomatonParser ()
Member Function Documentation
condition()
hybridautomatonParser::ConditionContext * hybridautomatonParser::condition ()
References hybridautomatonParser::ConditionContext::enterRule(), hybridautomatonParser::ConditionContext::exitRule(), hybridautomatonParser::ConditionContext::intervalhull(), KEY_CONDITION, KEY_INTERVAL_HULL, KEY_POLYTOPE, LEFTCURLYBRACKET, hybridautomatonParser::ConditionContext::polytope(), RIGHTCURLYBRACKET, and RuleCondition.
constraint()
hybridautomatonParser::ConstraintContext * hybridautomatonParser::constraint ()
References hybridautomatonParser::ConstraintContext::enterRule(), EQUAL, hybridautomatonParser::ConstraintContext::exitRule(), hybridautomatonParser::ConstraintContext::expression(), GEQ, GTR, LEQ, LSS, hybridautomatonParser::ConstraintContext::RELATION, RuleConstraint, and UNEQUAL.
constraints()
hybridautomatonParser::ConstraintsContext * hybridautomatonParser::constraints ()
References hybridautomatonParser::ConstraintsContext::constraint(), hybridautomatonParser::ConstraintsContext::enterRule(), hybridautomatonParser::ConstraintsContext::exitRule(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, NUMBER, PLUS, RuleConstraints, SCINUM, and VARIABLE.
Referenced by TEST_F().
direction()
hybridautomatonParser::DirectionContext * hybridautomatonParser::direction ()
References hybridautomatonParser::DirectionContext::enterRule(), hybridautomatonParser::DirectionContext::exitRule(), FROMTO, KEY_DIRECTION, RuleDirection, and VARIABLE.
expression() [1/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::expression ()
Referenced by expression().
expression() [2/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::expression (int precedence)
References COMMA, DIVIDE, EXPONENT, expression(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, MULTIPLY, NUMBER, PLUS, RIGHTROUNDBRACKET, RuleExpression, SCINUM, and VARIABLE.
expressionSempred()
bool hybridautomatonParser::expressionSempred (ExpressionContext * _localctx, size_t predicateIndex)
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, and _vocabulary.
Referenced by sempred().
flows()
hybridautomatonParser::FlowsContext * hybridautomatonParser::flows ()
References hybridautomatonParser::FlowsContext::enterRule(), hybridautomatonParser::FlowsContext::exitRule(), KEY_FLOWS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, RuleFlows, and hybridautomatonParser::FlowsContext::system().
formula()
hybridautomatonParser::FormulaContext * hybridautomatonParser::formula ()
References ASSIGN, DERIVATIVE, hybridautomatonParser::FormulaContext::enterRule(), hybridautomatonParser::FormulaContext::exitRule(), hybridautomatonParser::FormulaContext::expression(), hybridautomatonParser::FormulaContext::interval(), LEFTSQUAREBRACKET, RuleFormula, and VARIABLE.
getATN()
virtual const antlr4::atn::ATN& hybridautomatonParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string hybridautomatonParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & hybridautomatonParser::getRuleNames () const override virtual
References _ruleNames.
Referenced by getTokenNames().
getTokenNames()
virtual const std::vector<std::string>& hybridautomatonParser::getTokenNames () const inline override virtual
References _tokenNames, getRuleNames(), and getVocabulary().
getVocabulary()
dfa::Vocabulary & hybridautomatonParser::getVocabulary () const override virtual
References _vocabulary.
Referenced by getTokenNames().
guardcondition()
hybridautomatonParser::GuardconditionContext * hybridautomatonParser::guardcondition ()
References hybridautomatonParser::GuardconditionContext::condition(), hybridautomatonParser::GuardconditionContext::enterRule(), hybridautomatonParser::GuardconditionContext::exitRule(), KEY_CONDITION, KEY_GUARD_CONDITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleGuardcondition.
hpolytope()
hybridautomatonParser::HpolytopeContext * hybridautomatonParser::hpolytope ()
References hybridautomatonParser::HpolytopeContext::enterRule(), hybridautomatonParser::HpolytopeContext::exitRule(), LEFTCURLYBRACKET, hybridautomatonParser::HpolytopeContext::matrix(), RIGHTCURLYBRACKET, RuleHpolytope, and hybridautomatonParser::HpolytopeContext::vector().
Referenced by TEST_F().
hybridautomaton()
hybridautomatonParser::HybridautomatonContext * hybridautomatonParser::hybridautomaton ()
References hybridautomatonParser::HybridautomatonContext::enterRule(), hybridautomatonParser::HybridautomatonContext::exitRule(), hybridautomatonParser::HybridautomatonContext::hybridautomatonid(), KEY_HYBRID_AUTOMATON, LEFTCURLYBRACKET, hybridautomatonParser::HybridautomatonContext::locations(), RIGHTCURLYBRACKET, RuleHybridautomaton, hybridautomatonParser::HybridautomatonContext::transitions(), and hybridautomatonParser::HybridautomatonContext::variables().
Referenced by TEST_F().
hybridautomatonid()
hybridautomatonParser::HybridautomatonidContext * hybridautomatonParser::hybridautomatonid ()
References hybridautomatonParser::HybridautomatonidContext::enterRule(), hybridautomatonParser::HybridautomatonidContext::exitRule(), KEY_NAME, RuleHybridautomatonid, and VARIABLE.
interval()
hybridautomatonParser::IntervalContext * hybridautomatonParser::interval ()
References hybridautomatonParser::IntervalContext::_tset251, hybridautomatonParser::IntervalContext::_tset264, hybridautomatonParser::IntervalContext::_tset284, hybridautomatonParser::IntervalContext::_tset297, COMMA, hybridautomatonParser::IntervalContext::enterRule(), hybridautomatonParser::IntervalContext::exitRule(), KEY_INFINITY, LEFTSQUAREBRACKET, MINUS, NUMBER, hybridautomatonParser::IntervalContext::OP, PLUS, RIGHTSQUAREBRACKET, RuleInterval, SCINUM, and hybridautomatonParser::IntervalContext::VAL.
Referenced by TEST_F().
intervalhull()
hybridautomatonParser::IntervalhullContext * hybridautomatonParser::intervalhull ()
References COMMA, hybridautomatonParser::IntervalhullContext::enterRule(), hybridautomatonParser::IntervalhullContext::exitRule(), hybridautomatonParser::IntervalhullContext::interval(), KEY_INTERVAL_HULL, LEFTCURLYBRACKET, LEFTSQUAREBRACKET, RIGHTCURLYBRACKET, and RuleIntervalhull.
Referenced by TEST_F().
invariantcondition()
hybridautomatonParser::InvariantconditionContext * hybridautomatonParser::invariantcondition ()
References hybridautomatonParser::InvariantconditionContext::condition(), hybridautomatonParser::InvariantconditionContext::enterRule(), hybridautomatonParser::InvariantconditionContext::exitRule(), KEY_CONDITION, KEY_INVARIANT_CONDITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleInvariantcondition.
jump()
hybridautomatonParser::JumpContext * hybridautomatonParser::jump ()
References hybridautomatonParser::JumpContext::direction(), hybridautomatonParser::JumpContext::enterRule(), hybridautomatonParser::JumpContext::exitRule(), hybridautomatonParser::JumpContext::guardcondition(), KEY_JUMP, LEFTCURLYBRACKET, hybridautomatonParser::JumpContext::resetmap(), RIGHTCURLYBRACKET, and RuleJump.
locations()
hybridautomatonParser::LocationsContext * hybridautomatonParser::locations ()
References hybridautomatonParser::LocationsContext::enterRule(), hybridautomatonParser::LocationsContext::exitRule(), KEY_LOCATIONS, KEY_MODEL, LEFTCURLYBRACKET, hybridautomatonParser::LocationsContext::model(), RIGHTCURLYBRACKET, and RuleLocations.
Referenced by TEST_F().
matrix()
hybridautomatonParser::MatrixContext * hybridautomatonParser::matrix ()
References COMMA, hybridautomatonParser::MatrixContext::enterRule(), hybridautomatonParser::MatrixContext::exitRule(), KEY_COL_MAJOR_ORDER, KEY_MATRIX, KEY_ROW_MAJOR_ORDER, LEFTCURLYBRACKET, LEFTROUNDBRACKET, hybridautomatonParser::MatrixContext::MAJOR_ORDER, RIGHTCURLYBRACKET, RuleMatrix, and hybridautomatonParser::MatrixContext::vector().
Referenced by TEST_F().
model()
hybridautomatonParser::ModelContext * hybridautomatonParser::model ()
References hybridautomatonParser::ModelContext::enterRule(), hybridautomatonParser::ModelContext::exitRule(), hybridautomatonParser::ModelContext::flows(), hybridautomatonParser::ModelContext::invariantcondition(), KEY_MODEL, LEFTCURLYBRACKET, hybridautomatonParser::ModelContext::modelid(), RIGHTCURLYBRACKET, and RuleModel.
modelid()
hybridautomatonParser::ModelidContext * hybridautomatonParser::modelid ()
References hybridautomatonParser::ModelidContext::enterRule(), hybridautomatonParser::ModelidContext::exitRule(), KEY_NAME, RuleModelid, and VARIABLE.
polytope()
hybridautomatonParser::PolytopeContext * hybridautomatonParser::polytope ()
References hybridautomatonParser::PolytopeContext::enterRule(), hybridautomatonParser::PolytopeContext::exitRule(), hybridautomatonParser::PolytopeContext::hpolytope(), KEY_POLYTOPE, RulePolytope, and hybridautomatonParser::PolytopeContext::vpolytope().
resetmap()
hybridautomatonParser::ResetmapContext * hybridautomatonParser::resetmap ()
References hybridautomatonParser::ResetmapContext::enterRule(), hybridautomatonParser::ResetmapContext::exitRule(), KEY_RESET_MAP, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, RuleResetmap, hybridautomatonParser::ResetmapContext::updatefunction(), and VARIABLE.
sempred()
bool hybridautomatonParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References expressionSempred().
system()
hybridautomatonParser::SystemContext * hybridautomatonParser::system ()
References hybridautomatonParser::SystemContext::enterRule(), hybridautomatonParser::SystemContext::exitRule(), hybridautomatonParser::SystemContext::formula(), RuleSystem, and VARIABLE.
Referenced by TEST_F().
transitions()
hybridautomatonParser::TransitionsContext * hybridautomatonParser::transitions ()
References hybridautomatonParser::TransitionsContext::enterRule(), hybridautomatonParser::TransitionsContext::exitRule(), hybridautomatonParser::TransitionsContext::jump(), KEY_JUMP, KEY_TRANSITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleTransitions.
Referenced by TEST_F().
updatefunction()
hybridautomatonParser::UpdatefunctionContext * hybridautomatonParser::updatefunction ()
References DEFINE, hybridautomatonParser::UpdatefunctionContext::enterRule(), hybridautomatonParser::UpdatefunctionContext::exitRule(), hybridautomatonParser::UpdatefunctionContext::expression(), RuleUpdatefunction, and VARIABLE.
variables()
hybridautomatonParser::VariablesContext * hybridautomatonParser::variables ()
References COMMA, hybridautomatonParser::VariablesContext::enterRule(), hybridautomatonParser::VariablesContext::exitRule(), KEY_VARIABLES, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, RuleVariables, and VARIABLE.
vector()
hybridautomatonParser::VectorContext * hybridautomatonParser::vector ()
References hybridautomatonParser::VectorContext::_tset115, hybridautomatonParser::VectorContext::_tset135, COMMA, hybridautomatonParser::VectorContext::enterRule(), hybridautomatonParser::VectorContext::exitRule(), LEFTROUNDBRACKET, MINUS, NUMBER, hybridautomatonParser::VectorContext::OP, PLUS, RIGHTROUNDBRACKET, and RuleVector.
Referenced by TEST_F().
vpolytope()
hybridautomatonParser::VpolytopeContext * hybridautomatonParser::vpolytope ()
References COMMA, hybridautomatonParser::VpolytopeContext::enterRule(), hybridautomatonParser::VpolytopeContext::exitRule(), LEFTCURLYBRACKET, LEFTROUNDBRACKET, RIGHTCURLYBRACKET, RuleVpolytope, and hybridautomatonParser::VpolytopeContext::vector().
Referenced by TEST_F().
Member Data Documentation
_atn
atn::ATN hybridautomatonParser::_atn static private
Referenced by expressionSempred(), getATN(), hybridautomatonParser(), and hybridautomatonParser::Initializer::Initializer().
_decisionToDFA
std::vector< dfa::DFA > hybridautomatonParser::_decisionToDFA static private
Referenced by expressionSempred(), hybridautomatonParser(), and hybridautomatonParser::Initializer::Initializer().
_init
hybridautomatonParser::Initializer hybridautomatonParser::_init static private
Referenced by hybridautomatonParser::Initializer::Initializer().
_literalNames
std::vector< std::string > hybridautomatonParser::_literalNames static private
Initial value:
= {
  "", "'HYBRID_AUTOMATON'", "'VARIABLES'", "'LOCATIONS'", "'MODEL'", "'FLOWS'",
  "'INVARIANT_CONDITIONS'", "'SETTINGS'", "'ANALYSIS'", "'FORWARD'", "'BACKWARD'",
  "'TIME_HORIZON'", "'STEP'", "'GEOMETRY'", "'PLOT'", "'PRINT'", "'MAX_JUMP'",
  "'START_MODEL_ID'", "'INITIAL_CONDITION'", "'TRANSITIONS'", "'URGENT'",
  "'JUMP'", "'DIRECTION'", "'GUARD_CONDITIONS'", "'RESET_MAP'", "'INTERVAL_HULL'",
  "'POLYTOPE'", "'CONDITION'", "'MATRIX'", "'ROW_MAJOR'", "'COL_MAJOR'",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "'NAME'", "'ON'", "'OFF'", "'TRUE'", "'FALSE'", "",
  "", "", "", "'{'", "'}'", "'('", "')'", "'['", "']'", "','", "'=='", "'!='",
  "'>='", "'<='", "'<'", "'>'", "':='", "", "'='", "'+'", "'-'", "'*'",
  "'/'", "'^'", "'''"
}
Referenced by expressionSempred().
_ruleNames
std::vector< std::string > hybridautomatonParser::_ruleNames static private
Initial value:
= {
  "hybridautomatonid", "variables", "hybridautomaton", "condition", "polytope",
  "hpolytope", "vpolytope", "matrix", "vector", "intervalhull", "constraints",
  "constraint", "system", "formula", "interval", "expression", "modelid",
  "flows", "invariantcondition", "model", "locations", "direction", "guardcondition",
  "updatefunction", "resetmap", "jump", "transitions"
}
Referenced by expressionSempred(), and getRuleNames().
_serializedATN
std::vector< uint16_t > hybridautomatonParser::_serializedATN static private
Referenced by expressionSempred(), and hybridautomatonParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache hybridautomatonParser::_sharedContextCache static private
Referenced by expressionSempred(), and hybridautomatonParser().
_symbolicNames
std::vector< std::string > hybridautomatonParser::_symbolicNames static private
Initial value:
= {
  "", "KEY_HYBRID_AUTOMATON", "KEY_VARIABLES", "KEY_LOCATIONS", "KEY_MODEL",
  "KEY_FLOWS", "KEY_INVARIANT_CONDITIONS", "KEY_SETTINGS", "KEY_ANALYSIS",
  "KEY_ANALYSIS_FORWARD", "KEY_ANALYSIS_BACKWARD", "KEY_TIME_HORIZON", "KEY_STEP",
  "KEY_GEOMETRY", "KEY_PLOT_FLAG", "KEY_PRINT_FLAG", "KEY_MAX_JUMP", "KEY_START_MODEL_ID",
  "KEY_INITIAL_CONDITION", "KEY_TRANSITIONS", "KEY_URGENT", "KEY_JUMP",
  "KEY_DIRECTION", "KEY_GUARD_CONDITIONS", "KEY_RESET_MAP", "KEY_INTERVAL_HULL",
  "KEY_POLYTOPE", "KEY_CONDITION", "KEY_MATRIX", "KEY_ROW_MAJOR_ORDER",
  "KEY_COL_MAJOR_ORDER", "KEY_SIN_FUNCTION", "KEY_ARCSIN_FUNCTION", "KEY_COS_FUNCTION",
  "KEY_ARCCOS_FUNCTION", "KEY_TAN_FUNCTION", "KEY_ARCTAN_FUNCTION", "KEY_COT_FUNCTION",
  "KEY_ARCCOT_FUNCTION", "KEY_LN_FUNCTION", "KEY_LOG_FUNCTION", "KEY_NATURAL_EXP_FUNCTION",
  "KEY_SINH_FUNCTION", "KEY_ARCSINH_FUNCTION", "KEY_COSH_FUNCTION", "KEY_ARCCOSH_FUNCTION",
  "KEY_TANH_FUNCTION", "KEY_ARCTANH_FUNCTION", "KEY_COTH_FUNCTION", "KEY_ARCCOTH_FUNCTION",
  "KEY_SQR_FUNCTION", "KEY_SQRT_FUNCTION", "KEY_ABS_FUNCTION", "KEY_POWER_FUNCTION",
  "KEY_NAME", "KEY_SWITCH_ON", "KEY_SWITCH_OFF", "KEY_BOOL_TRUE", "KEY_BOOL_FALSE",
  "KEY_INFINITY", "SCINUM", "NUMBER", "VARIABLE", "LEFTCURLYBRACKET", "RIGHTCURLYBRACKET",
  "LEFTROUNDBRACKET", "RIGHTROUNDBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET",
  "COMMA", "EQUAL", "UNEQUAL", "GEQ", "LEQ", "LSS", "GTR", "DEFINE", "FROMTO",
  "ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", "DERIVATIVE",
  "COMMENT", "WS"
}
Referenced by expressionSempred(), and hybridautomatonParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > hybridautomatonParser::_tokenNames static private
Referenced by expressionSempred(), getTokenNames(), and hybridautomatonParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary hybridautomatonParser::_vocabulary static private
Referenced by expressionSempred(), getVocabulary(), and hybridautomatonParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp