irafhy: irafhy::ODESolver Class Reference
irafhy::ODESolver Class Reference
#include <ODESolver.h>
Static Public Member Functions
static capd::C0Rect2Set solve (const System &system, const capd::C0Rect2Set &set, const Time &duration, int TMOrder=30)
solve the initial value problem using wrapped capd non-rigorous ode solver
Member Function Documentation
solve()
capd::C0Rect2Set irafhy::ODESolver::solve (const System & system, const capd::C0Rect2Set & set, const Time & duration, int TMOrder = 30) static
solve the initial value problem using wrapped capd non-rigorous ode solver
Parameters
system continuous dynamics
set initial state set
duration duration of the computation
TMOrder max order of the taylor model
Returns
resulting state set
References irafhy::Time::end(), irafhy::System::odeSystem(), irafhy::Time::range(), and irafhy::Time::start().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/solver/ODESolver.h
/home/jianqiang/CLionProjects/irafhy/src/utility/solver/ODESolver.cpp