irafhy: hybridautomatonParser::ConditionContext Class Reference
hybridautomatonParser::ConditionContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ConditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_CONDITION ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
IntervalhullContext * intervalhull ()
PolytopeContext * polytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConditionContext()
hybridautomatonParser::ConditionContext::ConditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ConditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ConditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterCondition().
Referenced by hybridautomatonParser::condition().
exitRule()
void hybridautomatonParser::ConditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitCondition().
Referenced by hybridautomatonParser::condition().
getRuleIndex()
size_t hybridautomatonParser::ConditionContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleCondition.
intervalhull()
hybridautomatonParser::IntervalhullContext * hybridautomatonParser::ConditionContext::intervalhull ()
Referenced by hybridautomatonParser::condition(), and irafhy::DefinitionVisitor::visitCondition().
KEY_CONDITION()
tree::TerminalNode * hybridautomatonParser::ConditionContext::KEY_CONDITION ()
References hybridautomatonParser::KEY_CONDITION.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::ConditionContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
polytope()
hybridautomatonParser::PolytopeContext * hybridautomatonParser::ConditionContext::polytope ()
Referenced by hybridautomatonParser::condition(), and irafhy::DefinitionVisitor::visitCondition().
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::ConditionContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp