irafhy: transitionsParser::TransitionsContext Class Reference
transitionsParser::TransitionsContext Class Reference
#include <transitionsParser.h>
Public Member Functions
TransitionsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_TRANSITIONS ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< JumpContext * > jump ()
JumpContext * jump (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
TransitionsContext()
transitionsParser::TransitionsContext::TransitionsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::TransitionsContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::TransitionsContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterTransitions().
Referenced by transitionsParser::transitions().
exitRule()
void transitionsParser::TransitionsContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitTransitions().
Referenced by transitionsParser::transitions().
getRuleIndex()
size_t transitionsParser::TransitionsContext::getRuleIndex () const override virtual
References transitionsParser::RuleTransitions.
jump() [1/2]
std::vector< transitionsParser::JumpContext * > transitionsParser::TransitionsContext::jump ()
Referenced by transitionsParser::transitions().
jump() [2/2]
transitionsParser::JumpContext * transitionsParser::TransitionsContext::jump (size_t i)
KEY_TRANSITIONS()
tree::TerminalNode * transitionsParser::TransitionsContext::KEY_TRANSITIONS ()
References transitionsParser::KEY_TRANSITIONS.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::TransitionsContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::TransitionsContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp