irafhy: locationsParser::ExpExpContext Class Reference
locationsParser::ExpExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
ExpExpContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EXPONENT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpExpContext()
locationsParser::ExpExpContext::ExpExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ExpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ExpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterExpExp().
exitRule()
void locationsParser::ExpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitExpExp().
EXPONENT()
tree::TerminalNode * locationsParser::ExpExpContext::EXPONENT ()
References locationsParser::EXPONENT.
expression() [1/2]
std::vector< locationsParser::ExpressionContext * > locationsParser::ExpExpContext::expression ()
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::ExpExpContext::expression (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp