irafhy: settingsParser::ExpMulDivContext Class Reference
settingsParser::ExpMulDivContext Class Reference
#include <settingsParser.h>
Public Member Functions
ExpMulDivContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * MULTIPLY ()
antlr4::tree::TerminalNode * DIVIDE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpMulDivContext()
settingsParser::ExpMulDivContext::ExpMulDivContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ExpMulDivContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIVIDE()
tree::TerminalNode * settingsParser::ExpMulDivContext::DIVIDE ()
References settingsParser::DIVIDE.
enterRule()
void settingsParser::ExpMulDivContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterExpMulDiv().
exitRule()
void settingsParser::ExpMulDivContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitExpMulDiv().
expression() [1/2]
std::vector< settingsParser::ExpressionContext * > settingsParser::ExpMulDivContext::expression ()
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::ExpMulDivContext::expression (size_t i)
MULTIPLY()
tree::TerminalNode * settingsParser::ExpMulDivContext::MULTIPLY ()
References settingsParser::MULTIPLY.
Member Data Documentation
OP
antlr4::Token* settingsParser::ExpMulDivContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp