irafhy: definitionParser::CoshExpContext Class Reference
definitionParser::CoshExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
CoshExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COSH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CoshExpContext()
definitionParser::CoshExpContext::CoshExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::CoshExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::CoshExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterCoshExp().
exitRule()
void definitionParser::CoshExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitCoshExp().
expression()
definitionParser::ExpressionContext * definitionParser::CoshExpContext::expression ()
KEY_COSH_FUNCTION()
tree::TerminalNode * definitionParser::CoshExpContext::KEY_COSH_FUNCTION ()
References definitionParser::KEY_COSH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::CoshExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::CoshExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp