irafhy: settingsParser::HpolytopeContext Class Reference
settingsParser::HpolytopeContext Class Reference
#include <settingsParser.h>
Public Member Functions
HpolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
MatrixContext * matrix ()
VectorContext * vector ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
HpolytopeContext()
settingsParser::HpolytopeContext::HpolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::HpolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::HpolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterHpolytope().
Referenced by settingsParser::hpolytope().
exitRule()
void settingsParser::HpolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitHpolytope().
Referenced by settingsParser::hpolytope().
getRuleIndex()
size_t settingsParser::HpolytopeContext::getRuleIndex () const override virtual
References settingsParser::RuleHpolytope.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::HpolytopeContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
matrix()
settingsParser::MatrixContext * settingsParser::HpolytopeContext::matrix ()
Referenced by settingsParser::hpolytope(), and irafhy::SettingsVisitor::visitHpolytope().
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::HpolytopeContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
vector()
settingsParser::VectorContext * settingsParser::HpolytopeContext::vector ()
Referenced by settingsParser::hpolytope(), and irafhy::SettingsVisitor::visitHpolytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp