irafhy: hybridautomatonParser::AtanExpContext Class Reference
hybridautomatonParser::AtanExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
AtanExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCTAN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AtanExpContext()
hybridautomatonParser::AtanExpContext::AtanExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::AtanExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::AtanExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterAtanExp().
exitRule()
void hybridautomatonParser::AtanExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitAtanExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::AtanExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitAtanExp().
KEY_ARCTAN_FUNCTION()
tree::TerminalNode * hybridautomatonParser::AtanExpContext::KEY_ARCTAN_FUNCTION ()
References hybridautomatonParser::KEY_ARCTAN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AtanExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AtanExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp