irafhy: hybridautomatonParser::CothExpContext Class Reference
hybridautomatonParser::CothExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
CothExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COTH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CothExpContext()
hybridautomatonParser::CothExpContext::CothExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::CothExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::CothExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterCothExp().
exitRule()
void hybridautomatonParser::CothExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitCothExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::CothExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitCothExp().
KEY_COTH_FUNCTION()
tree::TerminalNode * hybridautomatonParser::CothExpContext::KEY_COTH_FUNCTION ()
References hybridautomatonParser::KEY_COTH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CothExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CothExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp