irafhy: locationsParser::SinExpContext Class Reference
locationsParser::SinExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
SinExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SIN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinExpContext()
locationsParser::SinExpContext::SinExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::SinExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::SinExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterSinExp().
exitRule()
void locationsParser::SinExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitSinExp().
expression()
locationsParser::ExpressionContext * locationsParser::SinExpContext::expression ()
KEY_SIN_FUNCTION()
tree::TerminalNode * locationsParser::SinExpContext::KEY_SIN_FUNCTION ()
References locationsParser::KEY_SIN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::SinExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::SinExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp