irafhy: settingsParser::AnalysissettingContext Class Reference
settingsParser::AnalysissettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
AnalysissettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_ANALYSIS ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * KEY_ANALYSIS_FORWARD ()
antlr4::tree::TerminalNode * KEY_ANALYSIS_BACKWARD ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * ANALYSIS = nullptr
Constructor & Destructor Documentation
AnalysissettingContext()
settingsParser::AnalysissettingContext::AnalysissettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::AnalysissettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::AnalysissettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::AnalysissettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterAnalysissetting().
Referenced by settingsParser::analysissetting().
exitRule()
void settingsParser::AnalysissettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitAnalysissetting().
Referenced by settingsParser::analysissetting().
getRuleIndex()
size_t settingsParser::AnalysissettingContext::getRuleIndex () const override virtual
References settingsParser::RuleAnalysissetting.
KEY_ANALYSIS()
tree::TerminalNode * settingsParser::AnalysissettingContext::KEY_ANALYSIS ()
References settingsParser::KEY_ANALYSIS.
KEY_ANALYSIS_BACKWARD()
tree::TerminalNode * settingsParser::AnalysissettingContext::KEY_ANALYSIS_BACKWARD ()
References settingsParser::KEY_ANALYSIS_BACKWARD.
KEY_ANALYSIS_FORWARD()
tree::TerminalNode * settingsParser::AnalysissettingContext::KEY_ANALYSIS_FORWARD ()
References settingsParser::KEY_ANALYSIS_FORWARD.
Member Data Documentation
ANALYSIS
antlr4::Token* settingsParser::AnalysissettingContext::ANALYSIS = nullptr
Referenced by settingsParser::analysissetting(), and irafhy::SettingsVisitor::visitAnalysissetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp