irafhy: irafhy::Point Class Reference
irafhy::Point Class Reference
#include <point.h>
Public Member Functions
Point ()
default constructor
Point (const Point &point)=default
copy constructor
Point (Point &&point)=default
move constructor
Point (double value)
constructor of the point in one dimensional space with given value as coordinate
Point (const std::vector< double > &coordinate)
constructor with given coordinate
Point (const Eigen::VectorXd &coordinate)
constructor with given coordinate
Point (Eigen::VectorXd &&coordinate)
constructor with given coordinate
virtual ~Point ()=default
destructor
Eigen::VectorXd coordinate () const
get the coordinate of the point
double value (std::size_t index) const
get the value of coordinate in specified dimension
int dimension () const
get the dimension of the space which the point in
bool empty () const
check if the point in valid space or not
bool operator< (const Point &rhs) const
relational operator
bool operator<= (const Point &rhs) const
relational operator
bool operator> (const Point &rhs) const
relational operator
bool operator>= (const Point &rhs) const
relational operator
bool operator== (const Point &rhs) const
relational operator
bool operator!= (const Point &rhs) const
relational operator
Point & operator+= (const Eigen::VectorXd &rhs)
addition assignment operator
Point & operator+= (const Point &rhs)
addition assignment operator
Point & operator-= (const Eigen::VectorXd &rhs)
subtraction assignment operator
Point & operator-= (const Point &rhs)
subtraction assignment operator
Point & operator- ()
unary minus operator
Point & operator/= (double divisor)
division assignment operator
Point & operator*= (double factor)
multiplication assignment operator
Point & operator= (const Eigen::VectorXd &rhs)
assignment operator
Point & operator= (Eigen::VectorXd &&rhs)
assignment operator
Point & operator= (const Point &rhs)=default
assignment operator
Point & operator= (Point &&rhs) noexcept=default
assignment operator
double & operator[] (std::size_t index)
get the value of the specified dimension
const double & operator[] (std::size_t index) const
get the value of the specified dimension
Static Public Member Functions
static Point zero (std::size_t dimension=0)
constructor of the origin of the given target space
static Point one (std::size_t dimension=0)
constructor of a point which all elements of the coordinate are ones in given target space
Private Attributes
Eigen::VectorXd coordinate_
coordinate of the point
Constructor & Destructor Documentation
Point() [1/7]
irafhy::Point::Point ()
default constructor
References coordinate_.
Referenced by one(), irafhy::operator*(), irafhy::operator+(), irafhy::operator-(), irafhy::operator/(), and zero().
Point() [2/7]
irafhy::Point::Point (const Point & point) default
copy constructor
Parameters
point given point
Point() [3/7]
irafhy::Point::Point (Point && point) default
move constructor
Parameters
point given point
Point() [4/7]
irafhy::Point::Point (double value) explicit
constructor of the point in one dimensional space with given value as coordinate
Parameters
value given value
References coordinate_, and value().
Point() [5/7]
irafhy::Point::Point (const std::vector< double > & coordinate) explicit
constructor with given coordinate
Parameters
coordinate given coordinate of the point
References coordinate_.
Point() [6/7]
irafhy::Point::Point (const Eigen::VectorXd & coordinate) explicit
constructor with given coordinate
Parameters
coordinate given coordinate of the point
References coordinate(), and coordinate_.
Point() [7/7]
irafhy::Point::Point (Eigen::VectorXd && coordinate) explicit
constructor with given coordinate
Parameters
coordinate given coordinate of the point
References coordinate(), and coordinate_.
~Point()
virtual irafhy::Point::~Point () virtual default
destructor
Member Function Documentation
coordinate()
Eigen::VectorXd irafhy::Point::coordinate () const
get the coordinate of the point
Returns
the coordinate of the point
References coordinate_.
Referenced by irafhy::HalfSpace::contains(), irafhy::HalfSpace::holds(), operator!=(), irafhy::operator*(), irafhy::operator+(), irafhy::operator-(), irafhy::operator/(), operator<(), irafhy::operator<<(), operator<=(), operator==(), operator>(), operator>=(), Point(), and irafhy::Polytope::Polytope().
dimension()
int irafhy::Point::dimension () const
get the dimension of the space which the point in
Returns
the dimension of the space
References coordinate_.
Referenced by irafhy::IntervalHull::contains(), irafhy::IntervalHull::IntervalHull(), operator*=(), irafhy::operator+(), operator+=(), irafhy::operator-(), operator-=(), and operator/=().
empty()
bool irafhy::Point::empty () const
check if the point in valid space or not
Returns
TRUE if the dimension of the space greater than zero
References coordinate_.
Referenced by irafhy::IntervalHull::IntervalHull().
one()
Point irafhy::Point::one (std::size_t dimension = 0) static
constructor of a point which all elements of the coordinate are ones in given target space
Parameters
dimension dimension of target space
Returns
resulting point instance
References Point().
operator!=()
bool irafhy::Point::operator!= (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point unequal to the right hand side one's
References coordinate(), and coordinate_.
operator*=()
Point & irafhy::Point::operator*= (double factor)
multiplication assignment operator
Parameters
factor given factor
Returns
resulting point whose coordinate is the product of the current coordinate and the given factor
References coordinate_, and dimension().
operator+=() [1/2]
Point & irafhy::Point::operator+= (const Eigen::VectorXd & rhs)
addition assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point whose coordinate is the summation of the current coordinate and the right hand side one's
References coordinate_, and dimension().
operator+=() [2/2]
Point & irafhy::Point::operator+= (const Point & rhs)
addition assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point whose coordinate is the summation of the current coordinate and the right hand side one's
References coordinate_, dimension(), and value().
operator-()
Point & irafhy::Point::operator- ()
unary minus operator
Returns
resulting point whose coordinate is the current coordinate multiply by minus one
References coordinate_.
operator-=() [1/2]
Point & irafhy::Point::operator-= (const Eigen::VectorXd & rhs)
subtraction assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point whose coordinate is the subtraction of the current coordinate and the right hand side one's
References coordinate_, and dimension().
operator-=() [2/2]
Point & irafhy::Point::operator-= (const Point & rhs)
subtraction assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point whose coordinate is the subtraction of the current coordinate and the right hand side one's
References coordinate_, dimension(), and value().
operator/=()
Point & irafhy::Point::operator/= (double divisor)
division assignment operator
Parameters
divisor given divisor
Returns
resulting point whose coordinate is the quotient of the current coordinate divided by the given divisor
References coordinate_, and dimension().
operator<()
bool irafhy::Point::operator< (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point less than the right hand side one's
References coordinate(), and coordinate_.
operator<=()
bool irafhy::Point::operator<= (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point less than or equal to the right hand side one's
References coordinate(), and coordinate_.
operator=() [1/4]
Point & irafhy::Point::operator= (const Eigen::VectorXd & rhs)
assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point
References coordinate_.
operator=() [2/4]
Point & irafhy::Point::operator= (Eigen::VectorXd && rhs)
assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point
References coordinate_.
operator=() [3/4]
Point& irafhy::Point::operator= (const Point & rhs) default
assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point
operator=() [4/4]
Point& irafhy::Point::operator= (Point && rhs) default noexcept
assignment operator
Parameters
rhs right hand side of the operator
Returns
resulting point
operator==()
bool irafhy::Point::operator== (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point equal to the right hand side one's
References coordinate(), and coordinate_.
operator>()
bool irafhy::Point::operator> (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point greater than the right hand side one's
References coordinate(), and coordinate_.
operator>=()
bool irafhy::Point::operator>= (const Point & rhs) const
relational operator
Parameters
rhs right hand side of the operator
Returns
TRUE if the coordinate of the point greater than or equal to the right hand side one's
References coordinate(), and coordinate_.
operator[]() [1/2]
double & irafhy::Point::operator[] (std::size_t index)
get the value of the specified dimension
Parameters
index index of the dimension
Returns
value of the specified dimension
References coordinate_.
operator[]() [2/2]
const double & irafhy::Point::operator[] (std::size_t index) const
get the value of the specified dimension
Parameters
index index of the dimension
Returns
value of the specified dimension
References coordinate_.
value()
double irafhy::Point::value (std::size_t index) const
get the value of coordinate in specified dimension
Parameters
index index of the dimension
Returns
value in target dimension
References coordinate_.
Referenced by operator+=(), operator-=(), and Point().
zero()
Point irafhy::Point::zero (std::size_t dimension = 0) static
constructor of the origin of the given target space
Parameters
dimension dimension of the target space
Returns
resulting origin
References Point().
Referenced by irafhy::Polytope::Empty().
Member Data Documentation
coordinate_
Eigen::VectorXd irafhy::Point::coordinate_ private
coordinate of the point
Referenced by coordinate(), dimension(), empty(), operator!=(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator[](), Point(), and value().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/representation/geometric/basic/point.h
/home/jianqiang/CLionProjects/irafhy/src/representation/geometric/basic/point.cpp