irafhy: locationsParser::TanhExpContext Class Reference
locationsParser::TanhExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
TanhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TANH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanhExpContext()
locationsParser::TanhExpContext::TanhExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::TanhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::TanhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterTanhExp().
exitRule()
void locationsParser::TanhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitTanhExp().
expression()
locationsParser::ExpressionContext * locationsParser::TanhExpContext::expression ()
KEY_TANH_FUNCTION()
tree::TerminalNode * locationsParser::TanhExpContext::KEY_TANH_FUNCTION ()
References locationsParser::KEY_TANH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::TanhExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::TanhExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp