irafhy: transitionsParser::PolytopeContext Class Reference
transitionsParser::PolytopeContext Class Reference
#include <transitionsParser.h>
Public Member Functions
PolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
PolytopeContext()
transitionsParser::PolytopeContext::PolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::PolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::PolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterPolytope().
Referenced by transitionsParser::polytope().
exitRule()
void transitionsParser::PolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitPolytope().
Referenced by transitionsParser::polytope().
getRuleIndex()
size_t transitionsParser::PolytopeContext::getRuleIndex () const override virtual
References transitionsParser::RulePolytope.
hpolytope()
transitionsParser::HpolytopeContext * transitionsParser::PolytopeContext::hpolytope ()
Referenced by transitionsParser::polytope().
KEY_POLYTOPE()
tree::TerminalNode * transitionsParser::PolytopeContext::KEY_POLYTOPE ()
References transitionsParser::KEY_POLYTOPE.
vpolytope()
transitionsParser::VpolytopeContext * transitionsParser::PolytopeContext::vpolytope ()
Referenced by transitionsParser::polytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp