irafhy: transitionsParser::VariableContext Class Reference
transitionsParser::VariableContext Class Reference
#include <transitionsParser.h>
Public Member Functions
VariableContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
VariableContext()
transitionsParser::VariableContext::VariableContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::VariableContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::VariableContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterVariable().
exitRule()
void transitionsParser::VariableContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitVariable().
VARIABLE()
tree::TerminalNode * transitionsParser::VariableContext::VARIABLE ()
References transitionsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp