irafhy: hybridautomatonParser::VariableContext Class Reference
hybridautomatonParser::VariableContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
VariableContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
VariableContext()
hybridautomatonParser::VariableContext::VariableContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::VariableContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::VariableContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterVariable().
exitRule()
void hybridautomatonParser::VariableContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitVariable().
VARIABLE()
tree::TerminalNode * hybridautomatonParser::VariableContext::VARIABLE ()
References hybridautomatonParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp