irafhy: definitionParser::IntervalhullContext Class Reference
definitionParser::IntervalhullContext Class Reference
#include <definitionParser.h>
Public Member Functions
IntervalhullContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< IntervalContext * > interval ()
IntervalContext * interval (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntervalhullContext()
definitionParser::IntervalhullContext::IntervalhullContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::IntervalhullContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > definitionParser::IntervalhullContext::COMMA ()
References definitionParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * definitionParser::IntervalhullContext::COMMA (size_t i)
References definitionParser::COMMA.
enterRule()
void definitionParser::IntervalhullContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterIntervalhull().
Referenced by definitionParser::intervalhull().
exitRule()
void definitionParser::IntervalhullContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitIntervalhull().
Referenced by definitionParser::intervalhull().
getRuleIndex()
size_t definitionParser::IntervalhullContext::getRuleIndex () const override virtual
References definitionParser::RuleIntervalhull.
interval() [1/2]
std::vector< definitionParser::IntervalContext * > definitionParser::IntervalhullContext::interval ()
Referenced by definitionParser::intervalhull().
interval() [2/2]
definitionParser::IntervalContext * definitionParser::IntervalhullContext::interval (size_t i)
KEY_INTERVAL_HULL()
tree::TerminalNode * definitionParser::IntervalhullContext::KEY_INTERVAL_HULL ()
References definitionParser::KEY_INTERVAL_HULL.
LEFTCURLYBRACKET()
tree::TerminalNode * definitionParser::IntervalhullContext::LEFTCURLYBRACKET ()
References definitionParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * definitionParser::IntervalhullContext::RIGHTCURLYBRACKET ()
References definitionParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp