irafhy: definitionParser::VpolytopeContext Class Reference
definitionParser::VpolytopeContext Class Reference
#include <definitionParser.h>
Public Member Functions
VpolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
VpolytopeContext()
definitionParser::VpolytopeContext::VpolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::VpolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > definitionParser::VpolytopeContext::COMMA ()
References definitionParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * definitionParser::VpolytopeContext::COMMA (size_t i)
References definitionParser::COMMA.
enterRule()
void definitionParser::VpolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterVpolytope().
Referenced by definitionParser::vpolytope().
exitRule()
void definitionParser::VpolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitVpolytope().
Referenced by definitionParser::vpolytope().
getRuleIndex()
size_t definitionParser::VpolytopeContext::getRuleIndex () const override virtual
References definitionParser::RuleVpolytope.
LEFTCURLYBRACKET()
tree::TerminalNode * definitionParser::VpolytopeContext::LEFTCURLYBRACKET ()
References definitionParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * definitionParser::VpolytopeContext::RIGHTCURLYBRACKET ()
References definitionParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< definitionParser::VectorContext * > definitionParser::VpolytopeContext::vector ()
Referenced by definitionParser::vpolytope().
vector() [2/2]
definitionParser::VectorContext * definitionParser::VpolytopeContext::vector (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp