irafhy: definitionParser::ExpAddSubContext Class Reference
definitionParser::ExpAddSubContext Class Reference
#include <definitionParser.h>
Public Member Functions
ExpAddSubContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * PLUS ()
antlr4::tree::TerminalNode * MINUS ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpAddSubContext()
definitionParser::ExpAddSubContext::ExpAddSubContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ExpAddSubContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ExpAddSubContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterExpAddSub().
exitRule()
void definitionParser::ExpAddSubContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitExpAddSub().
expression() [1/2]
std::vector< definitionParser::ExpressionContext * > definitionParser::ExpAddSubContext::expression ()
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::ExpAddSubContext::expression (size_t i)
MINUS()
tree::TerminalNode * definitionParser::ExpAddSubContext::MINUS ()
References definitionParser::MINUS.
PLUS()
tree::TerminalNode * definitionParser::ExpAddSubContext::PLUS ()
References definitionParser::PLUS.
Member Data Documentation
OP
antlr4::Token* definitionParser::ExpAddSubContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp