irafhy: settingsParser::LnExpContext Class Reference
settingsParser::LnExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
LnExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LnExpContext()
settingsParser::LnExpContext::LnExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::LnExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::LnExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterLnExp().
exitRule()
void settingsParser::LnExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitLnExp().
expression()
settingsParser::ExpressionContext * settingsParser::LnExpContext::expression ()
KEY_LN_FUNCTION()
tree::TerminalNode * settingsParser::LnExpContext::KEY_LN_FUNCTION ()
References settingsParser::KEY_LN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::LnExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::LnExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp