irafhy: settingsParser::InitialconditionsettingContext Class Reference
settingsParser::InitialconditionsettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
InitialconditionsettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INITIAL_CONDITION ()
antlr4::tree::TerminalNode * DEFINE ()
ConditionContext * condition ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
InitialconditionsettingContext()
settingsParser::InitialconditionsettingContext::InitialconditionsettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::InitialconditionsettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
condition()
settingsParser::ConditionContext * settingsParser::InitialconditionsettingContext::condition ()
Referenced by settingsParser::initialconditionsetting(), and irafhy::SettingsVisitor::visitInitialconditionsetting().
DEFINE()
tree::TerminalNode * settingsParser::InitialconditionsettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::InitialconditionsettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterInitialconditionsetting().
Referenced by settingsParser::initialconditionsetting().
exitRule()
void settingsParser::InitialconditionsettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitInitialconditionsetting().
Referenced by settingsParser::initialconditionsetting().
getRuleIndex()
size_t settingsParser::InitialconditionsettingContext::getRuleIndex () const override virtual
References settingsParser::RuleInitialconditionsetting.
KEY_INITIAL_CONDITION()
tree::TerminalNode * settingsParser::InitialconditionsettingContext::KEY_INITIAL_CONDITION ()
References settingsParser::KEY_INITIAL_CONDITION.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp