irafhy: hybridautomatonParser::VectorContext Class Reference
hybridautomatonParser::VectorContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset115 = nullptr
antlr4::Token * _tset135 = nullptr
Constructor & Destructor Documentation
VectorContext()
hybridautomatonParser::VectorContext::VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::VectorContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::VectorContext::COMMA ()
References hybridautomatonParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * hybridautomatonParser::VectorContext::COMMA (size_t i)
References hybridautomatonParser::COMMA.
enterRule()
void hybridautomatonParser::VectorContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterVector().
Referenced by hybridautomatonParser::vector().
exitRule()
void hybridautomatonParser::VectorContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitVector().
Referenced by hybridautomatonParser::vector().
getRuleIndex()
size_t hybridautomatonParser::VectorContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleVector.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::VectorContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::VectorContext::MINUS ()
References hybridautomatonParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * hybridautomatonParser::VectorContext::MINUS (size_t i)
References hybridautomatonParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::VectorContext::NUMBER ()
References hybridautomatonParser::NUMBER.
Referenced by irafhy::DefinitionVisitor::visitVector().
NUMBER() [2/2]
tree::TerminalNode * hybridautomatonParser::VectorContext::NUMBER (size_t i)
References hybridautomatonParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::VectorContext::PLUS ()
References hybridautomatonParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * hybridautomatonParser::VectorContext::PLUS (size_t i)
References hybridautomatonParser::PLUS.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::VectorContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
Member Data Documentation
_tset115
antlr4::Token* hybridautomatonParser::VectorContext::_tset115 = nullptr
Referenced by hybridautomatonParser::vector().
_tset135
antlr4::Token* hybridautomatonParser::VectorContext::_tset135 = nullptr
Referenced by hybridautomatonParser::vector().
minusToken
antlr4::Token* hybridautomatonParser::VectorContext::minusToken = nullptr
OP
std::vector<antlr4::Token *> hybridautomatonParser::VectorContext::OP
Referenced by hybridautomatonParser::vector(), and irafhy::DefinitionVisitor::visitVector().
plusToken
antlr4::Token* hybridautomatonParser::VectorContext::plusToken = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp