irafhy: transitionsParser::CotExpContext Class Reference
transitionsParser::CotExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
CotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CotExpContext()
transitionsParser::CotExpContext::CotExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::CotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::CotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterCotExp().
exitRule()
void transitionsParser::CotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitCotExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::CotExpContext::expression ()
KEY_COT_FUNCTION()
tree::TerminalNode * transitionsParser::CotExpContext::KEY_COT_FUNCTION ()
References transitionsParser::KEY_COT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::CotExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::CotExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp