irafhy: definitionParser::TanhExpContext Class Reference
definitionParser::TanhExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
TanhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TANH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanhExpContext()
definitionParser::TanhExpContext::TanhExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::TanhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::TanhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterTanhExp().
exitRule()
void definitionParser::TanhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitTanhExp().
expression()
definitionParser::ExpressionContext * definitionParser::TanhExpContext::expression ()
KEY_TANH_FUNCTION()
tree::TerminalNode * definitionParser::TanhExpContext::KEY_TANH_FUNCTION ()
References definitionParser::KEY_TANH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::TanhExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::TanhExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp