irafhy: locationsParser::ExpressionContext Class Reference
locationsParser::ExpressionContext Class Reference
#include <locationsParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpressionContext() [1/2]
locationsParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
ExpressionContext() [2/2]
locationsParser::ExpressionContext::ExpressionContext () default
Member Function Documentation
copyFrom()
void locationsParser::ExpressionContext::copyFrom (ExpressionContext * context)
Referenced by locationsParser::AcosExpContext::AcosExpContext(), locationsParser::AcoshExpContext::AcoshExpContext(), locationsParser::AcotExpContext::AcotExpContext(), locationsParser::AcothExpContext::AcothExpContext(), locationsParser::AsinExpContext::AsinExpContext(), locationsParser::AsinhExpContext::AsinhExpContext(), locationsParser::AtanExpContext::AtanExpContext(), locationsParser::AtanhExpContext::AtanhExpContext(), locationsParser::ConstantContext::ConstantContext(), locationsParser::CosExpContext::CosExpContext(), locationsParser::CoshExpContext::CoshExpContext(), locationsParser::CotExpContext::CotExpContext(), locationsParser::CothExpContext::CothExpContext(), locationsParser::ExpAddSubContext::ExpAddSubContext(), locationsParser::ExpBraContext::ExpBraContext(), locationsParser::ExpExpContext::ExpExpContext(), locationsParser::ExpMulDivContext::ExpMulDivContext(), locationsParser::LnExpContext::LnExpContext(), locationsParser::LogExpContext::LogExpContext(), locationsParser::NegExpContext::NegExpContext(), locationsParser::NexpExpContext::NexpExpContext(), locationsParser::PosExpContext::PosExpContext(), locationsParser::PowExpContext::PowExpContext(), locationsParser::SinExpContext::SinExpContext(), locationsParser::SinhExpContext::SinhExpContext(), locationsParser::SqrExpContext::SqrExpContext(), locationsParser::SqrtExpContext::SqrtExpContext(), locationsParser::TanExpContext::TanExpContext(), locationsParser::TanhExpContext::TanhExpContext(), and locationsParser::VariableContext::VariableContext().
getRuleIndex()
size_t locationsParser::ExpressionContext::getRuleIndex () const override virtual
References locationsParser::RuleExpression.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp