irafhy: settingsParser::PlotsettingContext Class Reference
settingsParser::PlotsettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
PlotsettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_PLOT_FLAG ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * KEY_SWITCH_ON ()
antlr4::tree::TerminalNode * KEY_SWITCH_OFF ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * SWITCH = nullptr
Constructor & Destructor Documentation
PlotsettingContext()
settingsParser::PlotsettingContext::PlotsettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::PlotsettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::PlotsettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::PlotsettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterPlotsetting().
Referenced by settingsParser::plotsetting().
exitRule()
void settingsParser::PlotsettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitPlotsetting().
Referenced by settingsParser::plotsetting().
getRuleIndex()
size_t settingsParser::PlotsettingContext::getRuleIndex () const override virtual
References settingsParser::RulePlotsetting.
KEY_PLOT_FLAG()
tree::TerminalNode * settingsParser::PlotsettingContext::KEY_PLOT_FLAG ()
References settingsParser::KEY_PLOT_FLAG.
KEY_SWITCH_OFF()
tree::TerminalNode * settingsParser::PlotsettingContext::KEY_SWITCH_OFF ()
References settingsParser::KEY_SWITCH_OFF.
KEY_SWITCH_ON()
tree::TerminalNode * settingsParser::PlotsettingContext::KEY_SWITCH_ON ()
References settingsParser::KEY_SWITCH_ON.
Member Data Documentation
SWITCH
antlr4::Token* settingsParser::PlotsettingContext::SWITCH = nullptr
Referenced by settingsParser::plotsetting(), and irafhy::SettingsVisitor::visitPlotsetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp