irafhy: transitionsParser::CothExpContext Class Reference
transitionsParser::CothExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
CothExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COTH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CothExpContext()
transitionsParser::CothExpContext::CothExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::CothExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::CothExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterCothExp().
exitRule()
void transitionsParser::CothExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitCothExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::CothExpContext::expression ()
KEY_COTH_FUNCTION()
tree::TerminalNode * transitionsParser::CothExpContext::KEY_COTH_FUNCTION ()
References transitionsParser::KEY_COTH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::CothExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::CothExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp