irafhy: definitionParser::ConstraintContext Class Reference
definitionParser::ConstraintContext Class Reference
#include <definitionParser.h>
Public Member Functions
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EQUAL ()
antlr4::tree::TerminalNode * UNEQUAL ()
antlr4::tree::TerminalNode * GEQ ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * LSS ()
antlr4::tree::TerminalNode * GTR ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * RELATION = nullptr
Constructor & Destructor Documentation
ConstraintContext()
definitionParser::ConstraintContext::ConstraintContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ConstraintContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ConstraintContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterConstraint().
Referenced by definitionParser::constraint().
EQUAL()
tree::TerminalNode * definitionParser::ConstraintContext::EQUAL ()
References definitionParser::EQUAL.
exitRule()
void definitionParser::ConstraintContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitConstraint().
Referenced by definitionParser::constraint().
expression() [1/2]
std::vector< definitionParser::ExpressionContext * > definitionParser::ConstraintContext::expression ()
Referenced by definitionParser::constraint().
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::ConstraintContext::expression (size_t i)
GEQ()
tree::TerminalNode * definitionParser::ConstraintContext::GEQ ()
References definitionParser::GEQ.
getRuleIndex()
size_t definitionParser::ConstraintContext::getRuleIndex () const override virtual
References definitionParser::RuleConstraint.
GTR()
tree::TerminalNode * definitionParser::ConstraintContext::GTR ()
References definitionParser::GTR.
LEQ()
tree::TerminalNode * definitionParser::ConstraintContext::LEQ ()
References definitionParser::LEQ.
LSS()
tree::TerminalNode * definitionParser::ConstraintContext::LSS ()
References definitionParser::LSS.
UNEQUAL()
tree::TerminalNode * definitionParser::ConstraintContext::UNEQUAL ()
References definitionParser::UNEQUAL.
Member Data Documentation
RELATION
antlr4::Token* definitionParser::ConstraintContext::RELATION = nullptr
Referenced by definitionParser::constraint().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp