irafhy: locationsParser::AcosExpContext Class Reference
locationsParser::AcosExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
AcosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcosExpContext()
locationsParser::AcosExpContext::AcosExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::AcosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::AcosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterAcosExp().
exitRule()
void locationsParser::AcosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitAcosExp().
expression()
locationsParser::ExpressionContext * locationsParser::AcosExpContext::expression ()
KEY_ARCCOS_FUNCTION()
tree::TerminalNode * locationsParser::AcosExpContext::KEY_ARCCOS_FUNCTION ()
References locationsParser::KEY_ARCCOS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::AcosExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::AcosExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp