irafhy: settingsParser::AcothExpContext Class Reference
settingsParser::AcothExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
AcothExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOTH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcothExpContext()
settingsParser::AcothExpContext::AcothExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::AcothExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::AcothExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterAcothExp().
exitRule()
void settingsParser::AcothExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitAcothExp().
expression()
settingsParser::ExpressionContext * settingsParser::AcothExpContext::expression ()
KEY_ARCCOTH_FUNCTION()
tree::TerminalNode * settingsParser::AcothExpContext::KEY_ARCCOTH_FUNCTION ()
References settingsParser::KEY_ARCCOTH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcothExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcothExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp