irafhy: hybridautomatonParser::SqrExpContext Class Reference
hybridautomatonParser::SqrExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
SqrExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SQR_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SqrExpContext()
hybridautomatonParser::SqrExpContext::SqrExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::SqrExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::SqrExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterSqrExp().
exitRule()
void hybridautomatonParser::SqrExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitSqrExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::SqrExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitSqrExp().
KEY_SQR_FUNCTION()
tree::TerminalNode * hybridautomatonParser::SqrExpContext::KEY_SQR_FUNCTION ()
References hybridautomatonParser::KEY_SQR_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SqrExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SqrExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp