irafhy: settingsParser::AcoshExpContext Class Reference
settingsParser::AcoshExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
AcoshExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOSH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcoshExpContext()
settingsParser::AcoshExpContext::AcoshExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::AcoshExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::AcoshExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterAcoshExp().
exitRule()
void settingsParser::AcoshExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitAcoshExp().
expression()
settingsParser::ExpressionContext * settingsParser::AcoshExpContext::expression ()
KEY_ARCCOSH_FUNCTION()
tree::TerminalNode * settingsParser::AcoshExpContext::KEY_ARCCOSH_FUNCTION ()
References settingsParser::KEY_ARCCOSH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcoshExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::AcoshExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp