irafhy: settingsParser::CotExpContext Class Reference
settingsParser::CotExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
CotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CotExpContext()
settingsParser::CotExpContext::CotExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::CotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::CotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterCotExp().
exitRule()
void settingsParser::CotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitCotExp().
expression()
settingsParser::ExpressionContext * settingsParser::CotExpContext::expression ()
KEY_COT_FUNCTION()
tree::TerminalNode * settingsParser::CotExpContext::KEY_COT_FUNCTION ()
References settingsParser::KEY_COT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::CotExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::CotExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp