irafhy: settingsParser::GeometrysettingContext Class Reference
settingsParser::GeometrysettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
GeometrysettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_GEOMETRY ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * VALUE = nullptr
Constructor & Destructor Documentation
GeometrysettingContext()
settingsParser::GeometrysettingContext::GeometrysettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::GeometrysettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::GeometrysettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::GeometrysettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterGeometrysetting().
Referenced by settingsParser::geometrysetting().
exitRule()
void settingsParser::GeometrysettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitGeometrysetting().
Referenced by settingsParser::geometrysetting().
getRuleIndex()
size_t settingsParser::GeometrysettingContext::getRuleIndex () const override virtual
References settingsParser::RuleGeometrysetting.
KEY_GEOMETRY()
tree::TerminalNode * settingsParser::GeometrysettingContext::KEY_GEOMETRY ()
References settingsParser::KEY_GEOMETRY.
KEY_INTERVAL_HULL()
tree::TerminalNode * settingsParser::GeometrysettingContext::KEY_INTERVAL_HULL ()
References settingsParser::KEY_INTERVAL_HULL.
KEY_POLYTOPE()
tree::TerminalNode * settingsParser::GeometrysettingContext::KEY_POLYTOPE ()
References settingsParser::KEY_POLYTOPE.
Member Data Documentation
VALUE
antlr4::Token* settingsParser::GeometrysettingContext::VALUE = nullptr
Referenced by settingsParser::geometrysetting(), and irafhy::SettingsVisitor::visitGeometrysetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp