irafhy: settingsParser::ExpAddSubContext Class Reference
settingsParser::ExpAddSubContext Class Reference
#include <settingsParser.h>
Public Member Functions
ExpAddSubContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * PLUS ()
antlr4::tree::TerminalNode * MINUS ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpAddSubContext()
settingsParser::ExpAddSubContext::ExpAddSubContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ExpAddSubContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::ExpAddSubContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterExpAddSub().
exitRule()
void settingsParser::ExpAddSubContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitExpAddSub().
expression() [1/2]
std::vector< settingsParser::ExpressionContext * > settingsParser::ExpAddSubContext::expression ()
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::ExpAddSubContext::expression (size_t i)
MINUS()
tree::TerminalNode * settingsParser::ExpAddSubContext::MINUS ()
References settingsParser::MINUS.
PLUS()
tree::TerminalNode * settingsParser::ExpAddSubContext::PLUS ()
References settingsParser::PLUS.
Member Data Documentation
OP
antlr4::Token* settingsParser::ExpAddSubContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp