irafhy: settingsParser::NegExpContext Class Reference
settingsParser::NegExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
NegExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * MINUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NegExpContext()
settingsParser::NegExpContext::NegExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::NegExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::NegExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterNegExp().
exitRule()
void settingsParser::NegExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitNegExp().
expression()
settingsParser::ExpressionContext * settingsParser::NegExpContext::expression ()
MINUS()
tree::TerminalNode * settingsParser::NegExpContext::MINUS ()
References settingsParser::MINUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp