irafhy: locationsParser::AcotExpContext Class Reference
locationsParser::AcotExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
AcotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcotExpContext()
locationsParser::AcotExpContext::AcotExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::AcotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::AcotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterAcotExp().
exitRule()
void locationsParser::AcotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitAcotExp().
expression()
locationsParser::ExpressionContext * locationsParser::AcotExpContext::expression ()
KEY_ARCCOT_FUNCTION()
tree::TerminalNode * locationsParser::AcotExpContext::KEY_ARCCOT_FUNCTION ()
References locationsParser::KEY_ARCCOT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::AcotExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::AcotExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp