irafhy: hybridautomatonParser::ModelidContext Class Reference
hybridautomatonParser::ModelidContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ModelidContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_NAME ()
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ModelidContext()
hybridautomatonParser::ModelidContext::ModelidContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ModelidContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ModelidContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterModelid().
Referenced by hybridautomatonParser::modelid().
exitRule()
void hybridautomatonParser::ModelidContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitModelid().
Referenced by hybridautomatonParser::modelid().
getRuleIndex()
size_t hybridautomatonParser::ModelidContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleModelid.
KEY_NAME()
tree::TerminalNode * hybridautomatonParser::ModelidContext::KEY_NAME ()
References hybridautomatonParser::KEY_NAME.
VARIABLE()
tree::TerminalNode * hybridautomatonParser::ModelidContext::VARIABLE ()
References hybridautomatonParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp