irafhy: locationsParser::CosExpContext Class Reference
locationsParser::CosExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
CosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CosExpContext()
locationsParser::CosExpContext::CosExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::CosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::CosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterCosExp().
exitRule()
void locationsParser::CosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitCosExp().
expression()
locationsParser::ExpressionContext * locationsParser::CosExpContext::expression ()
KEY_COS_FUNCTION()
tree::TerminalNode * locationsParser::CosExpContext::KEY_COS_FUNCTION ()
References locationsParser::KEY_COS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::CosExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::CosExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp