irafhy: hybridautomatonParser::PolytopeContext Class Reference
hybridautomatonParser::PolytopeContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
PolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
PolytopeContext()
hybridautomatonParser::PolytopeContext::PolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::PolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::PolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterPolytope().
Referenced by hybridautomatonParser::polytope().
exitRule()
void hybridautomatonParser::PolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitPolytope().
Referenced by hybridautomatonParser::polytope().
getRuleIndex()
size_t hybridautomatonParser::PolytopeContext::getRuleIndex () const override virtual
References hybridautomatonParser::RulePolytope.
hpolytope()
hybridautomatonParser::HpolytopeContext * hybridautomatonParser::PolytopeContext::hpolytope ()
Referenced by hybridautomatonParser::polytope(), and irafhy::DefinitionVisitor::visitPolytope().
KEY_POLYTOPE()
tree::TerminalNode * hybridautomatonParser::PolytopeContext::KEY_POLYTOPE ()
References hybridautomatonParser::KEY_POLYTOPE.
vpolytope()
hybridautomatonParser::VpolytopeContext * hybridautomatonParser::PolytopeContext::vpolytope ()
Referenced by hybridautomatonParser::polytope(), and irafhy::DefinitionVisitor::visitPolytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp