irafhy: transitionsParser::DirectionContext Class Reference
transitionsParser::DirectionContext Class Reference
#include <transitionsParser.h>
Public Member Functions
DirectionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_DIRECTION ()
std::vector< antlr4::tree::TerminalNode * > VARIABLE ()
antlr4::tree::TerminalNode * VARIABLE (size_t i)
antlr4::tree::TerminalNode * FROMTO ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
DirectionContext()
transitionsParser::DirectionContext::DirectionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::DirectionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::DirectionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterDirection().
Referenced by transitionsParser::direction().
exitRule()
void transitionsParser::DirectionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitDirection().
Referenced by transitionsParser::direction().
FROMTO()
tree::TerminalNode * transitionsParser::DirectionContext::FROMTO ()
References transitionsParser::FROMTO.
getRuleIndex()
size_t transitionsParser::DirectionContext::getRuleIndex () const override virtual
References transitionsParser::RuleDirection.
KEY_DIRECTION()
tree::TerminalNode * transitionsParser::DirectionContext::KEY_DIRECTION ()
References transitionsParser::KEY_DIRECTION.
VARIABLE() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::DirectionContext::VARIABLE ()
References transitionsParser::VARIABLE.
VARIABLE() [2/2]
tree::TerminalNode * transitionsParser::DirectionContext::VARIABLE (size_t i)
References transitionsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp