irafhy: hybridautomatonParser::ExpressionContext Class Reference
hybridautomatonParser::ExpressionContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpressionContext() [1/2]
hybridautomatonParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
ExpressionContext() [2/2]
hybridautomatonParser::ExpressionContext::ExpressionContext () default
Member Function Documentation
copyFrom()
void hybridautomatonParser::ExpressionContext::copyFrom (ExpressionContext * context)
Referenced by hybridautomatonParser::AcosExpContext::AcosExpContext(), hybridautomatonParser::AcoshExpContext::AcoshExpContext(), hybridautomatonParser::AcotExpContext::AcotExpContext(), hybridautomatonParser::AcothExpContext::AcothExpContext(), hybridautomatonParser::AsinExpContext::AsinExpContext(), hybridautomatonParser::AsinhExpContext::AsinhExpContext(), hybridautomatonParser::AtanExpContext::AtanExpContext(), hybridautomatonParser::AtanhExpContext::AtanhExpContext(), hybridautomatonParser::ConstantContext::ConstantContext(), hybridautomatonParser::CosExpContext::CosExpContext(), hybridautomatonParser::CoshExpContext::CoshExpContext(), hybridautomatonParser::CotExpContext::CotExpContext(), hybridautomatonParser::CothExpContext::CothExpContext(), hybridautomatonParser::ExpAddSubContext::ExpAddSubContext(), hybridautomatonParser::ExpBraContext::ExpBraContext(), hybridautomatonParser::ExpExpContext::ExpExpContext(), hybridautomatonParser::ExpMulDivContext::ExpMulDivContext(), hybridautomatonParser::LnExpContext::LnExpContext(), hybridautomatonParser::LogExpContext::LogExpContext(), hybridautomatonParser::NegExpContext::NegExpContext(), hybridautomatonParser::NexpExpContext::NexpExpContext(), hybridautomatonParser::PosExpContext::PosExpContext(), hybridautomatonParser::PowExpContext::PowExpContext(), hybridautomatonParser::SinExpContext::SinExpContext(), hybridautomatonParser::SinhExpContext::SinhExpContext(), hybridautomatonParser::SqrExpContext::SqrExpContext(), hybridautomatonParser::SqrtExpContext::SqrtExpContext(), hybridautomatonParser::TanExpContext::TanExpContext(), hybridautomatonParser::TanhExpContext::TanhExpContext(), and hybridautomatonParser::VariableContext::VariableContext().
getRuleIndex()
size_t hybridautomatonParser::ExpressionContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleExpression.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp