irafhy: transitionsParser::PosExpContext Class Reference
transitionsParser::PosExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
PosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * PLUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PosExpContext()
transitionsParser::PosExpContext::PosExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::PosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::PosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterPosExp().
exitRule()
void transitionsParser::PosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitPosExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::PosExpContext::expression ()
PLUS()
tree::TerminalNode * transitionsParser::PosExpContext::PLUS ()
References transitionsParser::PLUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp