irafhy: settingsParser::PowExpContext Class Reference
settingsParser::PowExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
PowExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_POWER_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PowExpContext()
settingsParser::PowExpContext::PowExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::PowExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * settingsParser::PowExpContext::COMMA ()
References settingsParser::COMMA.
enterRule()
void settingsParser::PowExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterPowExp().
exitRule()
void settingsParser::PowExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitPowExp().
expression() [1/2]
std::vector< settingsParser::ExpressionContext * > settingsParser::PowExpContext::expression ()
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::PowExpContext::expression (size_t i)
KEY_POWER_FUNCTION()
tree::TerminalNode * settingsParser::PowExpContext::KEY_POWER_FUNCTION ()
References settingsParser::KEY_POWER_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::PowExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::PowExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp