irafhy: definitionParser::ConstantContext Class Reference
definitionParser::ConstantContext Class Reference
#include <definitionParser.h>
Public Member Functions
ConstantContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * NUMBER ()
antlr4::tree::TerminalNode * SCINUM ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ConstantContext()
definitionParser::ConstantContext::ConstantContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ConstantContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ConstantContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterConstant().
exitRule()
void definitionParser::ConstantContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitConstant().
NUMBER()
tree::TerminalNode * definitionParser::ConstantContext::NUMBER ()
References definitionParser::NUMBER.
SCINUM()
tree::TerminalNode * definitionParser::ConstantContext::SCINUM ()
References definitionParser::SCINUM.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp