irafhy: locationsParser::VariableContext Class Reference
locationsParser::VariableContext Class Reference
#include <locationsParser.h>
Public Member Functions
VariableContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
VariableContext()
locationsParser::VariableContext::VariableContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::VariableContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::VariableContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterVariable().
exitRule()
void locationsParser::VariableContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitVariable().
VARIABLE()
tree::TerminalNode * locationsParser::VariableContext::VARIABLE ()
References locationsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp