irafhy: settingsParser::ConstraintsContext Class Reference
settingsParser::ConstraintsContext Class Reference
#include <settingsParser.h>
Public Member Functions
ConstraintsContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ConstraintContext * > constraint ()
ConstraintContext * constraint (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConstraintsContext()
settingsParser::ConstraintsContext::ConstraintsContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ConstraintsContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
constraint() [1/2]
std::vector< settingsParser::ConstraintContext * > settingsParser::ConstraintsContext::constraint ()
Referenced by settingsParser::constraints().
constraint() [2/2]
settingsParser::ConstraintContext * settingsParser::ConstraintsContext::constraint (size_t i)
enterRule()
void settingsParser::ConstraintsContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterConstraints().
Referenced by settingsParser::constraints().
exitRule()
void settingsParser::ConstraintsContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitConstraints().
Referenced by settingsParser::constraints().
getRuleIndex()
size_t settingsParser::ConstraintsContext::getRuleIndex () const override virtual
References settingsParser::RuleConstraints.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp