irafhy: definitionParser::FormulaContext Class Reference
definitionParser::FormulaContext Class Reference
#include <definitionParser.h>
Public Member Functions
FormulaContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * ASSIGN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * DERIVATIVE ()
IntervalContext * interval ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FormulaContext()
definitionParser::FormulaContext::FormulaContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::FormulaContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ASSIGN()
tree::TerminalNode * definitionParser::FormulaContext::ASSIGN ()
References definitionParser::ASSIGN.
DERIVATIVE()
tree::TerminalNode * definitionParser::FormulaContext::DERIVATIVE ()
References definitionParser::DERIVATIVE.
enterRule()
void definitionParser::FormulaContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterFormula().
Referenced by definitionParser::formula().
exitRule()
void definitionParser::FormulaContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitFormula().
Referenced by definitionParser::formula().
expression()
definitionParser::ExpressionContext * definitionParser::FormulaContext::expression ()
Referenced by definitionParser::formula().
getRuleIndex()
size_t definitionParser::FormulaContext::getRuleIndex () const override virtual
References definitionParser::RuleFormula.
interval()
definitionParser::IntervalContext * definitionParser::FormulaContext::interval ()
Referenced by definitionParser::formula().
VARIABLE()
tree::TerminalNode * definitionParser::FormulaContext::VARIABLE ()
References definitionParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp