irafhy: locationsParser::IntervalhullContext Class Reference
locationsParser::IntervalhullContext Class Reference
#include <locationsParser.h>
Public Member Functions
IntervalhullContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< IntervalContext * > interval ()
IntervalContext * interval (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntervalhullContext()
locationsParser::IntervalhullContext::IntervalhullContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::IntervalhullContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalhullContext::COMMA ()
References locationsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * locationsParser::IntervalhullContext::COMMA (size_t i)
References locationsParser::COMMA.
enterRule()
void locationsParser::IntervalhullContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterIntervalhull().
Referenced by locationsParser::intervalhull().
exitRule()
void locationsParser::IntervalhullContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitIntervalhull().
Referenced by locationsParser::intervalhull().
getRuleIndex()
size_t locationsParser::IntervalhullContext::getRuleIndex () const override virtual
References locationsParser::RuleIntervalhull.
interval() [1/2]
std::vector< locationsParser::IntervalContext * > locationsParser::IntervalhullContext::interval ()
Referenced by locationsParser::intervalhull().
interval() [2/2]
locationsParser::IntervalContext * locationsParser::IntervalhullContext::interval (size_t i)
KEY_INTERVAL_HULL()
tree::TerminalNode * locationsParser::IntervalhullContext::KEY_INTERVAL_HULL ()
References locationsParser::KEY_INTERVAL_HULL.
LEFTCURLYBRACKET()
tree::TerminalNode * locationsParser::IntervalhullContext::LEFTCURLYBRACKET ()
References locationsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * locationsParser::IntervalhullContext::RIGHTCURLYBRACKET ()
References locationsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp