irafhy: transitionsParser::SqrExpContext Class Reference
transitionsParser::SqrExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
SqrExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SQR_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SqrExpContext()
transitionsParser::SqrExpContext::SqrExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::SqrExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::SqrExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterSqrExp().
exitRule()
void transitionsParser::SqrExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitSqrExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::SqrExpContext::expression ()
KEY_SQR_FUNCTION()
tree::TerminalNode * transitionsParser::SqrExpContext::KEY_SQR_FUNCTION ()
References transitionsParser::KEY_SQR_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::SqrExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::SqrExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp