irafhy: irafhy::Polytope Class Reference
irafhy::Polytope Class Reference
#include <polytope.h>
Public Member Functions
Polytope ()
constructor
Polytope (const Polytope &polytope)=default
copy constructor
Polytope (Polytope &&polytope) noexcept=default
move constructor
Polytope (const std::vector< Point > &points)
constructor with given points
Polytope (const std::vector< HalfSpace > &halfSpaces)
constructor with given half spaces
Polytope (const std::vector< capd::interval > &constraints)
constructor with given interval constraints
Polytope (const capd::C0Rect2Set &set)
constructor with given state set
Polytope (const Point &center, double radius)
constructor with given center and related radius
Polytope (const Eigen::VectorXd &center, double radius)
constructor with given coordinate of the center and related radius
~Polytope () override=default
destructor
std::vector< Point > pointConstraints () const
get the extreme vertices of the polytope
std::vector< HalfSpace > halfSpaceConstraints () const
get the half space constraints of the polytope
Point centroid () const
get the centroid of the polytope
std::vector< capd::interval > constraints () const
get the variance constraints of all dimensions
bool empty () const override
check if the polytope is empty or not
int dimension () const override
get the dimension of the space which the polytope in
double volume () const
get the volume of the polytope
bool intersect (const Polytope &rhs, Polytope &result) const override
check if the current polytope intersect with the given right hand side one or not
Polytope unite (const Polytope &rhs) const override
get the union of the current polytope and the given right hand side one
bool contains (const Point &point) const override
check if the given point inside the domain which defined by the current polytope or not
bool contains (const Eigen::VectorXd &coordinate) const override
check if the given coordinate inside the domain which defined by the current polytope or not
Polytope & operator= (const Polytope &rhs)=default
assignment operator
Polytope & operator= (Polytope &&rhs) noexcept=default
assignment operator
Public Member Functions inherited from irafhy::Geometry< Polytope >
virtual ~Geometry ()=default
destructor
Static Public Member Functions
static Polytope Empty (std::size_t dimension=0)
static constructor of Empty polytope
Private Member Functions
Polytope (const std::vector< Point > &pointConstraints, const std::vector< HalfSpace > &halfSpaceConstraints, double volume, int dimension)
constructor with given constraints and related information
void init (const convexConstraints &constraints)
initialize the polytope with given convex hull
std::vector< Point > verticesEnumerationDualPly (const std::vector< HalfSpace > &halfSpaces)
enumerate vertices using dual polytope method
std::vector< Point > verticesEnumerationIntersect (const std::vector< HalfSpace > &halfSpaces)
enumerate vertices using intersection computation
std::vector< Point > verticesEnumeration (const std::vector< capd::interval > &constraints)
enumerate extreme vertices with given constraints in interval form
std::vector< Point > verticesEnumeration (const Eigen::VectorXd &center, double radius)
enumerate extreme vertices with given center coordinate and related radius
Private Attributes
std::vector< Point > pointConstraints_
point constraints which define the convex hull entity
std::vector< HalfSpace > halfSpaceConstraints_
half spaces constraints which define the convex hull entity
double volume_ = 0.0
volume of the convex hull
int dimension_ = 0
dimension of the space which current convex hull in
Constructor & Destructor Documentation
Polytope() [1/10]
irafhy::Polytope::Polytope (const std::vector< Point > & pointConstraints, const std::vector< HalfSpace > & halfSpaceConstraints, double volume, int dimension) private
constructor with given constraints and related information
Parameters
pointConstraints point constraints of the convex hull entity
halfSpaceConstraints half spaces constraints of the convex hull entity
volume volume of the convex hull
dimension dimension of the space which the polytope in
References dimension(), dimension_, halfSpaceConstraints(), halfSpaceConstraints_, pointConstraints(), pointConstraints_, volume(), and volume_.
Polytope() [2/10]
irafhy::Polytope::Polytope ()
constructor
References dimension_, halfSpaceConstraints_, pointConstraints_, and volume_.
Referenced by Empty(), intersect(), and unite().
Polytope() [3/10]
irafhy::Polytope::Polytope (const Polytope & polytope) default
copy constructor
Parameters
polytope given polytope
Polytope() [4/10]
irafhy::Polytope::Polytope (Polytope && polytope) default noexcept
move constructor
Parameters
polytope given polytope
Polytope() [5/10]
irafhy::Polytope::Polytope (const std::vector< Point > & points) explicit
constructor with given points
Parameters
points given points
References irafhy::ConvexHull::constraints(), dimension_, halfSpaceConstraints_, init(), pointConstraints_, and volume_.
Polytope() [6/10]
irafhy::Polytope::Polytope (const std::vector< HalfSpace > & halfSpaces) explicit
constructor with given half spaces
Parameters
halfSpaces given half spaces
References irafhy::ConvexHull::constraints(), dimension(), dimension_, halfSpaceConstraints_, init(), pointConstraints_, verticesEnumerationIntersect(), and volume_.
Polytope() [7/10]
irafhy::Polytope::Polytope (const std::vector< capd::interval > & constraints) explicit
constructor with given interval constraints
Parameters
constraints given interval constraints
References irafhy::ConvexHull::constraints(), dimension_, halfSpaceConstraints_, init(), pointConstraints_, verticesEnumeration(), and volume_.
Polytope() [8/10]
irafhy::Polytope::Polytope (const capd::C0Rect2Set & set) explicit
constructor with given state set
Parameters
set given state set
References dimension(), dimension_, halfSpaceConstraints_, pointConstraints_, and volume_.
Polytope() [9/10]
irafhy::Polytope::Polytope (const Point & center, double radius)
constructor with given center and related radius
Parameters
center center of the polytope
radius radius which defines the variance of each dimension
References irafhy::ConvexHull::constraints(), irafhy::Point::coordinate(), init(), and verticesEnumeration().
Polytope() [10/10]
irafhy::Polytope::Polytope (const Eigen::VectorXd & center, double radius)
constructor with given coordinate of the center and related radius
Parameters
center coordinate of the center of the polytope
radius radius which defines the variance of each dimension
References irafhy::ConvexHull::constraints(), init(), and verticesEnumeration().
~Polytope()
irafhy::Polytope::~Polytope () override default
destructor
Member Function Documentation
centroid()
Point irafhy::Polytope::centroid () const
get the centroid of the polytope
Returns
the centroid of the polytope in Point form
References pointConstraints_.
constraints()
std::vector< capd::interval > irafhy::Polytope::constraints () const
get the variance constraints of all dimensions
Returns
variance constraints in interval vector form
References dimension_, and pointConstraints_.
Referenced by irafhy::CSPSolver::branchPruneSolve().
contains() [1/2]
bool irafhy::Polytope::contains (const Point & point) const override virtual
check if the given point inside the domain which defined by the current polytope or not
Parameters
point given point
Returns
TRUE if the given point inside the domain which defined by the current polytope
Implements irafhy::Geometry< Polytope >.
References halfSpaceConstraints_.
Referenced by intersect().
contains() [2/2]
bool irafhy::Polytope::contains (const Eigen::VectorXd & coordinate) const override virtual
check if the given coordinate inside the domain which defined by the current polytope or not
Parameters
coordinate given coordinate
Returns
TRUE if the given coordinate inside the domain which defined by the current polytope
Implements irafhy::Geometry< Polytope >.
References halfSpaceConstraints_.
dimension()
int irafhy::Polytope::dimension () const override virtual
get the dimension of the space which the polytope in
Returns
the dimension of the space which the polytope in
Implements irafhy::Geometry< Polytope >.
References dimension_.
Referenced by irafhy::CSPSolver::branchPruneSolve(), Empty(), irafhy::operator<<(), Polytope(), verticesEnumerationDualPly(), and verticesEnumerationIntersect().
Empty()
Polytope irafhy::Polytope::Empty (std::size_t dimension = 0) static
static constructor of Empty polytope
Parameters
dimension dimension of the space which the polytope in
Returns
resulting Empty polytope
References dimension(), irafhy::HalfSpace::Empty(), Polytope(), and irafhy::Point::zero().
Referenced by irafhy::Condition::Empty(), and intersect().
empty()
bool irafhy::Polytope::empty () const override virtual
check if the polytope is empty or not
Returns
TRUE if the polytope has zero volume or empty convex hull constraints
Implements irafhy::Geometry< Polytope >.
References halfSpaceConstraints_, pointConstraints_, and volume_.
Referenced by irafhy::CSPSolver::branchPruneSolve(), and intersect().
halfSpaceConstraints()
std::vector< HalfSpace > irafhy::Polytope::halfSpaceConstraints () const
get the half space constraints of the polytope
Returns
half space constraints of the polytope
References halfSpaceConstraints_.
Referenced by irafhy::CSPSolver::branchPruneSolve(), intersect(), irafhy::operator<<(), and Polytope().
init()
void irafhy::Polytope::init (const convexConstraints & constraints) private
initialize the polytope with given convex hull
Parameters
constraints
References irafhy::convexConstraints::dimension(), dimension_, irafhy::convexConstraints::halfSpaceConstraints(), halfSpaceConstraints_, irafhy::convexConstraints::pointConstraints(), pointConstraints_, irafhy::convexConstraints::volume(), and volume_.
Referenced by Polytope().
intersect()
bool irafhy::Polytope::intersect (const Polytope & rhs, Polytope & result) const override virtual
check if the current polytope intersect with the given right hand side one or not
Parameters
rhs right hand side polytope
result intersection of two polytope if exist
Returns
TRUE if the intersection of two polytope isn't empty
Implements irafhy::Geometry< Polytope >.
References contains(), dimension_, Empty(), empty(), halfSpaceConstraints(), halfSpaceConstraints_, pointConstraints(), pointConstraints_, and Polytope().
operator=() [1/2]
Polytope& irafhy::Polytope::operator= (const Polytope & rhs) default
assignment operator
Parameters
rhs right hand side polytope
Returns
resulting polytope
operator=() [2/2]
Polytope& irafhy::Polytope::operator= (Polytope && rhs) default noexcept
assignment operator
Parameters
rhs right hand side polytope
Returns
resulting polytope
pointConstraints()
std::vector< Point > irafhy::Polytope::pointConstraints () const
get the extreme vertices of the polytope
Returns
extreme vertices of the polytope
References pointConstraints_.
Referenced by intersect(), irafhy::operator<<(), Polytope(), and unite().
unite()
Polytope irafhy::Polytope::unite (const Polytope & rhs) const override virtual
get the union of the current polytope and the given right hand side one
Parameters
rhs right hand side polytope
Returns
resulting union of two polytope
Implements irafhy::Geometry< Polytope >.
References pointConstraints(), and Polytope().
verticesEnumeration() [1/2]
std::vector< Point > irafhy::Polytope::verticesEnumeration (const std::vector< capd::interval > & constraints) private
enumerate extreme vertices with given constraints in interval form
Parameters
constraints given space constraints
Returns
resulting extreme vertices of the target domain defined by the given constraints
Referenced by Polytope().
verticesEnumeration() [2/2]
std::vector< Point > irafhy::Polytope::verticesEnumeration (const Eigen::VectorXd & center, double radius) private
enumerate extreme vertices with given center coordinate and related radius
Parameters
center coordinate of the target domain
radius given radius
Returns
resulting extreme vertices of the target domain defined by the given center and related radius
verticesEnumerationDualPly()
std::vector< Point > irafhy::Polytope::verticesEnumerationDualPly (const std::vector< HalfSpace > & halfSpaces) private
enumerate vertices using dual polytope method
Parameters
halfSpaces given half spaces
Returns
resulting extreme vertices of the target domain defined by the given half spaces
References irafhy::ConvexHull::constraints(), dimension(), and irafhy::convexConstraints::faceVerticesIdx().
verticesEnumerationIntersect()
std::vector< Point > irafhy::Polytope::verticesEnumerationIntersect (const std::vector< HalfSpace > & halfSpaces) private
enumerate vertices using intersection computation
Parameters
halfSpaces given half spaces
Returns
resulting extreme vertices of the target domain defined by the given half spaces
References dimension(), and matplotlibcpp::fill().
Referenced by Polytope().
volume()
double irafhy::Polytope::volume () const
get the volume of the polytope
Returns
the volume of the polytope
References volume_.
Referenced by irafhy::operator<<(), and Polytope().
Member Data Documentation
dimension_
int irafhy::Polytope::dimension_ = 0 private
dimension of the space which current convex hull in
Referenced by constraints(), dimension(), init(), intersect(), and Polytope().
halfSpaceConstraints_
std::vector<HalfSpace> irafhy::Polytope::halfSpaceConstraints_ private
half spaces constraints which define the convex hull entity
Referenced by contains(), empty(), halfSpaceConstraints(), init(), intersect(), and Polytope().
pointConstraints_
std::vector<Point> irafhy::Polytope::pointConstraints_ private
point constraints which define the convex hull entity
Referenced by centroid(), constraints(), empty(), init(), intersect(), pointConstraints(), and Polytope().
volume_
double irafhy::Polytope::volume_ = 0.0 private
volume of the convex hull
Referenced by empty(), init(), Polytope(), and volume().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/representation/geometric/polytope.h
/home/jianqiang/CLionProjects/irafhy/src/representation/geometric/polytope.cpp