irafhy: transitionsParser::ExpAddSubContext Class Reference
transitionsParser::ExpAddSubContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ExpAddSubContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * PLUS ()
antlr4::tree::TerminalNode * MINUS ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpAddSubContext()
transitionsParser::ExpAddSubContext::ExpAddSubContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::ExpAddSubContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::ExpAddSubContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterExpAddSub().
exitRule()
void transitionsParser::ExpAddSubContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitExpAddSub().
expression() [1/2]
std::vector< transitionsParser::ExpressionContext * > transitionsParser::ExpAddSubContext::expression ()
expression() [2/2]
transitionsParser::ExpressionContext * transitionsParser::ExpAddSubContext::expression (size_t i)
MINUS()
tree::TerminalNode * transitionsParser::ExpAddSubContext::MINUS ()
References transitionsParser::MINUS.
PLUS()
tree::TerminalNode * transitionsParser::ExpAddSubContext::PLUS ()
References transitionsParser::PLUS.
Member Data Documentation
OP
antlr4::Token* transitionsParser::ExpAddSubContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp