irafhy: hybridautomatonParser::TanExpContext Class Reference
hybridautomatonParser::TanExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
TanExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TAN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanExpContext()
hybridautomatonParser::TanExpContext::TanExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::TanExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::TanExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterTanExp().
exitRule()
void hybridautomatonParser::TanExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitTanExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::TanExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitTanExp().
KEY_TAN_FUNCTION()
tree::TerminalNode * hybridautomatonParser::TanExpContext::KEY_TAN_FUNCTION ()
References hybridautomatonParser::KEY_TAN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::TanExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::TanExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp