irafhy: definitionParser::AcotExpContext Class Reference
definitionParser::AcotExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
AcotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcotExpContext()
definitionParser::AcotExpContext::AcotExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::AcotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::AcotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterAcotExp().
exitRule()
void definitionParser::AcotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitAcotExp().
expression()
definitionParser::ExpressionContext * definitionParser::AcotExpContext::expression ()
KEY_ARCCOT_FUNCTION()
tree::TerminalNode * definitionParser::AcotExpContext::KEY_ARCCOT_FUNCTION ()
References definitionParser::KEY_ARCCOT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::AcotExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::AcotExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp