irafhy: locationsParser::ConditionContext Class Reference
locationsParser::ConditionContext Class Reference
#include <locationsParser.h>
Public Member Functions
ConditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_CONDITION ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
IntervalhullContext * intervalhull ()
PolytopeContext * polytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConditionContext()
locationsParser::ConditionContext::ConditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ConditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ConditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterCondition().
Referenced by locationsParser::condition().
exitRule()
void locationsParser::ConditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitCondition().
Referenced by locationsParser::condition().
getRuleIndex()
size_t locationsParser::ConditionContext::getRuleIndex () const override virtual
References locationsParser::RuleCondition.
intervalhull()
locationsParser::IntervalhullContext * locationsParser::ConditionContext::intervalhull ()
Referenced by locationsParser::condition().
KEY_CONDITION()
tree::TerminalNode * locationsParser::ConditionContext::KEY_CONDITION ()
References locationsParser::KEY_CONDITION.
LEFTCURLYBRACKET()
tree::TerminalNode * locationsParser::ConditionContext::LEFTCURLYBRACKET ()
References locationsParser::LEFTCURLYBRACKET.
polytope()
locationsParser::PolytopeContext * locationsParser::ConditionContext::polytope ()
Referenced by locationsParser::condition().
RIGHTCURLYBRACKET()
tree::TerminalNode * locationsParser::ConditionContext::RIGHTCURLYBRACKET ()
References locationsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp