irafhy: transitionsParser::ConditionContext Class Reference
transitionsParser::ConditionContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ConditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_CONDITION ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
IntervalhullContext * intervalhull ()
PolytopeContext * polytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConditionContext()
transitionsParser::ConditionContext::ConditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::ConditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::ConditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterCondition().
Referenced by transitionsParser::condition().
exitRule()
void transitionsParser::ConditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitCondition().
Referenced by transitionsParser::condition().
getRuleIndex()
size_t transitionsParser::ConditionContext::getRuleIndex () const override virtual
References transitionsParser::RuleCondition.
intervalhull()
transitionsParser::IntervalhullContext * transitionsParser::ConditionContext::intervalhull ()
Referenced by transitionsParser::condition().
KEY_CONDITION()
tree::TerminalNode * transitionsParser::ConditionContext::KEY_CONDITION ()
References transitionsParser::KEY_CONDITION.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::ConditionContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
polytope()
transitionsParser::PolytopeContext * transitionsParser::ConditionContext::polytope ()
Referenced by transitionsParser::condition().
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::ConditionContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp