irafhy: hybridautomatonParser::SinhExpContext Class Reference
hybridautomatonParser::SinhExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
SinhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SINH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinhExpContext()
hybridautomatonParser::SinhExpContext::SinhExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::SinhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::SinhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterSinhExp().
exitRule()
void hybridautomatonParser::SinhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitSinhExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::SinhExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitSinhExp().
KEY_SINH_FUNCTION()
tree::TerminalNode * hybridautomatonParser::SinhExpContext::KEY_SINH_FUNCTION ()
References hybridautomatonParser::KEY_SINH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SinhExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::SinhExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp