irafhy: settingsParser::SystemContext Class Reference
settingsParser::SystemContext Class Reference
#include <settingsParser.h>
Public Member Functions
SystemContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FormulaContext * > formula ()
FormulaContext * formula (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SystemContext()
settingsParser::SystemContext::SystemContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::SystemContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::SystemContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterSystem().
Referenced by settingsParser::system().
exitRule()
void settingsParser::SystemContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitSystem().
Referenced by settingsParser::system().
formula() [1/2]
std::vector< settingsParser::FormulaContext * > settingsParser::SystemContext::formula ()
Referenced by settingsParser::system().
formula() [2/2]
settingsParser::FormulaContext * settingsParser::SystemContext::formula (size_t i)
getRuleIndex()
size_t settingsParser::SystemContext::getRuleIndex () const override virtual
References settingsParser::RuleSystem.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp