irafhy: definitionParser::LogExpContext Class Reference
definitionParser::LogExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
LogExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LOG_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LogExpContext()
definitionParser::LogExpContext::LogExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::LogExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::LogExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterLogExp().
exitRule()
void definitionParser::LogExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitLogExp().
expression()
definitionParser::ExpressionContext * definitionParser::LogExpContext::expression ()
KEY_LOG_FUNCTION()
tree::TerminalNode * definitionParser::LogExpContext::KEY_LOG_FUNCTION ()
References definitionParser::KEY_LOG_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::LogExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::LogExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp