irafhy: settingsParser::StartmodelidsettingContext Class Reference
settingsParser::StartmodelidsettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
StartmodelidsettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_START_MODEL_ID ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
StartmodelidsettingContext()
settingsParser::StartmodelidsettingContext::StartmodelidsettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::StartmodelidsettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::StartmodelidsettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::StartmodelidsettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterStartmodelidsetting().
Referenced by settingsParser::startmodelidsetting().
exitRule()
void settingsParser::StartmodelidsettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitStartmodelidsetting().
Referenced by settingsParser::startmodelidsetting().
getRuleIndex()
size_t settingsParser::StartmodelidsettingContext::getRuleIndex () const override virtual
References settingsParser::RuleStartmodelidsetting.
KEY_START_MODEL_ID()
tree::TerminalNode * settingsParser::StartmodelidsettingContext::KEY_START_MODEL_ID ()
References settingsParser::KEY_START_MODEL_ID.
VARIABLE()
tree::TerminalNode * settingsParser::StartmodelidsettingContext::VARIABLE ()
References settingsParser::VARIABLE.
Referenced by irafhy::SettingsVisitor::visitStartmodelidsetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp