irafhy: locationsParser::ConstantContext Class Reference
locationsParser::ConstantContext Class Reference
#include <locationsParser.h>
Public Member Functions
ConstantContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * NUMBER ()
antlr4::tree::TerminalNode * SCINUM ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ConstantContext()
locationsParser::ConstantContext::ConstantContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ConstantContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ConstantContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterConstant().
exitRule()
void locationsParser::ConstantContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitConstant().
NUMBER()
tree::TerminalNode * locationsParser::ConstantContext::NUMBER ()
References locationsParser::NUMBER.
SCINUM()
tree::TerminalNode * locationsParser::ConstantContext::SCINUM ()
References locationsParser::SCINUM.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp