irafhy: locationsParser::IntervalContext Class Reference
locationsParser::IntervalContext Class Reference
#include <locationsParser.h>
Public Member Functions
IntervalContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTSQUAREBRACKET ()
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTSQUAREBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< antlr4::tree::TerminalNode * > SCINUM ()
antlr4::tree::TerminalNode * SCINUM (size_t i)
std::vector< antlr4::tree::TerminalNode * > KEY_INFINITY ()
antlr4::tree::TerminalNode * KEY_INFINITY (size_t i)
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset251 = nullptr
antlr4::Token * numberToken = nullptr
std::vector< antlr4::Token * > VAL
antlr4::Token * scinumToken = nullptr
antlr4::Token * key_infinityToken = nullptr
antlr4::Token * _tset264 = nullptr
antlr4::Token * _tset284 = nullptr
antlr4::Token * _tset297 = nullptr
Constructor & Destructor Documentation
IntervalContext()
locationsParser::IntervalContext::IntervalContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::IntervalContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * locationsParser::IntervalContext::COMMA ()
References locationsParser::COMMA.
enterRule()
void locationsParser::IntervalContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterInterval().
Referenced by locationsParser::interval().
exitRule()
void locationsParser::IntervalContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitInterval().
Referenced by locationsParser::interval().
getRuleIndex()
size_t locationsParser::IntervalContext::getRuleIndex () const override virtual
References locationsParser::RuleInterval.
KEY_INFINITY() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalContext::KEY_INFINITY ()
References locationsParser::KEY_INFINITY.
KEY_INFINITY() [2/2]
tree::TerminalNode * locationsParser::IntervalContext::KEY_INFINITY (size_t i)
References locationsParser::KEY_INFINITY.
LEFTSQUAREBRACKET()
tree::TerminalNode * locationsParser::IntervalContext::LEFTSQUAREBRACKET ()
References locationsParser::LEFTSQUAREBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalContext::MINUS ()
References locationsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * locationsParser::IntervalContext::MINUS (size_t i)
References locationsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalContext::NUMBER ()
References locationsParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * locationsParser::IntervalContext::NUMBER (size_t i)
References locationsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalContext::PLUS ()
References locationsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * locationsParser::IntervalContext::PLUS (size_t i)
References locationsParser::PLUS.
RIGHTSQUAREBRACKET()
tree::TerminalNode * locationsParser::IntervalContext::RIGHTSQUAREBRACKET ()
References locationsParser::RIGHTSQUAREBRACKET.
SCINUM() [1/2]
std::vector< tree::TerminalNode * > locationsParser::IntervalContext::SCINUM ()
References locationsParser::SCINUM.
SCINUM() [2/2]
tree::TerminalNode * locationsParser::IntervalContext::SCINUM (size_t i)
References locationsParser::SCINUM.
Member Data Documentation
_tset251
antlr4::Token* locationsParser::IntervalContext::_tset251 = nullptr
Referenced by locationsParser::interval().
_tset264
antlr4::Token* locationsParser::IntervalContext::_tset264 = nullptr
Referenced by locationsParser::interval().
_tset284
antlr4::Token* locationsParser::IntervalContext::_tset284 = nullptr
Referenced by locationsParser::interval().
_tset297
antlr4::Token* locationsParser::IntervalContext::_tset297 = nullptr
Referenced by locationsParser::interval().
key_infinityToken
antlr4::Token* locationsParser::IntervalContext::key_infinityToken = nullptr
minusToken
antlr4::Token* locationsParser::IntervalContext::minusToken = nullptr
numberToken
antlr4::Token* locationsParser::IntervalContext::numberToken = nullptr
OP
std::vector<antlr4::Token *> locationsParser::IntervalContext::OP
Referenced by locationsParser::interval().
plusToken
antlr4::Token* locationsParser::IntervalContext::plusToken = nullptr
scinumToken
antlr4::Token* locationsParser::IntervalContext::scinumToken = nullptr
VAL
std::vector<antlr4::Token *> locationsParser::IntervalContext::VAL
Referenced by locationsParser::interval().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp