irafhy: definitionParser::CosExpContext Class Reference
definitionParser::CosExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
CosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CosExpContext()
definitionParser::CosExpContext::CosExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::CosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::CosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterCosExp().
exitRule()
void definitionParser::CosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitCosExp().
expression()
definitionParser::ExpressionContext * definitionParser::CosExpContext::expression ()
KEY_COS_FUNCTION()
tree::TerminalNode * definitionParser::CosExpContext::KEY_COS_FUNCTION ()
References definitionParser::KEY_COS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::CosExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::CosExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp