irafhy: irafhy::UpdateFunction Class Reference
irafhy::UpdateFunction Class Reference
#include <updateFunction.h>
Public Member Functions
UpdateFunction ()=default
constructor
UpdateFunction (const Formula &formula, long index)
constructor with given formula and index of the variable
~UpdateFunction ()=default
destructor
long index () const
get the index of the target variable
Formula formula () const
get the updating expression
void update (const capd::interval &time, const std::vector< capd::interval > &oriConstraints, const std::vector< capd::interval > &oriParams, std::vector< capd::interval > &constraints) const
update the target variable with given values
Private Attributes
long index_ = -1
index of the variable which shall be updated
Formula formula_
formula which used to calculate the value to update the target variable indicated by the index
Constructor & Destructor Documentation
UpdateFunction() [1/2]
irafhy::UpdateFunction::UpdateFunction () default
constructor
UpdateFunction() [2/2]
irafhy::UpdateFunction::UpdateFunction (const Formula & formula, long index)
constructor with given formula and index of the variable
Parameters
formula given formula
index index of the target variable
References formula(), formula_, index(), and index_.
~UpdateFunction()
irafhy::UpdateFunction::~UpdateFunction () default
destructor
Member Function Documentation
formula()
Formula irafhy::UpdateFunction::formula () const
get the updating expression
Returns
expression which used to update the target variable
References formula_.
Referenced by irafhy::operator<<(), and UpdateFunction().
index()
long irafhy::UpdateFunction::index () const
get the index of the target variable
Returns
the index of the target variable
References index_.
Referenced by irafhy::operator<<(), and UpdateFunction().
update()
void irafhy::UpdateFunction::update (const capd::interval & time, const std::vector< capd::interval > & oriConstraints, const std::vector< capd::interval > & oriParams, std::vector< capd::interval > & constraints) const
update the target variable with given values
Parameters
time time value in interval form
oriConstraints original values of the variables
oriParams original parameters' value
constraints updated variables
References formula_, index_, and irafhy::Formula::value().
Member Data Documentation
formula_
Formula irafhy::UpdateFunction::formula_ private
formula which used to calculate the value to update the target variable indicated by the index
Referenced by formula(), update(), and UpdateFunction().
index_
long irafhy::UpdateFunction::index_ = -1 private
index of the variable which shall be updated
Referenced by index(), update(), and UpdateFunction().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/representation/formal/hybridAutomaton/transitions/jump/updateFunction.h
/home/jianqiang/CLionProjects/irafhy/src/representation/formal/hybridAutomaton/transitions/jump/updateFunction.cpp