irafhy: hybridautomatonParser::TanhExpContext Class Reference
hybridautomatonParser::TanhExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
TanhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TANH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanhExpContext()
hybridautomatonParser::TanhExpContext::TanhExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::TanhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::TanhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterTanhExp().
exitRule()
void hybridautomatonParser::TanhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitTanhExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::TanhExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitTanhExp().
KEY_TANH_FUNCTION()
tree::TerminalNode * hybridautomatonParser::TanhExpContext::KEY_TANH_FUNCTION ()
References hybridautomatonParser::KEY_TANH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::TanhExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::TanhExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp