irafhy: settingsParser::ConditionContext Class Reference
settingsParser::ConditionContext Class Reference
#include <settingsParser.h>
Public Member Functions
ConditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_CONDITION ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
IntervalhullContext * intervalhull ()
PolytopeContext * polytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConditionContext()
settingsParser::ConditionContext::ConditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ConditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::ConditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterCondition().
Referenced by settingsParser::condition().
exitRule()
void settingsParser::ConditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitCondition().
Referenced by settingsParser::condition().
getRuleIndex()
size_t settingsParser::ConditionContext::getRuleIndex () const override virtual
References settingsParser::RuleCondition.
intervalhull()
settingsParser::IntervalhullContext * settingsParser::ConditionContext::intervalhull ()
Referenced by settingsParser::condition(), and irafhy::SettingsVisitor::visitCondition().
KEY_CONDITION()
tree::TerminalNode * settingsParser::ConditionContext::KEY_CONDITION ()
References settingsParser::KEY_CONDITION.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::ConditionContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
polytope()
settingsParser::PolytopeContext * settingsParser::ConditionContext::polytope ()
Referenced by settingsParser::condition(), and irafhy::SettingsVisitor::visitCondition().
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::ConditionContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp