irafhy: settingsParser::PrintsettingContext Class Reference
settingsParser::PrintsettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
PrintsettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_PRINT_FLAG ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * KEY_SWITCH_ON ()
antlr4::tree::TerminalNode * KEY_SWITCH_OFF ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * SWITCH = nullptr
Constructor & Destructor Documentation
PrintsettingContext()
settingsParser::PrintsettingContext::PrintsettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::PrintsettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::PrintsettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::PrintsettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterPrintsetting().
Referenced by settingsParser::printsetting().
exitRule()
void settingsParser::PrintsettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitPrintsetting().
Referenced by settingsParser::printsetting().
getRuleIndex()
size_t settingsParser::PrintsettingContext::getRuleIndex () const override virtual
References settingsParser::RulePrintsetting.
KEY_PRINT_FLAG()
tree::TerminalNode * settingsParser::PrintsettingContext::KEY_PRINT_FLAG ()
References settingsParser::KEY_PRINT_FLAG.
KEY_SWITCH_OFF()
tree::TerminalNode * settingsParser::PrintsettingContext::KEY_SWITCH_OFF ()
References settingsParser::KEY_SWITCH_OFF.
KEY_SWITCH_ON()
tree::TerminalNode * settingsParser::PrintsettingContext::KEY_SWITCH_ON ()
References settingsParser::KEY_SWITCH_ON.
Member Data Documentation
SWITCH
antlr4::Token* settingsParser::PrintsettingContext::SWITCH = nullptr
Referenced by settingsParser::printsetting(), and irafhy::SettingsVisitor::visitPrintsetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp