irafhy: locationsParser::ExpBraContext Class Reference
locationsParser::ExpBraContext Class Reference
#include <locationsParser.h>
Public Member Functions
ExpBraContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpBraContext()
locationsParser::ExpBraContext::ExpBraContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ExpBraContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ExpBraContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterExpBra().
exitRule()
void locationsParser::ExpBraContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitExpBra().
expression()
locationsParser::ExpressionContext * locationsParser::ExpBraContext::expression ()
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::ExpBraContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::ExpBraContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp