irafhy: definitionParser::ConditionContext Class Reference
definitionParser::ConditionContext Class Reference
#include <definitionParser.h>
Public Member Functions
ConditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_CONDITION ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
IntervalhullContext * intervalhull ()
PolytopeContext * polytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConditionContext()
definitionParser::ConditionContext::ConditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ConditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ConditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterCondition().
Referenced by definitionParser::condition().
exitRule()
void definitionParser::ConditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitCondition().
Referenced by definitionParser::condition().
getRuleIndex()
size_t definitionParser::ConditionContext::getRuleIndex () const override virtual
References definitionParser::RuleCondition.
intervalhull()
definitionParser::IntervalhullContext * definitionParser::ConditionContext::intervalhull ()
Referenced by definitionParser::condition().
KEY_CONDITION()
tree::TerminalNode * definitionParser::ConditionContext::KEY_CONDITION ()
References definitionParser::KEY_CONDITION.
LEFTCURLYBRACKET()
tree::TerminalNode * definitionParser::ConditionContext::LEFTCURLYBRACKET ()
References definitionParser::LEFTCURLYBRACKET.
polytope()
definitionParser::PolytopeContext * definitionParser::ConditionContext::polytope ()
Referenced by definitionParser::condition().
RIGHTCURLYBRACKET()
tree::TerminalNode * definitionParser::ConditionContext::RIGHTCURLYBRACKET ()
References definitionParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp