irafhy: transitionsParser::SystemContext Class Reference
transitionsParser::SystemContext Class Reference
#include <transitionsParser.h>
Public Member Functions
SystemContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FormulaContext * > formula ()
FormulaContext * formula (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SystemContext()
transitionsParser::SystemContext::SystemContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::SystemContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::SystemContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterSystem().
Referenced by transitionsParser::system().
exitRule()
void transitionsParser::SystemContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitSystem().
Referenced by transitionsParser::system().
formula() [1/2]
std::vector< transitionsParser::FormulaContext * > transitionsParser::SystemContext::formula ()
Referenced by transitionsParser::system().
formula() [2/2]
transitionsParser::FormulaContext * transitionsParser::SystemContext::formula (size_t i)
getRuleIndex()
size_t transitionsParser::SystemContext::getRuleIndex () const override virtual
References transitionsParser::RuleSystem.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp