irafhy: hybridautomatonParser::ExpMulDivContext Class Reference
hybridautomatonParser::ExpMulDivContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ExpMulDivContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * MULTIPLY ()
antlr4::tree::TerminalNode * DIVIDE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpMulDivContext()
hybridautomatonParser::ExpMulDivContext::ExpMulDivContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ExpMulDivContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIVIDE()
tree::TerminalNode * hybridautomatonParser::ExpMulDivContext::DIVIDE ()
References hybridautomatonParser::DIVIDE.
enterRule()
void hybridautomatonParser::ExpMulDivContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterExpMulDiv().
exitRule()
void hybridautomatonParser::ExpMulDivContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitExpMulDiv().
expression() [1/2]
std::vector< hybridautomatonParser::ExpressionContext * > hybridautomatonParser::ExpMulDivContext::expression ()
Referenced by irafhy::ItemVisitor::visitExpMulDiv().
expression() [2/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::ExpMulDivContext::expression (size_t i)
MULTIPLY()
tree::TerminalNode * hybridautomatonParser::ExpMulDivContext::MULTIPLY ()
References hybridautomatonParser::MULTIPLY.
Member Data Documentation
OP
antlr4::Token* hybridautomatonParser::ExpMulDivContext::OP = nullptr
Referenced by irafhy::ItemVisitor::visitExpMulDiv().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp