irafhy: settingsParser::VpolytopeContext Class Reference
settingsParser::VpolytopeContext Class Reference
#include <settingsParser.h>
Public Member Functions
VpolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
VpolytopeContext()
settingsParser::VpolytopeContext::VpolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::VpolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > settingsParser::VpolytopeContext::COMMA ()
References settingsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * settingsParser::VpolytopeContext::COMMA (size_t i)
References settingsParser::COMMA.
enterRule()
void settingsParser::VpolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterVpolytope().
Referenced by settingsParser::vpolytope().
exitRule()
void settingsParser::VpolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitVpolytope().
Referenced by settingsParser::vpolytope().
getRuleIndex()
size_t settingsParser::VpolytopeContext::getRuleIndex () const override virtual
References settingsParser::RuleVpolytope.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::VpolytopeContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::VpolytopeContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< settingsParser::VectorContext * > settingsParser::VpolytopeContext::vector ()
Referenced by irafhy::SettingsVisitor::visitVpolytope(), and settingsParser::vpolytope().
vector() [2/2]
settingsParser::VectorContext * settingsParser::VpolytopeContext::vector (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp