irafhy: definitionParser::PowExpContext Class Reference
definitionParser::PowExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
PowExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_POWER_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PowExpContext()
definitionParser::PowExpContext::PowExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::PowExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * definitionParser::PowExpContext::COMMA ()
References definitionParser::COMMA.
enterRule()
void definitionParser::PowExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterPowExp().
exitRule()
void definitionParser::PowExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitPowExp().
expression() [1/2]
std::vector< definitionParser::ExpressionContext * > definitionParser::PowExpContext::expression ()
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::PowExpContext::expression (size_t i)
KEY_POWER_FUNCTION()
tree::TerminalNode * definitionParser::PowExpContext::KEY_POWER_FUNCTION ()
References definitionParser::KEY_POWER_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::PowExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::PowExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp