irafhy: definitionParser::NegExpContext Class Reference
definitionParser::NegExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
NegExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * MINUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NegExpContext()
definitionParser::NegExpContext::NegExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::NegExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::NegExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterNegExp().
exitRule()
void definitionParser::NegExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitNegExp().
expression()
definitionParser::ExpressionContext * definitionParser::NegExpContext::expression ()
MINUS()
tree::TerminalNode * definitionParser::NegExpContext::MINUS ()
References definitionParser::MINUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp