irafhy: settingsParser::CoshExpContext Class Reference
settingsParser::CoshExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
CoshExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COSH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CoshExpContext()
settingsParser::CoshExpContext::CoshExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::CoshExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::CoshExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterCoshExp().
exitRule()
void settingsParser::CoshExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitCoshExp().
expression()
settingsParser::ExpressionContext * settingsParser::CoshExpContext::expression ()
KEY_COSH_FUNCTION()
tree::TerminalNode * settingsParser::CoshExpContext::KEY_COSH_FUNCTION ()
References settingsParser::KEY_COSH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::CoshExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::CoshExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp