irafhy: settingsParser::ExpExpContext Class Reference
settingsParser::ExpExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
ExpExpContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EXPONENT ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpExpContext()
settingsParser::ExpExpContext::ExpExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ExpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::ExpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterExpExp().
exitRule()
void settingsParser::ExpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitExpExp().
EXPONENT()
tree::TerminalNode * settingsParser::ExpExpContext::EXPONENT ()
References settingsParser::EXPONENT.
expression() [1/2]
std::vector< settingsParser::ExpressionContext * > settingsParser::ExpExpContext::expression ()
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::ExpExpContext::expression (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp