irafhy: locationsParser::NexpExpContext Class Reference
locationsParser::NexpExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
NexpExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_NATURAL_EXP_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NexpExpContext()
locationsParser::NexpExpContext::NexpExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::NexpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::NexpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterNexpExp().
exitRule()
void locationsParser::NexpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitNexpExp().
expression()
locationsParser::ExpressionContext * locationsParser::NexpExpContext::expression ()
KEY_NATURAL_EXP_FUNCTION()
tree::TerminalNode * locationsParser::NexpExpContext::KEY_NATURAL_EXP_FUNCTION ()
References locationsParser::KEY_NATURAL_EXP_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::NexpExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::NexpExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp