irafhy: hybridautomatonParser::ExpAddSubContext Class Reference
hybridautomatonParser::ExpAddSubContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ExpAddSubContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * PLUS ()
antlr4::tree::TerminalNode * MINUS ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpAddSubContext()
hybridautomatonParser::ExpAddSubContext::ExpAddSubContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ExpAddSubContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ExpAddSubContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterExpAddSub().
exitRule()
void hybridautomatonParser::ExpAddSubContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitExpAddSub().
expression() [1/2]
std::vector< hybridautomatonParser::ExpressionContext * > hybridautomatonParser::ExpAddSubContext::expression ()
Referenced by irafhy::ItemVisitor::visitExpAddSub().
expression() [2/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::ExpAddSubContext::expression (size_t i)
MINUS()
tree::TerminalNode * hybridautomatonParser::ExpAddSubContext::MINUS ()
References hybridautomatonParser::MINUS.
PLUS()
tree::TerminalNode * hybridautomatonParser::ExpAddSubContext::PLUS ()
References hybridautomatonParser::PLUS.
Member Data Documentation
OP
antlr4::Token* hybridautomatonParser::ExpAddSubContext::OP = nullptr
Referenced by irafhy::ItemVisitor::visitExpAddSub().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp