irafhy: hybridautomatonParser::UpdatefunctionContext Class Reference
hybridautomatonParser::UpdatefunctionContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
UpdatefunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * DEFINE ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
UpdatefunctionContext()
hybridautomatonParser::UpdatefunctionContext::UpdatefunctionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::UpdatefunctionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * hybridautomatonParser::UpdatefunctionContext::DEFINE ()
References hybridautomatonParser::DEFINE.
enterRule()
void hybridautomatonParser::UpdatefunctionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterUpdatefunction().
Referenced by hybridautomatonParser::updatefunction().
exitRule()
void hybridautomatonParser::UpdatefunctionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitUpdatefunction().
Referenced by hybridautomatonParser::updatefunction().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::UpdatefunctionContext::expression ()
Referenced by hybridautomatonParser::updatefunction().
getRuleIndex()
size_t hybridautomatonParser::UpdatefunctionContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleUpdatefunction.
VARIABLE()
tree::TerminalNode * hybridautomatonParser::UpdatefunctionContext::VARIABLE ()
References hybridautomatonParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp