irafhy: hybridautomatonParser::GuardconditionContext Class Reference
hybridautomatonParser::GuardconditionContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
GuardconditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_GUARD_CONDITIONS ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
ConditionContext * condition ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
GuardconditionContext()
hybridautomatonParser::GuardconditionContext::GuardconditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::GuardconditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
condition()
hybridautomatonParser::ConditionContext * hybridautomatonParser::GuardconditionContext::condition ()
Referenced by hybridautomatonParser::guardcondition().
enterRule()
void hybridautomatonParser::GuardconditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterGuardcondition().
Referenced by hybridautomatonParser::guardcondition().
exitRule()
void hybridautomatonParser::GuardconditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitGuardcondition().
Referenced by hybridautomatonParser::guardcondition().
getRuleIndex()
size_t hybridautomatonParser::GuardconditionContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleGuardcondition.
KEY_GUARD_CONDITIONS()
tree::TerminalNode * hybridautomatonParser::GuardconditionContext::KEY_GUARD_CONDITIONS ()
References hybridautomatonParser::KEY_GUARD_CONDITIONS.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::GuardconditionContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::GuardconditionContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp