irafhy: locationsParser::VectorContext Class Reference
locationsParser::VectorContext Class Reference
#include <locationsParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset115 = nullptr
antlr4::Token * _tset135 = nullptr
Constructor & Destructor Documentation
VectorContext()
locationsParser::VectorContext::VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::VectorContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > locationsParser::VectorContext::COMMA ()
References locationsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * locationsParser::VectorContext::COMMA (size_t i)
References locationsParser::COMMA.
enterRule()
void locationsParser::VectorContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterVector().
Referenced by locationsParser::vector().
exitRule()
void locationsParser::VectorContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitVector().
Referenced by locationsParser::vector().
getRuleIndex()
size_t locationsParser::VectorContext::getRuleIndex () const override virtual
References locationsParser::RuleVector.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::VectorContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > locationsParser::VectorContext::MINUS ()
References locationsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * locationsParser::VectorContext::MINUS (size_t i)
References locationsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > locationsParser::VectorContext::NUMBER ()
References locationsParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * locationsParser::VectorContext::NUMBER (size_t i)
References locationsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > locationsParser::VectorContext::PLUS ()
References locationsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * locationsParser::VectorContext::PLUS (size_t i)
References locationsParser::PLUS.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::VectorContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
Member Data Documentation
_tset115
antlr4::Token* locationsParser::VectorContext::_tset115 = nullptr
Referenced by locationsParser::vector().
_tset135
antlr4::Token* locationsParser::VectorContext::_tset135 = nullptr
Referenced by locationsParser::vector().
minusToken
antlr4::Token* locationsParser::VectorContext::minusToken = nullptr
OP
std::vector<antlr4::Token *> locationsParser::VectorContext::OP
Referenced by locationsParser::vector().
plusToken
antlr4::Token* locationsParser::VectorContext::plusToken = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp