irafhy: transitionsParser Class Reference
transitionsParser Class Reference
#include <transitionsParser.h>
Classes
class AcosExpContext
class AcoshExpContext
class AcotExpContext
class AcothExpContext
class AsinExpContext
class AsinhExpContext
class AtanExpContext
class AtanhExpContext
class ConditionContext
class ConstantContext
class ConstraintContext
class ConstraintsContext
class CosExpContext
class CoshExpContext
class CotExpContext
class CothExpContext
class DirectionContext
class ExpAddSubContext
class ExpBraContext
class ExpExpContext
class ExpMulDivContext
class ExpressionContext
class FormulaContext
class GuardconditionContext
class HpolytopeContext
struct Initializer
class IntervalContext
class IntervalhullContext
class JumpContext
class LnExpContext
class LogExpContext
class MatrixContext
class NegExpContext
class NexpExpContext
class PolytopeContext
class PosExpContext
class PowExpContext
class ResetmapContext
class SinExpContext
class SinhExpContext
class SqrExpContext
class SqrtExpContext
class SystemContext
class TanExpContext
class TanhExpContext
class TransitionsContext
class UpdatefunctionContext
class VariableContext
class VectorContext
class VpolytopeContext
Public Types
enum {
KEY_LOCATIONS = 1, KEY_MODEL = 2, KEY_FLOWS = 3, KEY_INVARIANT_CONDITIONS = 4,
KEY_SETTINGS = 5, KEY_ANALYSIS = 6, KEY_ANALYSIS_FORWARD = 7, KEY_ANALYSIS_BACKWARD = 8,
KEY_TIME_HORIZON = 9, KEY_STEP = 10, KEY_GEOMETRY = 11, KEY_PLOT_FLAG = 12,
KEY_PRINT_FLAG = 13, KEY_MAX_JUMP = 14, KEY_START_MODEL_ID = 15, KEY_INITIAL_CONDITION = 16,
KEY_TRANSITIONS = 17, KEY_URGENT = 18, KEY_JUMP = 19, KEY_DIRECTION = 20,
KEY_GUARD_CONDITIONS = 21, KEY_RESET_MAP = 22, KEY_INTERVAL_HULL = 23, KEY_POLYTOPE = 24,
KEY_CONDITION = 25, KEY_MATRIX = 26, KEY_ROW_MAJOR_ORDER = 27, KEY_COL_MAJOR_ORDER = 28,
KEY_SIN_FUNCTION = 29, KEY_ARCSIN_FUNCTION = 30, KEY_COS_FUNCTION = 31, KEY_ARCCOS_FUNCTION = 32,
KEY_TAN_FUNCTION = 33, KEY_ARCTAN_FUNCTION = 34, KEY_COT_FUNCTION = 35, KEY_ARCCOT_FUNCTION = 36,
KEY_LN_FUNCTION = 37, KEY_LOG_FUNCTION = 38, KEY_NATURAL_EXP_FUNCTION = 39, KEY_SINH_FUNCTION = 40,
KEY_ARCSINH_FUNCTION = 41, KEY_COSH_FUNCTION = 42, KEY_ARCCOSH_FUNCTION = 43, KEY_TANH_FUNCTION = 44,
KEY_ARCTANH_FUNCTION = 45, KEY_COTH_FUNCTION = 46, KEY_ARCCOTH_FUNCTION = 47, KEY_SQR_FUNCTION = 48,
KEY_SQRT_FUNCTION = 49, KEY_ABS_FUNCTION = 50, KEY_POWER_FUNCTION = 51, KEY_NAME = 52,
KEY_SWITCH_ON = 53, KEY_SWITCH_OFF = 54, KEY_BOOL_TRUE = 55, KEY_BOOL_FALSE = 56,
KEY_INFINITY = 57, SCINUM = 58, NUMBER = 59, VARIABLE = 60,
LEFTCURLYBRACKET = 61, RIGHTCURLYBRACKET = 62, LEFTROUNDBRACKET = 63, RIGHTROUNDBRACKET = 64,
LEFTSQUAREBRACKET = 65, RIGHTSQUAREBRACKET = 66, COMMA = 67, EQUAL = 68,
UNEQUAL = 69, GEQ = 70, LEQ = 71, LSS = 72,
GTR = 73, DEFINE = 74, FROMTO = 75, ASSIGN = 76,
PLUS = 77, MINUS = 78, MULTIPLY = 79, DIVIDE = 80,
EXPONENT = 81, DERIVATIVE = 82, COMMENT = 83, WS = 84
}
enum {
RuleDirection = 0, RuleGuardcondition = 1, RuleUpdatefunction = 2, RuleResetmap = 3,
RuleJump = 4, RuleTransitions = 5, RuleCondition = 6, RulePolytope = 7,
RuleHpolytope = 8, RuleVpolytope = 9, RuleMatrix = 10, RuleVector = 11,
RuleIntervalhull = 12, RuleConstraints = 13, RuleConstraint = 14, RuleSystem = 15,
RuleFormula = 16, RuleInterval = 17, RuleExpression = 18
}
Public Member Functions
transitionsParser (antlr4::TokenStream *input)
~transitionsParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
DirectionContext * direction ()
GuardconditionContext * guardcondition ()
UpdatefunctionContext * updatefunction ()
ResetmapContext * resetmap ()
JumpContext * jump ()
TransitionsContext * transitions ()
ConditionContext * condition ()
PolytopeContext * polytope ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
MatrixContext * matrix ()
VectorContext * vector ()
IntervalhullContext * intervalhull ()
ConstraintsContext * constraints ()
ConstraintContext * constraint ()
SystemContext * system ()
FormulaContext * formula ()
IntervalContext * interval ()
ExpressionContext * expression ()
ExpressionContext * expression (int precedence)
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool expressionSempred (ExpressionContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
KEY_LOCATIONS
KEY_MODEL
KEY_FLOWS
KEY_INVARIANT_CONDITIONS
KEY_SETTINGS
KEY_ANALYSIS
KEY_ANALYSIS_FORWARD
KEY_ANALYSIS_BACKWARD
KEY_TIME_HORIZON
KEY_STEP
KEY_GEOMETRY
KEY_PLOT_FLAG
KEY_PRINT_FLAG
KEY_MAX_JUMP
KEY_START_MODEL_ID
KEY_INITIAL_CONDITION
KEY_TRANSITIONS
KEY_URGENT
KEY_JUMP
KEY_DIRECTION
KEY_GUARD_CONDITIONS
KEY_RESET_MAP
KEY_INTERVAL_HULL
KEY_POLYTOPE
KEY_CONDITION
KEY_MATRIX
KEY_ROW_MAJOR_ORDER
KEY_COL_MAJOR_ORDER
KEY_SIN_FUNCTION
KEY_ARCSIN_FUNCTION
KEY_COS_FUNCTION
KEY_ARCCOS_FUNCTION
KEY_TAN_FUNCTION
KEY_ARCTAN_FUNCTION
KEY_COT_FUNCTION
KEY_ARCCOT_FUNCTION
KEY_LN_FUNCTION
KEY_LOG_FUNCTION
KEY_NATURAL_EXP_FUNCTION
KEY_SINH_FUNCTION
KEY_ARCSINH_FUNCTION
KEY_COSH_FUNCTION
KEY_ARCCOSH_FUNCTION
KEY_TANH_FUNCTION
KEY_ARCTANH_FUNCTION
KEY_COTH_FUNCTION
KEY_ARCCOTH_FUNCTION
KEY_SQR_FUNCTION
KEY_SQRT_FUNCTION
KEY_ABS_FUNCTION
KEY_POWER_FUNCTION
KEY_NAME
KEY_SWITCH_ON
KEY_SWITCH_OFF
KEY_BOOL_TRUE
KEY_BOOL_FALSE
KEY_INFINITY
SCINUM
NUMBER
VARIABLE
LEFTCURLYBRACKET
RIGHTCURLYBRACKET
LEFTROUNDBRACKET
RIGHTROUNDBRACKET
LEFTSQUAREBRACKET
RIGHTSQUAREBRACKET
COMMA
EQUAL
UNEQUAL
GEQ
LEQ
LSS
GTR
DEFINE
FROMTO
ASSIGN
PLUS
MINUS
MULTIPLY
DIVIDE
EXPONENT
DERIVATIVE
COMMENT
WS
anonymous enum
anonymous enum
Enumerator
RuleDirection
RuleGuardcondition
RuleUpdatefunction
RuleResetmap
RuleJump
RuleTransitions
RuleCondition
RulePolytope
RuleHpolytope
RuleVpolytope
RuleMatrix
RuleVector
RuleIntervalhull
RuleConstraints
RuleConstraint
RuleSystem
RuleFormula
RuleInterval
RuleExpression
Constructor & Destructor Documentation
transitionsParser()
transitionsParser::transitionsParser (antlr4::TokenStream * input)
References _atn, _decisionToDFA, and _sharedContextCache.
~transitionsParser()
transitionsParser::~transitionsParser ()
Member Function Documentation
condition()
transitionsParser::ConditionContext * transitionsParser::condition ()
References transitionsParser::ConditionContext::enterRule(), transitionsParser::ConditionContext::exitRule(), transitionsParser::ConditionContext::intervalhull(), KEY_CONDITION, KEY_INTERVAL_HULL, KEY_POLYTOPE, LEFTCURLYBRACKET, transitionsParser::ConditionContext::polytope(), RIGHTCURLYBRACKET, and RuleCondition.
constraint()
transitionsParser::ConstraintContext * transitionsParser::constraint ()
References transitionsParser::ConstraintContext::enterRule(), EQUAL, transitionsParser::ConstraintContext::exitRule(), transitionsParser::ConstraintContext::expression(), GEQ, GTR, LEQ, LSS, transitionsParser::ConstraintContext::RELATION, RuleConstraint, and UNEQUAL.
constraints()
transitionsParser::ConstraintsContext * transitionsParser::constraints ()
References transitionsParser::ConstraintsContext::constraint(), transitionsParser::ConstraintsContext::enterRule(), transitionsParser::ConstraintsContext::exitRule(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, NUMBER, PLUS, RuleConstraints, SCINUM, and VARIABLE.
direction()
transitionsParser::DirectionContext * transitionsParser::direction ()
References transitionsParser::DirectionContext::enterRule(), transitionsParser::DirectionContext::exitRule(), FROMTO, KEY_DIRECTION, RuleDirection, and VARIABLE.
expression() [1/2]
transitionsParser::ExpressionContext * transitionsParser::expression ()
Referenced by expression().
expression() [2/2]
transitionsParser::ExpressionContext * transitionsParser::expression (int precedence)
References COMMA, DIVIDE, EXPONENT, expression(), KEY_ARCCOS_FUNCTION, KEY_ARCCOSH_FUNCTION, KEY_ARCCOT_FUNCTION, KEY_ARCCOTH_FUNCTION, KEY_ARCSIN_FUNCTION, KEY_ARCSINH_FUNCTION, KEY_ARCTAN_FUNCTION, KEY_ARCTANH_FUNCTION, KEY_COS_FUNCTION, KEY_COSH_FUNCTION, KEY_COT_FUNCTION, KEY_COTH_FUNCTION, KEY_LN_FUNCTION, KEY_LOG_FUNCTION, KEY_NATURAL_EXP_FUNCTION, KEY_POWER_FUNCTION, KEY_SIN_FUNCTION, KEY_SINH_FUNCTION, KEY_SQR_FUNCTION, KEY_SQRT_FUNCTION, KEY_TAN_FUNCTION, KEY_TANH_FUNCTION, LEFTROUNDBRACKET, MINUS, MULTIPLY, NUMBER, PLUS, RIGHTROUNDBRACKET, RuleExpression, SCINUM, and VARIABLE.
expressionSempred()
bool transitionsParser::expressionSempred (ExpressionContext * _localctx, size_t predicateIndex)
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, and _vocabulary.
Referenced by sempred().
formula()
transitionsParser::FormulaContext * transitionsParser::formula ()
References ASSIGN, DERIVATIVE, transitionsParser::FormulaContext::enterRule(), transitionsParser::FormulaContext::exitRule(), transitionsParser::FormulaContext::expression(), transitionsParser::FormulaContext::interval(), LEFTSQUAREBRACKET, RuleFormula, and VARIABLE.
getATN()
virtual const antlr4::atn::ATN& transitionsParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string transitionsParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & transitionsParser::getRuleNames () const override virtual
References _ruleNames.
Referenced by getTokenNames().
getTokenNames()
virtual const std::vector<std::string>& transitionsParser::getTokenNames () const inline override virtual
References _tokenNames, getRuleNames(), and getVocabulary().
getVocabulary()
dfa::Vocabulary & transitionsParser::getVocabulary () const override virtual
References _vocabulary.
Referenced by getTokenNames().
guardcondition()
transitionsParser::GuardconditionContext * transitionsParser::guardcondition ()
References transitionsParser::GuardconditionContext::condition(), transitionsParser::GuardconditionContext::enterRule(), transitionsParser::GuardconditionContext::exitRule(), KEY_CONDITION, KEY_GUARD_CONDITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleGuardcondition.
hpolytope()
transitionsParser::HpolytopeContext * transitionsParser::hpolytope ()
References transitionsParser::HpolytopeContext::enterRule(), transitionsParser::HpolytopeContext::exitRule(), LEFTCURLYBRACKET, transitionsParser::HpolytopeContext::matrix(), RIGHTCURLYBRACKET, RuleHpolytope, and transitionsParser::HpolytopeContext::vector().
interval()
transitionsParser::IntervalContext * transitionsParser::interval ()
References transitionsParser::IntervalContext::_tset251, transitionsParser::IntervalContext::_tset264, transitionsParser::IntervalContext::_tset284, transitionsParser::IntervalContext::_tset297, COMMA, transitionsParser::IntervalContext::enterRule(), transitionsParser::IntervalContext::exitRule(), KEY_INFINITY, LEFTSQUAREBRACKET, MINUS, NUMBER, transitionsParser::IntervalContext::OP, PLUS, RIGHTSQUAREBRACKET, RuleInterval, SCINUM, and transitionsParser::IntervalContext::VAL.
intervalhull()
transitionsParser::IntervalhullContext * transitionsParser::intervalhull ()
References COMMA, transitionsParser::IntervalhullContext::enterRule(), transitionsParser::IntervalhullContext::exitRule(), transitionsParser::IntervalhullContext::interval(), KEY_INTERVAL_HULL, LEFTCURLYBRACKET, LEFTSQUAREBRACKET, RIGHTCURLYBRACKET, and RuleIntervalhull.
jump()
transitionsParser::JumpContext * transitionsParser::jump ()
References transitionsParser::JumpContext::direction(), transitionsParser::JumpContext::enterRule(), transitionsParser::JumpContext::exitRule(), transitionsParser::JumpContext::guardcondition(), KEY_JUMP, LEFTCURLYBRACKET, transitionsParser::JumpContext::resetmap(), RIGHTCURLYBRACKET, and RuleJump.
matrix()
transitionsParser::MatrixContext * transitionsParser::matrix ()
References COMMA, transitionsParser::MatrixContext::enterRule(), transitionsParser::MatrixContext::exitRule(), KEY_COL_MAJOR_ORDER, KEY_MATRIX, KEY_ROW_MAJOR_ORDER, LEFTCURLYBRACKET, LEFTROUNDBRACKET, transitionsParser::MatrixContext::MAJOR_ORDER, RIGHTCURLYBRACKET, RuleMatrix, and transitionsParser::MatrixContext::vector().
polytope()
transitionsParser::PolytopeContext * transitionsParser::polytope ()
References transitionsParser::PolytopeContext::enterRule(), transitionsParser::PolytopeContext::exitRule(), transitionsParser::PolytopeContext::hpolytope(), KEY_POLYTOPE, RulePolytope, and transitionsParser::PolytopeContext::vpolytope().
resetmap()
transitionsParser::ResetmapContext * transitionsParser::resetmap ()
References transitionsParser::ResetmapContext::enterRule(), transitionsParser::ResetmapContext::exitRule(), KEY_RESET_MAP, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, RuleResetmap, transitionsParser::ResetmapContext::updatefunction(), and VARIABLE.
sempred()
bool transitionsParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References expressionSempred().
system()
transitionsParser::SystemContext * transitionsParser::system ()
References transitionsParser::SystemContext::enterRule(), transitionsParser::SystemContext::exitRule(), transitionsParser::SystemContext::formula(), RuleSystem, and VARIABLE.
transitions()
transitionsParser::TransitionsContext * transitionsParser::transitions ()
References transitionsParser::TransitionsContext::enterRule(), transitionsParser::TransitionsContext::exitRule(), transitionsParser::TransitionsContext::jump(), KEY_JUMP, KEY_TRANSITIONS, LEFTCURLYBRACKET, RIGHTCURLYBRACKET, and RuleTransitions.
updatefunction()
transitionsParser::UpdatefunctionContext * transitionsParser::updatefunction ()
References DEFINE, transitionsParser::UpdatefunctionContext::enterRule(), transitionsParser::UpdatefunctionContext::exitRule(), transitionsParser::UpdatefunctionContext::expression(), RuleUpdatefunction, and VARIABLE.
vector()
transitionsParser::VectorContext * transitionsParser::vector ()
References transitionsParser::VectorContext::_tset115, transitionsParser::VectorContext::_tset135, COMMA, transitionsParser::VectorContext::enterRule(), transitionsParser::VectorContext::exitRule(), LEFTROUNDBRACKET, MINUS, NUMBER, transitionsParser::VectorContext::OP, PLUS, RIGHTROUNDBRACKET, and RuleVector.
vpolytope()
transitionsParser::VpolytopeContext * transitionsParser::vpolytope ()
References COMMA, transitionsParser::VpolytopeContext::enterRule(), transitionsParser::VpolytopeContext::exitRule(), LEFTCURLYBRACKET, LEFTROUNDBRACKET, RIGHTCURLYBRACKET, RuleVpolytope, and transitionsParser::VpolytopeContext::vector().
Member Data Documentation
_atn
atn::ATN transitionsParser::_atn static private
Referenced by expressionSempred(), getATN(), transitionsParser::Initializer::Initializer(), and transitionsParser().
_decisionToDFA
std::vector< dfa::DFA > transitionsParser::_decisionToDFA static private
Referenced by expressionSempred(), transitionsParser::Initializer::Initializer(), and transitionsParser().
_init
transitionsParser::Initializer transitionsParser::_init static private
Referenced by transitionsParser::Initializer::Initializer().
_literalNames
std::vector< std::string > transitionsParser::_literalNames static private
Initial value:
= {
  "", "'LOCATIONS'", "'MODEL'", "'FLOWS'", "'INVARIANT_CONDITIONS'", "'SETTINGS'",
  "'ANALYSIS'", "'FORWARD'", "'BACKWARD'", "'TIME_HORIZON'", "'STEP'", "'GEOMETRY'",
  "'PLOT'", "'PRINT'", "'MAX_JUMP'", "'START_MODEL_ID'", "'INITIAL_CONDITION'",
  "'TRANSITIONS'", "'URGENT'", "'JUMP'", "'DIRECTION'", "'GUARD_CONDITIONS'",
  "'RESET_MAP'", "'INTERVAL_HULL'", "'POLYTOPE'", "'CONDITION'", "'MATRIX'",
  "'ROW_MAJOR'", "'COL_MAJOR'", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "'NAME'", "'ON'",
  "'OFF'", "'TRUE'", "'FALSE'", "", "", "", "", "'{'", "'}'", "'('", "')'",
  "'['", "']'", "','", "'=='", "'!='", "'>='", "'<='", "'<'", "'>'", "':='",
  "", "'='", "'+'", "'-'", "'*'", "'/'", "'^'", "'''"
}
Referenced by expressionSempred().
_ruleNames
std::vector< std::string > transitionsParser::_ruleNames static private
Initial value:
= {
  "direction", "guardcondition", "updatefunction", "resetmap", "jump", "transitions",
  "condition", "polytope", "hpolytope", "vpolytope", "matrix", "vector",
  "intervalhull", "constraints", "constraint", "system", "formula", "interval",
  "expression"
}
Referenced by expressionSempred(), and getRuleNames().
_serializedATN
std::vector< uint16_t > transitionsParser::_serializedATN static private
Referenced by expressionSempred(), and transitionsParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache transitionsParser::_sharedContextCache static private
Referenced by expressionSempred(), and transitionsParser().
_symbolicNames
std::vector< std::string > transitionsParser::_symbolicNames static private
Initial value:
= {
  "", "KEY_LOCATIONS", "KEY_MODEL", "KEY_FLOWS", "KEY_INVARIANT_CONDITIONS",
  "KEY_SETTINGS", "KEY_ANALYSIS", "KEY_ANALYSIS_FORWARD", "KEY_ANALYSIS_BACKWARD",
  "KEY_TIME_HORIZON", "KEY_STEP", "KEY_GEOMETRY", "KEY_PLOT_FLAG", "KEY_PRINT_FLAG",
  "KEY_MAX_JUMP", "KEY_START_MODEL_ID", "KEY_INITIAL_CONDITION", "KEY_TRANSITIONS",
  "KEY_URGENT", "KEY_JUMP", "KEY_DIRECTION", "KEY_GUARD_CONDITIONS", "KEY_RESET_MAP",
  "KEY_INTERVAL_HULL", "KEY_POLYTOPE", "KEY_CONDITION", "KEY_MATRIX", "KEY_ROW_MAJOR_ORDER",
  "KEY_COL_MAJOR_ORDER", "KEY_SIN_FUNCTION", "KEY_ARCSIN_FUNCTION", "KEY_COS_FUNCTION",
  "KEY_ARCCOS_FUNCTION", "KEY_TAN_FUNCTION", "KEY_ARCTAN_FUNCTION", "KEY_COT_FUNCTION",
  "KEY_ARCCOT_FUNCTION", "KEY_LN_FUNCTION", "KEY_LOG_FUNCTION", "KEY_NATURAL_EXP_FUNCTION",
  "KEY_SINH_FUNCTION", "KEY_ARCSINH_FUNCTION", "KEY_COSH_FUNCTION", "KEY_ARCCOSH_FUNCTION",
  "KEY_TANH_FUNCTION", "KEY_ARCTANH_FUNCTION", "KEY_COTH_FUNCTION", "KEY_ARCCOTH_FUNCTION",
  "KEY_SQR_FUNCTION", "KEY_SQRT_FUNCTION", "KEY_ABS_FUNCTION", "KEY_POWER_FUNCTION",
  "KEY_NAME", "KEY_SWITCH_ON", "KEY_SWITCH_OFF", "KEY_BOOL_TRUE", "KEY_BOOL_FALSE",
  "KEY_INFINITY", "SCINUM", "NUMBER", "VARIABLE", "LEFTCURLYBRACKET", "RIGHTCURLYBRACKET",
  "LEFTROUNDBRACKET", "RIGHTROUNDBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET",
  "COMMA", "EQUAL", "UNEQUAL", "GEQ", "LEQ", "LSS", "GTR", "DEFINE", "FROMTO",
  "ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", "DERIVATIVE",
  "COMMENT", "WS"
}
Referenced by expressionSempred(), and transitionsParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > transitionsParser::_tokenNames static private
Referenced by expressionSempred(), getTokenNames(), and transitionsParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary transitionsParser::_vocabulary static private
Referenced by expressionSempred(), getVocabulary(), and transitionsParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp