irafhy: hybridautomatonParser::CoshExpContext Class Reference
hybridautomatonParser::CoshExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
CoshExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COSH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CoshExpContext()
hybridautomatonParser::CoshExpContext::CoshExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::CoshExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::CoshExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterCoshExp().
exitRule()
void hybridautomatonParser::CoshExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitCoshExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::CoshExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitCoshExp().
KEY_COSH_FUNCTION()
tree::TerminalNode * hybridautomatonParser::CoshExpContext::KEY_COSH_FUNCTION ()
References hybridautomatonParser::KEY_COSH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CoshExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CoshExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp