irafhy: hybridautomatonParser::DirectionContext Class Reference
hybridautomatonParser::DirectionContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
DirectionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_DIRECTION ()
std::vector< antlr4::tree::TerminalNode * > VARIABLE ()
antlr4::tree::TerminalNode * VARIABLE (size_t i)
antlr4::tree::TerminalNode * FROMTO ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
DirectionContext()
hybridautomatonParser::DirectionContext::DirectionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::DirectionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::DirectionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterDirection().
Referenced by hybridautomatonParser::direction().
exitRule()
void hybridautomatonParser::DirectionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitDirection().
Referenced by hybridautomatonParser::direction().
FROMTO()
tree::TerminalNode * hybridautomatonParser::DirectionContext::FROMTO ()
References hybridautomatonParser::FROMTO.
getRuleIndex()
size_t hybridautomatonParser::DirectionContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleDirection.
KEY_DIRECTION()
tree::TerminalNode * hybridautomatonParser::DirectionContext::KEY_DIRECTION ()
References hybridautomatonParser::KEY_DIRECTION.
VARIABLE() [1/2]
std::vector< tree::TerminalNode * > hybridautomatonParser::DirectionContext::VARIABLE ()
References hybridautomatonParser::VARIABLE.
VARIABLE() [2/2]
tree::TerminalNode * hybridautomatonParser::DirectionContext::VARIABLE (size_t i)
References hybridautomatonParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp