irafhy: definitionParser::HpolytopeContext Class Reference
definitionParser::HpolytopeContext Class Reference
#include <definitionParser.h>
Public Member Functions
HpolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
MatrixContext * matrix ()
VectorContext * vector ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
HpolytopeContext()
definitionParser::HpolytopeContext::HpolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::HpolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::HpolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterHpolytope().
Referenced by definitionParser::hpolytope().
exitRule()
void definitionParser::HpolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitHpolytope().
Referenced by definitionParser::hpolytope().
getRuleIndex()
size_t definitionParser::HpolytopeContext::getRuleIndex () const override virtual
References definitionParser::RuleHpolytope.
LEFTCURLYBRACKET()
tree::TerminalNode * definitionParser::HpolytopeContext::LEFTCURLYBRACKET ()
References definitionParser::LEFTCURLYBRACKET.
matrix()
definitionParser::MatrixContext * definitionParser::HpolytopeContext::matrix ()
Referenced by definitionParser::hpolytope().
RIGHTCURLYBRACKET()
tree::TerminalNode * definitionParser::HpolytopeContext::RIGHTCURLYBRACKET ()
References definitionParser::RIGHTCURLYBRACKET.
vector()
definitionParser::VectorContext * definitionParser::HpolytopeContext::vector ()
Referenced by definitionParser::hpolytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp