irafhy: transitionsParser::UpdatefunctionContext Class Reference
transitionsParser::UpdatefunctionContext Class Reference
#include <transitionsParser.h>
Public Member Functions
UpdatefunctionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * DEFINE ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
UpdatefunctionContext()
transitionsParser::UpdatefunctionContext::UpdatefunctionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::UpdatefunctionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * transitionsParser::UpdatefunctionContext::DEFINE ()
References transitionsParser::DEFINE.
enterRule()
void transitionsParser::UpdatefunctionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterUpdatefunction().
Referenced by transitionsParser::updatefunction().
exitRule()
void transitionsParser::UpdatefunctionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitUpdatefunction().
Referenced by transitionsParser::updatefunction().
expression()
transitionsParser::ExpressionContext * transitionsParser::UpdatefunctionContext::expression ()
Referenced by transitionsParser::updatefunction().
getRuleIndex()
size_t transitionsParser::UpdatefunctionContext::getRuleIndex () const override virtual
References transitionsParser::RuleUpdatefunction.
VARIABLE()
tree::TerminalNode * transitionsParser::UpdatefunctionContext::VARIABLE ()
References transitionsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp