irafhy: hybridautomatonParser::ResetmapContext Class Reference
hybridautomatonParser::ResetmapContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
ResetmapContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_RESET_MAP ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< UpdatefunctionContext * > updatefunction ()
UpdatefunctionContext * updatefunction (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ResetmapContext()
hybridautomatonParser::ResetmapContext::ResetmapContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::ResetmapContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::ResetmapContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterResetmap().
Referenced by hybridautomatonParser::resetmap().
exitRule()
void hybridautomatonParser::ResetmapContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitResetmap().
Referenced by hybridautomatonParser::resetmap().
getRuleIndex()
size_t hybridautomatonParser::ResetmapContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleResetmap.
KEY_RESET_MAP()
tree::TerminalNode * hybridautomatonParser::ResetmapContext::KEY_RESET_MAP ()
References hybridautomatonParser::KEY_RESET_MAP.
LEFTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::ResetmapContext::LEFTCURLYBRACKET ()
References hybridautomatonParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * hybridautomatonParser::ResetmapContext::RIGHTCURLYBRACKET ()
References hybridautomatonParser::RIGHTCURLYBRACKET.
updatefunction() [1/2]
std::vector< hybridautomatonParser::UpdatefunctionContext * > hybridautomatonParser::ResetmapContext::updatefunction ()
Referenced by hybridautomatonParser::resetmap().
updatefunction() [2/2]
hybridautomatonParser::UpdatefunctionContext * hybridautomatonParser::ResetmapContext::updatefunction (size_t i)
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp