irafhy: definitionParser::AcosExpContext Class Reference
definitionParser::AcosExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
AcosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcosExpContext()
definitionParser::AcosExpContext::AcosExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::AcosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::AcosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterAcosExp().
exitRule()
void definitionParser::AcosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitAcosExp().
expression()
definitionParser::ExpressionContext * definitionParser::AcosExpContext::expression ()
KEY_ARCCOS_FUNCTION()
tree::TerminalNode * definitionParser::AcosExpContext::KEY_ARCCOS_FUNCTION ()
References definitionParser::KEY_ARCCOS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::AcosExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::AcosExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp