irafhy: hybridautomatonParser::NexpExpContext Class Reference
hybridautomatonParser::NexpExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
NexpExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_NATURAL_EXP_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
NexpExpContext()
hybridautomatonParser::NexpExpContext::NexpExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::NexpExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::NexpExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterNexpExp().
exitRule()
void hybridautomatonParser::NexpExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitNexpExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::NexpExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitNexpExp().
KEY_NATURAL_EXP_FUNCTION()
tree::TerminalNode * hybridautomatonParser::NexpExpContext::KEY_NATURAL_EXP_FUNCTION ()
References hybridautomatonParser::KEY_NATURAL_EXP_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::NexpExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::NexpExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp