irafhy: settingsParser::AtanExpContext Class Reference
settingsParser::AtanExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
AtanExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCTAN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AtanExpContext()
settingsParser::AtanExpContext::AtanExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::AtanExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::AtanExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterAtanExp().
exitRule()
void settingsParser::AtanExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitAtanExp().
expression()
settingsParser::ExpressionContext * settingsParser::AtanExpContext::expression ()
KEY_ARCTAN_FUNCTION()
tree::TerminalNode * settingsParser::AtanExpContext::KEY_ARCTAN_FUNCTION ()
References settingsParser::KEY_ARCTAN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::AtanExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::AtanExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp