irafhy: settingsParser::StepSettingContext Class Reference
settingsParser::StepSettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
StepSettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_STEP ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * NUMBER ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
StepSettingContext()
settingsParser::StepSettingContext::StepSettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::StepSettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::StepSettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::StepSettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterStepSetting().
Referenced by settingsParser::stepSetting().
exitRule()
void settingsParser::StepSettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitStepSetting().
Referenced by settingsParser::stepSetting().
getRuleIndex()
size_t settingsParser::StepSettingContext::getRuleIndex () const override virtual
References settingsParser::RuleStepSetting.
KEY_STEP()
tree::TerminalNode * settingsParser::StepSettingContext::KEY_STEP ()
References settingsParser::KEY_STEP.
NUMBER()
tree::TerminalNode * settingsParser::StepSettingContext::NUMBER ()
References settingsParser::NUMBER.
Referenced by irafhy::SettingsVisitor::visitStepSetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp