irafhy: locationsParser::ExpAddSubContext Class Reference
locationsParser::ExpAddSubContext Class Reference
#include <locationsParser.h>
Public Member Functions
ExpAddSubContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * PLUS ()
antlr4::tree::TerminalNode * MINUS ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpAddSubContext()
locationsParser::ExpAddSubContext::ExpAddSubContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ExpAddSubContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ExpAddSubContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterExpAddSub().
exitRule()
void locationsParser::ExpAddSubContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitExpAddSub().
expression() [1/2]
std::vector< locationsParser::ExpressionContext * > locationsParser::ExpAddSubContext::expression ()
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::ExpAddSubContext::expression (size_t i)
MINUS()
tree::TerminalNode * locationsParser::ExpAddSubContext::MINUS ()
References locationsParser::MINUS.
PLUS()
tree::TerminalNode * locationsParser::ExpAddSubContext::PLUS ()
References locationsParser::PLUS.
Member Data Documentation
OP
antlr4::Token* locationsParser::ExpAddSubContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp