irafhy: transitionsParser::GuardconditionContext Class Reference
transitionsParser::GuardconditionContext Class Reference
#include <transitionsParser.h>
Public Member Functions
GuardconditionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_GUARD_CONDITIONS ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
ConditionContext * condition ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
GuardconditionContext()
transitionsParser::GuardconditionContext::GuardconditionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::GuardconditionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
condition()
transitionsParser::ConditionContext * transitionsParser::GuardconditionContext::condition ()
Referenced by transitionsParser::guardcondition().
enterRule()
void transitionsParser::GuardconditionContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterGuardcondition().
Referenced by transitionsParser::guardcondition().
exitRule()
void transitionsParser::GuardconditionContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitGuardcondition().
Referenced by transitionsParser::guardcondition().
getRuleIndex()
size_t transitionsParser::GuardconditionContext::getRuleIndex () const override virtual
References transitionsParser::RuleGuardcondition.
KEY_GUARD_CONDITIONS()
tree::TerminalNode * transitionsParser::GuardconditionContext::KEY_GUARD_CONDITIONS ()
References transitionsParser::KEY_GUARD_CONDITIONS.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::GuardconditionContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::GuardconditionContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp