irafhy: transitionsParser::FormulaContext Class Reference
transitionsParser::FormulaContext Class Reference
#include <transitionsParser.h>
Public Member Functions
FormulaContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * ASSIGN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * DERIVATIVE ()
IntervalContext * interval ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FormulaContext()
transitionsParser::FormulaContext::FormulaContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::FormulaContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ASSIGN()
tree::TerminalNode * transitionsParser::FormulaContext::ASSIGN ()
References transitionsParser::ASSIGN.
DERIVATIVE()
tree::TerminalNode * transitionsParser::FormulaContext::DERIVATIVE ()
References transitionsParser::DERIVATIVE.
enterRule()
void transitionsParser::FormulaContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterFormula().
Referenced by transitionsParser::formula().
exitRule()
void transitionsParser::FormulaContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitFormula().
Referenced by transitionsParser::formula().
expression()
transitionsParser::ExpressionContext * transitionsParser::FormulaContext::expression ()
Referenced by transitionsParser::formula().
getRuleIndex()
size_t transitionsParser::FormulaContext::getRuleIndex () const override virtual
References transitionsParser::RuleFormula.
interval()
transitionsParser::IntervalContext * transitionsParser::FormulaContext::interval ()
Referenced by transitionsParser::formula().
VARIABLE()
tree::TerminalNode * transitionsParser::FormulaContext::VARIABLE ()
References transitionsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp