irafhy: irafhy::Item Class Reference
irafhy::Item Class Reference
#include <item.h>
Public Member Functions
Item ()
constructor
Item (const Entity &entity)
constructor with given entity
~Item ()=default
destructor
std::function< capd::autodiff::Node(capd::autodiff::Node, capd::autodiff::Node[], int, capd::autodiff::Node[], int)> arithmetic () const
get the arithmetic function of the current item
capd::interval value (const capd::interval &t, const std::vector< capd::interval > &in, const std::vector< capd::interval > &params) const
get the value of the current item
Private Attributes
Entity entity_
Friends
std::ostream & operator<< (std::ostream &out, const Item &rhs)
out the given item to standard out stream
Constructor & Destructor Documentation
Item() [1/2]
irafhy::Item::Item ()
constructor
References entity_.
Item() [2/2]
irafhy::Item::Item (const Entity & entity) explicit
constructor with given entity
Parameters
entity given entity
References entity_.
~Item()
irafhy::Item::~Item () default
destructor
Member Function Documentation
arithmetic()
std::function< capd::autodiff::Node(capd::autodiff::Node, capd::autodiff::Node[], int, capd::autodiff::Node[], int)> irafhy::Item::arithmetic () const
get the arithmetic function of the current item
Returns
the arithmetic function of the current item
References irafhy::BINARY_T, irafhy::CONSTANT_T, entity_, irafhy::UNARY_T, and irafhy::VARIABLE_T.
Referenced by irafhy::Formula::arithmetic().
value()
capd::interval irafhy::Item::value (const capd::interval & t, const std::vector< capd::interval > & in, const std::vector< capd::interval > & params) const
get the value of the current item
Parameters
t time variable
in values of the given variables
params other necessary parameters
Returns
the value of the current item
References irafhy::BINARY_T, irafhy::CONSTANT_T, entity_, irafhy::UNARY_T, and irafhy::VARIABLE_T.
Referenced by irafhy::Constraint::isSatisfy(), and irafhy::Formula::value().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Item & rhs) friend
out the given item to standard out stream
Parameters
out given out stream
rhs given item
Returns
resulting out stream
Member Data Documentation
entity_
Entity irafhy::Item::entity_ private
entity of the item
Referenced by arithmetic(), Item(), irafhy::operator<<(), and value().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/representation/formal/basic/item.h
/home/jianqiang/CLionProjects/irafhy/src/representation/formal/basic/item.cpp