irafhy: hybridautomatonParser::PowExpContext Class Reference
hybridautomatonParser::PowExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
PowExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_POWER_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PowExpContext()
hybridautomatonParser::PowExpContext::PowExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::PowExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * hybridautomatonParser::PowExpContext::COMMA ()
References hybridautomatonParser::COMMA.
enterRule()
void hybridautomatonParser::PowExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterPowExp().
exitRule()
void hybridautomatonParser::PowExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitPowExp().
expression() [1/2]
std::vector< hybridautomatonParser::ExpressionContext * > hybridautomatonParser::PowExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitPowExp().
expression() [2/2]
hybridautomatonParser::ExpressionContext * hybridautomatonParser::PowExpContext::expression (size_t i)
KEY_POWER_FUNCTION()
tree::TerminalNode * hybridautomatonParser::PowExpContext::KEY_POWER_FUNCTION ()
References hybridautomatonParser::KEY_POWER_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::PowExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::PowExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp