irafhy: hybridautomatonParser::LogExpContext Class Reference
hybridautomatonParser::LogExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
LogExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LOG_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LogExpContext()
hybridautomatonParser::LogExpContext::LogExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::LogExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::LogExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterLogExp().
exitRule()
void hybridautomatonParser::LogExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitLogExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::LogExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitLogExp().
KEY_LOG_FUNCTION()
tree::TerminalNode * hybridautomatonParser::LogExpContext::KEY_LOG_FUNCTION ()
References hybridautomatonParser::KEY_LOG_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::LogExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::LogExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp