irafhy: locationsParser::ModelidContext Class Reference
locationsParser::ModelidContext Class Reference
#include <locationsParser.h>
Public Member Functions
ModelidContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_NAME ()
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ModelidContext()
locationsParser::ModelidContext::ModelidContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ModelidContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::ModelidContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterModelid().
Referenced by locationsParser::modelid().
exitRule()
void locationsParser::ModelidContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitModelid().
Referenced by locationsParser::modelid().
getRuleIndex()
size_t locationsParser::ModelidContext::getRuleIndex () const override virtual
References locationsParser::RuleModelid.
KEY_NAME()
tree::TerminalNode * locationsParser::ModelidContext::KEY_NAME ()
References locationsParser::KEY_NAME.
VARIABLE()
tree::TerminalNode * locationsParser::ModelidContext::VARIABLE ()
References locationsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp