irafhy: definitionParser::AtanExpContext Class Reference
definitionParser::AtanExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
AtanExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCTAN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AtanExpContext()
definitionParser::AtanExpContext::AtanExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::AtanExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::AtanExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterAtanExp().
exitRule()
void definitionParser::AtanExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitAtanExp().
expression()
definitionParser::ExpressionContext * definitionParser::AtanExpContext::expression ()
KEY_ARCTAN_FUNCTION()
tree::TerminalNode * definitionParser::AtanExpContext::KEY_ARCTAN_FUNCTION ()
References definitionParser::KEY_ARCTAN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::AtanExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::AtanExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp