irafhy: hybridautomatonParser::CosExpContext Class Reference
hybridautomatonParser::CosExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
CosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COS_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CosExpContext()
hybridautomatonParser::CosExpContext::CosExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::CosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::CosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterCosExp().
exitRule()
void hybridautomatonParser::CosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitCosExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::CosExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitCosExp().
KEY_COS_FUNCTION()
tree::TerminalNode * hybridautomatonParser::CosExpContext::KEY_COS_FUNCTION ()
References hybridautomatonParser::KEY_COS_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CosExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CosExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp