irafhy: irafhy::CSPSolver Class Reference
irafhy::CSPSolver Class Reference
#include <CSPSolver.h>
Static Public Member Functions
static std::vector< IntervalHull > exactBoundarySolve (const IntervalHull &intervalHull, double epsilon)
get the boundary interval hulls in specified precision
static std::vector< IntervalHull > branchPruneSolve (const IntervalHull &intervalHull, double epsilon)
get the boundary interval hulls of the given interval hull in specified precision using branch and prune method
static std::vector< IntervalHull > branchPruneSolve (const Constraints &constraints, double epsilon)
get the boundary interval hulls of the domain which defined by the given constraints in specified precision using branch and prune method
static std::vector< IntervalHull > branchPruneSolve (const Polytope &polytope, double epsilon)
get the boundary interval hulls of the domain which defined by the given constraints in specified precision using branch and prune method
Static Private Member Functions
static Eigen::MatrixXd extremeVerticesEnumeration (const Eigen::MatrixXd &A, const Eigen::VectorXd &b)
enumerate the extreme vertices of the convex hull which defined by the given linear system Ax<=b
Member Function Documentation
branchPruneSolve() [1/3]
std::vector< IntervalHull > irafhy::CSPSolver::branchPruneSolve (const IntervalHull & intervalHull, double epsilon) static
get the boundary interval hulls of the given interval hull in specified precision using branch and prune method
Parameters
intervalHull given interval hull
epsilon specified precision
Returns
resulting boundary precision
References irafhy::IntervalHull::constraints(), and irafhy::IntervalHull::dimension().
branchPruneSolve() [2/3]
std::vector< IntervalHull > irafhy::CSPSolver::branchPruneSolve (const Constraints & constraints, double epsilon) static
get the boundary interval hulls of the domain which defined by the given constraints in specified precision using branch and prune method
Parameters
constraints constraints which define the target domain
epsilon specified precision
Returns
resulting boundary interval hulls
References irafhy::Constraints::dimension(), extremeVerticesEnumeration(), irafhy::LESS_THAN_OR_EQUAL_TO, and irafhy::Constraints::size().
branchPruneSolve() [3/3]
std::vector< IntervalHull > irafhy::CSPSolver::branchPruneSolve (const Polytope & polytope, double epsilon) static
get the boundary interval hulls of the domain which defined by the given constraints in specified precision using branch and prune method
Parameters
polytope convex polytope which define the target domain
epsilon specified precision
Returns
resulting boundary interval hulls
References irafhy::Polytope::constraints(), irafhy::Polytope::dimension(), irafhy::Polytope::empty(), and irafhy::Polytope::halfSpaceConstraints().
exactBoundarySolve()
std::vector< IntervalHull > irafhy::CSPSolver::exactBoundarySolve (const IntervalHull & intervalHull, double epsilon) static
get the boundary interval hulls in specified precision
Parameters
intervalHull query interval hull
epsilon specified precision
Returns
resulting boundary interval hulls
References irafhy::IntervalHull::constraints(), and irafhy::IntervalHull::dimension().
extremeVerticesEnumeration()
Eigen::MatrixXd irafhy::CSPSolver::extremeVerticesEnumeration (const Eigen::MatrixXd & A, const Eigen::VectorXd & b) static private
enumerate the extreme vertices of the convex hull which defined by the given linear system Ax<=b
Parameters
A coefficient matrix of the given linear system
b offset vector of the given linear system
Returns
extreme vertices of the given convex hull
Referenced by branchPruneSolve().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/solver/CSPSolver.h
/home/jianqiang/CLionProjects/irafhy/src/utility/solver/CSPSolver.cpp