irafhy: settingsParser::PosExpContext Class Reference
settingsParser::PosExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
PosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * PLUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PosExpContext()
settingsParser::PosExpContext::PosExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::PosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::PosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterPosExp().
exitRule()
void settingsParser::PosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitPosExp().
expression()
settingsParser::ExpressionContext * settingsParser::PosExpContext::expression ()
PLUS()
tree::TerminalNode * settingsParser::PosExpContext::PLUS ()
References settingsParser::PLUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp