irafhy: locationsParser::SqrExpContext Class Reference
locationsParser::SqrExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
SqrExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SQR_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SqrExpContext()
locationsParser::SqrExpContext::SqrExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::SqrExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::SqrExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterSqrExp().
exitRule()
void locationsParser::SqrExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitSqrExp().
expression()
locationsParser::ExpressionContext * locationsParser::SqrExpContext::expression ()
KEY_SQR_FUNCTION()
tree::TerminalNode * locationsParser::SqrExpContext::KEY_SQR_FUNCTION ()
References locationsParser::KEY_SQR_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::SqrExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::SqrExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp