irafhy: definitionParser::ExpressionContext Class Reference
definitionParser::ExpressionContext Class Reference
#include <definitionParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpressionContext() [1/2]
definitionParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
ExpressionContext() [2/2]
definitionParser::ExpressionContext::ExpressionContext () default
Member Function Documentation
copyFrom()
void definitionParser::ExpressionContext::copyFrom (ExpressionContext * context)
Referenced by definitionParser::AcosExpContext::AcosExpContext(), definitionParser::AcoshExpContext::AcoshExpContext(), definitionParser::AcotExpContext::AcotExpContext(), definitionParser::AcothExpContext::AcothExpContext(), definitionParser::AsinExpContext::AsinExpContext(), definitionParser::AsinhExpContext::AsinhExpContext(), definitionParser::AtanExpContext::AtanExpContext(), definitionParser::AtanhExpContext::AtanhExpContext(), definitionParser::ConstantContext::ConstantContext(), definitionParser::CosExpContext::CosExpContext(), definitionParser::CoshExpContext::CoshExpContext(), definitionParser::CotExpContext::CotExpContext(), definitionParser::CothExpContext::CothExpContext(), definitionParser::ExpAddSubContext::ExpAddSubContext(), definitionParser::ExpBraContext::ExpBraContext(), definitionParser::ExpExpContext::ExpExpContext(), definitionParser::ExpMulDivContext::ExpMulDivContext(), definitionParser::LnExpContext::LnExpContext(), definitionParser::LogExpContext::LogExpContext(), definitionParser::NegExpContext::NegExpContext(), definitionParser::NexpExpContext::NexpExpContext(), definitionParser::PosExpContext::PosExpContext(), definitionParser::PowExpContext::PowExpContext(), definitionParser::SinExpContext::SinExpContext(), definitionParser::SinhExpContext::SinhExpContext(), definitionParser::SqrExpContext::SqrExpContext(), definitionParser::SqrtExpContext::SqrtExpContext(), definitionParser::TanExpContext::TanExpContext(), definitionParser::TanhExpContext::TanhExpContext(), and definitionParser::VariableContext::VariableContext().
getRuleIndex()
size_t definitionParser::ExpressionContext::getRuleIndex () const override virtual
References definitionParser::RuleExpression.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp