irafhy: transitionsParser::TanhExpContext Class Reference
transitionsParser::TanhExpContext Class Reference
#include <transitionsParser.h>
Public Member Functions
TanhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_TANH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
TanhExpContext()
transitionsParser::TanhExpContext::TanhExpContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::TanhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::TanhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterTanhExp().
exitRule()
void transitionsParser::TanhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitTanhExp().
expression()
transitionsParser::ExpressionContext * transitionsParser::TanhExpContext::expression ()
KEY_TANH_FUNCTION()
tree::TerminalNode * transitionsParser::TanhExpContext::KEY_TANH_FUNCTION ()
References transitionsParser::KEY_TANH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * transitionsParser::TanhExpContext::LEFTROUNDBRACKET ()
References transitionsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * transitionsParser::TanhExpContext::RIGHTROUNDBRACKET ()
References transitionsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp