irafhy: settingsParser::SinhExpContext Class Reference
settingsParser::SinhExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
SinhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SINH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinhExpContext()
settingsParser::SinhExpContext::SinhExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::SinhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::SinhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterSinhExp().
exitRule()
void settingsParser::SinhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitSinhExp().
expression()
settingsParser::ExpressionContext * settingsParser::SinhExpContext::expression ()
KEY_SINH_FUNCTION()
tree::TerminalNode * settingsParser::SinhExpContext::KEY_SINH_FUNCTION ()
References settingsParser::KEY_SINH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::SinhExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::SinhExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp