irafhy: hybridautomatonParser::AcotExpContext Class Reference
hybridautomatonParser::AcotExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
AcotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_ARCCOT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
AcotExpContext()
hybridautomatonParser::AcotExpContext::AcotExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::AcotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::AcotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterAcotExp().
exitRule()
void hybridautomatonParser::AcotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitAcotExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::AcotExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitAcotExp().
KEY_ARCCOT_FUNCTION()
tree::TerminalNode * hybridautomatonParser::AcotExpContext::KEY_ARCCOT_FUNCTION ()
References hybridautomatonParser::KEY_ARCCOT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AcotExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::AcotExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp