irafhy: settingsParser::IntervalhullContext Class Reference
settingsParser::IntervalhullContext Class Reference
#include <settingsParser.h>
Public Member Functions
IntervalhullContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< IntervalContext * > interval ()
IntervalContext * interval (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntervalhullContext()
settingsParser::IntervalhullContext::IntervalhullContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::IntervalhullContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalhullContext::COMMA ()
References settingsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * settingsParser::IntervalhullContext::COMMA (size_t i)
References settingsParser::COMMA.
enterRule()
void settingsParser::IntervalhullContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterIntervalhull().
Referenced by settingsParser::intervalhull().
exitRule()
void settingsParser::IntervalhullContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitIntervalhull().
Referenced by settingsParser::intervalhull().
getRuleIndex()
size_t settingsParser::IntervalhullContext::getRuleIndex () const override virtual
References settingsParser::RuleIntervalhull.
interval() [1/2]
std::vector< settingsParser::IntervalContext * > settingsParser::IntervalhullContext::interval ()
Referenced by settingsParser::intervalhull(), and irafhy::SettingsVisitor::visitIntervalhull().
interval() [2/2]
settingsParser::IntervalContext * settingsParser::IntervalhullContext::interval (size_t i)
KEY_INTERVAL_HULL()
tree::TerminalNode * settingsParser::IntervalhullContext::KEY_INTERVAL_HULL ()
References settingsParser::KEY_INTERVAL_HULL.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::IntervalhullContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::IntervalhullContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp