irafhy: hybridautomatonParser::PosExpContext Class Reference
hybridautomatonParser::PosExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
PosExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * PLUS ()
ExpressionContext * expression ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
PosExpContext()
hybridautomatonParser::PosExpContext::PosExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::PosExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::PosExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterPosExp().
exitRule()
void hybridautomatonParser::PosExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitPosExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::PosExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitPosExp().
PLUS()
tree::TerminalNode * hybridautomatonParser::PosExpContext::PLUS ()
References hybridautomatonParser::PLUS.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp