irafhy: settingsParser::MaxjumpsettingContext Class Reference
settingsParser::MaxjumpsettingContext Class Reference
#include <settingsParser.h>
Public Member Functions
MaxjumpsettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MAX_JUMP ()
antlr4::tree::TerminalNode * DEFINE ()
antlr4::tree::TerminalNode * NUMBER ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
MaxjumpsettingContext()
settingsParser::MaxjumpsettingContext::MaxjumpsettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::MaxjumpsettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEFINE()
tree::TerminalNode * settingsParser::MaxjumpsettingContext::DEFINE ()
References settingsParser::DEFINE.
enterRule()
void settingsParser::MaxjumpsettingContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterMaxjumpsetting().
Referenced by settingsParser::maxjumpsetting().
exitRule()
void settingsParser::MaxjumpsettingContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitMaxjumpsetting().
Referenced by settingsParser::maxjumpsetting().
getRuleIndex()
size_t settingsParser::MaxjumpsettingContext::getRuleIndex () const override virtual
References settingsParser::RuleMaxjumpsetting.
KEY_MAX_JUMP()
tree::TerminalNode * settingsParser::MaxjumpsettingContext::KEY_MAX_JUMP ()
References settingsParser::KEY_MAX_JUMP.
NUMBER()
tree::TerminalNode * settingsParser::MaxjumpsettingContext::NUMBER ()
References settingsParser::NUMBER.
Referenced by irafhy::SettingsVisitor::visitMaxjumpsetting().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp