irafhy: settingsParser::VectorContext Class Reference
settingsParser::VectorContext Class Reference
#include <settingsParser.h>
Public Member Functions
VectorContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset115 = nullptr
antlr4::Token * _tset135 = nullptr
Constructor & Destructor Documentation
VectorContext()
settingsParser::VectorContext::VectorContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::VectorContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > settingsParser::VectorContext::COMMA ()
References settingsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * settingsParser::VectorContext::COMMA (size_t i)
References settingsParser::COMMA.
enterRule()
void settingsParser::VectorContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterVector().
Referenced by settingsParser::vector().
exitRule()
void settingsParser::VectorContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitVector().
Referenced by settingsParser::vector().
getRuleIndex()
size_t settingsParser::VectorContext::getRuleIndex () const override virtual
References settingsParser::RuleVector.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::VectorContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > settingsParser::VectorContext::MINUS ()
References settingsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * settingsParser::VectorContext::MINUS (size_t i)
References settingsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > settingsParser::VectorContext::NUMBER ()
References settingsParser::NUMBER.
Referenced by irafhy::SettingsVisitor::visitVector().
NUMBER() [2/2]
tree::TerminalNode * settingsParser::VectorContext::NUMBER (size_t i)
References settingsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > settingsParser::VectorContext::PLUS ()
References settingsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * settingsParser::VectorContext::PLUS (size_t i)
References settingsParser::PLUS.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::VectorContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
Member Data Documentation
_tset115
antlr4::Token* settingsParser::VectorContext::_tset115 = nullptr
Referenced by settingsParser::vector().
_tset135
antlr4::Token* settingsParser::VectorContext::_tset135 = nullptr
Referenced by settingsParser::vector().
minusToken
antlr4::Token* settingsParser::VectorContext::minusToken = nullptr
OP
std::vector<antlr4::Token *> settingsParser::VectorContext::OP
Referenced by settingsParser::vector(), and irafhy::SettingsVisitor::visitVector().
plusToken
antlr4::Token* settingsParser::VectorContext::plusToken = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp