irafhy: locationsParser::LnExpContext Class Reference
locationsParser::LnExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
LnExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LnExpContext()
locationsParser::LnExpContext::LnExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::LnExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::LnExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterLnExp().
exitRule()
void locationsParser::LnExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitLnExp().
expression()
locationsParser::ExpressionContext * locationsParser::LnExpContext::expression ()
KEY_LN_FUNCTION()
tree::TerminalNode * locationsParser::LnExpContext::KEY_LN_FUNCTION ()
References locationsParser::KEY_LN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::LnExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::LnExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp