irafhy: hybridautomatonParser::FormulaContext Class Reference
hybridautomatonParser::FormulaContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
FormulaContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * ASSIGN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * DERIVATIVE ()
IntervalContext * interval ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FormulaContext()
hybridautomatonParser::FormulaContext::FormulaContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::FormulaContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ASSIGN()
tree::TerminalNode * hybridautomatonParser::FormulaContext::ASSIGN ()
References hybridautomatonParser::ASSIGN.
DERIVATIVE()
tree::TerminalNode * hybridautomatonParser::FormulaContext::DERIVATIVE ()
References hybridautomatonParser::DERIVATIVE.
enterRule()
void hybridautomatonParser::FormulaContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterFormula().
Referenced by hybridautomatonParser::formula().
exitRule()
void hybridautomatonParser::FormulaContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitFormula().
Referenced by hybridautomatonParser::formula().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::FormulaContext::expression ()
Referenced by hybridautomatonParser::formula(), and irafhy::SystemVisitor::visitFormula().
getRuleIndex()
size_t hybridautomatonParser::FormulaContext::getRuleIndex () const override virtual
References hybridautomatonParser::RuleFormula.
interval()
hybridautomatonParser::IntervalContext * hybridautomatonParser::FormulaContext::interval ()
Referenced by hybridautomatonParser::formula().
VARIABLE()
tree::TerminalNode * hybridautomatonParser::FormulaContext::VARIABLE ()
References hybridautomatonParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp