irafhy: locationsParser::SinhExpContext Class Reference
locationsParser::SinhExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
SinhExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SINH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SinhExpContext()
locationsParser::SinhExpContext::SinhExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::SinhExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::SinhExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterSinhExp().
exitRule()
void locationsParser::SinhExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitSinhExp().
expression()
locationsParser::ExpressionContext * locationsParser::SinhExpContext::expression ()
KEY_SINH_FUNCTION()
tree::TerminalNode * locationsParser::SinhExpContext::KEY_SINH_FUNCTION ()
References locationsParser::KEY_SINH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::SinhExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::SinhExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp