irafhy: definitionParser::VariableContext Class Reference
definitionParser::VariableContext Class Reference
#include <definitionParser.h>
Public Member Functions
VariableContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
VariableContext()
definitionParser::VariableContext::VariableContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::VariableContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::VariableContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterVariable().
exitRule()
void definitionParser::VariableContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitVariable().
VARIABLE()
tree::TerminalNode * definitionParser::VariableContext::VARIABLE ()
References definitionParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp