irafhy: definitionParser::PolytopeContext Class Reference
definitionParser::PolytopeContext Class Reference
#include <definitionParser.h>
Public Member Functions
PolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
PolytopeContext()
definitionParser::PolytopeContext::PolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::PolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::PolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterPolytope().
Referenced by definitionParser::polytope().
exitRule()
void definitionParser::PolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitPolytope().
Referenced by definitionParser::polytope().
getRuleIndex()
size_t definitionParser::PolytopeContext::getRuleIndex () const override virtual
References definitionParser::RulePolytope.
hpolytope()
definitionParser::HpolytopeContext * definitionParser::PolytopeContext::hpolytope ()
Referenced by definitionParser::polytope().
KEY_POLYTOPE()
tree::TerminalNode * definitionParser::PolytopeContext::KEY_POLYTOPE ()
References definitionParser::KEY_POLYTOPE.
vpolytope()
definitionParser::VpolytopeContext * definitionParser::PolytopeContext::vpolytope ()
Referenced by definitionParser::polytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp