irafhy: locationsParser::CotExpContext Class Reference
locationsParser::CotExpContext Class Reference
#include <locationsParser.h>
Public Member Functions
CotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CotExpContext()
locationsParser::CotExpContext::CotExpContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::CotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::CotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterCotExp().
exitRule()
void locationsParser::CotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitCotExp().
expression()
locationsParser::ExpressionContext * locationsParser::CotExpContext::expression ()
KEY_COT_FUNCTION()
tree::TerminalNode * locationsParser::CotExpContext::KEY_COT_FUNCTION ()
References locationsParser::KEY_COT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * locationsParser::CotExpContext::LEFTROUNDBRACKET ()
References locationsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * locationsParser::CotExpContext::RIGHTROUNDBRACKET ()
References locationsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp