irafhy: settingsParser::VariableContext Class Reference
settingsParser::VariableContext Class Reference
#include <settingsParser.h>
Public Member Functions
VariableContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * VARIABLE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
VariableContext()
settingsParser::VariableContext::VariableContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::VariableContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::VariableContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterVariable().
exitRule()
void settingsParser::VariableContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitVariable().
VARIABLE()
tree::TerminalNode * settingsParser::VariableContext::VARIABLE ()
References settingsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp