irafhy: irafhy::DefinitionVisitor Class Reference
irafhy::DefinitionVisitor Class Reference
#include <definitionVisitor.h>
Public Member Functions
DefinitionVisitor ()=default
constructor
DefinitionVisitor (const std::vector< std::string > &vars)
constructor with given variables
~DefinitionVisitor () override=default
destructor
antlrcpp::Any visitCondition (hybridautomatonParser::ConditionContext *ctx) override
condition visitor
antlrcpp::Any visitPolytope (hybridautomatonParser::PolytopeContext *ctx) override
polytope visitor
antlrcpp::Any visitHpolytope (hybridautomatonParser::HpolytopeContext *ctx) override
polytope which defined by half spaces visitor
antlrcpp::Any visitVpolytope (hybridautomatonParser::VpolytopeContext *ctx) override
polytope which defined by extreme vertices
antlrcpp::Any visitMatrix (hybridautomatonParser::MatrixContext *ctx) override
matrix visitor
antlrcpp::Any visitVector (hybridautomatonParser::VectorContext *ctx) override
vector visitor
antlrcpp::Any visitIntervalhull (hybridautomatonParser::IntervalhullContext *ctx) override
interval hull visitor
antlrcpp::Any visitInterval (hybridautomatonParser::IntervalContext *ctx) override
interval visitor
Private Member Functions
double strToNum (const std::string &numStr) const
convert given string to number
Private Attributes
std::vector< std::string > vars_
variables of the hybrid automaton
Constructor & Destructor Documentation
DefinitionVisitor() [1/2]
irafhy::DefinitionVisitor::DefinitionVisitor () default
constructor
DefinitionVisitor() [2/2]
irafhy::DefinitionVisitor::DefinitionVisitor (const std::vector< std::string > & vars) explicit
constructor with given variables
Parameters
vars variables of hybrid automaton
References vars_.
~DefinitionVisitor()
irafhy::DefinitionVisitor::~DefinitionVisitor () override default
destructor
Member Function Documentation
strToNum()
double irafhy::DefinitionVisitor::strToNum (const std::string & numStr) const private
convert given string to number
Parameters
numStr given string
Returns
resulting number
Referenced by visitInterval(), and visitVector().
visitCondition()
antlrcpp::Any irafhy::DefinitionVisitor::visitCondition (hybridautomatonParser::ConditionContext * ctx) override
condition visitor
Parameters
ctx context of condition
Returns
condition instance
visitHpolytope()
antlrcpp::Any irafhy::DefinitionVisitor::visitHpolytope (hybridautomatonParser::HpolytopeContext * ctx) override
polytope which defined by half spaces visitor
Parameters
ctx context of polytope
Returns
polytope instance
visitInterval()
antlrcpp::Any irafhy::DefinitionVisitor::visitInterval (hybridautomatonParser::IntervalContext * ctx) override
interval visitor
Parameters
ctx context of interval
Returns
interval instance
References irafhy::MINUS, and strToNum().
visitIntervalhull()
antlrcpp::Any irafhy::DefinitionVisitor::visitIntervalhull (hybridautomatonParser::IntervalhullContext * ctx) override
interval hull visitor
Parameters
ctx context of interval hull
Returns
interval hull instance
visitMatrix()
antlrcpp::Any irafhy::DefinitionVisitor::visitMatrix (hybridautomatonParser::MatrixContext * ctx) override
matrix visitor
Parameters
ctx context of matrix
Returns
matrix instance
visitPolytope()
antlrcpp::Any irafhy::DefinitionVisitor::visitPolytope (hybridautomatonParser::PolytopeContext * ctx) override
polytope visitor
Parameters
ctx context of polytope
Returns
polytope instance
visitVector()
antlrcpp::Any irafhy::DefinitionVisitor::visitVector (hybridautomatonParser::VectorContext * ctx) override
vector visitor
Parameters
ctx context of vector
Returns
vector instance
References irafhy::MINUS, and strToNum().
visitVpolytope()
antlrcpp::Any irafhy::DefinitionVisitor::visitVpolytope (hybridautomatonParser::VpolytopeContext * ctx) override
polytope which defined by extreme vertices
Parameters
ctx context of polytope
Returns
polytope instance
Member Data Documentation
vars_
std::vector<std::string> irafhy::DefinitionVisitor::vars_ private
variables of the hybrid automaton
Referenced by DefinitionVisitor().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/visitor/definitionVisitor.h
/home/jianqiang/CLionProjects/irafhy/src/utility/parser/visitor/definitionVisitor.cpp