irafhy: settingsParser::PolytopeContext Class Reference
settingsParser::PolytopeContext Class Reference
#include <settingsParser.h>
Public Member Functions
PolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
PolytopeContext()
settingsParser::PolytopeContext::PolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::PolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::PolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterPolytope().
Referenced by settingsParser::polytope().
exitRule()
void settingsParser::PolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitPolytope().
Referenced by settingsParser::polytope().
getRuleIndex()
size_t settingsParser::PolytopeContext::getRuleIndex () const override virtual
References settingsParser::RulePolytope.
hpolytope()
settingsParser::HpolytopeContext * settingsParser::PolytopeContext::hpolytope ()
Referenced by settingsParser::polytope(), and irafhy::SettingsVisitor::visitPolytope().
KEY_POLYTOPE()
tree::TerminalNode * settingsParser::PolytopeContext::KEY_POLYTOPE ()
References settingsParser::KEY_POLYTOPE.
vpolytope()
settingsParser::VpolytopeContext * settingsParser::PolytopeContext::vpolytope ()
Referenced by settingsParser::polytope(), and irafhy::SettingsVisitor::visitPolytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp