irafhy: irafhy::Plotter Class Reference
irafhy::Plotter Class Reference
#include <plotter.h>
Static Public Member Functions
static void plot (const std::vector< capd::interval > &timeSequence={}, const std::vector< IntervalHull > &intervalHulls={}, const std::vector< std::size_t > &dimensions={})
plot the given information
Member Function Documentation
plot()
void irafhy::Plotter::plot (const std::vector< capd::interval > & timeSequence = {}, const std::vector< IntervalHull > & intervalHulls = {}, const std::vector< std::size_t > & dimensions = {}) static
plot the given information
Parameters
timeSequence given time sequence
intervalHulls given interval hulls
dimensions dimensions which specify the data should be plotted
References matplotlibcpp::axis(), matplotlibcpp::figure_size(), matplotlibcpp::fill_between(), matplotlibcpp::show(), matplotlibcpp::title(), matplotlibcpp::xlabel(), matplotlibcpp::xlim(), matplotlibcpp::ylabel(), and matplotlibcpp::ylim().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/plotter.h
/home/jianqiang/CLionProjects/irafhy/src/utility/plotter.cpp