irafhy: transitionsParser::IntervalhullContext Class Reference
transitionsParser::IntervalhullContext Class Reference
#include <transitionsParser.h>
Public Member Functions
IntervalhullContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_INTERVAL_HULL ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< IntervalContext * > interval ()
IntervalContext * interval (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntervalhullContext()
transitionsParser::IntervalhullContext::IntervalhullContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::IntervalhullContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > transitionsParser::IntervalhullContext::COMMA ()
References transitionsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * transitionsParser::IntervalhullContext::COMMA (size_t i)
References transitionsParser::COMMA.
enterRule()
void transitionsParser::IntervalhullContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterIntervalhull().
Referenced by transitionsParser::intervalhull().
exitRule()
void transitionsParser::IntervalhullContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitIntervalhull().
Referenced by transitionsParser::intervalhull().
getRuleIndex()
size_t transitionsParser::IntervalhullContext::getRuleIndex () const override virtual
References transitionsParser::RuleIntervalhull.
interval() [1/2]
std::vector< transitionsParser::IntervalContext * > transitionsParser::IntervalhullContext::interval ()
Referenced by transitionsParser::intervalhull().
interval() [2/2]
transitionsParser::IntervalContext * transitionsParser::IntervalhullContext::interval (size_t i)
KEY_INTERVAL_HULL()
tree::TerminalNode * transitionsParser::IntervalhullContext::KEY_INTERVAL_HULL ()
References transitionsParser::KEY_INTERVAL_HULL.
LEFTCURLYBRACKET()
tree::TerminalNode * transitionsParser::IntervalhullContext::LEFTCURLYBRACKET ()
References transitionsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * transitionsParser::IntervalhullContext::RIGHTCURLYBRACKET ()
References transitionsParser::RIGHTCURLYBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp