irafhy: settingsParser::IntervalContext Class Reference
settingsParser::IntervalContext Class Reference
#include <settingsParser.h>
Public Member Functions
IntervalContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * LEFTSQUAREBRACKET ()
antlr4::tree::TerminalNode * COMMA ()
antlr4::tree::TerminalNode * RIGHTSQUAREBRACKET ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< antlr4::tree::TerminalNode * > SCINUM ()
antlr4::tree::TerminalNode * SCINUM (size_t i)
std::vector< antlr4::tree::TerminalNode * > KEY_INFINITY ()
antlr4::tree::TerminalNode * KEY_INFINITY (size_t i)
std::vector< antlr4::tree::TerminalNode * > PLUS ()
antlr4::tree::TerminalNode * PLUS (size_t i)
std::vector< antlr4::tree::TerminalNode * > MINUS ()
antlr4::tree::TerminalNode * MINUS (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * plusToken = nullptr
std::vector< antlr4::Token * > OP
antlr4::Token * minusToken = nullptr
antlr4::Token * _tset251 = nullptr
antlr4::Token * numberToken = nullptr
std::vector< antlr4::Token * > VAL
antlr4::Token * scinumToken = nullptr
antlr4::Token * key_infinityToken = nullptr
antlr4::Token * _tset264 = nullptr
antlr4::Token * _tset284 = nullptr
antlr4::Token * _tset297 = nullptr
Constructor & Destructor Documentation
IntervalContext()
settingsParser::IntervalContext::IntervalContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::IntervalContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA()
tree::TerminalNode * settingsParser::IntervalContext::COMMA ()
References settingsParser::COMMA.
Referenced by irafhy::SettingsVisitor::visitInterval().
enterRule()
void settingsParser::IntervalContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterInterval().
Referenced by settingsParser::interval().
exitRule()
void settingsParser::IntervalContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitInterval().
Referenced by settingsParser::interval().
getRuleIndex()
size_t settingsParser::IntervalContext::getRuleIndex () const override virtual
References settingsParser::RuleInterval.
KEY_INFINITY() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalContext::KEY_INFINITY ()
References settingsParser::KEY_INFINITY.
KEY_INFINITY() [2/2]
tree::TerminalNode * settingsParser::IntervalContext::KEY_INFINITY (size_t i)
References settingsParser::KEY_INFINITY.
LEFTSQUAREBRACKET()
tree::TerminalNode * settingsParser::IntervalContext::LEFTSQUAREBRACKET ()
References settingsParser::LEFTSQUAREBRACKET.
MINUS() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalContext::MINUS ()
References settingsParser::MINUS.
MINUS() [2/2]
tree::TerminalNode * settingsParser::IntervalContext::MINUS (size_t i)
References settingsParser::MINUS.
NUMBER() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalContext::NUMBER ()
References settingsParser::NUMBER.
NUMBER() [2/2]
tree::TerminalNode * settingsParser::IntervalContext::NUMBER (size_t i)
References settingsParser::NUMBER.
PLUS() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalContext::PLUS ()
References settingsParser::PLUS.
PLUS() [2/2]
tree::TerminalNode * settingsParser::IntervalContext::PLUS (size_t i)
References settingsParser::PLUS.
RIGHTSQUAREBRACKET()
tree::TerminalNode * settingsParser::IntervalContext::RIGHTSQUAREBRACKET ()
References settingsParser::RIGHTSQUAREBRACKET.
SCINUM() [1/2]
std::vector< tree::TerminalNode * > settingsParser::IntervalContext::SCINUM ()
References settingsParser::SCINUM.
SCINUM() [2/2]
tree::TerminalNode * settingsParser::IntervalContext::SCINUM (size_t i)
References settingsParser::SCINUM.
Member Data Documentation
_tset251
antlr4::Token* settingsParser::IntervalContext::_tset251 = nullptr
Referenced by settingsParser::interval().
_tset264
antlr4::Token* settingsParser::IntervalContext::_tset264 = nullptr
Referenced by settingsParser::interval().
_tset284
antlr4::Token* settingsParser::IntervalContext::_tset284 = nullptr
Referenced by settingsParser::interval().
_tset297
antlr4::Token* settingsParser::IntervalContext::_tset297 = nullptr
Referenced by settingsParser::interval().
key_infinityToken
antlr4::Token* settingsParser::IntervalContext::key_infinityToken = nullptr
minusToken
antlr4::Token* settingsParser::IntervalContext::minusToken = nullptr
numberToken
antlr4::Token* settingsParser::IntervalContext::numberToken = nullptr
OP
std::vector<antlr4::Token *> settingsParser::IntervalContext::OP
Referenced by settingsParser::interval(), and irafhy::SettingsVisitor::visitInterval().
plusToken
antlr4::Token* settingsParser::IntervalContext::plusToken = nullptr
scinumToken
antlr4::Token* settingsParser::IntervalContext::scinumToken = nullptr
VAL
std::vector<antlr4::Token *> settingsParser::IntervalContext::VAL
Referenced by settingsParser::interval(), and irafhy::SettingsVisitor::visitInterval().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp