irafhy: hybridautomatonParser::CotExpContext Class Reference
hybridautomatonParser::CotExpContext Class Reference
#include <hybridautomatonParser.h>
Public Member Functions
CotExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COT_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from hybridautomatonParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CotExpContext()
hybridautomatonParser::CotExpContext::CotExpContext (ExpressionContext * ctx)
References hybridautomatonParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any hybridautomatonParser::CotExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void hybridautomatonParser::CotExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::enterCotExp().
exitRule()
void hybridautomatonParser::CotExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References hybridautomatonListener::exitCotExp().
expression()
hybridautomatonParser::ExpressionContext * hybridautomatonParser::CotExpContext::expression ()
Referenced by irafhy::ItemVisitor::visitCotExp().
KEY_COT_FUNCTION()
tree::TerminalNode * hybridautomatonParser::CotExpContext::KEY_COT_FUNCTION ()
References hybridautomatonParser::KEY_COT_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CotExpContext::LEFTROUNDBRACKET ()
References hybridautomatonParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * hybridautomatonParser::CotExpContext::RIGHTROUNDBRACKET ()
References hybridautomatonParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/hybridautomatonParser.cpp