irafhy: settingsParser::MatrixContext Class Reference
settingsParser::MatrixContext Class Reference
#include <settingsParser.h>
Public Member Functions
MatrixContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_MATRIX ()
antlr4::tree::TerminalNode * LEFTCURLYBRACKET ()
std::vector< VectorContext * > vector ()
VectorContext * vector (size_t i)
antlr4::tree::TerminalNode * RIGHTCURLYBRACKET ()
antlr4::tree::TerminalNode * KEY_ROW_MAJOR_ORDER ()
antlr4::tree::TerminalNode * KEY_COL_MAJOR_ORDER ()
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * MAJOR_ORDER = nullptr
Constructor & Destructor Documentation
MatrixContext()
settingsParser::MatrixContext::MatrixContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::MatrixContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > settingsParser::MatrixContext::COMMA ()
References settingsParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * settingsParser::MatrixContext::COMMA (size_t i)
References settingsParser::COMMA.
enterRule()
void settingsParser::MatrixContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterMatrix().
Referenced by settingsParser::matrix().
exitRule()
void settingsParser::MatrixContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitMatrix().
Referenced by settingsParser::matrix().
getRuleIndex()
size_t settingsParser::MatrixContext::getRuleIndex () const override virtual
References settingsParser::RuleMatrix.
KEY_COL_MAJOR_ORDER()
tree::TerminalNode * settingsParser::MatrixContext::KEY_COL_MAJOR_ORDER ()
References settingsParser::KEY_COL_MAJOR_ORDER.
KEY_MATRIX()
tree::TerminalNode * settingsParser::MatrixContext::KEY_MATRIX ()
References settingsParser::KEY_MATRIX.
KEY_ROW_MAJOR_ORDER()
tree::TerminalNode * settingsParser::MatrixContext::KEY_ROW_MAJOR_ORDER ()
References settingsParser::KEY_ROW_MAJOR_ORDER.
LEFTCURLYBRACKET()
tree::TerminalNode * settingsParser::MatrixContext::LEFTCURLYBRACKET ()
References settingsParser::LEFTCURLYBRACKET.
RIGHTCURLYBRACKET()
tree::TerminalNode * settingsParser::MatrixContext::RIGHTCURLYBRACKET ()
References settingsParser::RIGHTCURLYBRACKET.
vector() [1/2]
std::vector< settingsParser::VectorContext * > settingsParser::MatrixContext::vector ()
Referenced by settingsParser::matrix(), and irafhy::SettingsVisitor::visitMatrix().
vector() [2/2]
settingsParser::VectorContext * settingsParser::MatrixContext::vector (size_t i)
Member Data Documentation
MAJOR_ORDER
antlr4::Token* settingsParser::MatrixContext::MAJOR_ORDER = nullptr
Referenced by settingsParser::matrix(), and irafhy::SettingsVisitor::visitMatrix().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp