irafhy: definitionParser::CothExpContext Class Reference
definitionParser::CothExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
CothExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_COTH_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
CothExpContext()
definitionParser::CothExpContext::CothExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::CothExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::CothExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterCothExp().
exitRule()
void definitionParser::CothExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitCothExp().
expression()
definitionParser::ExpressionContext * definitionParser::CothExpContext::expression ()
KEY_COTH_FUNCTION()
tree::TerminalNode * definitionParser::CothExpContext::KEY_COTH_FUNCTION ()
References definitionParser::KEY_COTH_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::CothExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::CothExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp