irafhy: settingsParser::LogExpContext Class Reference
settingsParser::LogExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
LogExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LOG_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LogExpContext()
settingsParser::LogExpContext::LogExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::LogExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::LogExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterLogExp().
exitRule()
void settingsParser::LogExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitLogExp().
expression()
settingsParser::ExpressionContext * settingsParser::LogExpContext::expression ()
KEY_LOG_FUNCTION()
tree::TerminalNode * settingsParser::LogExpContext::KEY_LOG_FUNCTION ()
References settingsParser::KEY_LOG_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::LogExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::LogExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp