irafhy: definitionParser::ExpMulDivContext Class Reference
definitionParser::ExpMulDivContext Class Reference
#include <definitionParser.h>
Public Member Functions
ExpMulDivContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * MULTIPLY ()
antlr4::tree::TerminalNode * DIVIDE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpMulDivContext()
definitionParser::ExpMulDivContext::ExpMulDivContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ExpMulDivContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIVIDE()
tree::TerminalNode * definitionParser::ExpMulDivContext::DIVIDE ()
References definitionParser::DIVIDE.
enterRule()
void definitionParser::ExpMulDivContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterExpMulDiv().
exitRule()
void definitionParser::ExpMulDivContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitExpMulDiv().
expression() [1/2]
std::vector< definitionParser::ExpressionContext * > definitionParser::ExpMulDivContext::expression ()
expression() [2/2]
definitionParser::ExpressionContext * definitionParser::ExpMulDivContext::expression (size_t i)
MULTIPLY()
tree::TerminalNode * definitionParser::ExpMulDivContext::MULTIPLY ()
References definitionParser::MULTIPLY.
Member Data Documentation
OP
antlr4::Token* definitionParser::ExpMulDivContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp