irafhy: locationsParser::PolytopeContext Class Reference
locationsParser::PolytopeContext Class Reference
#include <locationsParser.h>
Public Member Functions
PolytopeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * KEY_POLYTOPE ()
HpolytopeContext * hpolytope ()
VpolytopeContext * vpolytope ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
PolytopeContext()
locationsParser::PolytopeContext::PolytopeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any locationsParser::PolytopeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void locationsParser::PolytopeContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterPolytope().
Referenced by locationsParser::polytope().
exitRule()
void locationsParser::PolytopeContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitPolytope().
Referenced by locationsParser::polytope().
getRuleIndex()
size_t locationsParser::PolytopeContext::getRuleIndex () const override virtual
References locationsParser::RulePolytope.
hpolytope()
locationsParser::HpolytopeContext * locationsParser::PolytopeContext::hpolytope ()
Referenced by locationsParser::polytope().
KEY_POLYTOPE()
tree::TerminalNode * locationsParser::PolytopeContext::KEY_POLYTOPE ()
References locationsParser::KEY_POLYTOPE.
vpolytope()
locationsParser::VpolytopeContext * locationsParser::PolytopeContext::vpolytope ()
Referenced by locationsParser::polytope().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp