irafhy: transitionsParser::ExpMulDivContext Class Reference
transitionsParser::ExpMulDivContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ExpMulDivContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * MULTIPLY ()
antlr4::tree::TerminalNode * DIVIDE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from transitionsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpMulDivContext()
transitionsParser::ExpMulDivContext::ExpMulDivContext (ExpressionContext * ctx)
References transitionsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::ExpMulDivContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIVIDE()
tree::TerminalNode * transitionsParser::ExpMulDivContext::DIVIDE ()
References transitionsParser::DIVIDE.
enterRule()
void transitionsParser::ExpMulDivContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterExpMulDiv().
exitRule()
void transitionsParser::ExpMulDivContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitExpMulDiv().
expression() [1/2]
std::vector< transitionsParser::ExpressionContext * > transitionsParser::ExpMulDivContext::expression ()
expression() [2/2]
transitionsParser::ExpressionContext * transitionsParser::ExpMulDivContext::expression (size_t i)
MULTIPLY()
tree::TerminalNode * transitionsParser::ExpMulDivContext::MULTIPLY ()
References transitionsParser::MULTIPLY.
Member Data Documentation
OP
antlr4::Token* transitionsParser::ExpMulDivContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp