irafhy: settingsParser::FormulaContext Class Reference
settingsParser::FormulaContext Class Reference
#include <settingsParser.h>
Public Member Functions
FormulaContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * VARIABLE ()
antlr4::tree::TerminalNode * ASSIGN ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * DERIVATIVE ()
IntervalContext * interval ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FormulaContext()
settingsParser::FormulaContext::FormulaContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::FormulaContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ASSIGN()
tree::TerminalNode * settingsParser::FormulaContext::ASSIGN ()
References settingsParser::ASSIGN.
DERIVATIVE()
tree::TerminalNode * settingsParser::FormulaContext::DERIVATIVE ()
References settingsParser::DERIVATIVE.
enterRule()
void settingsParser::FormulaContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterFormula().
Referenced by settingsParser::formula().
exitRule()
void settingsParser::FormulaContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitFormula().
Referenced by settingsParser::formula().
expression()
settingsParser::ExpressionContext * settingsParser::FormulaContext::expression ()
Referenced by settingsParser::formula().
getRuleIndex()
size_t settingsParser::FormulaContext::getRuleIndex () const override virtual
References settingsParser::RuleFormula.
interval()
settingsParser::IntervalContext * settingsParser::FormulaContext::interval ()
Referenced by settingsParser::formula().
VARIABLE()
tree::TerminalNode * settingsParser::FormulaContext::VARIABLE ()
References settingsParser::VARIABLE.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp