irafhy: definitionParser::ExpBraContext Class Reference
definitionParser::ExpBraContext Class Reference
#include <definitionParser.h>
Public Member Functions
ExpBraContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
ExpBraContext()
definitionParser::ExpBraContext::ExpBraContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::ExpBraContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::ExpBraContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterExpBra().
exitRule()
void definitionParser::ExpBraContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitExpBra().
expression()
definitionParser::ExpressionContext * definitionParser::ExpBraContext::expression ()
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::ExpBraContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::ExpBraContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp