irafhy: definitionParser::LnExpContext Class Reference
definitionParser::LnExpContext Class Reference
#include <definitionParser.h>
Public Member Functions
LnExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_LN_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from definitionParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
LnExpContext()
definitionParser::LnExpContext::LnExpContext (ExpressionContext * ctx)
References definitionParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any definitionParser::LnExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::LnExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterLnExp().
exitRule()
void definitionParser::LnExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitLnExp().
expression()
definitionParser::ExpressionContext * definitionParser::LnExpContext::expression ()
KEY_LN_FUNCTION()
tree::TerminalNode * definitionParser::LnExpContext::KEY_LN_FUNCTION ()
References definitionParser::KEY_LN_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * definitionParser::LnExpContext::LEFTROUNDBRACKET ()
References definitionParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * definitionParser::LnExpContext::RIGHTROUNDBRACKET ()
References definitionParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp