irafhy: irafhy::viewer Class Reference
irafhy::viewer Class Reference
#include <viewer.h>
Static Public Member Functions
static void show (const std::vector< IntervalHull > &intervalHulls={}, const std::vector< std::vector< Point >> &points={}, const std::vector< capd::interval > &time={}, const std::vector< int > &dimension={}, VIEW_TYPE viewType=VIEW_TYPE::PLANE)
show the given interval hulls, point set using the wrapped viewer
static void show (const std::vector< Condition > &conditions={}, const std::vector< std::vector< Point >> &points={}, const std::vector< capd::interval > &time={}, const std::vector< int > &dimension={}, VIEW_TYPE viewType=VIEW_TYPE::PLANE)
show the given conditions, point set using wrapped viewer
Static Private Member Functions
static IntervalHullStruct intervalHullMatrix (const IntervalHull &intervalHulls, const capd::interval &time, const std::vector< int > &dimension)
construct the matrices which define the given inetrval hull
static Eigen::MatrixXd pointMatrix (const std::vector< Point > &point, const capd::interval &time, const std::vector< int > &dimension)
construct the coordinate matix of given point set
static void drawAxes (igl::opengl::glfw::Viewer &viewer, const std::vector< capd::interval > &ranges, const std::vector< std::string > &vars)
draw the axes and adaptive markers
Member Function Documentation
drawAxes()
void irafhy::viewer::drawAxes (igl::opengl::glfw::Viewer & viewer, const std::vector< capd::interval > & ranges, const std::vector< std::string > & vars) static private
draw the axes and adaptive markers
Parameters
viewer viewer which shall show the axes
ranges ranges of each showing dimension
vars related variable of each dimension
Referenced by show().
intervalHullMatrix()
IntervalHullStruct irafhy::viewer::intervalHullMatrix (const IntervalHull & intervalHulls, const capd::interval & time, const std::vector< int > & dimension) static private
construct the matrices which define the given inetrval hull
Parameters
intervalHulls given inetrval hull
time related time in interval form
dimension the dimension of the space which the given interval hull in
Returns
resulting interval hull struct
References irafhy::IntervalHull::empty().
Referenced by show().
pointMatrix()
Eigen::MatrixXd irafhy::viewer::pointMatrix (const std::vector< Point > & point, const capd::interval & time, const std::vector< int > & dimension) static private
construct the coordinate matix of given point set
Parameters
point given point set
time related time in interval form
dimension the dimension of the sapce which the given interval hull in
Returns
resulting coordinate matrix
Referenced by show().
show() [1/2]
void irafhy::viewer::show (const std::vector< IntervalHull > & intervalHulls = {}, const std::vector< std::vector< Point >> & points = {}, const std::vector< capd::interval > & time = {}, const std::vector< int > & dimension = {}, VIEW_TYPE viewType = VIEW_TYPE::PLANE) static
show the given interval hulls, point set using the wrapped viewer
Parameters
intervalHulls given interval hulls
points given point set
time time sequence
dimension dimensions specify the values shall be showed
viewType style of interval hulls' showing
References irafhy::IntervalHullStruct::_E, irafhy::IntervalHullStruct::_F, irafhy::IntervalHullStruct::_V, drawAxes(), intervalHullMatrix(), irafhy::LINE, irafhy::PLANE, irafhy::POINT, and pointMatrix().
show() [2/2]
void irafhy::viewer::show (const std::vector< Condition > & conditions = {}, const std::vector< std::vector< Point >> & points = {}, const std::vector< capd::interval > & time = {}, const std::vector< int > & dimension = {}, VIEW_TYPE viewType = VIEW_TYPE::PLANE) static
show the given conditions, point set using wrapped viewer
Parameters
conditions given condition
points given point set
time time sequence
dimension dimensions specify the values shall be showed
viewType style of conditions' showing
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/viewer.h
/home/jianqiang/CLionProjects/irafhy/src/utility/viewer.cpp