irafhy: transitionsParser::ConstraintContext Class Reference
transitionsParser::ConstraintContext Class Reference
#include <transitionsParser.h>
Public Member Functions
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EQUAL ()
antlr4::tree::TerminalNode * UNEQUAL ()
antlr4::tree::TerminalNode * GEQ ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * LSS ()
antlr4::tree::TerminalNode * GTR ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * RELATION = nullptr
Constructor & Destructor Documentation
ConstraintContext()
transitionsParser::ConstraintContext::ConstraintContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any transitionsParser::ConstraintContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void transitionsParser::ConstraintContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::enterConstraint().
Referenced by transitionsParser::constraint().
EQUAL()
tree::TerminalNode * transitionsParser::ConstraintContext::EQUAL ()
References transitionsParser::EQUAL.
exitRule()
void transitionsParser::ConstraintContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References transitionsListener::exitConstraint().
Referenced by transitionsParser::constraint().
expression() [1/2]
std::vector< transitionsParser::ExpressionContext * > transitionsParser::ConstraintContext::expression ()
Referenced by transitionsParser::constraint().
expression() [2/2]
transitionsParser::ExpressionContext * transitionsParser::ConstraintContext::expression (size_t i)
GEQ()
tree::TerminalNode * transitionsParser::ConstraintContext::GEQ ()
References transitionsParser::GEQ.
getRuleIndex()
size_t transitionsParser::ConstraintContext::getRuleIndex () const override virtual
References transitionsParser::RuleConstraint.
GTR()
tree::TerminalNode * transitionsParser::ConstraintContext::GTR ()
References transitionsParser::GTR.
LEQ()
tree::TerminalNode * transitionsParser::ConstraintContext::LEQ ()
References transitionsParser::LEQ.
LSS()
tree::TerminalNode * transitionsParser::ConstraintContext::LSS ()
References transitionsParser::LSS.
UNEQUAL()
tree::TerminalNode * transitionsParser::ConstraintContext::UNEQUAL ()
References transitionsParser::UNEQUAL.
Member Data Documentation
RELATION
antlr4::Token* transitionsParser::ConstraintContext::RELATION = nullptr
Referenced by transitionsParser::constraint().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/transitionsParser.cpp