irafhy: locationsParser::ExpMulDivContext Class Reference
locationsParser::ExpMulDivContext Class Reference
#include <locationsParser.h>
Public Member Functions
ExpMulDivContext (ExpressionContext *ctx)
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * MULTIPLY ()
antlr4::tree::TerminalNode * DIVIDE ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from locationsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Public Attributes
antlr4::Token * OP = nullptr
Constructor & Destructor Documentation
ExpMulDivContext()
locationsParser::ExpMulDivContext::ExpMulDivContext (ExpressionContext * ctx)
References locationsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any locationsParser::ExpMulDivContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIVIDE()
tree::TerminalNode * locationsParser::ExpMulDivContext::DIVIDE ()
References locationsParser::DIVIDE.
enterRule()
void locationsParser::ExpMulDivContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::enterExpMulDiv().
exitRule()
void locationsParser::ExpMulDivContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References locationsListener::exitExpMulDiv().
expression() [1/2]
std::vector< locationsParser::ExpressionContext * > locationsParser::ExpMulDivContext::expression ()
expression() [2/2]
locationsParser::ExpressionContext * locationsParser::ExpMulDivContext::expression (size_t i)
MULTIPLY()
tree::TerminalNode * locationsParser::ExpMulDivContext::MULTIPLY ()
References locationsParser::MULTIPLY.
Member Data Documentation
OP
antlr4::Token* locationsParser::ExpMulDivContext::OP = nullptr
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/locationsParser.cpp