irafhy: irafhy::Settings Class Reference
irafhy::Settings Class Reference
#include <settings.h>
Public Member Functions
virtual ~Settings ()=default
destructor
virtual void setDuration (const Time &duration)
set the duration of the simulation with given information
virtual void setStep (double step)
set the step size of the simulation
virtual void setMaxJump (long int maxJump)
set the max jumps
virtual void setPlot (bool plot)
set the plotting setting
virtual void setPrint (bool print)
set the print setting
virtual void setAnalysis (ANALYSIS analysis)
set the analysis type
virtual void setGeometry (GEOMETRY geometry)
set the geometry object type used to hold states during computation
virtual void setStartModelID (const std::string &startModelID)
set the id of the start mode
virtual void setInitCondition (const Condition &initCondition)
set the initial condition of the start mode with given condition
virtual Time duration () const
get the duration of the simulation
virtual double step () const
get the step size of the simulation
virtual long int maxJump () const
get the max allowed jumps for the duration
virtual bool plot () const
get the plotting setting of the simulation
virtual bool print () const
get the print setting of the simulation
virtual ANALYSIS analysis () const
get the analysis type
virtual GEOMETRY geometry () const
get the type of geometry object used to hold states
virtual std::string startModelID () const
get the id of the start mode
virtual Condition initCondition () const
get the initial condition of the start mode
virtual void help () const
help function
Protected Attributes
Time duration_ = Time(0.0, 0.0)
duration of the simulation
double step_ = -1.0
time step size of the iteration
long int maxJump_ = 1
max allowed jumps for the specified duration
bool plot_ = false
plot the results or not
bool print_ = false
print the results into files or not
ANALYSIS analysis_ = ANALYSIS::FORWARD
forward or backward
std::string startModelID_ = std::string()
id of the start mode
Condition initCondition_ = Condition::Empty()
initial condition of the start mode
GEOMETRY geometry_ = GEOMETRY::INTERVAL_HULL
geometry objects using to hold the states
Friends
std::ostream & operator<< (std::ostream &out, const Settings &rhs)
out the right hand side settings to standard out stream
Constructor & Destructor Documentation
~Settings()
virtual irafhy::Settings::~Settings () virtual default
destructor
Member Function Documentation
analysis()
ANALYSIS irafhy::Settings::analysis () const virtual
get the analysis type
Returns
type of the analysis, forward or backward
References analysis_.
Referenced by setAnalysis().
duration()
Time irafhy::Settings::duration () const virtual
get the duration of the simulation
Returns
the duration of the simulation
References duration_, and irafhy::Time::range().
Referenced by setDuration().
geometry()
GEOMETRY irafhy::Settings::geometry () const virtual
get the type of geometry object used to hold states
Returns
type of the geometry object, interval hull or polytope and so on
References geometry_.
Referenced by setGeometry().
help()
void irafhy::Settings::help () const virtual
help function
initCondition()
Condition irafhy::Settings::initCondition () const virtual
get the initial condition of the start mode
Returns
initial condition of the simulation
References irafhy::Condition::empty(), and initCondition_.
Referenced by setInitCondition().
maxJump()
long int irafhy::Settings::maxJump () const virtual
get the max allowed jumps for the duration
Returns
the max allowed jumps
References maxJump_.
Referenced by setMaxJump().
plot()
bool irafhy::Settings::plot () const virtual
get the plotting setting of the simulation
Returns
TRUE if allow to plot all results
References plot_.
Referenced by setPlot().
print()
bool irafhy::Settings::print () const virtual
get the print setting of the simulation
Returns
TRUE if allow to print all results into files
References print_.
Referenced by setPrint().
setAnalysis()
void irafhy::Settings::setAnalysis (ANALYSIS analysis) virtual
set the analysis type
Parameters
analysis given setting about analysis
References analysis(), and analysis_.
setDuration()
void irafhy::Settings::setDuration (const Time & duration) virtual
set the duration of the simulation with given information
Parameters
duration given duration setting
References duration(), duration_, and irafhy::Time::range().
Referenced by irafhy::SettingsVisitor::visitSetting().
setGeometry()
void irafhy::Settings::setGeometry (irafhy::GEOMETRY geometry) virtual
set the geometry object type used to hold states during computation
Parameters
geometry given geometry object setting
References geometry(), and geometry_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setInitCondition()
void irafhy::Settings::setInitCondition (const Condition & initCondition) virtual
set the initial condition of the start mode with given condition
Parameters
initCondition given initial condition
References irafhy::Condition::empty(), initCondition(), and initCondition_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setMaxJump()
void irafhy::Settings::setMaxJump (long int maxJump) virtual
set the max jumps
Parameters
maxJump given max jumps setting
References maxJump(), and maxJump_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setPlot()
void irafhy::Settings::setPlot (bool plot) virtual
set the plotting setting
Parameters
plot given plotting setting
References plot(), and plot_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setPrint()
void irafhy::Settings::setPrint (bool print) virtual
set the print setting
Parameters
print given print setting
References print(), and print_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setStartModelID()
void irafhy::Settings::setStartModelID (const std::string & startModelID) virtual
set the id of the start mode
Parameters
startModelID given start mode
References startModelID(), and startModelID_.
Referenced by irafhy::SettingsVisitor::visitSetting().
setStep()
void irafhy::Settings::setStep (double step) virtual
set the step size of the simulation
Parameters
step given step size setting
References step(), and step_.
Referenced by irafhy::SettingsVisitor::visitSetting().
startModelID()
std::string irafhy::Settings::startModelID () const virtual
get the id of the start mode
Returns
id of the start mode
References startModelID_.
Referenced by setStartModelID().
step()
double irafhy::Settings::step () const virtual
get the step size of the simulation
Returns
step size
References step_.
Referenced by setStep().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Settings & rhs) friend
out the right hand side settings to standard out stream
Parameters
out given out stream
rhs right hand side settings
Returns
resulting out stream
Member Data Documentation
analysis_
ANALYSIS irafhy::Settings::analysis_ = ANALYSIS::FORWARD protected
forward or backward
Referenced by analysis(), irafhy::operator<<(), and setAnalysis().
duration_
Time irafhy::Settings::duration_ = Time(0.0, 0.0) protected
duration of the simulation
Referenced by duration(), irafhy::operator<<(), and setDuration().
geometry_
GEOMETRY irafhy::Settings::geometry_ = GEOMETRY::INTERVAL_HULL protected
geometry objects using to hold the states
Referenced by geometry(), and setGeometry().
initCondition_
Condition irafhy::Settings::initCondition_ = Condition::Empty() protected
initial condition of the start mode
Referenced by initCondition(), irafhy::operator<<(), and setInitCondition().
maxJump_
long int irafhy::Settings::maxJump_ = 1 protected
max allowed jumps for the specified duration
Referenced by maxJump(), irafhy::operator<<(), and setMaxJump().
plot_
bool irafhy::Settings::plot_ = false protected
plot the results or not
Referenced by irafhy::operator<<(), plot(), and setPlot().
print_
bool irafhy::Settings::print_ = false protected
print the results into files or not
Referenced by irafhy::operator<<(), print(), and setPrint().
startModelID_
std::string irafhy::Settings::startModelID_ = std::string() protected
id of the start mode
Referenced by irafhy::operator<<(), setStartModelID(), and startModelID().
step_
double irafhy::Settings::step_ = -1.0 protected
time step size of the iteration
Referenced by irafhy::operator<<(), setStep(), and step().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/settings.h
/home/jianqiang/CLionProjects/irafhy/src/settings.cpp