irafhy: settingsParser::SqrExpContext Class Reference
settingsParser::SqrExpContext Class Reference
#include <settingsParser.h>
Public Member Functions
SqrExpContext (ExpressionContext *ctx)
antlr4::tree::TerminalNode * KEY_SQR_FUNCTION ()
antlr4::tree::TerminalNode * LEFTROUNDBRACKET ()
ExpressionContext * expression ()
antlr4::tree::TerminalNode * RIGHTROUNDBRACKET ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Member Functions inherited from settingsParser::ExpressionContext
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
ExpressionContext ()=default
void copyFrom (ExpressionContext *context)
virtual size_t getRuleIndex () const override
Constructor & Destructor Documentation
SqrExpContext()
settingsParser::SqrExpContext::SqrExpContext (ExpressionContext * ctx)
References settingsParser::ExpressionContext::copyFrom().
Member Function Documentation
accept()
antlrcpp::Any settingsParser::SqrExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::SqrExpContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterSqrExp().
exitRule()
void settingsParser::SqrExpContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitSqrExp().
expression()
settingsParser::ExpressionContext * settingsParser::SqrExpContext::expression ()
KEY_SQR_FUNCTION()
tree::TerminalNode * settingsParser::SqrExpContext::KEY_SQR_FUNCTION ()
References settingsParser::KEY_SQR_FUNCTION.
LEFTROUNDBRACKET()
tree::TerminalNode * settingsParser::SqrExpContext::LEFTROUNDBRACKET ()
References settingsParser::LEFTROUNDBRACKET.
RIGHTROUNDBRACKET()
tree::TerminalNode * settingsParser::SqrExpContext::RIGHTROUNDBRACKET ()
References settingsParser::RIGHTROUNDBRACKET.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp