irafhy: definitionParser::SystemContext Class Reference
definitionParser::SystemContext Class Reference
#include <definitionParser.h>
Public Member Functions
SystemContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FormulaContext * > formula ()
FormulaContext * formula (size_t i)
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
SystemContext()
definitionParser::SystemContext::SystemContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any definitionParser::SystemContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void definitionParser::SystemContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::enterSystem().
Referenced by definitionParser::system().
exitRule()
void definitionParser::SystemContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References definitionListener::exitSystem().
Referenced by definitionParser::system().
formula() [1/2]
std::vector< definitionParser::FormulaContext * > definitionParser::SystemContext::formula ()
Referenced by definitionParser::system().
formula() [2/2]
definitionParser::FormulaContext * definitionParser::SystemContext::formula (size_t i)
getRuleIndex()
size_t definitionParser::SystemContext::getRuleIndex () const override virtual
References definitionParser::RuleSystem.
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/definitionParser.cpp