irafhy: settingsParser::ConstraintContext Class Reference
settingsParser::ConstraintContext Class Reference
#include <settingsParser.h>
Public Member Functions
ConstraintContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
antlr4::tree::TerminalNode * EQUAL ()
antlr4::tree::TerminalNode * UNEQUAL ()
antlr4::tree::TerminalNode * GEQ ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * LSS ()
antlr4::tree::TerminalNode * GTR ()
virtual void enterRule (antlr4::tree::ParseTreeListener *listener) override
virtual void exitRule (antlr4::tree::ParseTreeListener *listener) override
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Public Attributes
antlr4::Token * RELATION = nullptr
Constructor & Destructor Documentation
ConstraintContext()
settingsParser::ConstraintContext::ConstraintContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any settingsParser::ConstraintContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
enterRule()
void settingsParser::ConstraintContext::enterRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::enterConstraint().
Referenced by settingsParser::constraint().
EQUAL()
tree::TerminalNode * settingsParser::ConstraintContext::EQUAL ()
References settingsParser::EQUAL.
exitRule()
void settingsParser::ConstraintContext::exitRule (antlr4::tree::ParseTreeListener * listener) override virtual
References settingsListener::exitConstraint().
Referenced by settingsParser::constraint().
expression() [1/2]
std::vector< settingsParser::ExpressionContext * > settingsParser::ConstraintContext::expression ()
Referenced by settingsParser::constraint().
expression() [2/2]
settingsParser::ExpressionContext * settingsParser::ConstraintContext::expression (size_t i)
GEQ()
tree::TerminalNode * settingsParser::ConstraintContext::GEQ ()
References settingsParser::GEQ.
getRuleIndex()
size_t settingsParser::ConstraintContext::getRuleIndex () const override virtual
References settingsParser::RuleConstraint.
GTR()
tree::TerminalNode * settingsParser::ConstraintContext::GTR ()
References settingsParser::GTR.
LEQ()
tree::TerminalNode * settingsParser::ConstraintContext::LEQ ()
References settingsParser::LEQ.
LSS()
tree::TerminalNode * settingsParser::ConstraintContext::LSS ()
References settingsParser::LSS.
UNEQUAL()
tree::TerminalNode * settingsParser::ConstraintContext::UNEQUAL ()
References settingsParser::UNEQUAL.
Member Data Documentation
RELATION
antlr4::Token* settingsParser::ConstraintContext::RELATION = nullptr
Referenced by settingsParser::constraint().
The documentation for this class was generated from the following files:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.h
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/parser/grammar/antlr4-runtime-cpp/settingsParser.cpp