irafhy: matplotlibcpp Namespace Reference
matplotlibcpp Namespace Reference
Namespaces
detail
internal
Classes
class Plot
struct select_npy_type
struct select_npy_type< bool >
struct select_npy_type< double >
struct select_npy_type< float >
struct select_npy_type< int16_t >
struct select_npy_type< int32_t >
struct select_npy_type< int64_t >
struct select_npy_type< int8_t >
struct select_npy_type< uint16_t >
struct select_npy_type< uint32_t >
struct select_npy_type< uint64_t >
struct select_npy_type< uint8_t >
Functions
void backend (const std::string &name)
bool annotate (std::string annotation, double x, double y)
template<typename Numeric >
PyObject * get_array (const std::vector< Numeric > &v)
template<typename Numeric >
PyObject * get_2darray (const std::vector<::std::vector< Numeric >> &v)
template<typename Numeric >
bool plot (const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
void plot_surface (const std::vector<::std::vector< Numeric >> &x, const std::vector<::std::vector< Numeric >> &y, const std::vector<::std::vector< Numeric >> &z, const std::map< std::string, std::string > &keywords=std::map< std::string, std::string >())
template<typename Numeric >
bool stem (const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
bool fill (const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
bool fill_between (const std::vector< Numeric > &x, const std::vector< Numeric > &y1, const std::vector< Numeric > &y2, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
bool hist (const std::vector< Numeric > &y, long bins=10, std::string color="b", double alpha=1.0, bool cumulative=false)
void imshow (const unsigned char *ptr, const int rows, const int columns, const int colors, const std::map< std::string, std::string > &keywords={})
void imshow (const float *ptr, const int rows, const int columns, const int colors, const std::map< std::string, std::string > &keywords={})
template<typename NumericX , typename NumericY >
bool scatter (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const double s=1.0)
template<typename Numeric >
bool bar (const std::vector< Numeric > &x, const std::vector< Numeric > &y, std::string ec="black", std::string ls="-", double lw=1.0, const std::map< std::string, std::string > &keywords={})
template<typename Numeric >
bool bar (const std::vector< Numeric > &y, std::string ec="black", std::string ls="-", double lw=1.0, const std::map< std::string, std::string > &keywords={})
bool subplots_adjust (const std::map< std::string, double > &keywords={})
template<typename Numeric >
bool named_hist (std::string label, const std::vector< Numeric > &y, long bins=10, std::string color="b", double alpha=1.0)
template<typename NumericX , typename NumericY >
bool plot (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::string &s="")
template<typename NumericX , typename NumericY , typename NumericU , typename NumericW >
bool quiver (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::vector< NumericU > &u, const std::vector< NumericW > &w, const std::map< std::string, std::string > &keywords={})
template<typename NumericX , typename NumericY >
bool stem (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::string &s="")
template<typename NumericX , typename NumericY >
bool semilogx (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::string &s="")
template<typename NumericX , typename NumericY >
bool semilogy (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::string &s="")
template<typename NumericX , typename NumericY >
bool loglog (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::string &s="")
template<typename NumericX , typename NumericY >
bool errorbar (const std::vector< NumericX > &x, const std::vector< NumericY > &y, const std::vector< NumericX > &yerr, const std::map< std::string, std::string > &keywords={})
template<typename Numeric >
bool named_plot (const std::string &name, const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool named_plot (const std::string &name, const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool named_semilogx (const std::string &name, const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool named_semilogy (const std::string &name, const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool named_loglog (const std::string &name, const std::vector< Numeric > &x, const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool plot (const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
bool plot (const std::vector< Numeric > &y, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
bool stem (const std::vector< Numeric > &y, const std::string &format="")
template<typename Numeric >
void text (Numeric x, Numeric y, const std::string &s="")
long figure (long number=-1)
bool fignum_exists (long number)
void figure_size (size_t w, size_t h)
void legend ()
template<typename Numeric >
void ylim (Numeric left, Numeric right)
template<typename Numeric >
void xlim (Numeric left, Numeric right)
double * xlim ()
double * ylim ()
template<typename Numeric >
void xticks (const std::vector< Numeric > &ticks, const std::vector< std::string > &labels={}, const std::map< std::string, std::string > &keywords={})
template<typename Numeric >
void xticks (const std::vector< Numeric > &ticks, const std::map< std::string, std::string > &keywords)
template<typename Numeric >
void yticks (const std::vector< Numeric > &ticks, const std::vector< std::string > &labels={}, const std::map< std::string, std::string > &keywords={})
template<typename Numeric >
void yticks (const std::vector< Numeric > &ticks, const std::map< std::string, std::string > &keywords)
void subplot (long nrows, long ncols, long plot_number)
void title (const std::string &titlestr, const std::map< std::string, std::string > &keywords={})
void suptitle (const std::string &suptitlestr, const std::map< std::string, std::string > &keywords={})
void axis (const std::string &axisstr)
void xlabel (const std::string &str, const std::map< std::string, std::string > &keywords={})
void ylabel (const std::string &str, const std::map< std::string, std::string > &keywords={})
void grid (bool flag)
void show (const bool block=true)
void close ()
void xkcd ()
void draw ()
template<typename Numeric >
void pause (Numeric interval)
void save (const std::string &filename)
void clf ()
void ion ()
std::vector< std::array< double, 2 > > ginput (const int numClicks=1, const std::map< std::string, std::string > &keywords={})
void tight_layout ()
template<typename... Args>
bool plot ()
template<typename A , typename B , typename... Args>
bool plot (const A &a, const B &b, const std::string &format, Args... args)
bool plot (const std::vector< double > &x, const std::vector< double > &y, const std::string &format="")
bool plot (const std::vector< double > &y, const std::string &format="")
bool plot (const std::vector< double > &x, const std::vector< double > &y, const std::map< std::string, std::string > &keywords)
Function Documentation
annotate()
bool matplotlibcpp::annotate (std::string annotation, double x, double y) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_annotate.
axis()
void matplotlibcpp::axis (const std::string & axisstr) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_axis.
Referenced by irafhy::Plotter::plot(), and plot_surface().
backend()
void matplotlibcpp::backend (const std::string & name) inline
bar() [1/2]
template<typename Numeric > bool matplotlibcpp::bar (const std::vector< Numeric > & x, const std::vector< Numeric > & y, std::string ec = "black", std::string ls = "-", double lw = 1.0, const std::map< std::string, std::string > & keywords = {})
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_bar.
Referenced by bar().
bar() [2/2]
template<typename Numeric > bool matplotlibcpp::bar (const std::vector< Numeric > & y, std::string ec = "black", std::string ls = "-", double lw = 1.0, const std::map< std::string, std::string > & keywords = {})
References bar().
clf()
void matplotlibcpp::clf () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_clf.
close()
void matplotlibcpp::close () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_close.
draw()
void matplotlibcpp::draw () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_draw.
errorbar()
template<typename NumericX , typename NumericY > bool matplotlibcpp::errorbar (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::vector< NumericX > & yerr, const std::map< std::string, std::string > & keywords = {})
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_errorbar.
fignum_exists()
bool matplotlibcpp::fignum_exists (long number) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_fignum_exists.
figure()
long matplotlibcpp::figure (long number = -1) inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_figure.
figure_size()
void matplotlibcpp::figure_size (size_t w, size_t h) inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_figure.
Referenced by irafhy::Plotter::plot().
fill()
template<typename Numeric > bool matplotlibcpp::fill (const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::map< std::string, std::string > & keywords)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_fill.
Referenced by irafhy::CSPSolver::exactBoundarySolve(), irafhy::CSPSolver::extremeVerticesEnumeration(), and irafhy::Polytope::verticesEnumerationIntersect().
fill_between()
template<typename Numeric > bool matplotlibcpp::fill_between (const std::vector< Numeric > & x, const std::vector< Numeric > & y1, const std::vector< Numeric > & y2, const std::map< std::string, std::string > & keywords)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_fill_between.
Referenced by irafhy::Plotter::plot().
get_2darray()
template<typename Numeric > PyObject* matplotlibcpp::get_2darray (const std::vector<::std::vector< Numeric >> & v)
References matplotlibcpp::detail::_interpreter::get(), and get_array().
Referenced by plot_surface().
get_array()
template<typename Numeric > PyObject* matplotlibcpp::get_array (const std::vector< Numeric > & v)
References matplotlibcpp::detail::_interpreter::get().
Referenced by bar(), errorbar(), fill(), fill_between(), get_2darray(), hist(), loglog(), named_hist(), named_loglog(), named_plot(), named_semilogx(), named_semilogy(), plot(), matplotlibcpp::Plot::Plot(), quiver(), scatter(), semilogx(), semilogy(), stem(), matplotlibcpp::Plot::update(), xticks(), and yticks().
ginput()
std::vector<std::array<double, 2> > matplotlibcpp::ginput (const int numClicks = 1, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_ginput.
grid()
void matplotlibcpp::grid (bool flag) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_grid.
hist()
template<typename Numeric > bool matplotlibcpp::hist (const std::vector< Numeric > & y, long bins = 10, std::string color = "b", double alpha = 1.0, bool cumulative = false)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_hist.
imshow() [1/2]
void matplotlibcpp::imshow (const unsigned char * ptr, const int rows, const int columns, const int colors, const std::map< std::string, std::string > & keywords = {})
References matplotlibcpp::internal::imshow().
Referenced by imshow().
imshow() [2/2]
void matplotlibcpp::imshow (const float * ptr, const int rows, const int columns, const int colors, const std::map< std::string, std::string > & keywords = {})
References matplotlibcpp::internal::imshow(), and imshow().
ion()
void matplotlibcpp::ion () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_ion.
legend()
void matplotlibcpp::legend () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_legend.
loglog()
template<typename NumericX , typename NumericY > bool matplotlibcpp::loglog (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_loglog.
named_hist()
template<typename Numeric > bool matplotlibcpp::named_hist (std::string label, const std::vector< Numeric > & y, long bins = 10, std::string color = "b", double alpha = 1.0)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_hist.
named_loglog()
template<typename Numeric > bool matplotlibcpp::named_loglog (const std::string & name, const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::string & format = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_loglog.
named_plot() [1/2]
template<typename Numeric > bool matplotlibcpp::named_plot (const std::string & name, const std::vector< Numeric > & y, const std::string & format = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_plot.
named_plot() [2/2]
template<typename Numeric > bool matplotlibcpp::named_plot (const std::string & name, const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::string & format = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_plot.
named_semilogx()
template<typename Numeric > bool matplotlibcpp::named_semilogx (const std::string & name, const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::string & format = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_semilogx.
named_semilogy()
template<typename Numeric > bool matplotlibcpp::named_semilogy (const std::string & name, const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::string & format = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_semilogy.
pause()
template<typename Numeric > void matplotlibcpp::pause (Numeric interval) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_pause.
plot() [1/9]
template<typename Numeric > bool matplotlibcpp::plot (const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::map< std::string, std::string > & keywords)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_plot.
Referenced by plot(), and irafhy::SettingsVisitor::visitSetting().
plot() [2/9]
template<typename NumericX , typename NumericY > bool matplotlibcpp::plot (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_plot.
plot() [3/9]
template<typename Numeric > bool matplotlibcpp::plot (const std::vector< Numeric > & y, const std::string & format = "")
References plot().
plot() [4/9]
template<typename Numeric > bool matplotlibcpp::plot (const std::vector< Numeric > & y, const std::map< std::string, std::string > & keywords)
References plot().
plot() [5/9]
template<typename... Args> bool matplotlibcpp::plot ()
plot() [6/9]
template<typename A , typename B , typename... Args> bool matplotlibcpp::plot (const A & a, const B & b, const std::string & format, Args... args)
References plot().
plot() [7/9]
bool matplotlibcpp::plot (const std::vector< double > & x, const std::vector< double > & y, const std::string & format = "") inline
plot() [8/9]
bool matplotlibcpp::plot (const std::vector< double > & y, const std::string & format = "") inline
plot() [9/9]
bool matplotlibcpp::plot (const std::vector< double > & x, const std::vector< double > & y, const std::map< std::string, std::string > & keywords) inline
plot_surface()
template<typename Numeric > void matplotlibcpp::plot_surface (const std::vector<::std::vector< Numeric >> & x, const std::vector<::std::vector< Numeric >> & y, const std::vector<::std::vector< Numeric >> & z, const std::map< std::string, std::string > & keywords = std::map<std::string, std::string>())
References axis(), matplotlibcpp::detail::_interpreter::get(), get_2darray(), matplotlibcpp::detail::_interpreter::s_python_colormap, matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_figure.
quiver()
template<typename NumericX , typename NumericY , typename NumericU , typename NumericW > bool matplotlibcpp::quiver (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::vector< NumericU > & u, const std::vector< NumericW > & w, const std::map< std::string, std::string > & keywords = {})
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_quiver.
save()
void matplotlibcpp::save (const std::string & filename) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_save.
scatter()
template<typename NumericX , typename NumericY > bool matplotlibcpp::scatter (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const double s = 1.0)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_scatter.
semilogx()
template<typename NumericX , typename NumericY > bool matplotlibcpp::semilogx (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_semilogx.
semilogy()
template<typename NumericX , typename NumericY > bool matplotlibcpp::semilogy (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_semilogy.
show()
void matplotlibcpp::show (const bool block = true) inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_show.
Referenced by irafhy::Plotter::plot().
stem() [1/3]
template<typename Numeric > bool matplotlibcpp::stem (const std::vector< Numeric > & x, const std::vector< Numeric > & y, const std::map< std::string, std::string > & keywords)
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_stem.
Referenced by stem().
stem() [2/3]
template<typename NumericX , typename NumericY > bool matplotlibcpp::stem (const std::vector< NumericX > & x, const std::vector< NumericY > & y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_stem.
stem() [3/3]
template<typename Numeric > bool matplotlibcpp::stem (const std::vector< Numeric > & y, const std::string & format = "")
References stem().
subplot()
void matplotlibcpp::subplot (long nrows, long ncols, long plot_number) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_subplot.
subplots_adjust()
bool matplotlibcpp::subplots_adjust (const std::map< std::string, double > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_subplots_adjust.
suptitle()
void matplotlibcpp::suptitle (const std::string & suptitlestr, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_suptitle.
text()
template<typename Numeric > void matplotlibcpp::text (Numeric x, Numeric y, const std::string & s = "")
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_text.
tight_layout()
void matplotlibcpp::tight_layout () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_tight_layout.
title()
void matplotlibcpp::title (const std::string & titlestr, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_title.
Referenced by irafhy::Plotter::plot().
xkcd()
void matplotlibcpp::xkcd () inline
References matplotlibcpp::detail::_interpreter::get(), matplotlibcpp::detail::_interpreter::s_python_empty_tuple, and matplotlibcpp::detail::_interpreter::s_python_function_xkcd.
xlabel()
void matplotlibcpp::xlabel (const std::string & str, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_xlabel.
Referenced by irafhy::Plotter::plot().
xlim() [1/2]
template<typename Numeric > void matplotlibcpp::xlim (Numeric left, Numeric right)
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_xlim.
Referenced by irafhy::Plotter::plot().
xlim() [2/2]
double* matplotlibcpp::xlim () inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_xlim.
xticks() [1/2]
template<typename Numeric > void matplotlibcpp::xticks (const std::vector< Numeric > & ticks, const std::vector< std::string > & labels = {}, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_xticks.
Referenced by xticks().
xticks() [2/2]
template<typename Numeric > void matplotlibcpp::xticks (const std::vector< Numeric > & ticks, const std::map< std::string, std::string > & keywords) inline
References xticks().
ylabel()
void matplotlibcpp::ylabel (const std::string & str, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_ylabel.
Referenced by irafhy::Plotter::plot().
ylim() [1/2]
template<typename Numeric > void matplotlibcpp::ylim (Numeric left, Numeric right)
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_ylim.
Referenced by irafhy::Plotter::plot().
ylim() [2/2]
double* matplotlibcpp::ylim () inline
References matplotlibcpp::detail::_interpreter::get(), and matplotlibcpp::detail::_interpreter::s_python_function_ylim.
yticks() [1/2]
template<typename Numeric > void matplotlibcpp::yticks (const std::vector< Numeric > & ticks, const std::vector< std::string > & labels = {}, const std::map< std::string, std::string > & keywords = {}) inline
References matplotlibcpp::detail::_interpreter::get(), get_array(), and matplotlibcpp::detail::_interpreter::s_python_function_yticks.
Referenced by yticks().
yticks() [2/2]
template<typename Numeric > void matplotlibcpp::yticks (const std::vector< Numeric > & ticks, const std::map< std::string, std::string > & keywords) inline
References yticks().