irafhy: irafhy Namespace Reference
irafhy Namespace Reference
Classes
class Analyser
class BinaryItem
class Condition
class Constant
class Constraint
class Constraints
class ConstraintsVisitor
struct convexConstraints
class ConvexHull
class CSPSolver
class DefinitionVisitor
struct entityVisitor
class Evaluation
class Formula
struct geoEntityVisitor
class Geometry
class GLPKWrapper
class HalfSpace
class HybridAutomaton
class HybridAutomatonParser
class HybridAutomatonVisitor
class IntervalHull
struct IntervalHullStruct
class Item
class ItemVisitor
class Jump
class Locations
class LocationsVisitor
class Model
class ODESolver
class Point
class Polytope
class Printer
class Settings
class SettingsParser
class SettingsVisitor
class State
class System
class SystemVisitor
struct Time
struct used to hold the duration information
class Transitions
class TransitionsVisitor
class UnaryItem
class UpdateFunction
class Variable
class Verifier
class viewer
Typedefs
using GeoEntity = boost::variant< IntervalHull, Polytope >
geometry entity which used for represent the interval hull or polytope and any other objects shall be supported in the future.
using Entity = boost::variant< Constant, Variable, UnaryItem, BinaryItem >
Enumerations
enum VIEW_TYPE { POINT, LINE, PLANE }
style of viewing geometry objects
enum UNARY {
OPPOSITE, SIN, ASIN, COS,
ACOS, TAN, ATAN, COT,
ACOT, LN, LOG, NEXP,
SINH, ASINH, COSH, ACOSH,
TANH, ATANH, COTH, ACOTH,
SQR, SQRT
}
supported unary math functions
enum BINARY {
PLUS, MINUS, MULTIPLY, DIVIDE,
POWER
}
supported binary math functions
enum ITEM_T { CONSTANT_T, VARIABLE_T, UNARY_T, BINARY_T }
type of the item assembling a formula
enum ANALYSIS { FORWARD, BACKWARD }
direction of the integration respect to the direction of vector filed
enum GEOMETRY { INTERVAL_HULL, POLYTOPE }
supported geometry object
enum LINEPROG_DIRECTION { MAX, MIN }
optimization direction of the linear programming
enum LINEPROG_SOLUTION {
UNDEFINED, FEASIBLE, INFEASIBLE, NO_FEASIBLE,
OPTIMAL, UNBOUNDED
}
status of the solution return by glpk
enum RELATION {
LESS_THAN, LESS_THAN_OR_EQUAL_TO, EQUAL_TO, UNEQUAL_TO,
GREATER_THAN_OR_EQUAL_TO, GREATER_THAN
}
relation between two expressions
enum CONSTRAINTS_SOLUTION { ALL_SATISFIED, PARTIAL_SATISFIED, ALL_UNSATISFIED }
flag which indicates the statue of the constraints system
Functions
std::ostream & operator<< (std::ostream &out, const Condition &rhs)
output the right hand side condition to the standard out stream
std::ostream & operator<< (std::ostream &out, const Constraint &rhs)
std::ostream & operator<< (std::ostream &out, const Constraints &rhs)
std::ostream & operator<< (std::ostream &out, const BinaryItem &rhs)
std::ostream & operator<< (std::ostream &out, const Constant &rhs)
std::ostream & operator<< (std::ostream &out, const UnaryItem &rhs)
std::ostream & operator<< (std::ostream &out, const Variable &rhs)
std::ostream & operator<< (std::ostream &out, const Formula &rhs)
std::ostream & operator<< (std::ostream &out, const Item &rhs)
std::ostream & operator<< (std::ostream &out, const System &rhs)
std::ostream & operator<< (std::ostream &out, const UpdateFunction &rhs)
out the right hand side update function to standard stream
std::ostream & operator<< (std::ostream &out, const HalfSpace &halfSpace)
out the right hand side half space to standard out stream
std::ostream & operator<< (std::ostream &out, const Point &point)
out the right hand side point to standard out stream
const Point operator+ (const Point &lhs, const Point &rhs)
binary addition operator
const Point operator+ (const Point &lhs, const Eigen::VectorXd &rhs)
binary addition operator
const Point operator+ (const Eigen::VectorXd &lhs, const Point &rhs)
binary addition operator
const Point operator- (const Point &lhs, const Point &rhs)
binary subtraction operator
const Point operator- (const Point &lhs, const Eigen::VectorXd &rhs)
binary subtraction operator
const Point operator- (const Eigen::VectorXd &lhs, const Point &rhs)
binary subtraction operator
const Point operator/ (const Point &lhs, double divisor)
binary division operator
const Point operator* (const Point &lhs, double factor)
binary multiplication operator
const Point operator* (double factor, const Point &rhs)
binary multiplication operator
std::ostream & operator<< (std::ostream &out, const IntervalHull &rhs)
out the right hand side interval hull to standard out stream
std::ostream & operator<< (std::ostream &out, const Polytope &rhs)
out the right hand side polytope to standard out stream
std::ostream & operator<< (std::ostream &out, const Settings &rhs)
template<typename Analyser , typename Verifier >
std::ostream & operator<< (std::ostream &out, const HybridAutomaton< Analyser, Verifier > &rhs)
out the given hybrid automaton to standard out stream
template<typename Analyser >
std::ostream & operator<< (std::ostream &out, const Locations< Analyser > &rhs)
out the right hand side locations object to standard stream
template<typename Analyser >
std::ostream & operator<< (std::ostream &out, const Model< Analyser > &rhs)
out the right hand side mode to standard out stream
template<typename Analyser >
std::ostream & operator<< (std::ostream &out, const Jump< Analyser > &rhs)
out the right hand side Jump object to standard out stream
template<typename Analyser >
std::ostream & operator<< (std::ostream &out, const Transitions< Analyser > &rhs)
out the right hand side transitions object to standard out stream
const HalfSpace operator- (const HalfSpace &halfSpace)
get a half space which has opposite normal
Typedef Documentation
Entity
using irafhy::Entity = typedef boost::variant<Constant, Variable, UnaryItem, BinaryItem>
GeoEntity
using irafhy::GeoEntity = typedef boost::variant<IntervalHull, Polytope>
geometry entity which used for represent the interval hull or polytope and any other objects shall be supported in the future.
Enumeration Type Documentation
ANALYSIS
enum irafhy::ANALYSIS
direction of the integration respect to the direction of vector filed
Enumerator
FORWARD
BACKWARD
BINARY
enum irafhy::BINARY
supported binary math functions
Enumerator
PLUS
MINUS
MULTIPLY
DIVIDE
POWER
CONSTRAINTS_SOLUTION
enum irafhy::CONSTRAINTS_SOLUTION
flag which indicates the statue of the constraints system
Enumerator
ALL_SATISFIED
PARTIAL_SATISFIED
ALL_UNSATISFIED
GEOMETRY
enum irafhy::GEOMETRY
supported geometry object
Enumerator
INTERVAL_HULL
POLYTOPE
ITEM_T
enum irafhy::ITEM_T
type of the item assembling a formula
Enumerator
CONSTANT_T
VARIABLE_T
UNARY_T
BINARY_T
LINEPROG_DIRECTION
enum irafhy::LINEPROG_DIRECTION
optimization direction of the linear programming
Enumerator
MAX
MIN
LINEPROG_SOLUTION
enum irafhy::LINEPROG_SOLUTION
status of the solution return by glpk
Enumerator
UNDEFINED
FEASIBLE
INFEASIBLE
NO_FEASIBLE
OPTIMAL
UNBOUNDED
RELATION
enum irafhy::RELATION
relation between two expressions
Enumerator
LESS_THAN
LESS_THAN_OR_EQUAL_TO
EQUAL_TO
UNEQUAL_TO
GREATER_THAN_OR_EQUAL_TO
GREATER_THAN
UNARY
enum irafhy::UNARY
supported unary math functions
Enumerator
OPPOSITE
SIN
ASIN
COS
ACOS
TAN
ATAN
COT
ACOT
LN
LOG
NEXP
SINH
ASINH
COSH
ACOSH
TANH
ATANH
COTH
ACOTH
SQR
SQRT
VIEW_TYPE
enum irafhy::VIEW_TYPE
style of viewing geometry objects
Enumerator
POINT
LINE
PLANE
Function Documentation
operator*() [1/2]
const Point irafhy::operator* (const Point & lhs, double factor)
binary multiplication operator
Parameters
lhs left hand side of the operator
factor right hand side of the operator as the factor
Returns
resulting point whose coordinate is the product of given point's coordinate and the factor
References irafhy::Point::coordinate(), and irafhy::Point::Point().
operator*() [2/2]
const Point irafhy::operator* (double factor, const Point & rhs)
binary multiplication operator
Parameters
factor left hand side of the operator as the factor
rhs right hand side of the operator
Returns
resulting point whose coordinate is the product of given factor and given point's coordinate
References irafhy::Point::coordinate(), and irafhy::Point::Point().
operator+() [1/3]
const Point irafhy::operator+ (const Point & lhs, const Point & rhs)
binary addition operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the summation of two given points' coordinates
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator+() [2/3]
const Point irafhy::operator+ (const Point & lhs, const Eigen::VectorXd & rhs)
binary addition operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the summation of given point's coordinate and the given coordinate
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator+() [3/3]
const Point irafhy::operator+ (const Eigen::VectorXd & lhs, const Point & rhs)
binary addition operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the summation of given coordinate and the given point's coordinate
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator-() [1/4]
const HalfSpace irafhy::operator- (const HalfSpace & halfSpace)
get a half space which has opposite normal
Parameters
halfSpace given half space
Returns
resulting half space
operator-() [2/4]
const Point irafhy::operator- (const Point & lhs, const Point & rhs)
binary subtraction operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the subtraction of given two points's coordinates
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator-() [3/4]
const Point irafhy::operator- (const Point & lhs, const Eigen::VectorXd & rhs)
binary subtraction operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the subtraction of the given point's coordinate and the given coordinate
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator-() [4/4]
const Point irafhy::operator- (const Eigen::VectorXd & lhs, const Point & rhs)
binary subtraction operator
Parameters
lhs left hand side of the operator
rhs right hand side of the operator
Returns
resulting point whose coordinate is the subtraction of the given coordinate and the given point's coordinate
References irafhy::Point::coordinate(), irafhy::Point::dimension(), and irafhy::Point::Point().
operator/()
const Point irafhy::operator/ (const Point & lhs, double divisor)
binary division operator
Parameters
lhs left hand side of the operator as dividend
divisor right hand side of the operator as divisor
Returns
resulting point whose coordinate is the quotient of the given point's coordinate and the divisor
References irafhy::Point::coordinate(), and irafhy::Point::Point().
operator<<() [1/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Constant & rhs)
Parameters
out given out stream
rhs given constant
Returns
resulting out stream
References irafhy::Constant::value_.
operator<<() [2/21]
std::ostream & irafhy::operator<< (std::ostream & out, const UpdateFunction & rhs)
out the right hand side update function to standard stream
Parameters
out given out stream
rhs given update function
Returns
resulting out stream
References irafhy::UpdateFunction::formula(), and irafhy::UpdateFunction::index().
operator<<() [3/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Constraints & rhs)
Parameters
out given out stream
rhs given right hand side constraints
Returns
resulting out stream
References irafhy::Constraints::inequalities_.
operator<<() [4/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Variable & rhs)
Parameters
out given out stream
rhs given variable
Returns
resulting out stream
References irafhy::Variable::index_.
operator<<() [5/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Formula & rhs)
Parameters
out given out stream
rhs given formula
Returns
resulting out stream
References irafhy::Formula::expression_, and irafhy::Formula::isReversed_.
operator<<() [6/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Constraint & rhs)
Parameters
out given out stream
rhs given constraint object
Returns
resulting out stream
References EQUAL_TO, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN, LESS_THAN_OR_EQUAL_TO, irafhy::Constraint::lhsExpression_, irafhy::Constraint::relation_, irafhy::Constraint::rhsExpression_, and UNEQUAL_TO.
operator<<() [7/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Item & rhs)
Parameters
out given out stream
rhs given item
Returns
resulting out stream
References BINARY_T, CONSTANT_T, irafhy::Item::entity_, UNARY_T, and VARIABLE_T.
operator<<() [8/21]
template<typename Analyser > std::ostream& irafhy::operator<< (std::ostream & out, const Locations< Analyser > & rhs)
out the right hand side locations object to standard stream
Template Parameters
Analyser module which specify the analyser of the hybrid automaton
Parameters
out the out stream
rhs given out stream
Returns
resulting out stream
operator<<() [9/21]
template<typename Analyser > std::ostream& irafhy::operator<< (std::ostream & out, const Transitions< Analyser > & rhs)
out the right hand side transitions object to standard out stream
Template Parameters
Analyser module which specify the analyser of the hybrid automaton
Parameters
out given out stream
rhs right hand side transitions object
Returns
resulting out stream
operator<<() [10/21]
std::ostream& irafhy::operator<< (std::ostream & out, const System & rhs)
Parameters
out given out stream
rhs given system
Returns
the resulting out stream
References irafhy::System::formulas_.
operator<<() [11/21]
std::ostream & irafhy::operator<< (std::ostream & out, const HalfSpace & halfSpace)
out the right hand side half space to standard out stream
Parameters
out given out stream
halfSpace right hand side half space
Returns
resulting out stream
References irafhy::HalfSpace::dimension(), irafhy::HalfSpace::normal(), and irafhy::HalfSpace::offset().
operator<<() [12/21]
std::ostream& irafhy::operator<< (std::ostream & out, const BinaryItem & rhs)
Parameters
out given out stream
rhs given binary item
Returns
resulting out stream
References DIVIDE, irafhy::BinaryItem::lhsOperand_, MINUS, MULTIPLY, irafhy::BinaryItem::operator_, PLUS, POWER, and irafhy::BinaryItem::rhsOperand_.
operator<<() [13/21]
std::ostream& irafhy::operator<< (std::ostream & out, const Settings & rhs)
Parameters
out given out stream
rhs right hand side settings
Returns
resulting out stream
References irafhy::Settings::analysis_, BACKWARD, irafhy::Settings::duration_, FORWARD, irafhy::Settings::initCondition_, irafhy::Settings::maxJump_, irafhy::Settings::plot_, irafhy::Settings::print_, irafhy::Settings::startModelID_, and irafhy::Settings::step_.
operator<<() [14/21]
template<typename Analyser > std::ostream& irafhy::operator<< (std::ostream & out, const Model< Analyser > & rhs)
out the right hand side mode to standard out stream
Template Parameters
Analyser module which specify the analyser of the mode
Parameters
out given out stream
rhs right hand side mode
Returns
resulting out stream
operator<<() [15/21]
template<typename Analyser > std::ostream& irafhy::operator<< (std::ostream & out, const Jump< Analyser > & rhs)
out the right hand side Jump object to standard out stream
Template Parameters
Analyser module which specify the analyser of the hybrid automaton
Parameters
out given out stream
rhs right hand side Jump object
Returns
resulting out stream
operator<<() [16/21]
std::ostream & irafhy::operator<< (std::ostream & out, const Point & point)
out the right hand side point to standard out stream
Parameters
out given out stream
point right hand side point
Returns
resulting out stream
References irafhy::Point::coordinate().
operator<<() [17/21]
template<typename Analyser , typename Verifier > std::ostream& irafhy::operator<< (std::ostream & out, const HybridAutomaton< Analyser, Verifier > & rhs)
out the given hybrid automaton to standard out stream
Template Parameters
Analyser module which specify the analyser of the given hybrid automaton
Verifier module which specify the verifier of the given hybrid automaton
Parameters
out given out stream
rhs right hand side hybrid automaton
Returns
resulting out stream
operator<<() [18/21]
std::ostream & irafhy::operator<< (std::ostream & out, const Condition & rhs)
output the right hand side condition to the standard out stream
Parameters
out the given out stream
rhs the given right hand side condition
Returns
the resulting out stream
References irafhy::Condition::entity(), INTERVAL_HULL, and POLYTOPE.
operator<<() [19/21]
std::ostream & irafhy::operator<< (std::ostream & out, const IntervalHull & rhs)
out the right hand side interval hull to standard out stream
Parameters
out given out stream
rhs right hand side interval hull
Returns
resulting out stream
References irafhy::IntervalHull::constraints(), and irafhy::IntervalHull::dimension().
operator<<() [20/21]
std::ostream& irafhy::operator<< (std::ostream & out, const UnaryItem & rhs)
Parameters
out given out stream
rhs given unary item
Returns
resulting out stream
References ACOS, ACOSH, ACOT, ACOTH, ASIN, ASINH, ATAN, ATANH, COS, COSH, COT, COTH, LN, LOG, NEXP, irafhy::UnaryItem::operand_, irafhy::UnaryItem::operator_, OPPOSITE, SIN, SINH, SQR, SQRT, TAN, and TANH.
operator<<() [21/21]
std::ostream & irafhy::operator<< (std::ostream & out, const Polytope & rhs)
out the right hand side polytope to standard out stream
Parameters
out given out stream
rhs right hand side polytope
Returns
resulting out stream
References irafhy::Polytope::dimension(), irafhy::Polytope::halfSpaceConstraints(), irafhy::Polytope::pointConstraints(), and irafhy::Polytope::volume().