irafhy: /home/jianqiang/CLionProjects/irafhy/test/representationTest/geometricTest/basicTest/pointTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <Eigen/Core>
#include <random>
#include <vector>
#include <irafhy/representation/geometric/basic/point.h>
Classes
class PointTest
Functions
TEST_F (PointTest, constructor)
TEST_F (PointTest, memberFunctions)
TEST_F (PointTest, operations)
TEST_F (PointTest, comparisons)
TEST_F (PointTest, outStream)
Function Documentation
TEST_F() [1/5]
TEST_F (PointTest , constructor)
References PointTest::coordinate_0, PointTest::coordinate_1, PointTest::dimension, irafhy::Point::one(), and irafhy::Point::zero().
TEST_F() [2/5]
TEST_F (PointTest , memberFunctions)
References irafhy::Point::coordinate(), PointTest::coordinate_0, PointTest::dimension, irafhy::Point::dimension(), and irafhy::Point::empty().
TEST_F() [3/5]
TEST_F (PointTest , operations)
References PointTest::coordinate_0, PointTest::coordinate_1, and PointTest::dimension.
TEST_F() [4/5]
TEST_F (PointTest , comparisons)
References PointTest::coordinate_0, and PointTest::coordinate_1.
TEST_F() [5/5]
TEST_F (PointTest , outStream)
References PointTest::coordinate_0.