irafhy: /home/jianqiang/CLionProjects/irafhy/test/representationTest/geometricTest/intervalHullTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <capd/capdlib.h>
#include <random>
#include <irafhy/representation/geometric/intervalHull.h>
#include <irafhy/representation/geometric/basic/point.h>
Classes
class IntervalHullTest
Functions
TEST_F (IntervalHullTest, constructor)
TEST_F (IntervalHullTest, memberFunctions)
TEST_F (IntervalHullTest, operations)
TEST_F (IntervalHullTest, outStream)
Function Documentation
TEST_F() [1/4]
TEST_F (IntervalHullTest , constructor)
References IntervalHullTest::constraints, and IntervalHullTest::points.
TEST_F() [2/4]
TEST_F (IntervalHullTest , memberFunctions)
References IntervalHullTest::constraints, irafhy::IntervalHull::dimension(), IntervalHullTest::dimension, irafhy::IntervalHull::empty(), irafhy::IntervalHull::intersect(), IntervalHullTest::points, and irafhy::IntervalHull::unite().
TEST_F() [3/4]
TEST_F (IntervalHullTest , operations)
References IntervalHullTest::constraints, irafhy::IntervalHull::contains(), and IntervalHullTest::coordinate.
TEST_F() [4/4]
TEST_F (IntervalHullTest , outStream)
References IntervalHullTest::constraints.