irafhy: /home/jianqiang/CLionProjects/irafhy/test/representationTest/geometricTest/basicTest/halfSpaceTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <Eigen/Core>
#include <irafhy/representation/geometric/basic/halfSpace.h>
Classes
class HalfSpaceTest
Functions
TEST_F (HalfSpaceTest, constructor)
TEST_F (HalfSpaceTest, memberFunctions)
TEST_F (HalfSpaceTest, operations)
TEST_F (HalfSpaceTest, outStream)
Function Documentation
TEST_F() [1/4]
TEST_F (HalfSpaceTest , constructor)
References HalfSpaceTest::dimension, irafhy::HalfSpace::Empty(), HalfSpaceTest::normal, and HalfSpaceTest::offset.
TEST_F() [2/4]
TEST_F (HalfSpaceTest , memberFunctions)
References irafhy::HalfSpace::contains(), HalfSpaceTest::dimension, irafhy::HalfSpace::dimension(), irafhy::HalfSpace::holds(), HalfSpaceTest::normal, irafhy::HalfSpace::normal(), HalfSpaceTest::offset, and irafhy::HalfSpace::offset().
TEST_F() [3/4]
TEST_F (HalfSpaceTest , operations)
References HalfSpaceTest::normal, and HalfSpaceTest::offset.
TEST_F() [4/4]
TEST_F (HalfSpaceTest , outStream)
References HalfSpaceTest::normal, and HalfSpaceTest::offset.