irafhy: irafhy::Time Struct Reference
irafhy::Time Struct Reference
struct used to hold the duration information
#include <metaStructure.h>
Public Member Functions
Time ()
constructor
Time (const Time &time)=default
copy constructor
Time (Time &&time) noexcept=default
move constructor
Time (const double &start, const double &end)
constructor with given start and end of the duration
double start () const
get the start of the duration
double end () const
get the end of the duration
double range () const
get the range of the interval specified by duration
bool operator< (const Time &rhs) const
relational operator
Time & operator= (const Time &time)=default
assignment operator
Time & operator= (Time &&time) noexcept=default
assignment operator
~Time ()=default
destructor
Public Attributes
double start_ = 0.0
start of the duration
double end_ = 0.0
end of the duration
Friends
std::ostream & operator<< (std::ostream &out, const Time &time)
out the given right hand side duration to standard out stream
Detailed Description
struct used to hold the duration information
Constructor & Destructor Documentation
Time() [1/4]
irafhy::Time::Time () inline
constructor
Time() [2/4]
irafhy::Time::Time (const Time & time) default
copy constructor
Parameters
time given duration
Time() [3/4]
irafhy::Time::Time (Time && time) default noexcept
move constructor
Parameters
time given duration
Time() [4/4]
irafhy::Time::Time (const double & start, const double & end) inline
constructor with given start and end of the duration
Parameters
start start of the duration
end end of the duration
References end(), and start().
~Time()
irafhy::Time::~Time () default
destructor
Referenced by operator<().
Member Function Documentation
end()
double irafhy::Time::end () const inline
get the end of the duration
Returns
the end of the duration
References end_.
Referenced by operator<(), irafhy::ODESolver::solve(), and Time().
operator<()
bool irafhy::Time::operator< (const Time & rhs) const inline
relational operator
Parameters
rhs right hand side duration
Returns
TRUE if start or end less than the right hand side one
References end(), operator=(), start(), and ~Time().
operator=() [1/2]
Time& irafhy::Time::operator= (const Time & time) inline default
assignment operator
Parameters
time right hand side duration
Returns
resulting duration
Referenced by operator<().
operator=() [2/2]
Time& irafhy::Time::operator= (Time && time) inline default noexcept
assignment operator
Parameters
time right hand side duration
Returns
resulting duration
range()
double irafhy::Time::range () const inline
get the range of the interval specified by duration
Returns
the reange of the interval specified by duration
References start_.
Referenced by irafhy::Settings::duration(), irafhy::Settings::setDuration(), and irafhy::ODESolver::solve().
start()
double irafhy::Time::start () const inline
get the start of the duration
Returns
the start of the duration
References start_.
Referenced by operator<(), irafhy::ODESolver::solve(), and Time().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Time & time) friend
out the given right hand side duration to standard out stream
Parameters
out given out stream
time given right hand side duration
Returns
resulting out stream
Member Data Documentation
end_
double irafhy::Time::end_ = 0.0
end of the duration
Referenced by end().
start_
double irafhy::Time::start_ = 0.0
start of the duration
Referenced by range(), and start().
The documentation for this struct was generated from the following file:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/definition/metaStructure.h