irafhy: irafhy::convexConstraints Struct Reference
irafhy::convexConstraints Struct Reference
#include <convexHull.hpp>
Public Member Functions
convexConstraints ()=default
constructor
convexConstraints (const convexConstraints &constraints)=default
copy constructor
convexConstraints (convexConstraints &&constraints) noexcept=default
move constructor
convexConstraints (std::vector< Point > &pointConstraints, std::vector< HalfSpace > &halfSpaceConstraints, std::vector< std::vector< HalfSpace >> neighborHalfSpaces, std::vector< std::vector< Point >> facetVertices, std::vector< std::vector< int >> facetVerticesIdx, double volume, int dimension)
constructor with given information
std::vector< Point > pointConstraints () const
get the extreme vertices which define the convex hull
std::vector< HalfSpace > halfSpaceConstraints () const
get the half space constraints which define the convex hull
std::vector< std::vector< HalfSpace > > neighborHalfSpaces () const
get the vector storing each facet's neighbor facets
std::vector< std::vector< Point > > faceVertices () const
get the vertices of each facet
std::vector< std::vector< int > > faceVerticesIdx () const
get the indexes of each facet
double volume () const
get the volume of the convex hull
int dimension () const
get the dimension of the space which the convex hull in
Private Attributes
std::vector< Point > pointConstraints_
extreme vertices which define the convex hull
std::vector< HalfSpace > halfSpaceConstraints_
boundary half spaces which define the convex hull
std::vector< std::vector< HalfSpace > > neighborHalfSpaces_
each half space's neighbor half spaces
std::vector< std::vector< Point > > facetVertices_
each facet's extreme vertices
std::vector< std::vector< int > > facetVerticesIdx_
indexes of each facet's extreme vertices in whole convex hull extreme vertices
double volume_ {}
volume of the convex hull
int dimension_ {}
dimension of the space which the convex hull in
Constructor & Destructor Documentation
convexConstraints() [1/4]
irafhy::convexConstraints::convexConstraints () default
constructor
Referenced by irafhy::ConvexHull::constraints().
convexConstraints() [2/4]
irafhy::convexConstraints::convexConstraints (const convexConstraints & constraints) default
copy constructor
Parameters
constraints given constraint which defines the convex hull
convexConstraints() [3/4]
irafhy::convexConstraints::convexConstraints (convexConstraints && constraints) default noexcept
move constructor
Parameters
constraints constraints which defines the convex hull
convexConstraints() [4/4]
irafhy::convexConstraints::convexConstraints (std::vector< Point > & pointConstraints, std::vector< HalfSpace > & halfSpaceConstraints, std::vector< std::vector< HalfSpace >> neighborHalfSpaces, std::vector< std::vector< Point >> facetVertices, std::vector< std::vector< int >> facetVerticesIdx, double volume, int dimension) inline
constructor with given information
Parameters
pointConstraints extreme vertices which define the convex hull
halfSpaceConstraints half space constraints which define the convex hull
neighborHalfSpaces vector storing each facet's neighbor facets
facetVertices extreme vertices of each facet
facetVerticesIdx indexes of each facet's extreme vertices in whole convex hull extreme vertices
volume volume of the convex hull
dimension dimension which the convex hull in
Member Function Documentation
dimension()
int irafhy::convexConstraints::dimension () const inline
get the dimension of the space which the convex hull in
Returns
the dimension of the space which the convex hull in
References dimension_.
Referenced by irafhy::ConvexHull::constraints(), and irafhy::Polytope::init().
faceVertices()
std::vector<std::vector<Point> > irafhy::convexConstraints::faceVertices () const inline
get the vertices of each facet
Returns
the vertices of each facet
References facetVertices_.
faceVerticesIdx()
std::vector<std::vector<int> > irafhy::convexConstraints::faceVerticesIdx () const inline
get the indexes of each facet
Returns
indexes of each facet
References facetVerticesIdx_.
Referenced by irafhy::Polytope::verticesEnumerationDualPly().
halfSpaceConstraints()
std::vector<HalfSpace> irafhy::convexConstraints::halfSpaceConstraints () const inline
get the half space constraints which define the convex hull
Returns
the half space constraints of the convex hull
References halfSpaceConstraints_.
Referenced by irafhy::ConvexHull::constraints(), and irafhy::Polytope::init().
neighborHalfSpaces()
std::vector<std::vector<HalfSpace> > irafhy::convexConstraints::neighborHalfSpaces () const inline
get the vector storing each facet's neighbor facets
Returns
the vector storing each facet's neighbor facets
References neighborHalfSpaces_.
Referenced by irafhy::ConvexHull::constraints().
pointConstraints()
std::vector<Point> irafhy::convexConstraints::pointConstraints () const inline
get the extreme vertices which define the convex hull
Returns
the extreme vertices of the convex hull
References pointConstraints_.
Referenced by irafhy::ConvexHull::constraints(), and irafhy::Polytope::init().
volume()
double irafhy::convexConstraints::volume () const inline
get the volume of the convex hull
Returns
the volume of the convex hull
References volume_.
Referenced by irafhy::Polytope::init().
Member Data Documentation
dimension_
int irafhy::convexConstraints::dimension_ {} private
dimension of the space which the convex hull in
Referenced by dimension().
facetVertices_
std::vector<std::vector<Point> > irafhy::convexConstraints::facetVertices_ private
each facet's extreme vertices
Referenced by faceVertices().
facetVerticesIdx_
std::vector<std::vector<int> > irafhy::convexConstraints::facetVerticesIdx_ private
indexes of each facet's extreme vertices in whole convex hull extreme vertices
Referenced by faceVerticesIdx().
halfSpaceConstraints_
std::vector<HalfSpace> irafhy::convexConstraints::halfSpaceConstraints_ private
boundary half spaces which define the convex hull
Referenced by halfSpaceConstraints().
neighborHalfSpaces_
std::vector<std::vector<HalfSpace> > irafhy::convexConstraints::neighborHalfSpaces_ private
each half space's neighbor half spaces
Referenced by neighborHalfSpaces().
pointConstraints_
std::vector<Point> irafhy::convexConstraints::pointConstraints_ private
extreme vertices which define the convex hull
Referenced by pointConstraints().
volume_
double irafhy::convexConstraints::volume_ {} private
volume of the convex hull
Referenced by volume().
The documentation for this struct was generated from the following file:
/home/jianqiang/CLionProjects/irafhy/include/irafhy/utility/compGeometry/convexHull.hpp