irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/parserTest/visitorTest/definitionVisitorTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <capd/capdlib.h>
#include <vector>
#include <fstream>
#include <boost/filesystem.hpp>
#include <irafhy/representation/formal/basic/condition.h>
#include <irafhy/utility/parser/visitor/definitionVisitor.h>
Classes
class runDefinitionVisitorTest
Functions
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTest_condition_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_hpolytope_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_vpolytope_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_matrix_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_vector_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_intervalHull_Test)
TEST_F (runDefinitionVisitorTest, runDefinitionVisitorTests_interval_Test)
Function Documentation
TEST_F() [1/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTest_condition_Test)
TEST_F() [2/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_hpolytope_Test)
References hybridautomatonParser::hpolytope(), and runDefinitionVisitorTest::hpolytopeIfstream.
TEST_F() [3/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_vpolytope_Test)
References hybridautomatonParser::vpolytope(), and runDefinitionVisitorTest::vpolytopeIfstream.
TEST_F() [4/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_matrix_Test)
References hybridautomatonParser::matrix(), and runDefinitionVisitorTest::matrixIfstream.
TEST_F() [5/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_vector_Test)
References hybridautomatonParser::vector(), and runDefinitionVisitorTest::vectorIfstream.
TEST_F() [6/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_intervalHull_Test)
References hybridautomatonParser::intervalhull(), and runDefinitionVisitorTest::intervalHullIfstream.
TEST_F() [7/7]
TEST_F (runDefinitionVisitorTest , runDefinitionVisitorTests_interval_Test)
References hybridautomatonParser::interval(), and runDefinitionVisitorTest::intervalIfstream.