irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/optimizerTest/linearProgTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <capd/capdlib.h>
#include <irafhy/utility/optimizer/linearProg/GLPKWrapper.h>
#include <limits>
Classes
class runLinearProgTest
Functions
TEST_F (runLinearProgTest, evaluation)
Function Documentation
TEST_F()
TEST_F (runLinearProgTest , evaluation)
References runLinearProgTest::constraintColBounds, runLinearProgTest::constraintMatrix, runLinearProgTest::constraintRowBounds, irafhy::GLPKWrapper::init(), irafhy::MAX, runLinearProgTest::objectCoefficients, runLinearProgTest::objectConstant, irafhy::GLPKWrapper::result(), and irafhy::GLPKWrapper::solve().