irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/parserTest/visitorTest/locationsVisitorTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <fstream>
#include <capd/capdlib.h>
#include <boost/filesystem.hpp>
#include <irafhy/utility/parser/visitor/locationsVisitor.h>
#include <overApproximateForward/analyser/analyser.h>
Classes
class runLocationsVisitorTest
Functions
TEST_F (runLocationsVisitorTest, case_0)
TEST_F (runLocationsVisitorTest, case_1)
TEST_F (runLocationsVisitorTest, case_2)
Function Documentation
TEST_F() [1/3]
TEST_F (runLocationsVisitorTest , case_0)
References runLocationsVisitorTest::example_0Ifstream, and hybridautomatonParser::locations().
TEST_F() [2/3]
TEST_F (runLocationsVisitorTest , case_1)
References runLocationsVisitorTest::example_1Ifstream, and hybridautomatonParser::locations().
TEST_F() [3/3]
TEST_F (runLocationsVisitorTest , case_2)
References runLocationsVisitorTest::example_2Ifstream, and hybridautomatonParser::locations().