irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/solverTest/CSPSolverTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <string>
#include <fstream>
#include <boost/filesystem.hpp>
#include <irafhy/utility/solver/CSPSolver.h>
#include <irafhy/representation/geometric/intervalHull.h>
#include <irafhy/utility/viewer.h>
Classes
class runCSPSolverTest
Functions
TEST_F (runCSPSolverTest, case_0)
TEST_F (runCSPSolverTest, case_1)
TEST_F (runCSPSolverTest, case_2)
Function Documentation
TEST_F() [1/3]
TEST_F (runCSPSolverTest , case_0)
References runCSPSolverTest::_2dIntervalHull, irafhy::LINE, irafhy::viewer::show(), and irafhy::CSPSolver::solve().
TEST_F() [2/3]
TEST_F (runCSPSolverTest , case_1)
References runCSPSolverTest::_3dIntervalHull, irafhy::LINE, irafhy::viewer::show(), and irafhy::CSPSolver::solve().
TEST_F() [3/3]
TEST_F (runCSPSolverTest , case_2)