irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/solverTest/ODESolverTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <string>
#include <fstream>
#include <capd/capdlib.h>
#include <boost/filesystem.hpp>
#include <irafhy/utility/solver/ODESolver.h>
#include <irafhy/utility/viewer.h>
#include <irafhy/utility/parser/visitor/systemVisitor.h>
Classes
class runODESolverTest
Functions
TEST_F (runODESolverTest, case_0)
TEST_F (runODESolverTest, case_1)
TEST_F (runODESolverTest, case_2)
TEST_F (runODESolverTest, case_3)
TEST_F (runODESolverTest, case_4)
Function Documentation
TEST_F() [1/5]
TEST_F (runODESolverTest , case_0)
References runODESolverTest::example_0Ifstream, irafhy::PLANE, irafhy::Time::range(), irafhy::Condition::set(), irafhy::viewer::show(), irafhy::ODESolver::solve(), and hybridautomatonParser::system().
TEST_F() [2/5]
TEST_F (runODESolverTest , case_1)
References runODESolverTest::example_1Ifstream, irafhy::PLANE, irafhy::Time::range(), irafhy::Condition::set(), irafhy::viewer::show(), irafhy::ODESolver::solve(), and hybridautomatonParser::system().
TEST_F() [3/5]
TEST_F (runODESolverTest , case_2)
References runODESolverTest::example_2Ifstream, irafhy::PLANE, irafhy::Time::range(), irafhy::Condition::set(), irafhy::viewer::show(), irafhy::ODESolver::solve(), and hybridautomatonParser::system().
TEST_F() [4/5]
TEST_F (runODESolverTest , case_3)
References runODESolverTest::example_3Ifstream, irafhy::Condition::set(), irafhy::ODESolver::solve(), and hybridautomatonParser::system().
TEST_F() [5/5]
TEST_F (runODESolverTest , case_4)
References runODESolverTest::example_4Ifstream, irafhy::PLANE, irafhy::Time::range(), irafhy::Condition::set(), irafhy::viewer::show(), irafhy::ODESolver::solve(), and hybridautomatonParser::system().