irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/parserTest/parserTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <capd/capdlib.h>
#include <fstream>
#include <string>
#include <boost/filesystem.hpp>
#include <irafhy/representation/formal/basic/constraints.h>
#include <irafhy/utility/parser/hybridAutomatonParser.h>
#include <irafhy/utility/parser/settingsParser.h>
#include <underApproximateBackwardUsingPolytope/analyser/analyser.h>
#include <underApproximateBackwardUsingPolytope/verifier/verifier.h>
#include <underApproximateBackwardUsingPolytope/settings/settings.h>
Classes
class runParserTest
Functions
TEST_F (runParserTest, case_0)
TEST_F (runParserTest, case_1)
Function Documentation
TEST_F() [1/2]
TEST_F (runParserTest , case_0)
References runParserTest::modelPath, and irafhy::HybridAutomatonParser< Analyser, Verifier >::parse().
TEST_F() [2/2]
TEST_F (runParserTest , case_1)
References runParserTest::modelPath, irafhy::HybridAutomatonParser< Analyser, Verifier >::parse(), irafhy::SettingsParser::parse(), runParserTest::settingsPath, and irafhy::HybridAutomaton< Analyser, Verifier >::variables().