irafhy: /home/jianqiang/CLionProjects/irafhy/test/utilityTest/parserTest/visitorTest/settingsVisitorTest/runTest.cpp File Reference
runTest.cpp File Reference
#include <gtest/gtest.h>
#include <vector>
#include <fstream>
#include <string>
#include <boost/filesystem.hpp>
#include <capd/capdlib.h>
#include <irafhy/utility/parser/visitor/settingsVisitor.h>
#include <overApproximateForward/settings/settings.h>
#include <underApproximateBackwardUsingPolytope/settings/settings.h>
Classes
class runSettingsVisitorTest
Functions
TEST_F (runSettingsVisitorTest, case_0)
TEST_F (runSettingsVisitorTest, case_1)
TEST_F (runSettingsVisitorTest, case_2)
Function Documentation
TEST_F() [1/3]
TEST_F (runSettingsVisitorTest , case_0)
References runSettingsVisitorTest::example_0Ifstream, irafhy::Settings::help(), and settingsParser::setting().
TEST_F() [2/3]
TEST_F (runSettingsVisitorTest , case_1)
References runSettingsVisitorTest::example_1Ifstream, irafhy::Settings::help(), and settingsParser::setting().
TEST_F() [3/3]
TEST_F (runSettingsVisitorTest , case_2)
References runSettingsVisitorTest::example_2Ifstream, irafhy::Settings::help(), and settingsParser::setting().