grammar locations;
import definition;

modelid: KEY_NAME VARIABLE;
flows: KEY_FLOWS LEFTCURLYBRACKET system RIGHTCURLYBRACKET;
invariantcondition:
	KEY_INVARIANT_CONDITIONS LEFTCURLYBRACKET condition? RIGHTCURLYBRACKET;
model:
	KEY_MODEL LEFTCURLYBRACKET modelid flows invariantcondition RIGHTCURLYBRACKET;
locations:
	KEY_LOCATIONS LEFTCURLYBRACKET model+ RIGHTCURLYBRACKET;