grammar transitions;
import definition;

direction: KEY_DIRECTION VARIABLE FROMTO VARIABLE;
guardcondition:
	KEY_GUARD_CONDITIONS LEFTCURLYBRACKET condition? RIGHTCURLYBRACKET;
updatefunction: VARIABLE DEFINE expression;
resetmap:
	KEY_RESET_MAP LEFTCURLYBRACKET updatefunction* RIGHTCURLYBRACKET;
jump:
	KEY_JUMP LEFTCURLYBRACKET direction guardcondition resetmap RIGHTCURLYBRACKET;
transitions:
	KEY_TRANSITIONS LEFTCURLYBRACKET jump* RIGHTCURLYBRACKET;